(use-modules (ice-9 format)
((rnrs) :version (6) #:prefix r6rs:)
(system vm trace)
)
(let ((prog_name "guile_llama_cpp")
(version_string "0.2"))
(format #t "~:a ~:a Copyright 2024 Li-Cheng (Andy) Tai ~%" prog_name  version_string)
(format #t "License: GNU LGPL3+ ~%"))
(load-extension "libguile_llama_cpp.so" "scm_init_guile_llama_cpp_module")
(format #t "libguile_llama_cpp.so loaded ~%")