#! /bin/sh
# -*- mode: scheme
install_dir=$(dirname $0)/..
local_lib_dir=${install_dir}/share/guile/site/3.0/scripts  #follow make install directory hierarchy of autotools
export GUILE_LOAD_PATH=${install_dir}:${local_lib_dir}:${GUILE_LOAD_PATH}
export LD_LIBRARY_PATH=${install_dir}/lib:${LD_LIBRARY_PATH}
exec guile -e main -s "$0" "$@"
!#
(use-modules (rnrs)
(system foreign))
(include-from-path "init_common.scm")
(use-modules (guile-llama-cpp))
(include-from-path "utils.scm")
(define (tokenize prompt-text model-path)
(let ((prompt #f)
(model-params #f)
(context-params #f)
(model #f)
(ctx #f)
(n-tokens-max #f)
(tokens #f)
(n-tokens #f))
(llama-backend-init)
(set! model-params (llama-model-default-params))
(set! model (llama-load-model-from-file model-path model-params))
(set! context-params (llama-context-default-params))
(llama-context-params-seed-set context-params 1234)
(llama-context-params-n-ctx-set context-params 2048)
(llama-context-params-n-threads-set context-params 8)
(llama-context-params-n-threads-batch-set context-params 8)
(set! ctx (llama-new-context-with-model model context-params))
(set! n-tokens-max (llama-context-params-n-ctx-get context-params))
(set! tokens (new-llama-token-array n-tokens-max))
(set! n-tokens (llama-tokenize (llama-get-model ctx) prompt-text (llama-token-array-cast tokens) n-tokens-max  #t #f))
(format #t "prompt text  '~:a'  prompt length ~:a   n tokens  ~:a ~%"  prompt-text (string-length prompt-text) n-tokens)
(do ((i 0 (+ i 1)))
((>= i  n-tokens) #t)
(format #t "~:a " (llama-token-array-getitem tokens i))
(format #t "~:a ~%" (llama-token-to-piece-return-string ctx (llama-token-array-getitem tokens i))))
(llama-free ctx)
(llama-free-model model)
(llama-backend-free)
n-tokens
))
(define (main args)
(let* ((t #f)
(prompt-text (cadr args))
(model-path (caddr args))
)
(format #t "args:  '~:a' ~:a ~%"  prompt-text model-path)
(set! t (tokenize prompt-text model-path))
(format #t "tokenize result: ~:a  ~%"  t)
(exit 0)))