import json
class DTESNUsageExample:
    def __init__(self):
        self.base_url = 'http://localhost:8000'
        self.endpoints = {'health': '/health', 'root': '/deep_tree_echo/', 'process': '/deep_tree_echo/process', 'status': '/deep_tree_echo/status', 'membrane_info': '/deep_tree_echo/membrane_info', 'esn_state': '/deep_tree_echo/esn_state'}
    def show_endpoint_documentation(self):
        print('📚 Deep Tree Echo FastAPI Endpoints Documentation')
        print('=' * 60)
        print()
        endpoints_info = {'GET /health': {'description': 'Health check for the Deep Tree Echo service', 'response_example': {'status': 'healthy', 'service': 'deep_tree_echo', 'version': '1.0.0'}}, 'GET /deep_tree_echo/': {'description': 'Root endpoint with service information', 'response_example': {'service': 'Deep Tree Echo API', 'version': '1.0.0', 'server_rendered': True, 'endpoints': ['process', 'status', 'membrane_info', 'esn_state']}}, 'POST /deep_tree_echo/process': {'description': 'Process input through DTESN system', 'request_example': {'input_data': 'Hello Deep Tree Echo', 'membrane_depth': 4, 'esn_size': 512, 'processing_mode': 'server_side'}, 'response_example': {'status': 'success', 'result': {'processed_output': 'dtesn_result'}, 'membrane_layers': 4, 'processing_time_ms': 15.2, 'server_rendered': True}}, 'GET /deep_tree_echo/status': {'description': 'Get DTESN system operational status', 'response_example': {'dtesn_system': 'operational', 'server_side': True, 'processing_capabilities': {'max_membrane_depth': 8, 'max_esn_size': 1024}}}, 'GET /deep_tree_echo/membrane_info': {'description': 'Information about P-System membrane hierarchy', 'response_example': {'membrane_type': 'P-System', 'hierarchy_type': 'rooted_tree', 'oeis_sequence': 'A000081', 'server_rendered': True}}, 'GET /deep_tree_echo/esn_state': {'description': 'Echo State Network reservoir information', 'response_example': {'reservoir_type': 'echo_state_network', 'state': 'ready', 'spectral_radius': 0.95, 'server_rendered': True}}}
        for endpoint, info in endpoints_info.items():
            print(f'🔗 **{endpoint}**')
            print(f"   Description: {info['description']}")
            if 'request_example' in info:
                print('   Request Example:')
                print('   ```json')
                print(f"   {json.dumps(info['request_example'], indent=4)}")
                print('   ```')
            print('   Response Example:')
            print('   ```json')
            print(f"   {json.dumps(info['response_example'], indent=4)}")
            print('   ```')
            print()
    def show_curl_examples(self):
        print('💻 cURL Command Examples')
        print('=' * 30)
        print()
        curl_commands = [{'description': 'Health check', 'command': 'curl -X GET http://localhost:8000/health'}, {'description': 'Get service information', 'command': 'curl -X GET http://localhost:8000/deep_tree_echo/'}, {'description': 'Process text through DTESN', 'command': 'curl -X POST http://localhost:8000/deep_tree_echo/process \\\n  -H "Content-Type: application/json" \\\n  -d \'{\n    "input_data": "Hello Deep Tree Echo",\n    "membrane_depth": 3,\n    "esn_size": 256,\n    "processing_mode": "server_side"\n  }\'\n                '.strip()}, {'description': 'Get system status', 'command': 'curl -X GET http://localhost:8000/deep_tree_echo/status'}, {'description': 'Get membrane information', 'command': 'curl -X GET http://localhost:8000/deep_tree_echo/membrane_info'}, {'description': 'Get ESN state', 'command': 'curl -X GET http://localhost:8000/deep_tree_echo/esn_state'}]
        for i, cmd_info in enumerate(curl_commands, 1):
            print(f"{i}. **{cmd_info['description']}**")
            print('   ```bash')
            print(f"   {cmd_info['command']}")
            print('   ```')
            print()
    def show_python_client_example(self):
        print('🐍 Python Client Example')
        print('=' * 30)
        print()
        python_code = '\nimport asyncio\nimport aiohttp\nimport json\n\nclass DTESNClient:\n    def __init__(self, base_url="http://localhost:8000"):\n        self.base_url = base_url\n    \n    async def health_check(self):\n        """Check service health."""\n        async with aiohttp.ClientSession() as session:\n            async with session.get(f"{self.base_url}/health") as response:\n                return await response.json()\n    \n    async def get_status(self):\n        """Get DTESN system status."""\n        async with aiohttp.ClientSession() as session:\n            async with session.get(f"{self.base_url}/deep_tree_echo/status") as response:\n                return await response.json()\n    \n    async def process_text(self, text, membrane_depth=4, esn_size=512):\n        """Process text through DTESN system."""\n        data = {\n            "input_data": text,\n            "membrane_depth": membrane_depth,\n            "esn_size": esn_size,\n            "processing_mode": "server_side"\n        }\n        \n        async with aiohttp.ClientSession() as session:\n            async with session.post(\n                f"{self.base_url}/deep_tree_echo/process",\n                json=data\n            ) as response:\n                return await response.json()\n    \n    async def get_membrane_info(self):\n        """Get membrane hierarchy information."""\n        async with aiohttp.ClientSession() as session:\n            async with session.get(f"{self.base_url}/deep_tree_echo/membrane_info") as response:\n                return await response.json()\n\n# Usage example\nasync def main():\n    client = DTESNClient()\n    \n    # Health check\n    health = await client.health_check()\n    print(f"Health: {health}")\n    \n    # Process some text\n    result = await client.process_text("Deep Tree Echo test input")\n    print(f"Processing result: {json.dumps(result, indent=2)}")\n    \n    # Get system status\n    status = await client.get_status()\n    print(f"Status: {json.dumps(status, indent=2)}")\n\nif __name__ == "__main__":\n    asyncio.run(main())\n        '.strip()
        print('```python')
        print(python_code)
        print('```')
        print()
    def show_fastapi_integration(self):
        print('⚡ FastAPI Integration Example')
        print('=' * 40)
        print()
        integration_code = '\nfrom fastapi import FastAPI\nfrom aphrodite.endpoints.deep_tree_echo import create_app\nfrom aphrodite.endpoints.deep_tree_echo.config import DTESNConfig\nfrom aphrodite.engine.async_aphrodite import AsyncAphrodite\n\n# Create Aphrodite engine (optional)\n# engine = AsyncAphrodite.from_engine_args(engine_args)\n\n# Create DTESN configuration\nconfig = DTESNConfig(\n    max_membrane_depth=6,\n    esn_reservoir_size=1024,\n    bseries_max_order=12,\n    enable_caching=True,\n    enable_performance_monitoring=True\n)\n\n# Create FastAPI app with Deep Tree Echo endpoints\napp = create_app(engine=None, config=config)\n\n# Run with uvicorn\nif __name__ == "__main__":\n    import uvicorn\n    uvicorn.run(app, host="0.0.0.0", port=8000)\n        '.strip()
        print('```python')
        print(integration_code)
        print('```')
        print()
        print('🚀 **Running the server:**')
        print('```bash')
        print('python your_server.py')
        print('```')
        print()
        print('📖 **View API documentation:**')
        print('- Swagger UI: http://localhost:8000/docs')
        print('- ReDoc: http://localhost:8000/redoc')
        print()
def main():
    print('🧠 Deep Tree Echo FastAPI Usage Guide')
    print('=' * 50)
    print()
    print('This guide shows how to use the Deep Tree Echo FastAPI endpoints')
    print('for server-side DTESN (Deep Tree Echo System Network) processing.')
    print()
    example = DTESNUsageExample()
    example.show_endpoint_documentation()
    print('─' * 60)
    example.show_curl_examples()
    print('─' * 60)
    example.show_python_client_example()
    print('─' * 60)
    example.show_fastapi_integration()
    print('✨ **Summary**')
    print()
    print('The Deep Tree Echo FastAPI endpoints provide:')
    print('• ✅ Server-side rendering with no client dependencies')
    print('• ✅ Integration with Aphrodite Engine architecture')
    print('• ✅ DTESN processing (P-Systems + ESN + B-Series)')
    print('• ✅ Performance monitoring and caching')
    print('• ✅ Comprehensive API documentation')
    print('• ✅ Production-ready configuration management')
    print()
    print('🎯 Ready for production deployment!')
if __name__ == '__main__':
    main()