(use-modules (opencog) (opencog ure))
(ure-logger-set-level! "debug")
(load "kb.scm")
(load "rb.scm")
(define X (Variable "$X"))
(define target (synonymous nil-believes-max-believes-universe-is-math X))
(define results (cog-bc rrb target))