(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog logger))
(use-modules (opencog persist) (opencog persist-sql))
(use-modules (opencog nlp) (opencog nlp learn))
(use-modules (opencog matrix) (opencog exec))
(use-modules (opencog sheaf))
(use-modules (opencog cogserver))
(start-cogserver "x-test.conf")
(sql-open "postgres:///langtest?user=linas&password=asdf")
(define pca (make-pseudo-cset-api))
(define psa (add-pair-stars pca))
(define wpa (make-any-link-api))
(define wps (add-pair-stars wpa))
(define gca (make-gram-class-api))
(define gcs (add-pair-stars gca))