(define-module (opencog nlp fake))
(include-from-path "opencog/nlp/fake/zipf.scm")
(include-from-path "opencog/nlp/fake/zipf-zri.scm")
(include-from-path "opencog/nlp/fake/random-dict.scm")
(include-from-path "opencog/nlp/fake/print-dict.scm")