(define (make-zipf-generator/zri n s q)
  (define (hat x)
    (expt (+ x q) (- s)))
  (define _1-s (- 1 s))
  (define oms (/ 1 _1-s))
  (define (big-h x)
    (/ (expt (+ q x) _1-s) _1-s))
  (define (big-h-inv y)
    (- (expt (* y _1-s) oms) q))
  (define big-h-half (- (big-h 1.5) (hat 1)))
  (define big-h-n (big-h (+ n 0.5)))
  (define cut (- 1 (big-h-inv (- (big-h 1.5) (hat 1)))))
  (define dist (make-random-real-generator big-h-half big-h-n))
  (define (try)
    (define u (dist))
    (define x (big-h-inv u))
    (define kflt (floor (+ x 0.5)))
    (define k (exact kflt))
    (if (and (< 0 k)
             (or
               (<= (- k x) cut)
               (>= u (- (big-h (+ k 0.5)) (hat k))))) k #f))
  (define (loop-until)
    (define k (try))
    (if k k (loop-until)))
  loop-until)
(define (make-zipf-generator/one n s q)
  (define _1-s (- 1 s))
  (define (hat x)
    (define xpq (+ x q))
    (/ (expt xpq _1-s) xpq))
  (define (exn lg)
    (define (trm n u lg) (* lg (+ 1 (/ (* _1-s u) n))))
    (trm 2 (trm 3 (trm 4 1 lg) lg) lg))
  (define (lg y)
    (define yms (* y _1-s))
    (define (trm n u r) (- (/ 1 n) (* u r)))
    (* y (trm 1 yms (trm 2 yms (trm 3 yms (trm 4 yms 0))))))
  (define (big-h x)
    (exn (log (+ q x))))
  (define (big-h-inv y)
    (- (exp (lg y)) q))
  (define big-h-half (- (big-h 1.5) (hat 1)))
  (define big-h-n (big-h (+ n 0.5)))
  (define cut (- 1 (big-h-inv (- (big-h 1.5) (/ 1 (+ 1 q))))))
  (define dist (make-random-real-generator big-h-half big-h-n))
  (define (try)
    (define u (dist))
    (define x (big-h-inv u))
    (define kflt (floor (+ x 0.5)))
    (define k (exact kflt))
    (if (and (< 0 k)
             (or
               (<= (- k x) cut)
               (>= u (- (big-h (+ k 0.5)) (hat k))))) k #f))
  (define (loop-until)
    (define k (try))
    (if k k (loop-until)))
  loop-until)
(define make-zipf-generator
  (case-lambda
    ((n)
     (make-zipf-generator n 1.0 0.0))
    ((n s)
     (make-zipf-generator n s 0.0))
    ((n s q)
     (if (< 1e-5 (abs (- 1 s)))
         (make-zipf-generator/zri n s q)
         (make-zipf-generator/one n s q)))))