(use-modules (opencog))
(use-modules (opencog ure))
(load-from-path "ure-utils.scm")
(load-from-path "tests/ure/rules/crisp-modus-ponens-rule.scm")
(load-from-path "tests/ure/rules/fc-deduction-rule.scm")
(define fc-rbs (ConceptNode "fc-rule-base"))
(define crisp-modus-ponens-tv (stv 0.4 0.9))
(define crisp-deduction-tv (stv 0.6 0.9))
(define fc-rules (list (list crisp-modus-ponens-rule-name crisp-modus-ponens-tv)
(list fc-deduction-rule-name crisp-deduction-tv)))
(ure-add-rules fc-rbs fc-rules)
(ure-set-num-parameter fc-rbs "URE:maximum-iterations" 20)