(use-modules (opencog))
(use-modules (opencog ure))
(load-from-path "ure-utils.scm")
(load-from-path "tests/ure/rules/fc-deduction-rule.scm")
(define fc-deduction-rbs (ConceptNode "fc-deduction-rule-base"))
(ure-add-rules fc-deduction-rbs (list fc-deduction-rule-name))
(ure-set-maximum-iterations fc-deduction-rbs 20)