(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog matrix) (opencog persist))
(define (is-info-similar? MIOBJ CUTOFF WORD-A WORD-B)
	(define (get-info-sim wa wb) (MIOBJ 'mmt-fmi wa wb))
	(define sim (get-info-sim WORD-A WORD-B))
	(< CUTOFF sim)
)
(define (foo LLOBJ)
	(let* ((stars-obj (add-pair-stars LLOBJ))
			(suppt-obj (add-support-api stars-obj))
			(trans-obj (add-transpose-api stars-obj))
			(symio-obj (add-symmetric-mi-compute trans-obj))
		)
	(define sorted-djs
		(sort (stars-obj 'right-basis)
			(lambda (da db)
				(> (suppt-obj `left-count da) (suppt-obj `left-count db)))))
(format #t "foo")
	)
)