TEXT mmuinit0(SB), $0
MOVW $64, R3
MOVW R3, CTR
MOVW $0, R4
tlbloop:
TLBIE R4
SYNC
ADD $BIT(19), R4
BDNZ tlbloop
TLBSYNC
MOVW $(KZERO|(0x7ff<<2)|2), R3
MOVW $(PTEVALID|PTEWRITE), R4
MOVW R3, SPR(IBATU(0))
MOVW R4, SPR(IBATL(0))
MOVW R3, SPR(DBATU(0))
MOVW R4, SPR(DBATL(0))
ADD $(1<<28), R3
ADD $(1<<28), R4
MOVW R3, SPR(IBATU(1))
MOVW R4, SPR(IBATL(1))
MOVW R3, SPR(DBATU(1))
MOVW R4, SPR(DBATL(1))
MOVW $(FPGABASE|(0x7f<<2)|2), R3
MOVW $(FPGABASE|PTEWRITE|PTEUNCACHED), R4
MOVW R3, SPR(DBATU(2))
MOVW R4, SPR(DBATL(2))
MOVW R0, SPR(IBATU(2))
MOVW R0, SPR(IBATL(2))
MOVW $(INTMEM|(0x7ff<<2)|2), R3
MOVW $(INTMEM|PTEWRITE|PTEUNCACHED), R4
MOVW R3, SPR(DBATU(3))
MOVW R4, SPR(DBATL(3))
MOVW R0, SPR(IBATU(3))
MOVW R0, SPR(IBATL(3))
MOVW LR, R3
OR $KZERO, R3
MOVW R3, SPR(SRR0)
MOVW MSR, R4
OR $(MSR_IR|MSR_DR|MSR_RI|MSR_FP), R4
MOVW R4, SPR(SRR1)
RFI
RETURN