TEXT mmuinit0(SB), $0
MOVW $64, R3
MOVW R3, CTR
MOVW $0, R4
tlbloop:
TLBIE R4
SYNC
ADD $BIT(19), R4
BDNZ tlbloop
TLBSYNC
MOVW $(KZERO|(0x7ff<<2)|2), R3
MOVW $(PTEVALID|PTEWRITE), R4
MOVW R3, SPR(DBATU(2))
MOVW R4, SPR(DBATL(2))
MOVW R3, SPR(IBATU(2))
MOVW R4, SPR(IBATL(2))
MOVW LR, R3
OR $KZERO, R3
MOVW R3, SPR(SRR0)
MOVW MSR, R4
OR $(MSR_IR|MSR_DR|MSR_RI|MSR_FP), R4
MOVW R4, SPR(SRR1)
RFI
RETURN