#define PACKAGE "ragel"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "ragel"
#define PACKAGE_STRING "ragel 6.9"
#define PACKAGE_TARNAME "ragel"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "6.9"
#define VERSION "6.9"