(use-modules (opencog) (opencog exec))
(use-modules (opencog metta))
(use-modules (opencog test-runner))
(opencog-test-runner)
(define tname "metta-lisp-test")
(test-begin tname)
(MeTTa "(= (fact $x) (if (< $x 2) 1 (* $x (fact (- $x 1)))))")
(define fact5 (cog-execute! (MeTTa "(fact 5)")))
(define ef5 (MeTTa "120"))
(test-assert "factorial-five" (equal? fact5 ef5))
(MeTTa "(= foo 6)")
(define fact6 (cog-execute! (MeTTa "(fact foo)")))
(define ef6 (MeTTa "720"))
(test-assert "factorial-six" (equal? fact6 ef6))
(test-end tname)
(opencog-test-end)