(use-modules (opencog) (opencog exec))
(use-modules (opencog test-runner))
(opencog-test-runner)
(define tname "link-column-test")
(test-begin tname)
(define itli (list
(Item "a")
(Item "b")
(Item "c")
(Item "d")))
(define itcol (LinkColumn (List itli)))
(define itvec (cog-execute! itcol))
(format #t "Item list vect: ~A\n" itvec)
(test-assert "Item list vect" (equal? itvec (LinkValue itli)))
(define dircol (LinkColumn itli))
(define dirvec (cog-execute! dircol))
(format #t "Direct item vect: ~A\n" dirvec)
(test-assert "Direct vect" (equal? dirvec (LinkValue itli)))
(test-end tname)
(opencog-test-end)