(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(opencog-test-runner)
(define lower-space (cog-atomspace))
(define upper-space (cog-new-atomspace lower-space))
(define basic-lo-delete "test basic extract from below")
(test-begin basic-lo-delete)
(begin
(cog-set-atomspace! lower-space)
(define a (Concept "a"))
(define b (Concept "b"))
(cog-set-atomspace! upper-space)
(define li (Link a b))
(cog-set-atomspace! lower-space)
(test-equal "lower-size" 2 (length (cog-get-atoms 'Atom #t)))
(test-assert "extract-fail" (not (cog-extract! a)))
(test-equal "ex-lower-size" 2 (length (cog-get-atoms 'Atom #t)))
(test-assert "extract-works" (cog-extract-recursive! a))
(test-equal "post-ex-lower-size" 1 (length (cog-get-atoms 'Atom #t)))
(test-equal "empty-income" 0 (length (cog-incoming-set b)))
(cog-set-atomspace! upper-space)
(test-equal "upper-blown" 1 (length (cog-get-atoms 'Atom #t)))
(test-equal "upper-b-only" (list b) (cog-get-atoms 'Atom #t))
)
(test-end basic-lo-delete)
(define basic-hi-delete "test basic extract from above")
(test-begin basic-hi-delete)
(begin
(cog-atomspace-clear lower-space)
(cog-atomspace-clear upper-space)
(cog-set-atomspace! lower-space)
(define a (Concept "a"))
(define b (Concept "b"))
(cog-atomspace-ro! lower-space)
(cog-set-atomspace! upper-space)
(define li (Link a b))
(cog-atomspace-cow! #t upper-space)
(cog-set-atomspace! lower-space)
(test-equal "lower-size" 2 (length (cog-get-atoms 'Atom #t)))
(cog-set-atomspace! upper-space)
(test-equal "upper-size" 3 (length (cog-get-atoms 'Atom #t)))
(test-assert "extract-fail" (not (cog-extract! a)))
(test-equal "ex-upper-size" 3 (length (cog-get-atoms 'Atom #t)))
(test-assert "extract-works" (cog-extract-recursive! a))
(test-equal "post-ex-upper-size" 1 (length (cog-get-atoms 'Atom #t)))
(test-equal "empty-income" 0 (length (cog-incoming-set b)))
(cog-set-atomspace! lower-space)
(test-equal "lower-ok" 2 (length (cog-get-atoms 'Atom #t)))
)
(test-end basic-hi-delete)
(define basic-clean-delete "test clean extraction below")
(test-begin basic-clean-delete)
(begin
(cog-atomspace-clear lower-space)
(cog-atomspace-clear upper-space)
(cog-set-atomspace! lower-space)
(cog-atomspace-rw! lower-space)
(cog-atomspace-cow! #t lower-space)
(define a (Concept "a"))
(define b (Concept "b"))
(cog-set-atomspace! upper-space)
(cog-atomspace-cow! #t upper-space)
(define li (Link a b))
(cog-set-atomspace! lower-space)
(test-equal "lower-size" 2 (length (cog-get-atoms 'Atom #t)))
(test-assert "extract-works" (cog-extract! a))
(test-equal "ex-lower-size" 1 (length (cog-get-atoms 'Atom #t)))
(test-equal "lower-b-only" (list b) (cog-get-atoms 'Atom #t))
(test-equal "empty-income" 0 (length (cog-incoming-set b)))
(cog-set-atomspace! upper-space)
(test-equal "upper-OK-list" 1 (length (cog-get-all-roots)))
(test-equal "upper-list" (list li) (cog-get-all-roots))
(cog-set-atomspace! lower-space)
(define alo (Concept "a"))
(cog-set-atomspace! upper-space)
(test-equal "upper-all-there" 3 (length (cog-get-atoms 'Atom #t)))
(test-equal "unhidden" alo (gar li))
)
(test-end basic-clean-delete)
(opencog-test-end)