(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(opencog-test-runner)
(define base-space (cog-atomspace))
(define (make-space-list LST NUM)
	(if (<= NUM 0) LST
		(let ((newspace (cog-new-atomspace (cog-atomspace))))
			(cog-set-atomspace! newspace)
			(make-space-list (cons newspace LST) (- NUM 1)))))
(define num-spaces 20)
(define space-list (reverse (make-space-list (list base-space) num-spaces)))
(define astack "verify AtomSpace stack")
(test-begin astack)
(cog-set-atomspace! base-space)
(define curr-space base-space)
(for-each (lambda (space)
		(test-equal "space-env-size" 1 (length (cog-atomspace-env space)))
		(test-equal "space-parent" curr-space (car (cog-atomspace-env space)))
		(test-assert "space-distinct"
			(not (equal? space (car (cog-atomspace-env space)))))
		(set! curr-space space)
	)
	(cdr space-list))
(test-end astack)
(define vstack "simple value stack")
(test-begin vstack)
(define cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(Concept "hello" (ctv 1 0 cnt))
		(set! cnt (+ 1 cnt)))
	space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(test-equal "membership" space
			(cog-atomspace (cog-node 'Concept "hello")))
		(test-equal "count-tv" cnt
			(inexact->exact (cog-tv-count (cog-tv (cog-node 'Concept "hello")))))
		(test-equal "atomspace-size" 1 (count-all))
		(set! cnt (+ 1 cnt)))
	space-list)
(test-end vstack)
(define ostack "simple outgoing stack")
(test-begin ostack)
(cog-set-atomspace! base-space)
(Concept "foo")
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(test-equal "membership" space
			(cog-atomspace (cog-node 'Concept "hello")))
		(test-equal "atomspace-size" 2 (count-all))
	)
	space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(cog-set-tv! (List (Concept "hello") (Concept "foo"))
			(CountTruthValue 1 0 (* cnt 2)))
		(set! cnt (+ 1 cnt)))
	space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(define local-hello (Concept "hello"))
		(define local-list (List (Concept "hello") (Concept "foo")))
		(test-equal "count-tv" cnt
			(inexact->exact (cog-tv-count (cog-tv local-hello))))
		(test-equal "out-equality" local-hello (gar local-list))
		(test-equal "count-tv-out" cnt
			(inexact->exact (cog-tv-count (cog-tv (gar local-list)))))
		(test-equal "membership-gar-oset" space
			(cog-atomspace (gar local-list)))
		(test-equal "membership-local" space
			(cog-atomspace local-hello))
		(test-equal "membership-hello" space
			(cog-atomspace (Concept "hello")))
		(test-equal "membership-foo" base-space
			(cog-atomspace (Concept "foo")))
		(set! cnt (+ 1 cnt)))
	space-list)
(test-end ostack)
(define istack "simple incoming stack")
(test-begin istack)
(for-each cog-atomspace-clear space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(Concept "hello" (ctv 1 0 cnt))
		(set! cnt (+ 1 cnt)))
	space-list)
(cog-set-atomspace! base-space)
(Concept "foo")
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(test-equal "membership" space
			(cog-atomspace (cog-node 'Concept "hello")))
		(test-equal "atomspace-size" 2 (count-all))
	)
	space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(cog-set-tv! (List (Concept "hello") (Concept "foo"))
			(CountTruthValue 1 0 (* cnt 2)))
		(set! cnt (+ 1 cnt)))
	space-list)
(set! cnt 0)
(for-each (lambda (space)
		(cog-set-atomspace! space)
		(test-equal "count-tv" cnt
			(inexact->exact (cog-tv-count (cog-tv (Concept "hello")))))
		(test-equal "atomspace-size" 3 (count-all))
		(test-equal "incoming-size" 1 (cog-incoming-size (Concept "foo")))
		(test-equal "incoming-size" 1 (cog-incoming-size (Concept "hello")))
		(test-equal "membership-hello" space
			(cog-atomspace (Concept "hello")))
		(test-equal "membership-foo" base-space
			(cog-atomspace (Concept "foo")))
		(test-equal "membership-link" space
			(cog-atomspace (car (cog-incoming-set (Concept "hello")))))
		(test-equal "incoming-equal"
			(cog-incoming-set (Concept "hello"))
			(cog-incoming-set (Concept "foo")))
		(test-equal "list-tv" (* 2 cnt)
			(inexact->exact (cog-tv-count (cog-tv
				(car (cog-incoming-set (Concept "foo")))))))
		(set! cnt (+ 1 cnt)))
	space-list)
(test-end istack)
(opencog-test-end)