(use-modules (opencog) (opencog sheaf))
(define (mkvert NVERTS)
	(Concept (format #f "vertex ~D"
		(round (inexact->exact (* NVERTS (random:exp)))))))
(define mi-pred (Predicate "Faux MI Key"))
(define (make-pairs MPAIRS NVERTS)
	(define (mkpair)
		(Evaluation (Predicate "benchy") (List (mkvert NVERTS) (mkvert NVERTS))))
	(define (mkmi) (+ 4 (* 5 (random:normal))))
	(define (mkwpair)
		(cog-set-value! (mkpair) mi-pred (FloatValue (mkmi))))
	(define (mkmprs M)
		(if (< 0 M) (begin (mkwpair) (mkmprs (- M 1)))))
	(mkmprs MPAIRS)
)
(define (mksent LEN NVERTS)
	(define (mkwlist lst len)
		(if (< 0 len)
			(mkwlist (cons (mkvert NVERTS) lst) (- len 1))
			lst))
	(mkwlist '() LEN)
)
(define (cnt-edges SENT)
	(define (cnt-em CNT lst)
		(define frst (car lst))
		(define rest (cdr lst))
		(define nlinks 0)
		(if (null? rest) CNT
			(begin
				(for-each
					(lambda (rght)
						(if (not (null? (cog-link 'ListLink frst rght)))
							(set! nlinks (+ 1 nlinks))))
					rest)
				(cnt-em (+ CNT nlinks) rest))))
	(cnt-em 0 SENT)
)
(define (score-faux LEFT RIGHT DIST)
	(define llpr (cog-link 'ListLink LEFT RIGHT))
	(if (null? llpr) -10000.0
		(cog-value-ref
			(cog-value (Evaluation (Predicate "benchy") llpr) mi-pred) 0))
)
(define (score-dist-limit LEFT RIGHT DIST)
	(if (< 6 DIST) -10000.0 (score-faux LEFT RIGHT DIST))
)
(define (report-rate THUNK CNT)
	(define start (get-internal-real-time))
	(let ((foo (THUNK)))
		(define ela (exact->inexact (/ (- (get-internal-real-time) start)
			 internal-time-units-per-second)))
		(format #t "Performed ~D ops in ~A seconds, at ~A ops/sec\n"
			CNT ela (/ CNT ela))
		ela))
(define (report-perf LEN)
	(define nsents (if (< 10 LEN) (if (< 20 LEN) 140 800) 6000))
	(define (mksents howmany sentlen)
		(if (< 0 howmany)
			(begin
				(mksent sentlen nvocab)
				(mksents (- howmany 1) sentlen))))
	(define (parse-them howmany sentlen)
		(if (< 0 howmany)
			(begin
				(mst-parse-atom-seq (mksent sentlen nvocab) score-faux)
				(parse-them (- howmany 1) sentlen))))
	(define baseline (report-rate (lambda () (mksents nsents LEN)) nsents))
	(define measurme (report-rate (lambda () (parse-them nsents LEN)) nsents))
	(define adjusted-time (- measurme baseline))
	(define millisecs-per (* 1000 (/ adjusted-time nsents)))
	(format #t "Sentence length = ~D Millisecs/parse = ~8F Parses/sec = ~8F\n"
		LEN millisecs-per (/ nsents adjusted-time))
)
(define (report-all SLEN MAXLEN)
	(if (< SLEN MAXLEN)
		(begin
			(report-perf SLEN)
			(report-all (+ SLEN 1) MAXLEN))))
(define nvocab 300)
(define npairs 701000)
(format #t "Creating ~D pairs for ~D words ... one moment please...\n"
	npairs nvocab)
(report-rate (lambda () (make-pairs npairs nvocab)) 1)
(report-all 2 35)