#ifndef gdevpxat_INCLUDED
# define gdevpxat_INCLUDED
typedef enum {
pxaPaletteDepth = 2,
pxaColorSpace,
pxaNullBrush,
pxaNullPen,
pxaPaletteData,
pxaPatternSelectID = 8,
pxaGrayLevel,
pxaLightness,
pxaRGBColor,
pxaPatternOrigin,
pxaNewDestinationSize,
pxaPrimaryArray,
pxaPrimaryDepth,
pxaSaturation,
pxaColorimetricColorSpace,
pxaXYChromaticities,
pxaWhiteReferencePoint,
pxaCRGBMinMax,
pxaGammaGain,
pxaAllObjectTypes = 29,
pxaTextObjects,
pxaVectorObjects,
pxaRasterObjects,
pxaDeviceMatrix,
pxaDitherMatrixDataType,
pxaDitherOrigin,
pxaMediaDestination,
pxaMediaSize,
pxaMediaSource,
pxaMediaType,
pxaOrientation,
pxaPageAngle,
pxaPageOrigin,
pxaPageScale,
pxaROP3,
pxaTxMode,
pxaCustomMediaSize = 47,
pxaCustomMediaSizeUnits,
pxaPageCopies,
pxaDitherMatrixSize,
pxaDitherMatrixDepth,
pxaSimplexPageMode,
pxaDuplexPageMode,
pxaDuplexPageSide,
pxaArcDirection = 65,
pxaBoundingBox,
pxaDashOffset,
pxaEllipseDimension,
pxaEndPoint,
pxaFillMode,
pxaLineCapStyle,
pxaLineJoinStyle,
pxaMiterLength,
pxaLineDashStyle,
pxaPenWidth,
pxaPoint,
pxaNumberOfPoints,
pxaSolidLine,
pxaStartPoint,
pxaPointType,
pxaControlPoint1,
pxaControlPoint2,
pxaClipRegion,
pxaClipMode,
pxaColorDepth = 98,
pxaBlockHeight,
pxaColorMapping,
pxaCompressMode,
pxaDestinationBox,
pxaDestinationSize,
pxaPatternPersistence,
pxaPatternDefineID,
pxaSourceHeight = 107,
pxaSourceWidth,
pxaStartLine,
pxaPadBytesMultiple,
pxaBlockByteLength,
pxaNumberOfScanLines = 115,
pxaColorTreatment = 120,
pxaCommentData = 129,
pxaDataOrg,
pxaMeasure = 134,
pxaSourceType = 136,
pxaUnitsPerMeasure,
pxaStreamName = 139,
pxaStreamDataLength,
pxaErrorReport = 143,
pxaVUExtension = 145,
pxaVUAttr1 = 147,
pxaCharAngle = 161,
pxaCharCode,
pxaCharDataSize,
pxaCharScale,
pxaCharShear,
pxaCharSize,
pxaFontHeaderLength,
pxaFontName,
pxaFontFormat,
pxaSymbolSet,
pxaTextData,
pxaCharSubModeArray,
pxaWritingMode,
pxaXSpacingData = 175,
pxaYSpacingData,
pxaCharBoldValue,
px_attribute_next
} px_attribute_t;
#endif