#ifndef gdevdljm_INCLUDED
#  define gdevdljm_INCLUDED
#include "gdevpcl.h"
#define PCL_NO_SPACING   0
#define PCL3_SPACING     1
#define PCL4_SPACING     2
#define PCL5_SPACING     4
#define PCL_ANY_SPACING\
(PCL3_SPACING | PCL4_SPACING | PCL5_SPACING)
#define PCL_MODE_2_COMPRESSION       8
#define PCL_MODE_3_COMPRESSION      16
#define PCL_END_GRAPHICS_DOES_RESET 32
#define PCL_HAS_DUPLEX              64
#define PCL_CAN_SET_PAPER_SIZE     128
#define PCL_CAN_PRINT_COPIES       256
#define PCL_MODE0 PCL3_SPACING
#define PCL_MODE0NS PCL_NO_SPACING
#define PCL_MODE2 (PCL4_SPACING | PCL_MODE_2_COMPRESSION)
#define PCL_MODE2P (PCL_NO_SPACING | PCL_MODE_2_COMPRESSION)
#define PCL_MODE3 (PCL5_SPACING | PCL_MODE_3_COMPRESSION)
#define PCL_MODE3NS (PCL_NO_SPACING | PCL_MODE_3_COMPRESSION)
#define PCL_DJ_FEATURES\
(PCL_MODE2 |\
PCL_END_GRAPHICS_DOES_RESET | PCL_CAN_SET_PAPER_SIZE)
#define PCL_DJ500_FEATURES\
(PCL_MODE3 |\
PCL_END_GRAPHICS_DOES_RESET | PCL_CAN_SET_PAPER_SIZE)
#define PCL_FS600_FEATURES\
(PCL_MODE3 |\
PCL_CAN_SET_PAPER_SIZE | PCL_CAN_PRINT_COPIES)
#define PCL_LJ_FEATURES\
(PCL_MODE0)
#define PCL_LJplus_FEATURES\
(PCL_MODE0)
#define PCL_LJ2p_FEATURES\
(PCL_MODE2P |\
PCL_CAN_SET_PAPER_SIZE)
#define PCL_LJ3_FEATURES\
(PCL_MODE3 |\
PCL_CAN_SET_PAPER_SIZE | PCL_CAN_PRINT_COPIES)
#define PCL_LJ3D_FEATURES\
(PCL_MODE3 |\
PCL_HAS_DUPLEX | PCL_CAN_SET_PAPER_SIZE | PCL_CAN_PRINT_COPIES)
#define PCL_LJ4_FEATURES\
(PCL_MODE3 |\
PCL_CAN_SET_PAPER_SIZE | PCL_CAN_PRINT_COPIES)
#define PCL_LJ4D_FEATURES\
(PCL_MODE3 |\
PCL_HAS_DUPLEX | PCL_CAN_SET_PAPER_SIZE | PCL_CAN_PRINT_COPIES)
#define PCL_LP2563B_FEATURES\
(PCL_MODE0NS |\
PCL_CAN_SET_PAPER_SIZE)
#define	PCL_OCE9050_FEATURES\
(PCL_MODE3NS |\
PCL_CAN_SET_PAPER_SIZE)
int dljet_mono_print_page(
gx_device_printer * pdev,
FILE * prn_stream,
int dots_per_inch,
int features,
const char *page_init
);
int dljet_mono_print_page_copies(
gx_device_printer * pdev,
FILE * prn_stream,
int num_copies,
int dots_per_inch,
int features,
const char *page_init
);
#endif