#ifndef gdevbjcl_INCLUDED
# define gdevbjcl_INCLUDED
#include <stdio.h>
#include "stream.h"
#define BJC_OPT_NUL 0x00000001
#define BJC_OPT_LF 0x00000002
#define BJC_OPT_IDENTIFY_CARTRIDGE 0x00000004
#define BJC_OPT_MONOCHROME_SMOOTHING 0x00000008
#define BJC_OPT_EXTENDED_MARGINS 0x00000010
#define BJC_OPT_PAGE_ID 0x00000020
#define BJC_OPT_RESOLUTION_360 0x00000040
#define BJC_OPT_RESOLUTION_300 0x00000080
#define BJC_OPT_RESOLUTION_HALF 0x00000100
#define BJC_OPT_RESOLUTION_QUARTER 0x00000200
#define BJC_OPT_RESOLUTION_2X 0x00000400
#define BJC_OPT_RESOLUTION_2X_1X 0x00000800
#define BJC_OPT_RESOLUTION_4X_2X 0x00001000
#define BJC_OPT_X_Y_RESOLUTION 0x00002000
#define BJC_OPT_MOVE_LINES 0x00004000
#define BJC_OPT_IMAGE_FORMAT 0x00008000
#define BJC_OPT_CONTINUE_IMAGE 0x00010000
#define BJC_OPT_INDEXED_IMAGE 0x00020000
#define BJC_OPT_SET_COLOR_COMPONENT 0x00040000
#define BJC_OPT_50\
(BJC_OPT_NUL | BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE |\
BJC_OPT_EXTENDED_MARGINS | BJC_OPT_PAGE_ID |\
BJC_OPT_RESOLUTION_360 | BJC_OPT_RESOLUTION_HALF |\
BJC_OPT_RESOLUTION_QUARTER | BJC_OPT_RESOLUTION_2X_1X |\
BJC_OPT_X_Y_RESOLUTION | BJC_OPT_MOVE_LINES | BJC_OPT_IMAGE_FORMAT |\
BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_70\
(BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE | BJC_OPT_MONOCHROME_SMOOTHING |\
BJC_OPT_RESOLUTION_360)
#define BJC_OPT_80\
BJC_OPT_50
#define BJC_OPT_210\
(BJC_OPT_IDENTIFY_CARTRIDGE | BJC_OPT_MONOCHROME_SMOOTHING |\
BJC_OPT_EXTENDED_MARGINS |\
BJC_OPT_RESOLUTION_360 |\
BJC_OPT_X_Y_RESOLUTION | BJC_OPT_MOVE_LINES | BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_250\
(BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE | BJC_OPT_MONOCHROME_SMOOTHING |\
BJC_OPT_EXTENDED_MARGINS | BJC_OPT_PAGE_ID |\
BJC_OPT_RESOLUTION_360 | BJC_OPT_RESOLUTION_HALF |\
BJC_OPT_RESOLUTION_QUARTER | BJC_OPT_RESOLUTION_2X_1X |\
BJC_OPT_X_Y_RESOLUTION | BJC_OPT_MOVE_LINES | BJC_OPT_IMAGE_FORMAT |\
BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_610\
(BJC_OPT_LF |\
BJC_OPT_RESOLUTION_360)
#define BJC_OPT_620\
BJC_OPT_610
#define BJC_OPT_4000\
(BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE | BJC_OPT_MONOCHROME_SMOOTHING |\
BJC_OPT_RESOLUTION_360 | BJC_OPT_RESOLUTION_HALF |\
BJC_OPT_RESOLUTION_QUARTER)
#define BJC_OPT_4100\
(BJC_OPT_IDENTIFY_CARTRIDGE |\
BJC_OPT_EXTENDED_MARGINS |\
BJC_OPT_RESOLUTION_360 |\
BJC_OPT_MOVE_LINES | BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_4200\
(BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE |\
BJC_OPT_EXTENDED_MARGINS | BJC_OPT_PAGE_ID |\
BJC_OPT_RESOLUTION_360 |\
BJC_OPT_MOVE_LINES | BJC_OPT_IMAGE_FORMAT | BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_4300\
BJC_OPT_250
#define BJC_OPT_4550\
BJC_OPT_250
#define BJC_OPT_4650\
BJC_OPT_250
#define BJC_OPT_5500\
(BJC_OPT_IDENTIFY_CARTRIDGE | BJC_OPT_MONOCHROME_SMOOTHING |\
BJC_OPT_EXTENDED_MARGINS |\
BJC_OPT_RESOLUTION_360 |\
BJC_OPT_MOVE_LINES | BJC_OPT_CONTINUE_IMAGE)
#define BJC_OPT_7000\
(BJC_OPT_NUL | BJC_OPT_LF |\
BJC_OPT_IDENTIFY_CARTRIDGE |\
BJC_OPT_EXTENDED_MARGINS | BJC_OPT_PAGE_ID |\
BJC_OPT_RESOLUTION_300 | BJC_OPT_RESOLUTION_2X_1X |\
BJC_OPT_RESOLUTION_4X_2X |\
BJC_OPT_MOVE_LINES | BJC_OPT_IMAGE_FORMAT | BJC_OPT_CONTINUE_IMAGE |\
BJC_OPT_INDEXED_IMAGE | BJC_OPT_SET_COLOR_COMPONENT)
#define BJC_ENUMERATE_OPTIONS(m)\
m(50, BJC_OPT_50)\
m(70, BJC_OPT_70)\
m(80, BJC_OPT_80)\
m(210, BJC_OPT_210)\
m(250, BJC_OPT_250)\
m(610, BJC_OPT_610)\
m(620, BJC_OPT_620)\
m(4000, BJC_OPT_4000)\
m(4100, BJC_OPT_4100)\
m(4200, BJC_OPT_4200)\
m(4300, BJC_OPT_4300)\
m(4550, BJC_OPT_4550)\
m(4650, BJC_OPT_4650)\
m(5500, BJC_OPT_5500)\
m(7000, BJC_OPT_7000)
void bjc_put_CR(stream *s);
void bjc_put_FF(stream *s);
void bjc_put_LF(stream *s);
void bjc_put_initial_condition(stream *s);
void bjc_put_initialize(stream *s);
typedef enum {
BJC_PRINT_COLOR_COLOR = 0x0,
BJC_PRINT_COLOR_MONOCHROME = 0x1,
BJC_PRINT_COLOR_MONOCHROME_WITH_SMOOTHING = 0x2
} bjc_print_color_t;
typedef enum {
BJC_PRINT_MEDIA_PLAIN_PAPER = 0x0,
BJC_PRINT_MEDIA_COATED_PAPER = 0x1,
BJC_PRINT_MEDIA_TRANSPARENCY_FILM = 0x2,
BJC_PRINT_MEDIA_BACK_PRINT_FILM = 0x3,
BJC_PRINT_MEDIA_TEXTILE_SHEET = 0x4,
BJC_PRINT_MEDIA_GLOSSY_PAPER = 0x5,
BJC_PRINT_MEDIA_HIGH_GLOSS_FILM = 0x6,
BJC_PRINT_MEDIA_HIGH_RESOLUTION_PAPER = 0x7
} bjc_print_media_t;
typedef enum {
BJC_PRINT_QUALITY_NORMAL = 0x0,
BJC_PRINT_QUALITY_HIGH = 0x1,
BJC_PRINT_QUALITY_DRAFT = 0x2,
BJC_PRINT_QUALITY_COLOR_NON_BLEED = 0x8
} bjc_print_quality_t;
typedef enum {
BJC_BLACK_DENSITY_NORMAL = 0x0,
BJC_BLACK_DENSITY_HIGH = 0x1
} bjc_black_density_t;
void bjc_put_print_method(stream *s, bjc_print_color_t color,
bjc_print_media_t media,
bjc_print_quality_t quality,
bjc_black_density_t density);
typedef enum {
BJC_70_PRINT_COLOR_SHORT_FINE = 0x0,
BJC_70_PRINT_COLOR_SHORT_HQ = 0x3,
BJC_70_PRINT_COLOR_SHORT_ECO = 0x4,
BJC_80_PRINT_COLOR_SHORT_STD = 0x0,
BJC_80_PRINT_COLOR_SHORT_STD_SPECIALTY = 0x1,
BJC_80_PRINT_COLOR_SHORT_HQ_SPECIALTY = 0x2,
BJC_80_PRINT_COLOR_SHORT_HQ = 0x3,
BJC_80_PRINT_COLOR_SHORT_HIGH_SPEED = 0x4,
BJC_210_PRINT_COLOR_SHORT_HQ = 0x0,
BJC_210_PRINT_COLOR_SHORT_FINE = 0x2,
BJC_210_PRINT_COLOR_SHORT_HIGH_SPEED = 0x4,
BJC_5500_PRINT_COLOR_SHORT_COATED = 0x0,
BJC_5500_PRINT_COLOR_SHORT_TRANSPARENCY = 0x1,
BJC_5500_PRINT_COLOR_SHORT_PLAIN = 0x2,
BJC_5500_PRINT_COLOR_SHORT_HQ_NON_BLEED = 0x3,
BJC_5500_PRINT_COLOR_SHORT_HIGH_SPEED = 0x4
} bjc_print_color_short_t;
void bjc_put_print_method_short(stream *s, bjc_print_color_short_t color);
typedef enum {
BJC_70_MEDIA_SUPPLY_MANUAL_1 = 0x0,
BJC_70_MEDIA_SUPPLY_MANUAL_2 = 0x1,
BJC_70_MEDIA_SUPPLY_ASF = 0x4,
BJC_250_MEDIA_SUPPLY_CONTINUOUS_FORM = 0x2,
BJC_250_MEDIA_SUPPLY_ASF_BIN_2 = 0x5,
BJC_250_MEDIA_SUPPLY_AUTO_SWITCH = 0xf,
BJC_4000_MEDIA_SUPPLY_CASSETTE = 0x8,
BJC_80_MEDIA_SUPPLY_ASF_OFFLINE = 0x0,
BJC_80_MEDIA_SUPPLY_ASF_ONLINE = 0x1
} bjc_media_supply_t;
typedef enum {
BJC_MEDIA_TYPE_PLAIN_PAPER = 0x0,
BJC_MEDIA_TYPE_COATED_PAPER = 0x1,
BJC_MEDIA_TYPE_TRANSPARENCY_FILM = 0x2,
BJC_MEDIA_TYPE_BACK_PRINT_FILM = 0x3,
BJC_MEDIA_TYPE_PAPER_WITH_LEAD = 0x4,
BJC_MEDIA_TYPE_TEXTILE_SHEET = 0x5,
BJC_MEDIA_TYPE_GLOSSY_PAPER = 0x6,
BJC_MEDIA_TYPE_HIGH_GLOSS_FILM = 0x7,
BJC_MEDIA_TYPE_ENVELOPE = 0x8,
BJC_MEDIA_TYPE_CARD = 0x9,
BJC_MEDIA_TYPE_HIGH_RESOLUTION_6X0 = 0xa,
BJC_MEDIA_TYPE_HIGH_RESOLUTION = 0xb,
BJC_MEDIA_TYPE_FULL_BLEED = 0xc,
BJC_MEDIA_TYPE_BANNER = 0xd
} bjc_media_type_t;
void bjc_put_media_supply(stream *s, bjc_media_supply_t supply,
bjc_media_type_t type);
typedef enum {
BJC_IDENTIFY_CARTRIDGE_PREPARE = 0x0,
BJC_IDENTIFY_CARTRIDGE_REQUEST = 0x1
} bjc_identify_cartridge_command_t;
void bjc_put_identify_cartridge(stream *s,
bjc_identify_cartridge_command_t command);
void bjc_put_page_margins(stream *s, int length10ths, int lm10ths,
int rm10ths, int indent60ths);
void bjc_put_extended_margins(stream *s, int length60ths, int lm60ths,
int rm60ths, int indent60ths);
void bjc_put_page_id(stream *s, int id);
typedef enum {
BJC_RASTER_COMPRESSION_NONE = 0x0,
BJC_RASTER_COMPRESSION_PACKBITS = 0x1
} bjc_raster_compression_t;
void bjc_put_compression(stream *s, bjc_raster_compression_t compression);
void bjc_put_raster_resolution(stream *s, int x_resolution, int y_resolution);
void bjc_put_raster_skip(stream *s, int skip);
typedef enum {
BJC_CMYK_IMAGE_CYAN = 'C',
BJC_CMYK_IMAGE_MAGENTA = 'M',
BJC_CMYK_IMAGE_YELLOW = 'Y',
BJC_CMYK_IMAGE_BLACK = 'K',
} bjc_cmyk_image_component_t;
void bjc_put_cmyk_image(stream *s, bjc_cmyk_image_component_t component,
const byte *data, int count);
void bjc_put_move_lines(stream *s, int lines);
void bjc_put_move_lines_unit(stream *s, int unit);
typedef enum {
BJC_IMAGE_FORMAT_REGULAR = 0x00,
BJC_IMAGE_FORMAT_INDEXED = 0x80
} bjc_image_format_t;
typedef enum {
BJC_INK_SYSTEM_REGULAR = 0x01,
BJC_INK_SYSTEM_PHOTO = 0x02,
BJC_INK_SYSTEM_REGULAR_DVM = 0x09,
BJC_INK_SYSTEM_PHOTO_DVM = 0x0a
} bjc_ink_system_t;
void bjc_put_image_format(stream *s, int depth,
bjc_image_format_t format,
bjc_ink_system_t ink);
void bjc_put_photo_image(stream *s, bool photo);
void bjc_put_continue_image(stream *s, const byte *data, int count);
void bjc_put_indexed_image(stream *s, int dot_rows, int dot_cols, int layers);
#endif