#include "stdpre.h"
#include "scommon.h"
#include "scanchar.h"
const byte scan_char_array[max_stream_exception + 256] =
{stream_exception_repeat(ctype_exception),
ctype_space,
ctype_name, ctype_name, ctype_name,
ctype_other,
ctype_name, ctype_name, ctype_name, ctype_name,
ctype_space,
ctype_space,
ctype_name,
ctype_space,
ctype_space,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name,
ctype_space,
ctype_name, ctype_name, ctype_name, ctype_name,
ctype_other,
ctype_name, ctype_name,
ctype_other,
ctype_other,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_other,
0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
ctype_name, ctype_name,
ctype_other,
ctype_name,
ctype_other,
ctype_name,
ctype_name,
10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
30, 31, 32, 33, 34, 35,
ctype_other,
ctype_name,
ctype_other,
ctype_name, ctype_name,
ctype_name,
10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
30, 31, 32, 33, 34, 35,
ctype_other,
ctype_name,
ctype_other,
ctype_name, ctype_name,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken, ctype_btoken,
ctype_btoken, ctype_btoken,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name, ctype_name, ctype_name, ctype_name,
ctype_name, ctype_name
};