#ifndef TTCONF_H
#define TTCONF_H
#undef const
#undef HAVE_MMAP
#undef STDC_HEADERS
#define WORDS_BIGENDIAN ARCH_IS_BIG_ENDIAN
#undef HAVE_GETPAGESIZE
#define HAVE_MEMCPY
#undef HAVE_VALLOC
#undef HAVE_FCNTL_H
#undef HAVE_UNISTD_H
#undef HAVE_GETOPT_H
#undef HAVE_CONIO_H
#undef HAVE_PRINT_FUNCTION
#define SIZEOF_INT  (1 << ARCH_LOG2_SIZEOF_INT)
#define SIZEOF_LONG (1 << ARCH_LOG2_SIZEOF_LONG)
#undef HAVE_BASENAME
#endif