(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(cog-rocks-open "rocks:///tmp/foo.rdb")
(List (Concept "A") (Concept "B"))
(Set (Concept "A") (Concept "B"))
(Set (Concept "A") (Concept "B") (Concept "C"))
(Evaluation (Predicate "foo")
(List (Concept "B") (Concept "C") (Concept "oh boy!")))
(store-atomspace)
(cog-atomspace-clear)
(cog-get-all-roots)
(define get-tail (Meet (List (Concept "A") (Variable "tail"))))
(define results-key (Predicate "results"))
(fetch-query get-tail results-key)
(cog-value get-tail results-key)
(cog-get-all-roots)
(List (Concept "A") (Concept "F"))
(store-atomspace)
(cog-extract-recursive! (Concept "F"))
(cog-get-all-roots)
(fetch-query get-tail results-key)
(cog-value get-tail results-key)
(cog-set-value! get-tail results-key #f)
(store-value get-tail results-key)
(fetch-query get-tail results-key)
(cog-value get-tail results-key)
(List (Concept "A") (Concept "G"))
(store-atomspace)
(cog-extract-recursive! (Concept "G"))
(fetch-query get-tail results-key)
(cog-value get-tail results-key)
(define metadata (Predicate "my metadata"))
(fetch-query get-tail results-key metadata #t)
(cog-value get-tail results-key)
(fetch-value get-tail metadata)
(cog-value get-tail metadata)
(cog-value->list (cog-value get-tail metadata))
(strftime "%c" (localtime  (inexact->exact (car
(cog-value->list (cog-value get-tail metadata))))))
(define b-holders (MaximalJoin (Present (Concept "B"))))
(fetch-query b-holders results-key)
(cog-value b-holders results-key)
(cog-get-all-roots)
(define tail-by-tail (Query
(TypedVariable (Variable "tail") (Type 'Concept))
(Present (List (Concept "A") (Variable "tail")))
(OrderedLink (Variable "tail") (Concept "by") (Variable "tail"))
))
(fetch-query tail-by-tail results-key)
(cog-value tail-by-tail results-key)