#! /usr/bin/env -S guile -l ./cogserver-pair.scm --
!#
(use-modules (opencog) (opencog learn))
(define pair-gate (make-gate))
(define observer (make-block-random-pair-observer))
(define (observe-block-pairs TXT)
	(wait-gate pair-gate)
	(observer TXT))
(define (start-pair-submit) #f)
(define (finish-pair-submit) #f)
(load "cogserver.scm")
(display "Fetch all words from database. This may take several minutes.\n")
(load-atoms-of-type 'WordNode)
(load-atoms-of-type 'SentenceNode)
(load-atoms-of-type 'ParseNode)
(open-gate pair-gate)