#! /usr/bin/env -S guile -l ./cogserver.scm --
!#
(use-modules (system repl common))
(use-modules (opencog) (opencog logger))
(use-modules (opencog persist))
(use-modules (opencog matrix))
(use-modules (opencog nlp) (opencog learn))
(use-modules (opencog cogserver))
(use-modules (srfi srfi-1))
(define startup-gate (make-gate))
(define env-prompt (getenv "PROMPT"))
(when (not env-prompt)
	(format #t "Error: Learning pipeline not configured!\n")
	(format #t "Did you forget to source a config file?\n")
	(format #t "Config files are in the `run-config` directory.\n")
	(exit -1))
(define (cog-prompt)
	(let ((level (length (cond
				((fluid-ref *repl-stack*) => cdr)
				(else '())))))
		(if (zero? level)
			(string-append env-prompt "> ")
			(format #f "~A [~A]> " env-prompt level))))
(repl-default-prompt-set! cog-prompt)
(define sns (getenv "STORAGE_NODE"))
(cond
	((string-prefix? "(Rocks" sns) (use-modules (opencog persist-rocks)))
	((string-prefix? "(Mono" sns) (use-modules (opencog persist-mono)))
	((string-prefix? "(Postgres" sns) (use-modules (opencog persist-sql)))
	((string-prefix? "(Cog" sns) (use-modules (opencog persist-cog)))
	(else (throw 'bad-storage-node 'unknown
		(format #f "Unknown storage node type ~A\n" sns))))
(define base-storage-node (eval-string sns))
(define write-buff (WriteBufferProxy "write buffer"))
(cog-set-value! write-buff (*-proxy-parts-*) base-storage-node)
(cog-set-value! write-buff (*-decay-const-*) (Number 600))
(define storage-node (ReadWriteProxy "buffered writer"))
(cog-set-value! storage-node (*-proxy-parts-*)
	(List base-storage-node write-buff))
(cog-open storage-node)
(define frame-tops '())
(when (not (string-prefix? "(Mono" sns))
	(set! frame-tops (load-frames))
	(if (< 1 (length frame-tops))
		(throw 'bad-frameset 'too-many-tops
			(format #f "Found more than one frame top: ~A\n" frame-tops)))
	(when (< 0 (length frame-tops))
		(cog-set-atomspace! (car frame-tops))))
(start-cogserver
	#:port (string->number (getenv "PORT"))
	#:web (string->number (getenv "WEBPORT"))
	#:mcp 0
	#:scmprompt (getenv "PROMPT")
	#:prompt (getenv "OCPROMPT")
	#:logfile (getenv "LOGFILE"))
(when (< 0 (length frame-tops))
	(set-cogserver-atomspace! (cog-atomspace)))
(open-gate startup-gate)
(define (exit-server)
	(block-until-idle)
	(cog-close storage-node)
	(block-until-idle)
	(exit 0))