#! /usr/bin/env -S guile -l ./cogserver-mst.scm --
!#
(use-modules (opencog) (opencog learn))
(use-modules (opencog nlp) (opencog persist) (opencog matrix))
(define mst-gate (make-gate))
(define observer (make-block-mpg-pipe-observer))
(define (observe-block-mpg TXT)
	(wait-gate mst-gate)
	(observer TXT))
(define (start-mst-submit) #f)
(define (finish-mst-submit) #f)
(load "cogserver.scm")
(display "Fetch all words from database. This may take several minutes.\n")
(load-atoms-of-type 'WordNode)
(fetch-atom (SentenceNode "MST"))
(fetch-atom (ParseNode "MST"))
(for-each fetch-atom (cog-get-atoms 'Anchor))
(display "Fetch all word-pairs. This may take well over half-an-hour!\n")
(define pair-obj (make-any-link-api))
(define cnt-obj (add-count-api pair-obj))
(define star-obj (add-pair-stars cnt-obj))
(pair-obj 'fetch-pairs)
(display "Fetch all bonds. This may take a long time as well!\n")
((make-bond-link-api) 'fetch-pairs)
(catch #t
	(lambda ()
		((add-report-api star-obj) 'num-pairs)
		(print-matrix-summary-report star-obj)
		(monitor-parse-rate #t)
		(open-gate mst-gate)
	)
	(lambda (key . args)
		(format #t "Warning! Word pair marginals missing!\n")
		(format #t "MST counting will not work without these!\n")
		(format #t "Run `(batch-pairs star-obj)` to compute them.\n")
		#f))