#! /usr/bin/env -S guile -l ./marginals-mst-shape.scm --
!#
(load "cogserver.scm")
(define pca (make-pseudo-cset-api))
(define csa (add-covering-sections pca))
(define csc (add-count-api csa))
(display "Fetch all sections. This may take a long while!\n")
(csc 'fetch-pairs)
(display "Create cross-sections. This may take a long while!\n")
(csc 'explode-sections)
(define btr (batch-transpose csc))
(btr 'clobber)
(btr 'mmt-marginals)
(print-matrix-summary-report csc)
(barrier storage-node)