#! /usr/bin/env -S guile
!#
(load "cogserver.scm")
(define ala (make-any-link-api))
(define aca (add-count-api ala))
(define asa (add-pair-stars aca))
(define trm (add-trimmer asa))
(batch-pairs asa)
(barrier storage-node)
(trm 'subtotal-trim asa 10 10 4)
(set! ala (make-any-link-api))
(set! aca (add-count-api ala))
(set! asa (add-pair-stars aca))
(batch-all-pair-mi asa)
(barrier storage-node)