#include "e.h"
char	*typesetter = "post";
int	ttype	= DEVPOST;
int	minsize	= 4;
int	dbg;
int	lp[200];
int	ct;
int	used[100];
int	ps;
int	deltaps	= 3;
int	dps_set = 0;
int	gsize	= 10;
int	ft	= '2';
Font	ftstack[10] = { '2', "2" };
Font	*ftp	= ftstack;
int	szstack[10];
int	nszstack = 0;
int	display	= 0;
int	synerr;
double	eht[100];
double	ebase[100];
int	lfont[100];
int	rfont[100];
int	lclass[100];
int	rclass[100];
int	eqnreg;
double	eqnht;
int	lefteq	= '\0';
int	righteq	= '\0';
int	markline = 0;