(Evaluation (stv 1 1)
(Predicate "P")
(Concept "A"))
(Evaluation (stv 1 1)
(Predicate "P")
(Concept "B"))
(Evaluation (stv 1 1)
(Predicate "P")
(Concept "C"))
(Evaluation (stv 1 1)
(Predicate "Q")
(Concept "A"))
(Evaluation (stv 1 1)
(Predicate "Q")
(Concept "B"))
(define bc-induction-target
(Evaluation
(Predicate "Q")
(Concept "C")))