(load-from-path "tests/ure/meta-rules/conditional-full-instantiation-meta-rule.scm")
(load-from-path "tests/ure/rules/fuzzy-conjunction-introduction-rule.scm")
(define rbs (Concept "URE"))
(ure-add-rule rbs conditional-full-instantiation-meta-rule-name)
(ure-add-rule rbs fuzzy-conjunction-introduction-1ary-rule-name)
(ure-add-rule rbs fuzzy-conjunction-introduction-2ary-rule-name)
(ure-add-rule rbs fuzzy-conjunction-introduction-3ary-rule-name)
(ure-add-rule rbs fuzzy-conjunction-introduction-4ary-rule-name)
(ure-add-rule rbs fuzzy-conjunction-introduction-5ary-rule-name)
(ure-set-maximum-iterations rbs 20)
(ure-set-complexity-penalty rbs 0.1)