(define B1 (Concept "B1"))
(define B2 (Concept "B2"))
(define B3 (Concept "B3"))
(define ball (Concept "ball"))
(define green (Concept "green"))
(define red_blue_absorb (Concept "red_blue_absorb"))
(Inheritance (stv 1 1) B1 ball)
(Inheritance (stv 1 1) B2 ball)
(Inheritance (stv 1 1) B3 ball)
(Inheritance (stv 1 1) B1 green)
(Inheritance (stv 1 1) B2 green)
(Inheritance (stv 1 1) B3 red_blue_absorb)
(ImplicationScope (stv 1 1)
(TypedVariable X (Type "ConceptNode"))
(Inheritance X red_blue_absorb)
(Inheritance X green))