#ifndef _LINUX_HDREG_H
#define _LINUX_HDREG_H
#define HD_IRQ 14
#define HD_DATA 0x1f0
#define HD_ERROR 0x1f1
#define HD_NSECTOR 0x1f2
#define HD_SECTOR 0x1f3
#define HD_LCYL 0x1f4
#define HD_HCYL 0x1f5
#define HD_CURRENT 0x1f6
#define HD_STATUS 0x1f7
#define HD_FEATURE HD_ERROR
#define HD_PRECOMP HD_FEATURE
#define HD_COMMAND HD_STATUS
#define HD_CMD 0x3f6
#define HD_ALTSTATUS 0x3f6
#define ERR_STAT 0x01
#define INDEX_STAT 0x02
#define ECC_STAT 0x04
#define DRQ_STAT 0x08
#define SEEK_STAT 0x10
#define WRERR_STAT 0x20
#define READY_STAT 0x40
#define BUSY_STAT 0x80
#define WIN_RESTORE 0x10
#define WIN_READ 0x20
#define WIN_WRITE 0x30
#define WIN_WRITE_VERIFY 0x3C
#define WIN_VERIFY 0x40
#define WIN_FORMAT 0x50
#define WIN_INIT 0x60
#define WIN_SEEK 0x70
#define WIN_DIAGNOSE 0x90
#define WIN_SPECIFY 0x91
#define WIN_SETIDLE1 0xE3
#define WIN_SETIDLE2 0x97
#define WIN_STANDBYNOW1 0xE0
#define WIN_STANDBYNOW2 0x94
#define WIN_SLEEPNOW1 0xE6
#define WIN_SLEEPNOW2 0x99
#define WIN_CHECKPOWERMODE1 0xE5
#define WIN_CHECKPOWERMODE2 0x98
#define WIN_DOORLOCK 0xde
#define WIN_DOORUNLOCK 0xdf
#define WIN_MULTREAD 0xC4
#define WIN_MULTWRITE 0xC5
#define WIN_SETMULT 0xC6
#define WIN_IDENTIFY 0xEC
#define WIN_IDENTIFY_DMA 0xEE
#define WIN_SETFEATURES 0xEF
#define WIN_READDMA 0xc8
#define WIN_WRITEDMA 0xca
#define WIN_READ_BUFFER 0xE4
#define WIN_WRITE_BUFFER 0xE8
#define WIN_SMART 0xb0
#define WIN_PIDENTIFY 0xA1
#define WIN_SRST 0x08
#define WIN_PACKETCMD 0xa0
#define SMART_READ_VALUES 0xd0
#define SMART_READ_THRESHOLDS 0xd1
#define SMART_AUTOSAVE 0xd2
#define SMART_SAVE 0xd3
#define SMART_IMMEDIATE_OFFLINE 0xd4
#define SMART_ENABLE 0xd8
#define SMART_DISABLE 0xd9
#define SMART_STATUS 0xda
#define SMART_AUTO_OFFLINE 0xdb
#define SECURITY_SET_PASSWORD 0xBA
#define SECURITY_UNLOCK 0xBB
#define SECURITY_ERASE_PREPARE 0xBC
#define SECURITY_ERASE_UNIT 0xBD
#define SECURITY_FREEZE_LOCK 0xBE
#define SECURITY_DISABLE_PASSWORD 0xBF
#define MARK_ERR 0x01
#define TRK0_ERR 0x02
#define ABRT_ERR 0x04
#define MCR_ERR 0x08
#define ID_ERR 0x10
#define ECC_ERR 0x40
#define BBD_ERR 0x80
#define ICRC_ERR 0x80
struct hd_geometry {
unsigned char heads;
unsigned char sectors;
unsigned short cylinders;
unsigned long start;
};
#define HDIO_GETGEO 0x0301
#define HDIO_GET_UNMASKINTR 0x0302
#define HDIO_GET_MULTCOUNT 0x0304
#define HDIO_OBSOLETE_IDENTITY 0x0307
#define HDIO_GET_KEEPSETTINGS 0x0308
#define HDIO_GET_32BIT 0x0309
#define HDIO_GET_NOWERR 0x030a
#define HDIO_GET_DMA 0x030b
#define HDIO_GET_NICE 0x030c
#define HDIO_GET_IDENTITY 0x030d
#define HDIO_DRIVE_CMD 0x031f
#define HDIO_SET_MULTCOUNT 0x0321
#define HDIO_SET_UNMASKINTR 0x0322
#define HDIO_SET_KEEPSETTINGS 0x0323
#define HDIO_SET_32BIT 0x0324
#define HDIO_SET_NOWERR 0x0325
#define HDIO_SET_DMA 0x0326
#define HDIO_SET_PIO_MODE 0x0327
#define HDIO_SCAN_HWIF 0x0328
#define HDIO_SET_NICE 0x0329
#define HDIO_UNREGISTER_HWIF 0x032a
struct hd_driveid {
unsigned short config;
unsigned short cyls;
unsigned short reserved2;
unsigned short heads;
unsigned short track_bytes;
unsigned short sector_bytes;
unsigned short sectors;
unsigned short vendor0;
unsigned short vendor1;
unsigned short vendor2;
unsigned char serial_no[20];
unsigned short buf_type;
unsigned short buf_size;
unsigned short ecc_bytes;
unsigned char fw_rev[8];
unsigned char model[40];
unsigned char max_multsect;
unsigned char vendor3;
unsigned short dword_io;
unsigned char vendor4;
unsigned char capability;
unsigned short reserved50;
unsigned char vendor5;
unsigned char tPIO;
unsigned char vendor6;
unsigned char tDMA;
unsigned short field_valid;
unsigned short cur_cyls;
unsigned short cur_heads;
unsigned short cur_sectors;
unsigned short cur_capacity0;
unsigned short cur_capacity1;
unsigned char multsect;
unsigned char multsect_valid;
unsigned int lba_capacity;
unsigned short dma_1word;
unsigned short dma_mword;
unsigned short eide_pio_modes;
unsigned short eide_dma_min;
unsigned short eide_dma_time;
unsigned short eide_pio;
unsigned short eide_pio_iordy;
unsigned short word69;
unsigned short word70;
unsigned short word71;
unsigned short word72;
unsigned short word73;
unsigned short word74;
unsigned short word75;
unsigned short word76;
unsigned short word77;
unsigned short word78;
unsigned short word79;
unsigned short word80;
unsigned short word81;
unsigned short command_sets;
unsigned short word83;
unsigned short word84;
unsigned short word85;
unsigned short word86;
unsigned short word87;
unsigned short dma_ultra;
unsigned short word89;
unsigned short word90;
unsigned short word91;
unsigned short word92;
unsigned short word93;
unsigned short word94;
unsigned short word95;
unsigned short word96;
unsigned short word97;
unsigned short word98;
unsigned short word99;
unsigned short word100;
unsigned short word101;
unsigned short word102;
unsigned short word103;
unsigned short word104;
unsigned short word105;
unsigned short word106;
unsigned short word107;
unsigned short word108;
unsigned short word109;
unsigned short word110;
unsigned short word111;
unsigned short word112;
unsigned short word113;
unsigned short word114;
unsigned short word115;
unsigned short word116;
unsigned short word117;
unsigned short word118;
unsigned short word119;
unsigned short word120;
unsigned short word121;
unsigned short word122;
unsigned short word123;
unsigned short word124;
unsigned short word125;
unsigned short word126;
unsigned short word127;
unsigned short security;
unsigned short reserved[127];
};
#define IDE_NICE_DSC_OVERLAP (0)
#define IDE_NICE_ATAPI_OVERLAP (1)
#define IDE_NICE_0 (2)
#define IDE_NICE_1 (3)
#define IDE_NICE_2 (4)
#ifdef __KERNEL__
#include <linux/config.h>
#ifdef CONFIG_BLK_DEV_HD
void hd_setup(char *, int *);
#endif
#if defined(CONFIG_BLK_DEV_IDE) || defined(CONFIG_BLK_DEV_IDE_MODULE)
int ide_register(int io_port, int ctl_port, int irq);
void ide_unregister(unsigned int);
#endif
#endif
#endif