(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog cogserver))
(use-modules (opencog persist) (opencog persist-cog-simple))
(include "test-utils.scm")
(define uri "cog://localhost:16020")
(start-cogserver #:port 16020)
(define server-space (cog-atomspace))
(cog-set-atomspace! (cog-new-atomspace))
(opencog-test-runner)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define surface-space (cog-new-atomspace mid2-space))
(define (setup-and-store)
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! mid1-space)
(Concept "bar" (ctv 1 0 4))
(cog-set-atomspace! mid2-space)
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 5))
(cog-set-atomspace! surface-space)
(define storage (CogSimpleStorageNode uri))
(cog-open storage)
(store-atom (ListLink (Concept "foo") (Concept "bar")))
(store-atom (Concept "foo"))
(store-atom (Concept "bar"))
(cog-close storage)
(cog-atomspace-clear surface-space)
(cog-atomspace-clear mid2-space)
(cog-atomspace-clear mid1-space)
(cog-atomspace-clear base-space)
)
(define (zap-spaces)
(set! surface-space #f)
(set! mid2-space #f)
(set! mid1-space #f)
(set! base-space #f)
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-deep-link)
(setup-and-store)
(cog-set-atomspace! surface-space)
(define storage (CogSimpleStorageNode uri))
(cog-open storage)
(load-atomspace)
(cog-close storage)
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(test-equal "link-space" mid2-space (cog-atomspace lilly))
(test-equal "foo-space" base-space (cog-atomspace (gar lilly)))
(test-equal "bar-space" mid1-space (cog-atomspace (gdr lilly)))
(test-equal "base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
(test-equal "mid1-tv" 4 (get-cnt (cog-node 'Concept "bar")))
(test-equal "mid2-tv" 5 (get-cnt lilly))
)
(define deep-link "test deep links")
(test-begin deep-link)
(test-deep-link)
(test-end deep-link)
(define (test-fresh-link)
(setup-and-store)
(zap-spaces)
(define new-base (cog-new-atomspace))
(cog-set-atomspace! new-base)
(define storage (CogSimpleStorageNode uri))
(cog-open storage)
(define surface (car (load-frames)))
(cog-set-atomspace! surface)
(load-atomspace)
(cog-close storage)
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(define mid-space (cog-outgoing-atom surface 0))
(test-equal "link-space" surface (cog-atomspace lilly))
(test-equal "foo-space" new-base (cog-atomspace (gar lilly)))
(test-equal "bar-space" mid-space (cog-atomspace (gdr lilly)))
(test-equal "base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
(test-equal "mid1-tv" 4 (get-cnt (cog-node 'Concept "bar")))
(test-equal "mid2-tv" 5 (get-cnt lilly))
)
(define fresh-link "test fresh link restore")
(test-begin fresh-link)
(test-fresh-link)
(test-end fresh-link)
(stop-cogserver)
(opencog-test-end)