(define-module (opencog miner))
(use-modules (opencog miner-config))
(load-extension (string-append opencog-ext-path-miner "libguile-miner") "opencog_miner_init")
(include-from-path "opencog/miner/miner-utils.scm")
(export-miner-utils)