(use-modules (opencog test-runner))
(opencog-test-runner)
(define suite-name "MI-calc-test-any")
(load "setup.scm")
(sql-open "postgres:///ULL_calcMI_any_test")
(define test-str-1 "The first test-sentence.")
(define test-str-2 "The second one")
(test-begin suite-name)
(define cnt-mode "any")
(define word-pair-atoms
	(list
		(make-word-pair "###LEFT-WALL###" "The" cnt-mode 2)
		(make-word-pair "###LEFT-WALL###" "first" cnt-mode 1)
		(make-word-pair "The" "first" cnt-mode 1)
		(make-word-pair "The" "test-sentence." cnt-mode 1)
		(make-word-pair "first" "test-sentence." cnt-mode 1)
		(make-word-pair "###LEFT-WALL###" "second" cnt-mode 1)
		(make-word-pair "The" "second" cnt-mode 1)
		(make-word-pair "The" "one" cnt-mode 1)
		(make-word-pair "second" "one" cnt-mode 1)
	)
)
(comp-mi cnt-mode)
(define MI-list
	(list (- (log2 5) 1) (- (log2 5) 2) (- (log2 5) 2) (- (log2 5) 2) (log2 5)
	(- (log2 5) 2) (- (log2 5) 2) (- (log2 5) 2) (log2 5))
)
(define tolerance 0.000001)
(define check-MI-text "Checking correct MI values 'any'")
(for-each
	(lambda (atom expected-MI)
		(define diff (- (get-MI-value atom) expected-MI))
		(test-assert check-MI-text (< (abs diff) tolerance))
	)
	word-pair-atoms MI-list
)
(sql-close)
(test-end suite-name)