(use-modules (opencog test-runner))
(opencog-test-runner)
(define suite-name "pair-count-tests")
(load "setup.scm") 
(sql-open "postgres:///ULL_tests")
(define test-str-1 "The first test-sentence.")
(define test-str-2 "The second one")
(test-begin suite-name)
(define cnt-mode "clique")
(define word-pair-atoms
	(list
		(make-word-pair "###LEFT-WALL###" "The" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "first" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "test-sentence." cnt-mode 0)
		(make-word-pair "The" "first" cnt-mode 0)
		(make-word-pair "The" "test-sentence." cnt-mode 0)
		(make-word-pair "first" "test-sentence." cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "second" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "one" cnt-mode 0)
		(make-word-pair "The" "second" cnt-mode 0)
		(make-word-pair "The" "one" cnt-mode 0)
		(make-word-pair "second" "one" cnt-mode 0)
	)
)
(define window 2)
(observe-text-mode test-str-1 cnt-mode window)
(observe-text-mode test-str-2 cnt-mode window)
(define counts-list
	(list 2 1 0 1 1 1 1 0 1 1 1)
)
(test-assert "Space-based tokenization" 
	(= (get-counts (list-ref word-pair-atoms 4)) (list-ref counts-list 4)))
(test-assert "LEFT-WALL added to parse" 
	(= (get-counts (list-ref word-pair-atoms 1)) (list-ref counts-list 1)))
(define check-cnts-text "Checking correct counts clique")
(for-each
	(lambda (atom count)
		(test-assert check-cnts-text (= (get-counts atom) count))
		(set-atom-count atom 0)
	)
	word-pair-atoms counts-list
)
(define cnt-mode "clique-dist")
(define window 2)
(observe-text-mode test-str-1 cnt-mode window)
(observe-text-mode test-str-2 cnt-mode window)
(set! counts-list
	(list 4 1 0 2 1 2 1 0 2 1 2)
)
(define check-cnts-text "Checking correct counts clique-dist")
(for-each
	(lambda (atom count)
		(test-assert check-cnts-text (= (get-counts atom) count))
		(set-atom-count atom 0)
	)
	word-pair-atoms counts-list
)
(define cnt-mode "any")
(set! word-pair-atoms
	(list
		(make-word-pair "###LEFT-WALL###" "The" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "first" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "test-sentence." cnt-mode 0)
		(make-word-pair "The" "first" cnt-mode 0)
		(make-word-pair "The" "test-sentence." cnt-mode 0)
		(make-word-pair "first" "test-sentence." cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "second" cnt-mode 0)
		(make-word-pair "###LEFT-WALL###" "one" cnt-mode 0)
		(make-word-pair "The" "second" cnt-mode 0)
		(make-word-pair "The" "one" cnt-mode 0)
		(make-word-pair "second" "one" cnt-mode 0)
	)
)
(set! counts-list
	(list 1 1 1 1 1 1 1 1 1 1 1)
)
(define window 0)
(observe-text-mode test-str-1 cnt-mode window)
(observe-text-mode test-str-2 cnt-mode window)
(define check-cnts-text "Checking minimum counts in 'any' mode")
(for-each
	(lambda (atom count)
		(test-assert check-cnts-text (>= (get-counts atom) count))
		(set-atom-count atom 0)
	)
	word-pair-atoms counts-list
)
(sql-close)
(test-end suite-name)