(use-modules
(opencog)
(opencog nlp)
(opencog persist)
(opencog persist-sql)
(opencog cogserver)
(opencog matrix))
(load-from-path "opencog/nlp/learn/common.scm")
(load "../run-poc/redefine-common.scm")
(load-from-path "opencog/nlp/learn/utilities.scm")
(load-from-path "opencog/nlp/learn/link-pipeline.scm")
(load "../run-poc/redefine-link-pipeline.scm")
(load-from-path "opencog/nlp/learn/singletons.scm")
(load-from-path "opencog/nlp/learn/batch-word-pair.scm")
(load-from-path "opencog/nlp/learn/mst-parser.scm")
(load "../run-poc/redefine-mst-parser.scm")
(load-from-path "opencog/nlp/learn/pseudo-csets.scm")
(load-from-path "opencog/nlp/learn/shape-vec.scm")
(load-from-path "opencog/nlp/learn/summary.scm")
(load-from-path "opencog/nlp/learn/gram-agglo.scm")
(load "../run-poc/compute-mi.scm")
(define (log2 x) (/ (log x) (log 2)))
(define (set-atom-count ATOM value)
(cog-set-tv! ATOM (cog-new-ctv 0 0 value))
(store-atom ATOM)
)
(define (make-word-pair word1 word2 MODE CNT)
(define pare (ListLink (WordNode word1) (WordNode word2)))
(define pair-atom
(if (equal? MODE "any")
(EvaluationLink (LinkGrammarRelationshipNode "ANY") pare)
(EvaluationLink pair-pred pare)
)
)
(set-atom-count pair-atom CNT)
pair-atom
)
(define mi-key (Predicate "*-Mutual Info Key-*"))
(define (get-MI-value PAIR-ATOM)
(cog-value-ref (cog-value PAIR-ATOM mi-key) 1)
)
(define (get-counts PAIR-ATOM)
(cog-value-ref (cog-tv PAIR-ATOM) 2)
)