(use-modules (opencog eva-behavior))
(DefineLink
(DefinedSchema "rightwards")
(ListLink
(Number 1)
(Number -0.5)
(Number 0)
))
(DefineLink
(DefinedSchema "leftwards")
(ListLink
(Number 1)
(Number 0.5)
(Number 0)
))
(DefineLink
(DefinedSchema "upwards")
(ListLink
(Number 1)
(Number 0)
(Number 0.3)
))
(DefineLink
(DefinedSchema "downwards")
(ListLink
(Number 1)
(Number 0)
(Number -0.3)
))
(DefineLink
(DefinedSchema "forwards")
(ListLink
(Number 1)
(Number 0)
(Number 0)
))
(ReferenceLink (WordNode "up")       (DefinedSchema "upwards"))
(ReferenceLink (WordNode "down")     (DefinedSchema "downwards"))
(ReferenceLink (WordNode "right")    (DefinedSchema "rightwards"))
(ReferenceLink (WordNode "left")     (DefinedSchema "leftwards"))
(ReferenceLink (WordNode "forward")  (DefinedSchema "forwards"))
(ReferenceLink (WordNode "ahead")    (DefinedSchema "forwards"))
(InheritanceLink (DefinedSchema "upwards")    (ConceptNode "schema-direction"))
(InheritanceLink (DefinedSchema "downwards")  (ConceptNode "schema-direction"))
(InheritanceLink (DefinedSchema "rightwards") (ConceptNode "schema-direction"))
(InheritanceLink (DefinedSchema "leftwards")  (ConceptNode "schema-direction"))
(InheritanceLink (DefinedSchema "forwards")   (ConceptNode "schema-direction"))
(ReferenceLink (WordNode "look") (DefinedPredicate "Gaze command"))
(ReferenceLink (WordNode "turn") (DefinedPredicate "Look command"))
(InheritanceLink (DefinedPredicate "Gaze command")
(ConceptNode "pred-direction"))
(InheritanceLink (DefinedPredicate "Look command")
(ConceptNode "pred-direction"))
(EvaluationLink
(PredicateNode "turn-action")
(ListLink
(ConceptNode "pred-direction")
(ConceptNode "schema-direction")))
(ReferenceLink (WordNode "up")       (Concept "upward"))
(ReferenceLink (WordNode "down")     (Concept "downward"))
(ReferenceLink (WordNode "right")    (Concept "rightwards"))
(ReferenceLink (WordNode "left")     (Concept "leftwards"))
(ReferenceLink (WordNode "forward")  (Concept "forward"))
(ReferenceLink (WordNode "ahead")    (Concept "forward"))
(Inheritance (Concept "upward")     (Concept "concept-direction"))
(Inheritance (Concept "downward")   (Concept "concept-direction"))
(Inheritance (Concept "rightwards") (Concept "concept-direction"))
(Inheritance (Concept "leftwards")  (Concept "concept-direction"))
(Inheritance (Concept "forward")    (Concept "concept-direction"))
(ReferenceLink (WordNode "look") (AnchorNode "*-gaze-direction-*"))
(ReferenceLink (WordNode "face") (AnchorNode "*-head-direction-*"))
(ReferenceLink (WordNode "turn") (AnchorNode "*-head-direction-*"))
(Inheritance (Anchor "*-gaze-direction-*") (Concept "model-direction"))
(Inheritance (Anchor "*-head-direction-*") (Concept "model-direction"))
(EvaluationLink
(PredicateNode "turn-model")
(ListLink
(ConceptNode "model-direction")
(ConceptNode "concept-direction")))
(ReferenceLink (WordNode "me")       (DefinedSchema "current-speaker"))
(ReferenceLink (WordNode "her")      (DefinedSchema "other-speaker"))
(ReferenceLink (WordNode "him")      (DefinedSchema "other-speaker"))
(ReferenceLink (WordNode "this")     (DefinedSchema "current-salient"))
(ReferenceLink (WordNode "that")     (DefinedSchema "current-salient"))
(ReferenceLink (WordNode "here")     (DefinedSchema "current-salient"))
(ReferenceLink (WordNode "there")    (DefinedSchema "current-salient"))
(Inheritance (DefinedSchema "current-speaker")  (Concept "schema-thing"))
(Inheritance (DefinedSchema "other-speaker")    (Concept "schema-thing"))
(Inheritance (DefinedSchema "current-salient")  (Concept "schema-thing"))
(ReferenceLink (WordNode "look") (DefinedPredicate "Look-at-thing cmd"))
(ReferenceLink (WordNode "turn") (DefinedPredicate "Look-at-thing cmd"))
(ReferenceLink (WordNode "face") (DefinedPredicate "Look-at-thing cmd"))
(Inheritance (DefinedPredicate "Look-at-thing cmd") (Concept "look-at-cmd"))
(EvaluationLink
(PredicateNode "look-at-action")
(ListLink
(ConceptNode "look-at-cmd")
(ConceptNode "schema-thing")))
(DefineLink
(DefinedSchema "afraid")
(ListLink
(Concept "imperative")
(Concept "afraid")
))
(DefineLink
(DefinedSchema "amused")
(ListLink
(Concept "imperative")
(Concept "amused")
))
(DefineLink
(DefinedSchema "bored")
(ListLink
(Concept "imperative")
(Concept "bored")
))
(DefineLink
(DefinedSchema "comprehending")
(ListLink
(Concept "imperative")
(Concept "comprehending")
))
(DefineLink
(DefinedSchema "confused")
(ListLink
(Concept "imperative")
(Concept "confused")
))
(DefineLink
(DefinedSchema "engaged")
(ListLink
(Concept "imperative")
(Concept "engaged")
))
(DefineLink
(DefinedSchema "happy")
(ListLink
(Concept "imperative")
(Concept "happy")
))
(DefineLink
(DefinedSchema "irritated")
(ListLink
(Concept "imperative")
(Concept "irritated")
))
(DefineLink
(DefinedSchema "recoil")
(ListLink
(Concept "imperative")
(Concept "recoil")
))
(DefineLink
(DefinedSchema "sad")
(ListLink
(Concept "imperative")
(Concept "sad")
))
(DefineLink
(DefinedSchema "surprised")
(ListLink
(Concept "imperative")
(Concept "surprised")
))
(DefineLink
(DefinedSchema "worry")
(ListLink
(Concept "imperative")
(Concept "worry")
))
(ReferenceLink (Word "express-action") (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "dramatize") (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "emote")   (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "enact")   (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "express") (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "feign")   (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "impersonate")(DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "mime")    (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "mimic")   (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "portray") (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "pretend") (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "show")    (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "act")     (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "be")      (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "look")    (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "play")    (DefinedPredicate "Show class expression"))
(ReferenceLink (WordNode "smile")  (DefinedSchema "happy"))
(ReferenceLink (WordNode "frown")  (DefinedSchema "sad"))
(ReferenceLink (WordNode "recoil") (DefinedSchema "recoil"))
(ReferenceLink (WordNode "worry")  (DefinedSchema "worry"))
(ReferenceLink (WordNode "afraid")       (DefinedSchema "afraid"))
(ReferenceLink (WordNode "amazed")       (DefinedSchema "surprised"))
(ReferenceLink (WordNode "angered")      (DefinedSchema "irritated"))
(ReferenceLink (WordNode "angry")        (DefinedSchema "irritated"))
(ReferenceLink (WordNode "anguished")    (DefinedSchema "worry"))
(ReferenceLink (WordNode "annoyed")      (DefinedSchema "irritated"))
(ReferenceLink (WordNode "anxious")      (DefinedSchema "worry"))
(ReferenceLink (WordNode "baffled")      (DefinedSchema "confused"))
(ReferenceLink (WordNode "befuddled")    (DefinedSchema "confused"))
(ReferenceLink (WordNode "bitter")       (DefinedSchema "sad"))
(ReferenceLink (WordNode "bored")        (DefinedSchema "bored"))
(ReferenceLink (WordNode "bothered")     (DefinedSchema "irritated"))
(ReferenceLink (WordNode "chagrined")    (DefinedSchema "confused"))
(ReferenceLink (WordNode "cheered")      (DefinedSchema "amused"))
(ReferenceLink (WordNode "cheerful")     (DefinedSchema "happy"))
(ReferenceLink (WordNode "comprehending")(DefinedSchema "comprehending"))
(ReferenceLink (WordNode "comprehensive")(DefinedSchema "comprehending"))
(ReferenceLink (WordNode "concerned")    (DefinedSchema "worry"))
(ReferenceLink (WordNode "confused")     (DefinedSchema "confused"))
(ReferenceLink (WordNode "dazed")        (DefinedSchema "confused"))
(ReferenceLink (WordNode "delighted")    (DefinedSchema "happy"))
(ReferenceLink (WordNode "demoralized")  (DefinedSchema "confused"))
(ReferenceLink (WordNode "discerning")   (DefinedSchema "comprehending"))
(ReferenceLink (WordNode "disgusted")    (DefinedSchema "recoil"))
(ReferenceLink (WordNode "disinterested")(DefinedSchema "bored"))
(ReferenceLink (WordNode "distracted")   (DefinedSchema "confused"))
(ReferenceLink (WordNode "distressed")   (DefinedSchema "worry"))
(ReferenceLink (WordNode "ecstatic")     (DefinedSchema "happy"))
(ReferenceLink (WordNode "elated")       (DefinedSchema "happy"))
(ReferenceLink (WordNode "embarassed")   (DefinedSchema "confused"))
(ReferenceLink (WordNode "engaged")      (DefinedSchema "engaged"))
(ReferenceLink (WordNode "enthusiastic") (DefinedSchema "engaged"))
(ReferenceLink (WordNode "entranced")    (DefinedSchema "engaged"))
(ReferenceLink (WordNode "fatigued")     (DefinedSchema "bored"))
(ReferenceLink (WordNode "fearful")      (DefinedSchema "afraid"))
(ReferenceLink (WordNode "frightened")   (DefinedSchema "afraid"))
(ReferenceLink (WordNode "glad")         (DefinedSchema "happy"))
(ReferenceLink (WordNode "happy")        (DefinedSchema "happy"))
(ReferenceLink (WordNode "heartbroken")  (DefinedSchema "sad"))
(ReferenceLink (WordNode "interested")   (DefinedSchema "engaged"))
(ReferenceLink (WordNode "irked")        (DefinedSchema "irritated"))
(ReferenceLink (WordNode "irritated")    (DefinedSchema "irritated"))
(ReferenceLink (WordNode "joyful")       (DefinedSchema "happy"))
(ReferenceLink (WordNode "joyous")       (DefinedSchema "happy"))
(ReferenceLink (WordNode "knowing")      (DefinedSchema "comprehending"))
(ReferenceLink (WordNode "knowlegable")  (DefinedSchema "comprehending"))
(ReferenceLink (WordNode "meloncholy")   (DefinedSchema "sad"))
(ReferenceLink (WordNode "meloncholic")  (DefinedSchema "sad"))
(ReferenceLink (WordNode "mournful")     (DefinedSchema "sad"))
(ReferenceLink (WordNode "muddled")      (DefinedSchema "confused"))
(ReferenceLink (WordNode "nauseated")    (DefinedSchema "recoil"))
(ReferenceLink (WordNode "nauseous")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "overjoyed")    (DefinedSchema "happy"))
(ReferenceLink (WordNode "perplexed")    (DefinedSchema "confused"))
(ReferenceLink (WordNode "perturbed")    (DefinedSchema "confused"))
(ReferenceLink (WordNode "petrified")    (DefinedSchema "afraid"))
(ReferenceLink (WordNode "pleased")      (DefinedSchema "amused"))
(ReferenceLink (WordNode "provoked")     (DefinedSchema "irritated"))
(ReferenceLink (WordNode "puzzled")      (DefinedSchema "confused"))
(ReferenceLink (WordNode "quesy")        (DefinedSchema "recoil"))
(ReferenceLink (WordNode "relaxed")      (DefinedSchema "amused"))
(ReferenceLink (WordNode "repelled")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "revulsed")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "revolted")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "sad")          (DefinedSchema "sad"))
(ReferenceLink (WordNode "scared")       (DefinedSchema "afraid"))
(ReferenceLink (WordNode "sorrowful")    (DefinedSchema "sad"))
(ReferenceLink (WordNode "sorry")        (DefinedSchema "sad"))
(ReferenceLink (WordNode "startled")     (DefinedSchema "surprised"))
(ReferenceLink (WordNode "surprised")    (DefinedSchema "surprised"))
(ReferenceLink (WordNode "terrorized")   (DefinedSchema "afraid"))
(ReferenceLink (WordNode "thrilled")     (DefinedSchema "happy"))
(ReferenceLink (WordNode "tired")        (DefinedSchema "bored"))
(ReferenceLink (WordNode "troubled")     (DefinedSchema "irritated"))
(ReferenceLink (WordNode "unsettled")    (DefinedSchema "irritated"))
(ReferenceLink (WordNode "upset")        (DefinedSchema "irritated"))
(ReferenceLink (WordNode "wistful")      (DefinedSchema "sad"))
(ReferenceLink (WordNode "worried")      (DefinedSchema "worry"))
(ReferenceLink (WordNode "affection")    (DefinedSchema "engaged"))
(ReferenceLink (WordNode "amazement")    (DefinedSchema "surprised"))
(ReferenceLink (WordNode "anguish")      (DefinedSchema "worry"))
(ReferenceLink (WordNode "antipathy")    (DefinedSchema "recoil"))
(ReferenceLink (WordNode "anxiousness")  (DefinedSchema "worry"))
(ReferenceLink (WordNode "apprehension") (DefinedSchema "worry"))
(ReferenceLink (WordNode "awareness")    (DefinedSchema "comprehending"))
(ReferenceLink (WordNode "bewilderment") (DefinedSchema "confused"))
(ReferenceLink (WordNode "boredom")      (DefinedSchema "bored"))
(ReferenceLink (WordNode "chagrin")      (DefinedSchema "confused"))
(ReferenceLink (WordNode "confusion")    (DefinedSchema "confused"))
(ReferenceLink (WordNode "comprehension")(DefinedSchema "comprehending"))
(ReferenceLink (WordNode "concern")      (DefinedSchema "worry"))
(ReferenceLink (WordNode "delight")      (DefinedSchema "happy"))
(ReferenceLink (WordNode "disgust")      (DefinedSchema "recoil"))
(ReferenceLink (WordNode "dislike")      (DefinedSchema "recoil"))
(ReferenceLink (WordNode "disorientation")(DefinedSchema "confused"))
(ReferenceLink (WordNode "distaste")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "distress")     (DefinedSchema "worry"))
(ReferenceLink (WordNode "doubt")        (DefinedSchema "worry"))
(ReferenceLink (WordNode "doubtful")     (DefinedSchema "worry"))
(ReferenceLink (WordNode "embarassment") (DefinedSchema "confused"))
(ReferenceLink (WordNode "engagement")   (DefinedSchema "engaged"))
(ReferenceLink (WordNode "enjoyment")    (DefinedSchema "happy"))
(ReferenceLink (WordNode "enthusiasm")   (DefinedSchema "engaged"))
(ReferenceLink (WordNode "exhuberance")  (DefinedSchema "happy"))
(ReferenceLink (WordNode "euphoria")     (DefinedSchema "happy"))
(ReferenceLink (WordNode "fear")         (DefinedSchema "afraid"))
(ReferenceLink (WordNode "fearfulness")  (DefinedSchema "afraid"))
(ReferenceLink (WordNode "fright")       (DefinedSchema "afraid"))
(ReferenceLink (WordNode "glee")         (DefinedSchema "happy"))
(ReferenceLink (WordNode "greif")        (DefinedSchema "sad"))
(ReferenceLink (WordNode "happiness")    (DefinedSchema "happy"))
(ReferenceLink (WordNode "hatred")       (DefinedSchema "recoil"))
(ReferenceLink (WordNode "heartache")    (DefinedSchema "sad"))
(ReferenceLink (WordNode "heartbreak")   (DefinedSchema "sad"))
(ReferenceLink (WordNode "hopelessness") (DefinedSchema "sad"))
(ReferenceLink (WordNode "intelligence") (DefinedSchema "comprehending"))
(ReferenceLink (WordNode "interest")     (DefinedSchema "engaged"))
(ReferenceLink (WordNode "irritation")   (DefinedSchema "irritated"))
(ReferenceLink (WordNode "jubilation")   (DefinedSchema "happy"))
(ReferenceLink (WordNode "loathing")     (DefinedSchema "recoil"))
(ReferenceLink (WordNode "meloncholy")   (DefinedSchema "sad"))
(ReferenceLink (WordNode "mournfulness") (DefinedSchema "sad"))
(ReferenceLink (WordNode "passion")      (DefinedSchema "engaged"))
(ReferenceLink (WordNode "perplexity")   (DefinedSchema "confused"))
(ReferenceLink (WordNode "puzzlement")   (DefinedSchema "confused"))
(ReferenceLink (WordNode "revulsion")    (DefinedSchema "recoil"))
(ReferenceLink (WordNode "sadness")      (DefinedSchema "sad"))
(ReferenceLink (WordNode "sorrow")       (DefinedSchema "sad"))
(ReferenceLink (WordNode "surprise")     (DefinedSchema "surprised"))
(ReferenceLink (WordNode "uneasiness")   (DefinedSchema "worry"))
(ReferenceLink (WordNode "worriment")    (DefinedSchema "worry"))
(ReferenceLink (WordNode "worry")        (DefinedSchema "worry"))
(InheritanceLink (DefinedPredicate "Show class expression")
(ConceptNode "pred-express"))
(InheritanceLink (DefinedSchema "afraid")    (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "amused")    (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "bored")     (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "comprehending") (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "confused")  (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "engaged")   (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "happy")     (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "irritated") (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "recoil")    (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "sad")       (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "surprised") (ConceptNode "schema-express"))
(InheritanceLink (DefinedSchema "worry")     (ConceptNode "schema-express"))
(EvaluationLink
(PredicateNode "express-action")
(ListLink
(ConceptNode "pred-express")
(ConceptNode "schema-express")))
(Reference (Word "express") (Anchor "*-facial-expression-*"))
(Inheritance (Anchor "*-facial-expression-*") (Concept "model-expression"))
(EvaluationLink
(PredicateNode "express-model")
(ListLink
(ConceptNode "model-expression")
(ConceptNode "schema-express")))
(DefineLink
(DefinedSchema "amused-gest")
(ListLink
(Concept "imperative")
(Concept "amused")
))
(DefineLink
(DefinedSchema "blink")
(ListLink
(Concept "imperative")
(Concept "blink")
))
(DefineLink
(DefinedSchema "nod-1")
(ListLink
(Concept "imperative")
(Concept "nod-1")
))
(DefineLink
(DefinedSchema "shake-2")
(ListLink
(Concept "imperative")
(Concept "shake-2")
))
(DefineLink
(DefinedSchema "thoughtful")
(ListLink
(Concept "imperative")
(Concept "thoughtful")
))
(DefineLink
(DefinedSchema "yawn-1")
(ListLink
(Concept "imperative")
(Concept "yawn-1")
))
(ReferenceLink (WordNode "amused")     (DefinedSchema "amused-gest"))
(ReferenceLink (WordNode "amusement")  (DefinedSchema "amused-gest"))
(ReferenceLink (WordNode "bob")        (DefinedSchema "nod-1"))
(ReferenceLink (WordNode "blink")      (DefinedSchema "blink"))
(ReferenceLink (WordNode "charmed")    (DefinedSchema "amused-gest"))
(ReferenceLink (WordNode "nod")        (DefinedSchema "nod-1"))
(ReferenceLink (WordNode "shake")      (DefinedSchema "shake-2"))
(ReferenceLink (WordNode "thinking")   (DefinedSchema "thoughtful"))
(ReferenceLink (WordNode "thought")    (DefinedSchema "thoughtful"))
(ReferenceLink (WordNode "thoughtful") (DefinedSchema "thoughtful"))
(ReferenceLink (WordNode "thoughtfulness") (DefinedSchema "thoughtful"))
(ReferenceLink (WordNode "yawn")       (DefinedSchema "yawn-1"))
(ReferenceLink (Word "gesture-action") (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "act")            (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "be")             (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "look")           (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "dramatize")   (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "emote")       (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "enact")       (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "express")     (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "feign")       (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "impersonate") (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "mime")        (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "mimic")       (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "portray")     (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "pretend")     (DefinedPredicate "Show class gesture"))
(ReferenceLink (Word "show")        (DefinedPredicate "Show class gesture"))
(InheritanceLink (DefinedPredicate "Show class gesture")
(ConceptNode "pred-gesture"))
(InheritanceLink (DefinedSchema "amused-gest")(Concept "schema-gesture"))
(InheritanceLink (DefinedSchema "blink")      (Concept "schema-gesture"))
(InheritanceLink (DefinedSchema "nod-1")      (Concept "schema-gesture"))
(InheritanceLink (DefinedSchema "shake-2")    (Concept "schema-gesture"))
(InheritanceLink (DefinedSchema "thoughtful") (Concept "schema-gesture"))
(InheritanceLink (DefinedSchema "yawn-1")     (Concept "schema-gesture"))
(EvaluationLink
(Predicate "gesture-action")
(ListLink
(Concept "pred-gesture")
(Concept "schema-gesture")))
(Define
(DefinedSchema "reasoning-demo")
(List (Concept "reasoning-demo")))
(Define
(DefinedSchema "philosophy-demo")
(List (Concept "philosophy-demo")))
(Define
(DefinedSchema "saliency-demo")
(List (Concept "saliency-demo")))
(Reference (Word "show") (DefinedPredicate "Do show demo"))
(Reference (Word "reasoning") (DefinedSchema "reasoning-demo"))
(Reference (Word "philosophy") (DefinedSchema "philosophy-demo"))
(Reference (Word "saliency") (DefinedSchema "saliency-demo"))
(Inheritance (DefinedPredicate "Do show demo") (Concept "pred-demo"))
(Inheritance (DefinedSchema "reasoning-demo") (Concept "schema-demo"))
(Inheritance (DefinedSchema "philosophy-demo") (Concept "schema-demo"))
(Inheritance (DefinedSchema "saliency-demo") (Concept "schema-demo"))
(Evaluation
(Predicate "demo-action")
(List
(Concept "pred-demo")
(Concept "schema-demo")))