(use-modules (opencog))
(use-modules (opencog nlp))
(use-modules (opencog nlp chatbot))
(nlp-parse "I am looking to the left")
(nlp-parse "I am looking to the right")
(nlp-parse "I am looking up")
(nlp-parse "I am looking upward")
(nlp-parse "I am looking downward")
(nlp-parse "I am looking leftwards")
(nlp-parse "I am looking rightwards")
(nlp-parse "I am looking forward")
(nlp-parse "I am looking at you")
(nlp-parse "I am smiling")
(nlp-parse "I am frowning")
(nlp-parse "I am not doing anything")