(use-modules (ice-9 readline))
(activate-readline)
(use-modules (opencog) (opencog cogserver))
(use-modules (opencog nlp))
(use-modules (opencog nlp chatbot))
(use-modules (opencog nlp chatbot-eva))
(use-modules (opencog eva-behavior))
(start-cogserver "../../lib/opencog-chatbot.conf")
(use-modules (opencog nlp relex2logic))
*unspecified*