(use-modules (opencog))
(use-modules (opencog exec))
(use-modules (opencog test-runner))
(if (resolve-module (list 'opencog 'persist) #:ensure #f)
	#t
	(add-to-load-path "../../../build/opencog/scm"))
(format #t "Load path is: ~A\n" %load-path)
(use-modules (opencog persist))
(opencog-test-runner)
(define tname "proxy-node")
(test-begin tname)
(define parts (Predicate "*-proxy-parts-*"))
(define foo (WriteThruProxy "foo"))
(define caught #f)
(catch 'C++-EXCEPTION
	(lambda ()
		(cog-set-value! foo parts (Concept "bar")))
	(lambda (key funcname msg)
		(format #t "Yes, we got the exception as expected\n")
		(set! caught #t)))
(test-assert "Failed to catch exception" caught)
(define wnull (WriteThruProxy "wnull"))
(cog-set-value! wnull parts (NullProxy "bar"))
(cog-open wnull)
(store-atom (Concept "boffo"))
(cog-close wnull)
(set! caught #f)
(catch 'C++-EXCEPTION (lambda () (store-atom (Concept "boffo")))
	(lambda (key funcname msg)
		(format #t "Yes, we got the exception as expected\n")
		(set! caught #t)))
(test-assert "Failed to catch exception" caught)
(define wmulti (WriteThruProxy "wmulti"))
(cog-set-value! wmulti parts
	(List
		(NullProxy "foo")
		(NullProxy "bar")
		(NullProxy "baz")))
(cog-open wmulti)
(store-atom (Concept "boffo"))
(cog-close wmulti)
(set! caught #f)
(catch 'C++-EXCEPTION (lambda () (store-atom (Concept "boffo")))
	(lambda (key funcname msg)
		(format #t "Yes, we got the exception as expected\n")
		(set! caught #t)))
(test-assert "Failed to catch exception" caught)
(define rnull (ReadThruProxy "wnull"))
(cog-set-value! rnull parts (NullProxy "bar"))
(cog-open rnull)
(fetch-atom (Concept "b1"))
(fetch-atom (Concept "b2"))
(fetch-atom (Concept "b3"))
(fetch-atom (Concept "b4"))
(cog-close rnull)
(set! caught #f)
(catch 'C++-EXCEPTION (lambda () (fetch-atom (Concept "boffo")))
	(lambda (key funcname msg)
		(format #t "Yes, we got the exception as expected\n")
		(set! caught #t)))
(test-assert "Failed to catch exception" caught)
(define rmulti (ReadThruProxy "wmulti"))
(cog-set-value! rmulti parts
	(List
		(NullProxy "foo")
		(NullProxy "bar")
		(NullProxy "baz")))
(cog-open rmulti)
(fetch-atom (Concept "b1"))
(fetch-atom (Concept "b2"))
(fetch-atom (Concept "b3"))
(fetch-atom (Concept "b4"))
(fetch-atom (Concept "b5"))
(fetch-atom (Concept "b6"))
(cog-close rmulti)
(set! caught #f)
(catch 'C++-EXCEPTION (lambda () (fetch-atom (Concept "boffo")))
	(lambda (key funcname msg)
		(format #t "Yes, we got the exception as expected\n")
		(set! caught #t)))
(test-assert "Failed to catch exception" caught)
(test-end tname)
(opencog-test-end)