(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog exec))
(define k (Predicate "key"))
(define a (Concept "my atom"))
(cog-set-value! a k (FloatValue 1 2 3))
(define vo (FloatValueOf a k))
(define tym (Times (Plus vo (Number 6 6 6)) (Number 2)))
(define b (Concept "other atom"))
(cog-set-value! b k (RandomStream 24))
(define sixes (make-list 24 6))
(define tymb (Times (Number 2) (Plus (FloatValueOf b k) (Number sixes)) ))