(define als (add-pair-stars pair-obj))
(define pfrq (add-pair-freq-api als))
(define ala (make-any-link-api))
(define all-hanprs (ala 'all-pairs))
(define alp (add-loop-api als))
(define (noop x) x)
(define all-hanprs (alp 'map-pair noop))
(define (score-and-rank SCORE-FN WORD-LIST)
(sort
(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST)
(lambda (a b) (> (car a) (car b)))))
(define (score SCORE-FN WORD-LIST)
(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST))
(define (hanpr-mi HANPR) (pfrq 'pair-fmi HANPR))
(define scored-hanpr-mi (score hanpr-mi all-hanprs))
(define binned-hanpr-mi (bin-count-simple scored-hanpr-mi 400))
(let ((outport (open-file "/tmp/binned-hanpr-mi.dat" "w")))
(print-bincounts-tsv binned-hanpr-mi outport)
(close outport))