(use-modules (opencog) (opencog persist) (opencog persist-file))
(use-modules (opencog test-runner))
(set! *random-state* (random-state-from-platform))
(define fname (format #f "/tmp/opencog-test-~D.scm" (random 1000000000)))
(format #t "Using file ~A\n" fname)
(opencog-test-runner)
(define tname "store_load_file")
(test-begin tname)
(define wa (Concept "foo"))
(cog-set-value! wa (Predicate "num") (FloatValue 1 2 3))
(cog-set-value! wa (Predicate "str") (StringValue "p" "q" "r"))
(define wli (Link (Concept "foo") (Concept "bar")))
(cog-set-value! wli (Predicate "num") (FloatValue 4 5 6))
(cog-set-value! wli (Predicate "str") (StringValue "x" "y" "z"))
(define wfsn (FileStorageNode fname))
(cog-open wfsn)
(store-atom wa wfsn)
(cog-set-value! wa (Predicate "num") (FloatValue 11 22 33))
(store-value wa (Predicate "num") wfsn)
(store-value wa (Predicate "num") wfsn)
(store-value wa (Predicate "num") wfsn)
(barrier wfsn)
(store-atomspace wfsn)
(cog-close wfsn)
(cog-atomspace-clear)
(define rfsn (FileStorageNode fname))
(cog-open rfsn)
(load-atomspace rfsn)
(cog-close rfsn)
(cog-prt-atomspace)
(define ra (Concept "foo"))
(test-assert "Concept Keys" (equal? 2 (length (cog-keys ra))))
(test-assert "Concept Num"
(equal? (cog-value ra (Predicate "num")) (FloatValue 11 22 33)))
(test-assert "Concept Str"
(equal? (cog-value ra (Predicate "str")) (StringValue "p" "q" "r")))
(define rli (Link (Concept "foo") (Concept "bar")))
(test-assert "List Keys" (equal? 2 (length (cog-keys rli))))
(test-assert "List Num"
(equal? (cog-value rli (Predicate "num")) (FloatValue 4 5 6)))
(test-assert "List Str"
(equal? (cog-value rli (Predicate "str")) (StringValue "x" "y" "z")))
(delete-file fname)
(test-end tname)
(opencog-test-end)