(define-module (opencog octomap))
(use-modules (srfi srfi-1) (opencog) (opencog exec))
(use-modules (opencog sp-config))
(load-extension (string-append opencog-ext-path-point-memory "liboctomap-types") "octomap_types_init")
(load "spacetime/octomap/octomap_types.scm")