(use-modules (opencog) (opencog exec))
(use-modules (opencog metta))
(MeTTa "(= (fact $x) (if (< $x 2) 1 (* $x (fact (- $x 1)))))")
(cog-execute! (MeTTa "(fact 5)"))
(MeTTa "(= foo 6)")
(cog-execute! (MeTTa "(fact foo)"))