(use-modules (opencog) (opencog persist) (opencog persist-sql))
(use-modules (opencog cogserver))
(use-modules (opencog nlp))
(use-modules (system repl common))
(use-modules (system repl server))
(use-modules (opencog logger))
(use-modules (opencog matrix))
(add-to-load-path ".")
(load "utilities.scm")
(define database-uri (get-connection-uri))
(define language (get-lang))
(repl-default-option-set! 'prompt (string-append "scheme@("
language "-mst)> "))
(start-cogserver (string-append "config/opencog-mst-" language ".conf"))
(sql-open database-uri)
(display "Fetching all words from database. This may take a few minutes.\n")
(fetch-all-words)
(display "Fetching all word-pairs. This may take a few minutes.\n")
(define pair-obj (make-any-link-api))
(define star-obj (add-pair-stars pair-obj))
(pair-obj 'fetch-pairs)
(sql-stats)
(sql-clear-cache)
(sql-clear-stats)
(display "Done fetching pairs.\n")