(use-modules (opencog) (opencog persist) (opencog persist-sql))
(use-modules (opencog cogserver))
(use-modules (opencog nlp))
(use-modules (system repl common))
(use-modules (system repl server))
(add-to-load-path ".")
(load "utilities.scm")
(define database-uri (get-connection-uri))
(define language (get-lang))
(repl-default-option-set! 'prompt (string-append "scheme@("
language "-pairs)> "))
(start-cogserver (string-append "config/opencog-" language ".conf"))
(sql-open database-uri)
(display "Opened database: ")
(display database-uri)
(display "\n")
(fetch-all-words)