(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(cog-rocks-open "rocks:///tmp/foo.rdb")
(cog-set-value! (Concept "a") (Predicate "flo") (FloatValue 1 2 3))
(cog-set-value! (Concept "a") (Predicate "blo") (FloatValue 4 5 6))
(cog-keys->alist (Concept "a"))
(store-atom (Concept "a"))
(cog-extract! (Concept "a"))
(cog-get-all-roots)
(fetch-value (Concept "a") (Predicate "blo"))
(cog-keys->alist (Concept "a"))
(cog-set-value! (Concept "a") (Predicate "blo") (StringValue "a" "b" "c"))
(fetch-atom (Concept "a"))
(cog-keys->alist (Concept "a"))