(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(define foo-store (RocksStorageNode "rocks:///tmp/foo.rdb"))
(define bar-store (RocksStorageNode "rocks:///tmp/bar.rdb"))
(cog-open foo-store)
(cog-open bar-store)
(cog-set-value! (Concept "a") (Predicate "a-key") (FloatValue 1 2 3))
(cog-set-value! (Concept "b") (Predicate "b-key") (FloatValue 4 5 6))
(store-atom (Concept "a") foo-store)
(store-atom (Concept "b") bar-store)
(cog-close foo-store)
(cog-close bar-store)
(clear)
(define foo-store (RocksStorageNode "rocks:///tmp/foo.rdb"))
(cog-open foo-store)
(load-atomspace foo-store)
(cog-get-all-roots)
(define bar-store (RocksStorageNode "rocks:///tmp/bar.rdb"))
(cog-open bar-store)
(load-atomspace bar-store)
(cog-get-all-roots)
(cog-close foo-store)
(cog-close bar-store)