(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog persist) (opencog persist-rocks))
(define (setup-and-store)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define mid3-space (cog-new-atomspace mid2-space))
(define surface-space (cog-new-atomspace mid3-space))
(define storage (RocksStorageNode "rocks:///tmp/frame-demo"))
(cog-open storage)
(store-frames surface-space)
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(store-atom (Concept "foo"))
(cog-set-atomspace! mid1-space)
(Concept "bar" (ctv 1 0 4))
(store-atom (Concept "bar"))
(cog-set-atomspace! mid2-space)
(store-atom (ListLink (Concept "foo") (Concept "bar") (ctv 1 0 5)))
(cog-set-atomspace! mid3-space)
(Concept "foo" (ctv 6 22 42))
(store-atom (Concept "foo"))
(cog-close storage)
(cog-atomspace-clear surface-space)
(cog-atomspace-clear mid3-space)
(cog-atomspace-clear mid2-space)
(cog-atomspace-clear mid1-space)
(cog-atomspace-clear base-space)
)
(setup-and-store)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/frame-demo"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(newline)
(format #t "The top space is:\n~A\n\n" top-space)
(define surface-space top-space)
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! mid2-space)
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(format #t "The list link is: ~A\n" lilly)
(define (check-spaces MSG A B)
(format #t "For ~A, expecting: ~A -- Got: ~A\n\n"
MSG (cog-name A) (cog-name B)))
(check-spaces "link-space" mid2-space (cog-atomspace lilly))
(check-spaces "foo-space" base-space (cog-atomspace (gar lilly)))
(check-spaces "bar-space" mid1-space (cog-atomspace (gdr lilly)))
(cog-set-atomspace! surface-space)
(define top-lilly (ListLink (Concept "foo") (Concept "bar")))
(format #t "The top-most list link is:\n~A\n" lilly)
(define (check-equal MSG A B)
(format #t "For ~A, expecting: ~A-- Got: ~A\n" MSG A B))
(cog-set-atomspace! base-space)
(check-equal "foo-tv in base" (ctv 1 0 3) (cog-tv (Concept "foo")))
(cog-set-atomspace! surface-space)
(check-equal "foo-tv on top" (ctv 6 22 42) (cog-tv (Concept "foo")))
(check-equal "bar-tv" (ctv 1 0 4) (cog-tv (Concept "bar")))
(check-equal "lilly-tv" (ctv 1 0 5) (cog-tv lilly))
(check-equal "top-tv" (ctv 1 0 5) (cog-tv top-lilly))
(exit)