(use-modules (opencog))
(define tv (SimpleTruthValue 0.1 0.2))
(cog-value->list tv)
(cog-value-ref tv 0)
(cog-value-ref tv 1)
(define a (Concept "aaa"))
(cog-set-tv! a tv)
(cog-tv a)
(cog-set-tv! (Concept "bbb") (CountTruthValue 1.0e-6 -19.9316 55))