#ifndef _KERN_CONSTANTS_H_
#define _KERN_CONSTANTS_H_
#define LOCK_INFO_MAX_ENTRIES       (1024 * 32)
#define LOCK_INFO_HASH_BUCKETS      1024
#define LOCK_DEFAULT_WAIT_TIME      100
#define LOCK_MAX_HELD               1000
#define LOCK_SPIN_LIMIT             1000000
#define IPC_REPLY_SIZE_DEFAULT      8192
#define IPC_STAT_COUNT_SIZE         512
#define IPC_CALL_STATS_MASK         0x7fff
#define MACH_EXCEPTION_BASE_ID      2400
#define MACH_EXCEPTION_REPLY_OFFSET 100
#define THREAD_STATE_MAX_SIZE       150
#define MICROSECONDS_PER_MILLISEC   1000
#define NANOSECONDS_PER_MILLISEC    1000000
#define MICROSECONDS_PER_SECOND     1000000
#define NANOSECONDS_PER_SECOND      1000000000
#define PERF_PERCENTAGE_SCALE       100
#define PERF_MIN_SAMPLES_FOR_REGRESSION  10
#define PERF_DEFAULT_PROFILE_INTERVAL_MS 100
#define SCHED_WAIT_HASH_SIZE        1031
#define SCHED_CPU_USAGE_RESET_TICKS 30
#define CONSOLE_TIMESTAMP_WIDTH     12
#define PRINTF_MAX_PRECISION        0x7fffffff
#endif