#ifndef _KERN_COUNTERS_
#define _KERN_COUNTERS_
#define counter_always(code) code
#if MACH_COUNTERS
#define counter(code) counter_always(code)
#else
#define counter(code)
#endif
typedef unsigned int mach_counter_t;
#if MACH_COUNTERS
extern mach_counter_t c_thread_invoke_hits;
extern mach_counter_t c_thread_invoke_misses;
extern mach_counter_t c_thread_invoke_csw;
extern mach_counter_t c_thread_handoff_hits;
extern mach_counter_t c_thread_handoff_misses;
extern mach_counter_t c_threads_current;
extern mach_counter_t c_threads_max;
extern mach_counter_t c_threads_min;
extern mach_counter_t c_threads_total;
extern mach_counter_t c_stacks_current;
extern mach_counter_t c_stacks_max;
extern mach_counter_t c_stacks_min;
extern mach_counter_t c_stacks_total;
extern mach_counter_t c_stack_alloc_hits;
extern mach_counter_t c_stack_alloc_misses;
extern mach_counter_t c_stack_alloc_max;
extern mach_counter_t c_clock_ticks;
extern mach_counter_t c_ipc_mqueue_send_block;
extern mach_counter_t c_ipc_mqueue_receive_block_user;
extern mach_counter_t c_ipc_mqueue_receive_block_kernel;
extern mach_counter_t c_mach_msg_trap_block_fast;
extern mach_counter_t c_mach_msg_trap_block_slow;
extern mach_counter_t c_mach_msg_trap_block_exc;
extern mach_counter_t c_exception_raise_block;
extern mach_counter_t c_swtch_block;
extern mach_counter_t c_swtch_pri_block;
extern mach_counter_t c_thread_switch_block;
extern mach_counter_t c_thread_switch_handoff;
extern mach_counter_t c_ast_taken_block;
extern mach_counter_t c_thread_halt_self_block;
extern mach_counter_t c_vm_fault_page_block_busy_user;
extern mach_counter_t c_vm_fault_page_block_busy_kernel;
extern mach_counter_t c_vm_fault_page_block_backoff_user;
extern mach_counter_t c_vm_fault_page_block_backoff_kernel;
extern mach_counter_t c_vm_page_wait_block_user;
extern mach_counter_t c_vm_page_wait_block_kernel;
extern mach_counter_t c_vm_pageout_block;
extern mach_counter_t c_vm_pageout_scan_block;
extern mach_counter_t c_idle_thread_block;
extern mach_counter_t c_idle_thread_handoff;
extern mach_counter_t c_sched_thread_block;
extern mach_counter_t c_io_done_thread_block;
extern mach_counter_t c_net_thread_block;
extern mach_counter_t c_reaper_thread_block;
extern mach_counter_t c_swapin_thread_block;
extern mach_counter_t c_action_thread_block;
#endif
#endif