#include <mach/port.h>
#include <mach/kern_return.h>
#include <kern/debug.h>
#include <kern/syscall_sw.h>
#include <mach/mach_traps.h>
#include <mach/message.h>
#include <kern/syscall_subr.h>
#include <kern/ipc_mig.h>
#include <kern/eventcount.h>
#include <ipc/mach_port.server.h>
boolean_t kern_invalid_debug = FALSE;
static mach_port_name_t	null_port(void)
{
if (kern_invalid_debug) SoftDebugger("null_port mach trap");
return(MACH_PORT_NULL);
}
static kern_return_t	kern_invalid(void)
{
if (kern_invalid_debug) SoftDebugger("kern_invalid mach trap");
return(KERN_INVALID_ARGUMENT);
}
mach_trap_t	mach_trap_table[] = {
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP_STACK(evc_wait, 1),
MACH_TRAP_STACK(evc_wait_clear, 1),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP_STACK(mach_msg_trap, 7),
MACH_TRAP(mach_reply_port, 0),
MACH_TRAP(mach_thread_self, 0),
MACH_TRAP(mach_task_self, 0),
MACH_TRAP(mach_host_self, 0),
#ifdef MACH_KDB
MACH_TRAP_STACK(mach_print, 1),
#else
MACH_TRAP_STACK(kern_invalid, 0),
#endif
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(syscall_device_writev_request, 6),
MACH_TRAP(syscall_device_write_request, 6),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(null_port, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP_STACK(swtch_pri, 1),
MACH_TRAP_STACK(swtch, 0),
MACH_TRAP_STACK(thread_switch, 3),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(syscall_vm_map, 11),
MACH_TRAP(syscall_vm_allocate, 4),
MACH_TRAP(syscall_vm_deallocate, 3),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(syscall_task_create, 3),
MACH_TRAP(syscall_task_terminate, 1),
MACH_TRAP(syscall_task_suspend, 1),
MACH_TRAP(syscall_task_set_special_port, 3),
MACH_TRAP(syscall_mach_port_allocate, 3),
MACH_TRAP(syscall_mach_port_deallocate, 2),
MACH_TRAP(syscall_mach_port_insert_right, 4),
MACH_TRAP(syscall_mach_port_allocate_name, 3),
MACH_TRAP(syscall_thread_depress_abort, 1),
MACH_TRAP(thread_set_self_state, 3),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
MACH_TRAP(kern_invalid, 0),
};
int	mach_trap_count = (sizeof(mach_trap_table) / sizeof(mach_trap_table[0]));