#pragma once
#include "CoreMinimal.h"
constexpr int32 CUBISM_EXECUTION_ORDER_MOTION = 100;
constexpr int32 CUBISM_EXECUTION_ORDER_RAYCAST = 110;
constexpr int32 CUBISM_EXECUTION_ORDER_POSE = 200;
constexpr int32 CUBISM_EXECUTION_ORDER_EXPRESSION = 300;
constexpr int32 CUBISM_EXECUTION_ORDER_EYEBLINK = 400;
constexpr int32 CUBISM_EXECUTION_ORDER_LIPSYNC = 500;
constexpr int32 CUBISM_EXECUTION_ORDER_PHYSICS = 600;
constexpr int32 CUBISM_EXECUTION_ORDER_MODEL = 900;
constexpr int32 CUBISM_EXECUTION_ORDER_RENDERER = 1000;