(use-modules (opencog) (opencog exec))
(Inheritance (Concept "reds basket")        (Concept "basket"))
(Inheritance (Concept "another red basket") (Concept "basket"))
(Inheritance (Concept "reds&greens basket") (Concept "basket"))
(Inheritance (Concept "yellows basket")     (Concept "basket"))
(Member (Concept "red ball")      (Concept "reds basket"))
(Member (Concept "red ball too")  (Concept "reds basket"))
(Member (Concept "red ball also") (Concept "reds basket"))
(Member (Concept "a red ball")    (Concept "another red basket"))
(Member (Concept "b red ball")    (Concept "another red basket"))
(Member (Concept "red ball also") (Concept "another red basket"))
(Member (Concept "red ball")      (Concept "reds&greens basket"))
(Member (Concept "red ball too")  (Concept "reds&greens basket"))
(Member (Concept "green ball")    (Concept "reds&greens basket"))
(Member (Concept "yellow ball")   (Concept "yellows basket"))
(Member (Concept "ochre ball")    (Concept "yellows basket"))
(Evaluation (Predicate "is red") (Concept "red ball"))
(Evaluation (Predicate "is red") (Concept "red ball too"))
(Evaluation (Predicate "is red") (Concept "red ball also"))
(Evaluation (Predicate "is red") (Concept "a red ball"))
(Evaluation (Predicate "is red") (Concept "b red ball"))
(Evaluation (Predicate "is green")  (Concept "green ball"))
(Evaluation (Predicate "is yellow") (Concept "yellow ball"))
(Evaluation (Predicate "is yellow") (Concept "ochre ball"))
(define get-baskets-with-only-red-balls
	(Bind
		(VariableList
			(TypedVariable (Variable "basket") (Type 'ConceptNode))
			(TypedVariable (Variable "ball")   (Type 'ConceptNode))
		)
		(And
			(Inheritance (Variable "basket") (Concept "basket"))
			(Member (Variable "ball") (Variable "basket"))
			(Always (Evaluation (Predicate "is red") (Variable "ball")))
		)
		(Variable "basket"))
)
(define baskets-with-same-color
	(Bind
		(VariableList
			(TypedVariable (Variable "basket")      (Type 'ConceptNode))
			(TypedVariable (Variable "some ball")   (Type 'ConceptNode))
			(TypedVariable (Variable "other ball")  (Type 'ConceptNode))
			(TypedVariable (Variable "some color")  (Type 'PredicateNode))
			(TypedVariable (Variable "other color") (Type 'PredicateNode))
		)
		(And
			(Inheritance (Variable "basket")       (Concept "basket"))
			(Member (Variable "some ball")         (Variable "basket"))
			(Member (Variable "other ball")        (Variable "basket"))
			(Evaluation (Variable "some color")    (Variable "some ball"))
			(Evaluation (Variable "other color")   (Variable "other ball"))
			(Always (Equal (Variable "some color") (Variable "other color")))
		)
		(Variable "basket"))
)