(define (stv mean conf) (cog-new-stv mean conf))
(define (same person)
	(EvaluationLink (stv 1 1)
		(PredicateNode "IsSamePerson")
		(ListLink
			(FeatureNode person)
			(FeatureNode person)
		)
	)
)
(define (fact person pred value)
	(same person)
	(EvaluationLink (stv 1 1)
		(PredicateNode pred)
		(ListLink
			(FeatureNode person)
			(ConceptNode value)
		)
	)
)
(define (neighbor person1 person2)
	(same person1)
	(same person2)
	(EvaluationLink (stv 1 1)
		(PredicateNode "Neighbor")
		(ListLink
			(FeatureNode person1)
			(FeatureNode person2)
		)
	)
)
(define (left-of house1 house2)
	(EvaluationLink (stv 1 1)
		(PredicateNode "LeftOf")
		(ListLink
			(ConceptNode house1)
			(ConceptNode house2)
		)
	)
)
(fact "person1" "Nationality" "Englishman")
(fact "person1" "LivesIn" "red house")
(fact "person2" "Nationality" "Swede")
(fact "person2" "Keeps" "dogs")
(fact "person3" "Nationality" "Dane")
(fact "person3" "Drinks" "tea")
(left-of "green house" "white house")
(fact "person5" "LivesIn" "green house")
(fact "person5" "Drinks" "coffee")
(fact "person6" "Smokes" "PallMall")
(fact "person6" "Keeps" "birds")
(fact "person7" "Smokes" "Dunhill")
(fact "person7" "LivesIn" "yellow house")
(fact "person8" "Drinks" "milk")
(fact "person8" "Address" "103 Main Street")
(fact "person9" "Nationality" "Norwegian")
(fact "person9" "Address" "101 Main Street")
(fact "person10" "Smokes" "Blend")
(neighbor "person10" "catperson")
(fact "catperson" "Keeps" "cats")
(fact "person11" "Smokes" "Blue Master")
(fact "person11" "Drinks" "bier")
(fact "person12" "Keeps" "horses")
(neighbor "person12" "dun_smoke_person")
(fact "dun_smoke_person" "Smokes" "Dunhill")
(fact "person13" "Nationality" "German")
(fact "person13" "Smokes" "Prince")
(fact "person14" "Nationality" "Norwegian")
(neighbor "person14" "blue_person")
(fact "blue_person" "LivesIn" "blue house")
(fact "person15" "Smokes" "Blend")
(neighbor "person15" "water_person")
(fact "water_person" "Drinks" "water")
(fact "person4" "LivesIn" "white house")
(fact "fish_person" "Keeps" "fish")
(define (successor house1 house2)
	(EvaluationLink (stv 1 1)
		(PredicateNode "Successor")
		(ListLink
			(ConceptNode house1)
			(ConceptNode house2)
		)
	)
)
(successor "101 Main Street" "102 Main Street")
(successor "102 Main Street" "103 Main Street")
(successor "103 Main Street" "104 Main Street")
(successor "104 Main Street" "105 Main Street")
(define (is-a x y)
	(InheritanceLink
		(ConceptNode x)
		(ConceptNode y)
	)
)
(is-a "red house" "house")
(is-a "white house" "house")
(is-a "green house" "house")
(is-a "yellow house" "house")
(is-a "blue house" "house")
(is-a "water" "drink")
(is-a "milk" "drink")
(is-a "bier" "drink")
(is-a "coffee" "drink")
(is-a "tea" "drink")
(is-a "Prince" "tobacco")
(is-a "PallMall" "tobacco")
(is-a "Dunhill" "tobacco")
(is-a "Blend" "tobacco")
(is-a "Blue Master" "tobacco")
(is-a "fish" "pet")
(is-a "dogs" "pet")
(is-a "birds" "pet")
(is-a "cats" "pet")
(is-a "horses" "pet")
(is-a "Englishman" "citizenship")
(is-a "Swede" "citizenship")
(is-a "Dane" "citizenship")
(is-a "Norwegian" "citizenship")
(is-a "German" "citizenship")