(use-modules (srfi srfi-1))
(define (stv mean conf) (cog-new-stv mean conf))
(define (not-same atom-a atom-b)
(define ne (not (equal? atom-a atom-b)))
(if ne (stv 1 1) (stv 0 1)))
(define (none-same atom-a atom-b atom-c atom-d atom-e)
(define ne (and
(not (equal? atom-a atom-b))
(not (equal? atom-a atom-c))
(not (equal? atom-a atom-d))
(not (equal? atom-a atom-e))
(not (equal? atom-b atom-c))
(not (equal? atom-b atom-d))
(not (equal? atom-b atom-e))
(not (equal? atom-c atom-d))
(not (equal? atom-c atom-e))
(not (equal? atom-d atom-e))))
(if ne (stv 1 1) (stv 0 1)))
(define VN VariableNode)
(define PN PredicateNode)
(define CN ConceptNode)
(define AN FeatureNode)
(define (clause t1 v1 t2 v2 t3 v3)
(EvaluationLink
(t1 v1)
(ListLink
(t2 v2)
(t3 v3)
)
)
)
(define (not-clause t1 v1 t2 v2 t3 v3)
(EvaluationLink
(t1 v1)
(ListLink
(t2 v2)
(AntiLink (t3 v3))
)
)
)
(define (differ t2 v2 t3 v3)
(EvaluationLink
(GroundedPredicateNode "scm:not-same")
(ListLink
(t2 v2)
(t3 v3)
)
)
)
(define (decl-var type var)
(TypedVariableLink
(VariableNode var)
(TypeNode type)
)
)
(define (is-same-rule)
(BindLink
(VariableList
(decl-var "PredicateNode" "$predicate")
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "ConceptNode" "$attribute")
)
(AndLink
(clause VN "$predicate" VN "$person_a" VN "$attribute")
(clause VN "$predicate" VN "$person_b" VN "$attribute")
(AbsentLink
(clause PN "IsSamePerson" VN "$person_a" VN "$person_b")
)
)
(clause PN "IsSamePerson" VN "$person_a" VN "$person_b")
)
)
(define (transitive-rule)
(BindLink
(VariableList
(decl-var "PredicateNode" "$predicate")
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "ConceptNode" "$attribute")
)
(AndLink
(clause VN "$predicate" VN "$person_a" VN "$attribute")
(clause PN "IsSamePerson" VN "$person_a" VN "$person_b")
(AbsentLink
(clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(define (transitive-not-rule)
(BindLink
(VariableList
(decl-var "PredicateNode" "$predicate")
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "ConceptNode" "$attribute")
)
(AndLink
(not-clause VN "$predicate" VN "$person_a" VN "$attribute")
(clause PN "IsSamePerson" VN "$person_a" VN "$person_b")
(AbsentLink
(not-clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(not-clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(define (by-elimination-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person")
(decl-var "PredicateNode" "$predicate")
(decl-var "ConceptNode" "$attr_a")
(decl-var "ConceptNode" "$attr_b")
(decl-var "ConceptNode" "$attr_c")
(decl-var "ConceptNode" "$attr_d")
(decl-var "ConceptNode" "$attr_e")
(decl-var "ConceptNode" "$attr_type")
)
(AndLink
(not-clause VN "$predicate" VN "$person" VN "$attr_a")
(not-clause VN "$predicate" VN "$person" VN "$attr_b")
(not-clause VN "$predicate" VN "$person" VN "$attr_c")
(not-clause VN "$predicate" VN "$person" VN "$attr_d")
(InheritanceLink (VN "$attr_a") (VN "$attr_type"))
(InheritanceLink (VN "$attr_b") (VN "$attr_type"))
(InheritanceLink (VN "$attr_c") (VN "$attr_type"))
(InheritanceLink (VN "$attr_d") (VN "$attr_type"))
(InheritanceLink (VN "$attr_e") (VN "$attr_type"))
(EvaluationLink
(GroundedPredicateNode "scm:none-same")
(ListLink
(VN "$attr_a")
(VN "$attr_b")
(VN "$attr_c")
(VN "$attr_d")
(VN "$attr_e")
)
)
)
(clause VN "$predicate" VN "$person" VN "$attr_e")
)
)
(define (distinct-attr-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "PredicateNode" "$predicate_common")
(decl-var "ConceptNode" "$attribute_comm_a")
(decl-var "ConceptNode" "$attribute_comm_b")
(decl-var "PredicateNode" "$predicate_exclusive")
(decl-var "ConceptNode" "$attribute_excl")
)
(AndLink
(clause VN "$predicate_common" VN "$person_a" VN "$attribute_comm_a")
(clause VN "$predicate_common" VN "$person_b" VN "$attribute_comm_b")
(differ VN "$attribute_comm_a" VN "$attribute_comm_b")
(clause VN "$predicate_exclusive" VN "$person_a" VN "$attribute_excl")
)
(not-clause VN "$predicate_exclusive" VN "$person_b" VN "$attribute_excl")
)
)
(define (neighbor-not-attr-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "PredicateNode" "$predicate")
(decl-var "ConceptNode" "$attribute")
)
(AndLink
(clause VN "$predicate" VN "$person_a" VN "$attribute")
(clause PN "Neighbor" VN "$person_a" VN "$person_b")
(AbsentLink
(not-clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(not-clause VN "$predicate" VN "$person_b" VN "$attribute")
)
)
(define (first-addr-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "ConceptNode" "$addr_a")
(decl-var "ConceptNode" "$addr_b")
)
(AndLink
(clause PN "Address" VN "$person_a" CN "101 Main Street")
(clause PN "Address" VN "$person_a" VN "$addr_a")
(clause PN "Neighbor" VN "$person_a" VN "$person_b")
(clause PN "Successor" VN "$addr_a" VN "$addr_b")
(AbsentLink
(clause PN "Address" VN "$person_b" VN "$addr_b")
)
)
(clause PN "Address" VN "$person_b" VN "$addr_b")
)
)
(define (neighbor-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
(decl-var "ConceptNode" "$addr_a")
(decl-var "ConceptNode" "$addr_b")
)
(AndLink
(clause PN "Address" VN "$person_a" VN "$addr_a")
(clause PN "Address" VN "$person_b" VN "$addr_b")
(clause PN "Successor" VN "$addr_a" VN "$addr_b")
(AbsentLink
(clause PN "Neighbor" VN "$person_a" VN "$person_b")
)
)
(clause PN "Neighbor" VN "$person_a" VN "$person_b")
)
)
(define (neighbor-symmetry-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person_a")
(decl-var "FeatureNode" "$person_b")
)
(AndLink
(clause PN "Neighbor" VN "$person_a" VN "$person_b")
(AbsentLink
(clause PN "Neighbor" VN "$person_b" VN "$person_a")
)
)
(clause PN "Neighbor" VN "$person_b" VN "$person_a")
)
)
(define (found-solution-rule)
(BindLink
(VariableList
(decl-var "FeatureNode" "$person")
(decl-var "ConceptNode" "$nationality")
(decl-var "ConceptNode" "$drink")
(decl-var "ConceptNode" "$smoke")
(decl-var "ConceptNode" "$pet")
(decl-var "ConceptNode" "$house")
(decl-var "ConceptNode" "$addr")
)
(AndLink
(clause PN "Nationality" VN "$person" VN "$nationality")
(clause PN "Drinks"      VN "$person" VN "$drink")
(clause PN "Smokes"      VN "$person" VN "$smoke")
(clause PN "Keeps"       VN "$person" VN "$pet")
(clause PN "LivesIn"     VN "$person" VN "$house")
(clause PN "Address"     VN "$person" VN "$addr")
(AbsentLink
(OrderedLink
(VN "$nationality")
(VN "$drink")
(VN "$smoke")
(VN "$pet")
(VN "$house")
(VN "$addr")
)
)
)
(OrderedLink
(VN "$nationality")
(VN "$drink")
(VN "$smoke")
(VN "$pet")
(VN "$house")
(VN "$addr")
)
)
)