(define (stv mean conf) (cog-new-stv mean conf))
(EvaluationLink (stv 1 1)
(PredicateNode "Nationality")
(ListLink
(FeatureNode "person1")
(ConceptNode "British")
)
)
(EvaluationLink (stv 1 1)
(PredicateNode "LivesIn")
(ListLink
(FeatureNode "person1")
(ConceptNode "red_house")
)
)
(EvaluationLink (stv 1 1)
(PredicateNode "LivesIn")
(ListLink
(FeatureNode "person2")
(ConceptNode "red_house")
)
)
(EvaluationLink (stv 1 1)
(PredicateNode "KeepsPet")
(ListLink
(FeatureNode "person2")
(ConceptNode "fish")
)
)