(use-modules (opencog) (opencog exec))
(use-modules (opencog test-runner))
(opencog-test-runner)
(define tname "dot-lambda-test")
(test-begin tname)
(Evaluation (Predicate "has legs") (Concept "dog") (CountTruthValue 1 0 1))
(Evaluation (Predicate "has nose") (Concept "dog") (CountTruthValue 1 0 2))
(Evaluation (Predicate "has tail") (Concept "dog") (CountTruthValue 1 0 3))
(Evaluation (Predicate "furry")    (Concept "dog") (CountTruthValue 1 0 4))
(Evaluation (Predicate "domestic") (Concept "dog") (CountTruthValue 1 0 5))
(Evaluation (Predicate "has legs") (Concept "cat") (CountTruthValue 1 0 1))
(Evaluation (Predicate "has nose") (Concept "cat") (CountTruthValue 1 0 2))
(Evaluation (Predicate "has tail") (Concept "cat") (CountTruthValue 1 0 3))
(Evaluation (Predicate "furry")    (Concept "cat") (CountTruthValue 1 0 4))
(Evaluation (Predicate "domestic") (Concept "cat") (CountTruthValue 1 0 5))
(define qdot-math
	(Query
		(TypedVariable (Variable "$prop") (Type 'Predicate))
		(Present
			(Evaluation (Variable "$prop") (Concept "dog"))
			(Evaluation (Variable "$prop") (Concept "cat")))
		(Put
			(Lambda (Variable "$foo")
				(Times
					(CountOf (Evaluation (Variable "$foo") (Concept "dog")))
					(CountOf (Evaluation (Variable "$foo") (Concept "cat")))))
			(Variable "$prop"))))
(define five-five (cog-execute! (Accumulate qdot-math)))
(test-assert "final dot product" (equal? (FloatValue 55) five-five))
(test-end tname)
(opencog-test-end)