(use-modules (opencog) (opencog exec))
(use-modules (opencog test-runner))
(opencog-test-runner)
(define tname "dot-identical-test")
(test-begin tname)
(Evaluation (Predicate "has legs") (Concept "dog") (CountTruthValue 1 0 1))
(Evaluation (Predicate "has nose") (Concept "dog") (CountTruthValue 1 0 2))
(Evaluation (Predicate "has tail") (Concept "dog") (CountTruthValue 1 0 3))
(Evaluation (Predicate "furry")    (Concept "dog") (CountTruthValue 1 0 4))
(Evaluation (Predicate "domestic") (Concept "dog") (CountTruthValue 1 0 5))
(Evaluation (Predicate "has legs") (Concept "cat") (CountTruthValue 1 0 1))
(Evaluation (Predicate "has nose") (Concept "cat") (CountTruthValue 1 0 2))
(Evaluation (Predicate "has tail") (Concept "cat") (CountTruthValue 1 0 3))
(Evaluation (Predicate "furry")    (Concept "cat") (CountTruthValue 1 0 4))
(Evaluation (Predicate "domestic") (Concept "cat") (CountTruthValue 1 0 5))
(define qdot-math
	(Query
		(VariableList
			(TypedVariable (Variable "$prop") (Type 'Predicate))
			(TypedVariable (Variable "$dog") (Type 'Evaluation))
			(TypedVariable (Variable "$cat") (Type 'Evaluation))
		)
		(And
			(Identical (Variable "$dog")
				(Evaluation (Variable "$prop") (Concept "dog")))
			(Identical (Variable "$cat")
				(Evaluation (Variable "$prop") (Concept "cat")))
		)
		(Times
			(CountOf (Variable "$dog"))
			(CountOf (Variable "$cat")))))
(define five-five (cog-execute! (Accumulate qdot-math)))
(test-assert "final dot product" (equal? (FloatValue 55) five-five))
(test-end tname)
(opencog-test-end)