(use-modules (opencog))
(use-modules (opencog exec))
(define estero
	(BindLink
		(VariableList
			(TypedVariable (Variable "$carboxyH1") (Type 'H))
			(TypedVariable (Variable "$carboxyO1") (Type 'O))
			(TypedVariable (Variable "$carboxyC1") (Type 'C))
			(TypedVariable (Variable "$carboxyO2") (Type 'O))
			(TypedVariable (Variable "$hydroxH1") (Type 'H))
			(TypedVariable (Variable "$hydroxO1") (Type 'O))
			(Variable "carboxy moiety")
			(Variable "hydroxy moiety")
			(Glob "rest of carboxy")
			(Glob "rest of hydroxy")
		)
		(AndLink
			(Molecule
				(DBo (Variable "$carboxyC1") (Variable "$carboxyO2"))
				(SBo (Variable "$carboxyC1") (Variable "$carboxyO1"))
				(SBo (Variable "$carboxyO1") (Variable "$carboxyH1"))
				(SBo (Variable "$carboxyC1") (Variable "carboxy moiety"))
				(Glob "rest of carboxy")
			)
			(Not (Identical (Variable "$carboxyO1") (Variable "carboxy moiety")))
			(Molecule
				(SBo (Variable "$hydroxO1") (Variable "$hydroxH1"))
				(SBo (Variable "hydroxy moiety") (Variable "$hydroxO1"))
				(Glob "rest of hydroxy")
			)
			(Not (Identical (Variable "$hydroxH1") (Variable "hydroxy moiety")))
			(Not (Identical (Variable "$carboxyO1") (Variable "$hydroxO1")))
			(Not (Identical (Variable "$carboxyH1") (Variable "$hydroxH1")))
		)
		(AndLink
			(Molecule
				(DBo (Variable "$carboxyC1") (Variable "$carboxyO2"))
				(SBo (Variable "$carboxyC1") (Variable "$carboxyO1"))
				(SBo (Variable "$carboxyC1") (Variable "carboxy moiety"))
				(Glob "rest of carboxy")
				(SBo (Variable "$carboxyO1") (Variable "hydroxy moiety"))
				(Glob "rest of hydroxy")
			)
			(Molecule
				(SBo (Variable "$hydroxO1") (Variable "$carboxyH1"))
				(SBo (Variable "$hydroxO1") (Variable "$hydroxH1"))
			)
		)
	)
)
(Molecule
	(DBo (C "the carboxyl carb") (O "oxy two"))
	(SBo (C "the carboxyl carb") (O "oxy one"))
	(SBo (O "oxy one") (H "carboxyl proton"))
	(SBo (C "the carboxyl carb") (Fe "carbox R"))
	(SBo (Fe "carbox R") (Ni "more carbox junk"))
)
(Molecule
	(SBo (O "hydroxyl oxy") (H "hydroxyl proton"))
	(SBo (C "hydroxyl carbon") (O "hydroxyl oxy"))
	(SBo (C "hydroxyl carbon") (Zn "hydrox R"))
	(SBo (Zn "hydrox R") (Cu "junk hydrox moiety"))
)