(define (stv mean conf) (cog-new-stv mean conf))
(InheritanceLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(AtTimeLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(PrepositionalRelationshipNode "Big Red Button")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(FeatureNode "here kitty kitty")
	(EvaluationLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(ConceptNode "big idea")
	(ExecutionLink (stv 1.0 1.0)
		(FeatureNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(FeatureLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(WordNode "bird is the word")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(SemeNode "ActivationModulatorUpdater")
	(ConceptNode "big idea")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(HebbianLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(define (bind_oo)
	(BindLink
		(VariableList
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
		(MemberLink (stv 1.0 1.0)
			(VariableNode "$var_schema")
			(VariableNode "$var_number")
			(ExecutionLink (stv 1.0 1.0)
				(VariableNode "$var_schema")
				(ListLink
					(LemmaNode "thing1")
					(LemmaNode "thing2")
					(LemmaNode "thing3")
				)
			)
		)
		(ListLink
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
	)
)
(SubsetLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(WordNode "bird is the word")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ParseLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing ohh noo")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)
(MemberLink (stv 1.0 1.0)
	(PrepositionalRelationshipNode "Big Red Button")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(LemmaNode "thing1")
			(LemmaNode "thing2")
			(LemmaNode "thing3")
		)
	)
)