(InheritanceLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(AtTimeLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(PrepositionalRelationshipNode "Big Red Button")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(FeatureNode "here kitty kitty")
	(EvaluationLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(ConceptNode "big idea")
	(SetLink
		(FeatureNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(FeatureLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(WordNode "bird is the word")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SemeNode "ActivationModulatorUpdater")
	(ConceptNode "big idea")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(HebbianLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(define (bind_uuu)
	(BindLink
		(VariableList
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
		(SimilarityLink
			(VariableNode "$var_schema")
			(VariableNode "$var_number")
			(SetLink
				(LemmaNode "thing3")
				(LemmaNode "thing1")
				(VariableNode "$var_schema")
				(LemmaNode "thing2")
			)
			(SetLink
				(NumberNode "2.0")
				(VariableNode "$var_number")
				(NumberNode "3.0")
				(NumberNode "1.0")
			)
		)
		(ListLink
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
	)
)
(SubsetLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(WordNode "bird is the word")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ParseLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(SchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing ohh noo")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)
(SimilarityLink
	(PrepositionalRelationshipNode "Big Red Button")
	(NumberNode "0.24")
	(SetLink
		(SchemaNode "ActivationModulatorUpdater")
		(LemmaNode "thing1")
		(LemmaNode "thing2")
		(LemmaNode "thing3")
	)
	(SetLink
		(NumberNode "0.24")
		(NumberNode "1.0")
		(NumberNode "2.0")
		(NumberNode "3.0")
	)
)