(define (stv mean conf) (cog-new-stv mean conf))
(SimilarityLink (stv 1.0 1.0)
	(GroundedSchemaNode "ActivationModulatorUpdater")
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink)
	)
)
(define (pair)
	(BindLink
		(VariableList
			(VariableNode "$var_one")
			(VariableNode "$var_two")
		)
		(SimilarityLink (stv 1.0 1.0)
			(VariableNode "$var_one")
			(VariableNode "$var_two")
			(ExecutionLink (stv 1.0 1.0)
				(GroundedSchemaNode "ActivationModulatorUpdater")
				(ListLink)
			)
		)
		(ListLink
			(VariableNode "$var_one")
			(VariableNode "$var_two")
		)
	)
)
(define (blink)
	(BindLink
		(VariableList
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
		(SimilarityLink (stv 1.0 1.0)
			(VariableNode "$var_schema")
			(VariableNode "$var_number")
			(ExecutionLink (stv 1.0 1.0)
				(VariableNode "$var_schema")
				(ListLink)
			)
		)
		(ListLink
			(VariableNode "$var_number")
			(VariableNode "$var_schema")
		)
	)
)
(define (blinker)
	(BindLink
		(VariableList
			(VariableNode "$vbr_schema")
			(VariableNode "$vbr_number")
		)
		(SimilarityLink (stv 1.0 1.0)
			(VariableNode "$vbr_schema")
			(VariableNode "$vbr_number")
			(ExecutionLink (stv 1.0 1.0)
				(VariableNode "$vbr_schema")
				(ListLink)
			)
		)
		(ListLink
			(VariableNode "$vbr_number")
			(VariableNode "$vbr_schema")
		)
	)
)