(define (stv mean conf) (cog-new-stv mean conf))
(SimilarityLink (stv 1.0 1.0)
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink)
	)
)
(SimilarityLink (stv 1.0 1.0)
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(SemeNode "We are legion; we are Anonymous")
		(ListLink)
	)
)
(SimilarityLink (stv 1.0 1.0)
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink
			(ConceptNode "ring a ling a ding")
		)
	)
)
(SimilarityLink (stv 1.0 1.0)
	(NumberNode "0.24")
	(AtTimeLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink)
	)
)
(UnorderedLink (stv 1.0 1.0)
	(NumberNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink)
	)
)
(SimilarityLink (stv 1.0 1.0)
	(WordNode "0.24")
	(ExecutionLink (stv 1.0 1.0)
		(GroundedSchemaNode "ActivationModulatorUpdater")
		(ListLink)
	)
)
(define (blank)
	(BindLink
		(VariableList
			(TypedVariableLink
				(VariableNode "$var_number_node_type")
				(TypeNode "NumberNode")
			)
		)
		(SimilarityLink
			(VariableNode "$var_number_node_type")
			(ExecutionLink
				(GroundedSchemaNode "ActivationModulatorUpdater")
				(ListLink)
			)
		)
		(ListLink
			(VariableNode "$var_number_node_type")
		)
	)
)