(define (select-substitution-term TyV)
  (let* (
         (V (gar TyV))
         (query (GetLink TyV V))
         (result (cog-execute! query)))
    (extract-hypergraph query)
    (select-rnd-outgoing result)))
(define (select-substitution-terms TyVs)
  (let* (
         (typed-vars (cog-outgoing-set TyVs))
         (terms (map select-substitution-term typed-vars)))
    (apply ListLink terms)))
(define (select-rnd-outgoing link)
  (let* ((outgoings (cog-outgoing-set link))
         (outgoings-len (length outgoings)))
    (if (< 0 outgoings-len)
        (list-ref outgoings (random outgoings-len))
        #f)))
(define (rm-list-ref l i)
  (append (take l i) (drop l (+ i 1))))
(define (select-rm-rnd-outgoing link)
  (let* ((link-type (cog-type link))
         (outgoings (cog-outgoing-set link))
         (rnd-index (random (length outgoings)))
         (rnd-atom (list-ref outgoings rnd-index))
         (remain-list (rm-list-ref outgoings rnd-index))
         (remain (apply cog-new-link link-type remain-list)))
    (list rnd-atom remain)))
(define (select-conditioned-substitution-terms TyVs P)
  (let* (
         (query (GetLink TyVs P))
         (result (cog-execute! query)))
    (extract-hypergraph query)
    (select-rnd-outgoing result)))