#ifndef VERSION_H_
#define VERSION_H_	1
#ifndef NETPGP_AUTOCONF_VERSION
#define NETPGP_AUTOCONF_VERSION	PACKAGE_VERSION
#endif
#ifndef NETPGP_MAINTAINER
#define NETPGP_MAINTAINER	PACKAGE_BUGREPORT
#endif
#define NETPGP_BASE_VERSION	"3.99.99"
#define NETPGP_VERSION_CAT(a, b)	"NetPGP for Delta Chat " a "/[" b "]"
#define NETPGP_VERSION_STRING \
NETPGP_VERSION_CAT(NETPGP_BASE_VERSION, NETPGP_AUTOCONF_VERSION)
#endif