(use-modules (srfi srfi-1))
(use-modules (opencog logger))
(define (strip-type-from-variable TyV)
  (if (equal? (cog-type TyV) 'TypedVariableLink)
      (gar TyV)
      (TyV)))
(define (select-substitution-term TyV)
  (let* (
         (V (strip-type-from-variable TyV))
         (query (GetLink TyV V))
         (result (cog-execute! query)))
    (extract-hypergraph query)
    (select-rnd-outgoing result)))
(define (select-substitution-terms TyVs)
  (let* (
         (typed-vars (cog-outgoing-set TyVs))
         (terms (map select-substitution-term typed-vars)))
    (apply ListLink terms)))
(define (select-rnd-outgoing link)
  (let* ((outgoings (cog-outgoing-set link))
         (outgoings-len (length outgoings)))
    (if (< 0 outgoings-len)
        (list-ref outgoings (random outgoings-len))
        #f)))
(define (rm-list-ref l i)
  (append (take l i) (drop l (+ i 1))))
(define (select-rm-rnd-outgoing link)
  (let* ((link-type (cog-type link))
         (outgoings (cog-outgoing-set link))
         (rnd-index (random (length outgoings)))
         (rnd-atom (list-ref outgoings rnd-index))
         (remain-list (rm-list-ref outgoings rnd-index))
         (remain (apply cog-new-link link-type remain-list)))
    (list rnd-atom remain)))
(define (variable-free? V A)
  (if (member V (cog-free-variables A)) #t #f))
(define (typed-variable-free? TyV A)
  (variable-free? (strip-type-from-variable TyV) A))
(define (variable-list TyVs)
  (if (equal? (cog-type TyVs) 'VariableList)
      (cog-outgoing-set TyVs)
      (list TyVs)))
(define (typed-variables-free? TyVs A)
  (every (lambda (TyV) (typed-variable-free? TyV A)) (variable-list TyVs)))
(define (filter-free-typed-variables TyVs A)
  (let ((typed-variable-free-in-A? (lambda (TyV) (typed-variable-free? TyV A))))
    (VariableList (filter typed-variable-free-in-A? (variable-list TyVs)))))
(define (unfree-variables TyVs A)
  (let* ((unfree-var-in-A? (lambda (TyV) (not (typed-variable-free? TyV A))))
         (unfree-typed-vars (filter unfree-var-in-A? (variable-list TyVs)))
         (unfree-vars (map strip-type-from-variable unfree-typed-vars)))
    unfree-vars))
(define (select-conditioned-substitution-terms TyVs P)
  (let* (
         (unfree-vars (unfree-variables TyVs P))
         (query-body (if (null? unfree-vars) P (And P unfree-vars)))
         (query (GetLink TyVs query-body))
         (results (cog-execute! query)))
        (extract-hypergraph query)
        (select-rnd-outgoing results)))