(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define test-close-open "test dtor-close")
(test-begin test-close-open)
(define rsn (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open rsn)
(List (Concept "A") (Concept "B"))
(Set (Concept "A") (Concept "B"))
(Set (Concept "A") (Concept "B") (Concept "C"))
(store-atomspace)
(cog-atomspace-clear)
(test-equal #t (cog-atom? rsn))
(test-equal #f (cog-atom rsn))
(format #t "The rsn right now is: ~A\n" rsn)
(test-equal #f (cog-atom? rsn))
(define rsn (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open rsn)
(load-atomspace)
(test-equal #t (cog-atom? rsn))
(cog-close rsn)
(test-end test-close-open)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)