(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(use-modules (opencog persist-mono))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (setup-and-store)
	(Concept "foo" (ctv 1 0 3))
	(Concept "bar" (ctv 1 0 4))
	(ListLink (Concept "bar") (ctv 1 0 5))
	(ListLink (Concept "foo") (List (Concept "bar")) (ctv 1 0 6))
	(define mstorage (MonoStorageNode "monospace:///tmp/cog-rocks-unit-test"))
	(cog-open mstorage)
	(store-atom (Concept "foo"))
	(store-atom (Concept "bar"))
	(store-atom (ListLink (Concept "foo") (List (Concept "bar"))))
	(cog-close mstorage)
	(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
	(cog-open storage)
	(store-frames (cog-atomspace))
	(cog-set-atomspace! (cog-new-atomspace (cog-atomspace)))
	(store-atom (Concept "foo" (ctv 1 0 7)))
	(store-atom (Concept "bar"))
	(store-atom (ListLink (Concept "foo") (List (Concept "bar")) (ctv 1 0 8)))
	(cog-close storage)
	(cog-atomspace-clear (cog-atomspace))
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-promotion)
	(setup-and-store)
	(cog-atomspace-clear (cog-atomspace))
	(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
	(cog-open storage)
	(define top-space (car (load-frames)))
	(cog-set-atomspace! top-space)
	(load-atomspace)
	(cog-close storage)
	(define lilly (ListLink (Concept "foo") (List (Concept "bar"))))
	(test-equal "link-tv" 8 (get-cnt lilly))
	(test-equal "foo-tv" 7 (get-cnt (cog-node 'Concept "foo")))
	(test-equal "bar-tv" 4 (get-cnt (cog-node 'Concept "bar")))
	(test-equal "link-bar-tv" 0 (get-cnt (cog-link 'List (Concept "bar"))))
	(cog-set-atomspace! (gar top-space))
	(test-equal "link-tv" 6 (get-cnt
		(cog-link 'List (Concept "foo") (List (Concept "bar")))))
	(test-equal "foo-tv" 3 (get-cnt (cog-node 'Concept "foo")))
	(test-equal "bar-tv" 4 (get-cnt (cog-node 'Concept "bar")))
	(test-equal "link-bar-tv" 0 (get-cnt (cog-link 'List (Concept "bar"))))
)
(define (kill-top-store)
	(cog-atomspace-clear (cog-atomspace))
	(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
	(cog-open storage)
	(define top-space (car (load-frames)))
	(delete-frame! top-space)
	(cog-close storage)
)
(define (test-remainder)
	(cog-atomspace-clear (cog-atomspace))
	(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
	(cog-open storage)
	(define top-space (car (load-frames)))
	(cog-set-atomspace! top-space)
	(load-atomspace)
	(cog-close storage)
	(define lilly (ListLink (Concept "foo") (List (Concept "bar"))))
	(test-equal "link-tv" 6 (get-cnt lilly))
	(test-equal "foo-tv" 3 (get-cnt (cog-node 'Concept "foo")))
	(test-equal "bar-tv" 4 (get-cnt (cog-node 'Concept "bar")))
	(test-equal "link-bar-tv" 0 (get-cnt (cog-link 'List (Concept "bar"))))
)
(define promotion "test promotion")
(test-begin promotion)
(test-promotion)
(kill-top-store)
(test-remainder)
(test-end promotion)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)