(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (setup-and-store)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define surface-space (cog-new-atomspace mid2-space))
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! mid1-space)
(Concept "bar" (ctv 1 0 4))
(cog-set-atomspace! mid2-space)
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 5))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames surface-space)
(store-atom (ListLink (Concept "foo") (Concept "bar")))
(store-atom (Concept "foo"))
(store-atom (Concept "bar"))
(cog-close storage)
(cog-atomspace-clear surface-space)
(cog-atomspace-clear mid2-space)
(cog-atomspace-clear mid1-space)
(cog-atomspace-clear base-space)
)
(define (delete-top-frame)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(delete-frame! top-space)
(cog-close storage)
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (count-depth space cnt)
(if (< 0 (length (cog-outgoing-set space)))
(count-depth (gar space) (+ 1 cnt))
cnt))
(define (test-delete-frame)
(setup-and-store)
(define keep-me-around (cog-new-atomspace))
(cog-set-atomspace! keep-me-around)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(test-equal "top-depth" 4 (count-depth top-space 1))
(delete-top-frame)
(cog-set-atomspace! (cog-new-atomspace))
(cog-open storage)
(set! top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(test-equal "top-depth" 3 (count-depth top-space 1))
(delete-top-frame)
(cog-set-atomspace! (cog-new-atomspace))
(cog-open storage)
(set! top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(test-equal "top-depth" 2 (count-depth top-space 1))
(define mid1-space top-space)
(define base-space (cog-outgoing-atom mid1-space 0))
(test-assert "lily-gone" (nil? (cog-link 'ListLink
(Concept "foo") (Concept "bar"))))
(test-equal "foo-space" base-space (cog-atomspace (cog-node 'Concept "foo")))
(test-equal "bar-space" mid1-space (cog-atomspace (cog-node 'Concept "bar")))
(test-equal "base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
(test-equal "mid1-tv" 4 (get-cnt (cog-node 'Concept "bar")))
(format #t "The keeper is ~A\n" keep-me-around)
)
(define delete-frame "test deletion of frames")
(test-begin delete-frame)
(test-delete-frame)
(test-end delete-frame)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)