(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (setup-and-store)
(define left-space (cog-atomspace))
(define right-space (cog-new-atomspace))
(define top-space (cog-new-atomspace (list left-space right-space)))
(cog-set-atomspace! left-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! right-space)
(Concept "bar" (ctv 1 0 4))
(cog-set-atomspace! top-space)
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 8))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames top-space)
(store-atom (ListLink (Concept "foo") (Concept "bar")))
(store-atom (Concept "foo"))
(store-atom (Concept "bar"))
(cog-close storage)
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-wye)
(setup-and-store)
(define new-base (cog-new-atomspace))
(cog-set-atomspace! new-base)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(define left-space (cog-outgoing-atom top-space 0))
(define right-space (cog-outgoing-atom top-space 1))
(test-assert "wye-unequal" (not (equal? left-space right-space)))
(test-assert "wye-uuid" (not (equal?
(cog-atomspace-uuid left-space)
(cog-atomspace-uuid right-space))))
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(test-equal "top-space" top-space (cog-atomspace lilly))
(test-equal "foo-space" left-space (cog-atomspace (gar lilly)))
(test-equal "bar-space" right-space (cog-atomspace (gdr lilly)))
(test-equal "left-tv" 3 (get-cnt (cog-node 'Concept "foo")))
(test-equal "right-tv" 4 (get-cnt (cog-node 'Concept "bar")))
(test-equal "top-tv" 8 (get-cnt lilly))
)
(define wye "test wye pattern")
(test-begin wye)
(test-wye)
(test-end wye)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)