(use-modules (srfi srfi-1))
(define (whack dirname)
(define (unlink dir)
(define fname (readdir dir))
(when (not (eof-object? fname))
(let ((fpath (string-append dirname "/" fname)))
(when (equal? 'regular (stat:type (stat fpath)))
(delete-file fpath))
(unlink dir))))
(when (access? dirname F_OK)
(let ((dir (opendir dirname)))
(unlink dir)
(closedir dir)
(rmdir dirname))))