(use-modules (opencog) (opencog persist) (opencog persist-file))
(use-modules (opencog test-runner))
(set! *random-state* (random-state-from-platform))
(define fbase (format #f "/tmp/opencog-test-~D.scm" (random 1000000000)))
(define fsub1 (format #f "/tmp/opencog-test-~D.scm" (random 1000000000)))
(define fsub2 (format #f "/tmp/opencog-test-~D.scm" (random 1000000000)))
(format #t "Using files:\n~A\n~A\n~A\n" fbase fsub1 fsub2)
(opencog-test-runner)
(define tname "store_episodes")
(test-begin tname)
(define base-space (cog-atomspace))
(ConceptNode "foo")
(cog-set-value! (ConceptNode "foo") (Predicate "bunch o numbers")
		(FloatValue 1 2 3.14159 4 5 6))
(cog-set-value! (ConceptNode "foo") (Predicate "some words")
		(StringValue "once" "upon" "a" "time"))
(cog-set-value! (ConceptNode "foo") (Predicate "some atoms")
		(LinkValue (Concept "dog") (Concept "cat") (Concept "mouse")))
(cog-set-value! (ConceptNode "foo") (Predicate "real life")
		(AtomSpace "happy thoughts"))
(cog-set-value! (ConceptNode "foo") (Predicate "repressed mem")
		(AtomSpace "crushing defeat"))
(cog-set-atomspace!
	(cog-value (ConceptNode "foo") (Predicate "real life")))
(ListLink (Concept "mom") (Concept "dad"))
(ListLink (Concept "first crush") (Concept "Gilanda"))
(ListLink (Concept "stack blocks"))
(cog-set-atomspace! base-space)
(cog-set-atomspace!
	(cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(ListLink (Concept "misdemeanor") (Concept "vandalism"))
(ListLink (Concept "furious") (Concept "anger"))
(cog-set-atomspace! base-space)
(format #t "Atom counts in subspaces are ~A ~A ~A\n"
	(count-all)
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem"))))
(test-assert "base-count" (equal? 11 (count-all)))
(test-assert "space1-count" (equal? 8
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 6
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(define fsn (FileStorageNode fbase))
(cog-open fsn)
(store-atomspace)
(cog-close fsn)
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(define as-two (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(define fsa (FileStorageNode fsub1))
(define fsb (FileStorageNode fsub2))
(cog-open fsa)
(cog-open fsb)
(cog-set-atomspace! as-one)
(store-atomspace fsa)
(cog-close fsa)
(cog-set-atomspace! as-two)
(store-atomspace fsb)
(cog-close fsb)
(cog-set-atomspace! base-space)
(cog-prt-atomspace)
(cog-prt-atomspace as-one)
(cog-prt-atomspace as-two)
(set! as-one #f)
(set! as-two #f)
(set! fsa #f)
(set! fsb #f)
(set! fsn #f)
(gc) (gc)
(cog-atomspace-clear)
(define gsn (FileStorageNode fbase))
(define gsa (FileStorageNode fsub1))
(define gsb (FileStorageNode fsub2))
(cog-open gsn)
(load-atomspace)
(cog-close gsn)
(format #t "Loaded Atom counts ~A ~A ~A\n"
	(count-all)
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem"))))
(test-assert "base-count" (equal? 18 (count-all)))
(test-assert "space1-count" (equal? 0
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 0
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(define as-two (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(cog-open gsa)
(cog-open gsb)
(cog-set-atomspace! as-one)
(load-atomspace gsa)
(cog-close gsa)
(cog-set-atomspace! as-two)
(load-atomspace gsb)
(cog-close gsb)
(cog-set-atomspace! base-space)
(format #t "Return to base; Loaded Atom counts ~A ~A ~A\n"
	(count-all)
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem"))))
(test-assert "base-count" (equal? 18 (count-all)))
(test-assert "space1-count" (equal? 11
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 9
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(cog-prt-atomspace)
(cog-prt-atomspace as-one)
(cog-prt-atomspace as-two)
(delete-file fbase)
(delete-file fsub1)
(delete-file fsub2)
(test-end tname)
(opencog-test-end)