#ifndef MASTER_INTERFACE_H
#define MASTER_INTERFACE_H
struct master_status {
pid_t pid;
unsigned int uid;
unsigned int available_count;
};
struct log_service_handshake {
#define MASTER_LOG_MAGIC 0x02ff03fe
unsigned int log_magic;
#define MASTER_LOG_PREFIX_NAME "MASTER"
unsigned int prefix_len;
};
enum master_login_state {
MASTER_LOGIN_STATE_NONFULL = 0,
MASTER_LOGIN_STATE_FULL
};
#define MASTER_IS_PARENT_ENV "DOVECOT_CHILD_PROCESS"
#define MASTER_UID_ENV "GENERATION"
#define MASTER_SERVICE_ENV "SERVICE_NAME"
#define MASTER_CLIENT_LIMIT_ENV "CLIENT_LIMIT"
#define MASTER_PROCESS_LIMIT_ENV "PROCESS_LIMIT"
#define MASTER_PROCESS_MIN_AVAIL_ENV "PROCESS_MIN_AVAIL"
#define MASTER_SERVICE_COUNT_ENV "SERVICE_COUNT"
#define MASTER_SERVICE_IDLE_KILL_ENV "IDLE_KILL"
#define MASTER_CONFIG_FILE_ENV "CONFIG_FILE"
#define MASTER_CONFIG_FILE_SOCKET_ENV "CONFIG_FILE_SOCKET"
#define MASTER_VERBOSE_PROCTITLE_ENV "VERBOSE_PROCTITLE"
#define MASTER_DOVECOT_VERSION_ENV "DOVECOT_VERSION"
#define MASTER_SSL_KEY_PASSWORD_ENV "SSL_KEY_PASSWORD"
#define MASTER_SERVICE_SOCKET_COUNT_ENV "SOCKET_COUNT"
#define MASTER_SERVICE_LOG_SERVICE_ENV "LOG_SERVICE"
#define DOVECOT_LOG_STDERR_TIMESTAMP_ENV "LOG_STDERR_TIMESTAMP"
#define DOVECOT_PRESERVE_ENVS_ENV "DOVECOT_PRESERVE_ENVS"
#define DOVECOT_LOG_DEBUG_ENV "LOG_DEBUG"
#define DOVECOT_CONFIG_FD_ENV "DOVECOT_CONFIG_FD"
#define DOVECOT_STATS_WRITER_SOCKET_PATH "STATS_WRITER_SOCKET_PATH"
#define MASTER_ANVIL_FD 3
#define MASTER_ANVIL_LOG_FDPASS_FD 4
#define MASTER_LOGIN_NOTIFY_FD 4
#define MASTER_STATUS_FD 5
#define MASTER_DEAD_FD 6
#define MASTER_CONFIG_FD 7
#define MASTER_LISTEN_FD_FIRST 8
#define MASTER_LOGIN_TIMEOUT_SECS (3*60)
#define MASTER_AUTH_SERVER_TIMEOUT_SECS (MASTER_LOGIN_TIMEOUT_SECS - 30)
#define MASTER_AUTH_LOOKUP_TIMEOUT_SECS (MASTER_AUTH_SERVER_TIMEOUT_SECS + 5)
#endif