(use-modules (opencog))
(DatalogAst "likes(john, mary).")
(cog-outgoing-atom (DatalogAst "likes(john, mary).") 0)
(DatalogAst "girl(sue) :- daughter(sue,mary).")
(DatalogAst "friends(X, Y) :- likes(X, Y), likes(Y, X).")
(DatalogAst "likes('John', car(bmw)).")