(load "../rules/crisp-modus-ponens-rule.scm")
(load "../rules/crisp-deduction-rule.scm")
(define crisp-rbs (ConceptNode "crisp-rule-base"))
(define (crisp-fc source)
  (cog-fc crisp-rbs source))
(define (crisp-bc target)
  (cog-bc crisp-rbs target))
(define crisp-modus-ponens-tv (stv 0.4 0.9))
(define crisp-deduction-tv (stv 0.6 0.9))
(define crisp-rules (list (list crisp-modus-ponens-rule-name crisp-modus-ponens-tv)
                          (list crisp-deduction-rule-name crisp-deduction-tv)))
(ure-add-rules crisp-rbs crisp-rules)
(ure-set-maximum-iterations crisp-rbs 20)