(load "../rules/crisp-deduction-rule.scm")
(define crisp-deduction-rbs (ConceptNode "crisp-deduction-rule-base"))
(define (crisp-deduction-fc source)
(cog-fc crisp-deduction-rbs source))
(define (crisp-deduction-bc target)
(cog-bc crisp-deduction-rbs target))
(ure-add-rules crisp-deduction-rbs (list crisp-deduction-rule-name))
(ure-set-num-parameter crisp-deduction-rbs "URE:maximum-iterations" 20)
(ure-set-fuzzy-bool-parameter crisp-deduction-rbs "URE:attention-allocation" 0)