package middlewares
import (
"github.com/golang-module/carbon"
"github.com/labstack/echo/v4"
"github.com/labstack/echo/v4/middleware"
)
func CORS() echo.MiddlewareFunc {
return middleware.CORSWithConfig(middleware.CORSConfig{
AllowOriginFunc: func(origin string) (bool, error) {
return true, nil
},
AllowHeaders: []string{
echo.HeaderAccept,
echo.HeaderAcceptEncoding,
echo.HeaderAllow,
echo.HeaderAuthorization,
echo.HeaderContentDisposition,
echo.HeaderContentEncoding,
echo.HeaderContentLength,
echo.HeaderContentType,
echo.HeaderCookie,
echo.HeaderSetCookie,
echo.HeaderIfModifiedSince,
echo.HeaderLastModified,
echo.HeaderLocation,
echo.HeaderRetryAfter,
echo.HeaderUpgrade,
echo.HeaderVary,
echo.HeaderWWWAuthenticate,
echo.HeaderXForwardedFor,
echo.HeaderXForwardedProto,
echo.HeaderXForwardedProtocol,
echo.HeaderXForwardedSsl,
echo.HeaderXUrlScheme,
echo.HeaderXHTTPMethodOverride,
echo.HeaderXRealIP,
echo.HeaderXRequestID,
echo.HeaderXCorrelationID,
echo.HeaderXRequestedWith,
echo.HeaderServer,
echo.HeaderOrigin,
echo.HeaderCacheControl,
echo.HeaderConnection,
echo.HeaderAccessControlRequestMethod,
echo.HeaderAccessControlRequestHeaders,
echo.HeaderAccessControlAllowOrigin,
echo.HeaderAccessControlAllowMethods,
echo.HeaderAccessControlAllowHeaders,
echo.HeaderAccessControlAllowCredentials,
echo.HeaderAccessControlExposeHeaders,
echo.HeaderAccessControlMaxAge,
echo.HeaderStrictTransportSecurity,
echo.HeaderXContentTypeOptions,
echo.HeaderXXSSProtection,
echo.HeaderXFrameOptions,
echo.HeaderContentSecurityPolicy,
echo.HeaderContentSecurityPolicyReportOnly,
echo.HeaderXCSRFToken,
echo.HeaderReferrerPolicy,
"x-stainless-os",
"x-stainless-lang",
"x-stainless-package-version",
"x-stainless-runtime",
"x-stainless-arch",
"x-stainless-runtime-version",
},
AllowMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"},
MaxAge:       carbon.SecondsPerWeek,
ExposeHeaders: []string{
"Traceparent",
echo.HeaderContentType,
echo.HeaderContentLength,
echo.HeaderContentEncoding,
echo.HeaderContentDisposition,
},
})
}