(include "cogserver.scm")
(display "Fetch all disjuncts. This may take 5-10 minutes.\n")
(display "If this is taking longer, your datasets might be too big!\n")
(display "In this case, review the README about trimming.\n")
(define cset-obj (make-pseudo-cset-api))
(cset-obj 'fetch-pairs)
(define star-obj cset-obj)
(fetch-atom (AnchorNode "data logger"))
(print-matrix-summary-report star-obj)