(load "cogserver.scm")
(display "Fetch all words from database. This may take several minutes.\n")
(load-atoms-of-type 'WordNode)
(display "Fetch all word-pairs. This may take well over half-an-hour!\n")
(define pair-obj (make-any-link-api))
(define star-obj (add-pair-stars pair-obj))
(pair-obj 'fetch-pairs)
(catch #t
	(lambda () ((add-report-api star-obj) 'num-pairs))
	(lambda (key . args)
		(format #t "Word pair marginals missing; computing them now.\n")
		(batch-pairs star-obj)
		#f))
(print-matrix-summary-report star-obj)