#define	mpdighi  (mpdigit)(1U<<(Dbits-1))
#define DIGITS(x) ((Dbits - 1 + (x))/Dbits)
#define MAXUINT ((uint)-1)
#define MAXINT (MAXUINT>>1)
#define MININT (MAXINT+1)
#define MAXUVLONG ((uvlong) ~0)
#define MAXVLONG (MAXUVLONG>>1)
#define MINVLONG (MAXVLONG+((uvlong) 1))