(use-modules (opencog))
(define-module (opencog asmoses)
  #:use-module (opencog)
  #:use-module (opencog asmoses-config)
)
(load-extension (string-append atom_types_path "libasmoses_types") "asmoses_types_init")
(load-from-path  "opencog/asmoses/types/atom_types.scm")
(export)