typedef struct object *pobj;
extern void gc_mark(pobj);
extern void gc_unmark(pobj);
extern int gc_marked(pobj);
extern int n_children(pobj);
extern pobj child_n(pobj, int);
extern int root_size(void);
extern pobj root_elt(int);
extern void clear_freelist(void);
extern void add_to_free_list(pobj);
extern int N_OBJS;
extern pobj obj_number(int);