typedef struct PhysUart PhysUart;
typedef struct Uart Uart;
struct PhysUart
{
char*	name;
Uart*	(*pnp)(void);
void	(*enable)(Uart*, int);
void	(*disable)(Uart*);
void	(*kick)(Uart*);
void	(*dobreak)(Uart*, int);
int	(*baud)(Uart*, int);
int	(*bits)(Uart*, int);
int	(*stop)(Uart*, int);
int	(*parity)(Uart*, int);
void	(*modemctl)(Uart*, int);
void	(*rts)(Uart*, int);
void	(*dtr)(Uart*, int);
long	(*status)(Uart*, void*, long, long);
void	(*fifo)(Uart*, int);
void	(*power)(Uart*, int);
int	(*getc)(Uart*);
void	(*putc)(Uart*, int);
};
enum {
Stagesize=	1024
};
struct Uart
{
void*	regs;
void*	saveregs;
char*	name;
ulong	freq;
int	bits;
int	stop;
int	parity;
int	baud;
PhysUart*phys;
int	console;
int	special;
Uart*	next;
QLock;
int	type;
int	dev;
int	opens;
int	enabled;
Uart	*elist;
int	perr;
int	ferr;
int	oerr;
int	berr;
int	serr;
int	(*putc)(Queue*, int);
Queue	*iq;
Queue	*oq;
Lock	rlock;
uchar	istage[Stagesize];
uchar	*iw;
uchar	*ir;
uchar	*ie;
Lock	tlock;
uchar	ostage[Stagesize];
uchar	*op;
uchar	*oe;
int	drain;
int	modem;
int	xonoff;
int	blocked;
int	cts, dsr, dcd, dcdts;
int	ctsbackoff;
int	hup_dsr, hup_dcd;
int	dohup;
Rendez	r;
};
extern Uart*	consuart;
extern int	uartctl(Uart*, char*);
extern int	uartgetc(void);
extern void	uartkick(void*);
extern void	uartmouse(Uart*, int (*)(Queue*, int), int);
extern void	uartsetmouseputc(Uart*, int (*)(Queue*, int));
extern void	uartputc(int);
extern void	uartputs(char*, int);
extern void	uartrecv(Uart*, char);
extern Uart*	uartsetup(Uart*);
extern int		uartstageoutput(Uart*);