typedef struct Flash Flash;
struct Flash {
QLock;
Flash*	next;
char*	name;
void*	addr;
ulong	size;
void *	archdata;
int	(*reset)(Flash*);
int	(*eraseall)(Flash*);
int	(*erasezone)(Flash*, int);
int	(*read)(Flash*, ulong, void*, long);
int	(*write)(Flash*, ulong, void*, long);
int	(*suspend)(Flash*);
int	(*resume)(Flash*);
int	(*attach)(Flash*);
uchar	id;
uchar	devid;
int	width;
int	erasesize;
void*	data;
ulong	unusable;
};
void	addflashcard(char*, int (*)(Flash*));
int	archflashreset(int instance, char*, int, void**, long*, void **archdata);
int	archflash12v(int);
void	archflashwp(void *archdata, int);
void archnand_init(void *archdata);
void archnand_claim(void *archdata, int claim);
void archnand_setCLEandALE(void *archdata, int cle, int ale);
void archnand_write(void *archdata, void *buf, int len);
void archnand_read(void *archdata, void *buf, int len);