(use-modules (opencog))
(use-modules (opencog logger))
(cog-logger-set-timestamp! #f)
(cog-logger-set-stdout! #t)
(cog-logger-set-sync! #t)
(define initial-as (cog-atomspace))
(define auxiliary-as (cog-new-atomspace))
(define pre-pre-as (cog-set-atomspace! auxiliary-as))
(define auxiliary-A (Concept "A"))
(define pre-as (cog-set-atomspace! (cog-atomspace auxiliary-A)))
(cog-logger-info "[1] current as = ~a" (cog-atomspace))
(cog-logger-info "[1] auxiliary-as = ~a" auxiliary-as)
(cog-logger-info "[1] pre-as = ~a" pre-as)
(cog-set-atomspace! pre-as)
(cog-logger-info "[2] current as = ~a" (cog-atomspace))
(cog-logger-info "[2] auxiliary-as = ~a" auxiliary-as)
(cog-set-atomspace! pre-pre-as)
(cog-logger-info "[3] current as = ~a" (cog-atomspace))
(cog-logger-info "[3] initial-as = ~a" initial-as)
(define pre-as-again (cog-set-atomspace! auxiliary-as))
(define A (Concept "A"))
(cog-set-atomspace! pre-as-again)
(gc)
(sleep 1)
(define A-as (cog-atomspace A))