(use-modules (opencog) (opencog test-runner))
(use-modules (opencog python))
(opencog-test-runner)
(define t "opencog-python-sniff-test")
(test-begin t)
(define rc (python-eval "print ('Hello world\\n', 2+2)"))
(define expected "Hello world\n 4\n")
(define expected-in-cxxtest "")
(format #t "python-eval returned this: >>~A<<\n" rc)
(test-assert "Oh no! python-eval is borken!"
(or (string=? rc expected)
(string=? rc expected-in-cxxtest)))
(test-end t)
(opencog-test-end)