(use-modules (opencog)
             (opencog test-runner))
(opencog-test-runner)
(define t "opencog-test-runner-fail")
(test-begin t)
(test-equal "Failing-test" (Node "a") (Link))
(test-end t)
(opencog-test-end)