(use-modules (opencog)
(opencog test-runner))
(opencog-test-runner)
(define t "opencog-test-runner-pass")
(test-begin t)
(test-equal "Passing-test" (Node "a") (Node "a"))
(test-end t)
(opencog-test-end)