(define counter (ConceptNode "asdf"))
(define (test-incr-cnt) (cog-inc-count! counter 1))
(define key (PredicateNode "key"))
(define (test-incr-value) (cog-inc-value! counter key 0.5 3))
(define partner (ConceptNode "partner"))
(define pare (ListLink partner counter))
(define recount (cog-get-partner pare partner))
(define evl (EvaluationLink (WordNode "asdf") pare))
(define rrcnt (cog-pred-get-partner evl partner))
(define ref (ReferenceLink (ConceptNode "asdf") (WordNode "pqrs")))
(define wref (car (cog-get-link 'ReferenceLink 'ConceptNode (WordNode "pqrs"))))
(define cpts (Set (cog-get-atoms 'ConceptNode)))
(define cpts-n-subtypes (Set (cog-get-atoms 'ConceptNode #t)))
(define nodes-n-subtypes (Set (cog-get-atoms 'Node #t)))
(define x-cpts (Set (ConceptNode "asdf") (ConceptNode "partner")))
(define x-cpts-n-subtypes x-cpts)
(define x-nodes-n-subtypes (Set
(ConceptNode "asdf")
(ConceptNode "partner")
(PredicateNode "key")
(WordNode "asdf")
(WordNode "pqrs")))