(load "kb.scm")
(load "pln-config.scm")
(cog-execute! implication-total-instantiation-rule)
(cog-execute! implication-scope-to-implication-rule)
(cog-execute! predicate-lambda-evaluation-rule)
(cog-execute! inversion-implication-rule)
(cog-execute! implication-implicant-conjunction-rule)
(cog-execute! and-lambda-factorization-double-implication-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! implication-to-implication-scope-rule)
(for-each (lambda (i) (cog-execute! implication-total-instantiation-rule)) (iota 10))
(cog-execute! equivalence-scope-distribution-rule)
(cog-execute! equivalence-to-implication-rule)
(cog-execute! implication-to-implication-scope-rule)
(cog-execute! implication-total-instantiation-rule)
(define results (cog-execute! and-introduction-grounded-evaluation-rule))