#ifndef _SYS_SOCKET_H
# error "Never include <bits/socket_type.h> directly; use <sys/socket.h> instead."
#endif
enum __socket_type
{
SOCK_STREAM = 1,
#define SOCK_STREAM SOCK_STREAM
SOCK_DGRAM = 2,
#define SOCK_DGRAM SOCK_DGRAM
SOCK_RAW = 3,
#define SOCK_RAW SOCK_RAW
SOCK_RDM = 4,
#define SOCK_RDM SOCK_RDM
SOCK_SEQPACKET = 5,
#define SOCK_SEQPACKET SOCK_SEQPACKET
SOCK_DCCP = 6,
#define SOCK_DCCP SOCK_DCCP
SOCK_PACKET = 10,
#define SOCK_PACKET SOCK_PACKET
SOCK_CLOEXEC = 02000000,
#define SOCK_CLOEXEC SOCK_CLOEXEC
SOCK_NONBLOCK = 00004000
#define SOCK_NONBLOCK SOCK_NONBLOCK
};