#define HAVE_VPRINTF 1
#define RETSIGTYPE void
#define STDC_HEADERS 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_DUP2 1
#define HAVE_MEMCHR 1
#define HAVE_SIGACTION 1
#define HAVE_STRCHR 1
#define HAVE_STRERROR 1
#define HAVE_TMPNAM 1
#define HAVE_DIRENT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1