(use-modules (srfi srfi-1))
(use-modules (ice-9 threads))
(use-modules (opencog logger))
(use-modules (opencog randgen))
(use-modules (opencog exec))
(use-modules (opencog ure))
(use-modules (opencog miner))
(define icl-logger (cog-new-logger))
(cog-logger-set-component! icl-logger "ICL")
(define (icl-logger-set-level! l) (cog-logger-set-level! icl-logger l))
(define (icl-logger-get-level) (cog-logger-get-level icl-logger))
(define (icl-logger-set-stdout! . args) (apply cog-logger-set-stdout! (cons icl-logger args)))
(define (icl-logger-set-sync! . args) (apply cog-logger-set-sync! (cons icl-logger args)))
(define (icl-logger-error-enabled?) (cog-logger-error-enabled? icl-logger))
(define (icl-logger-warn-enabled?) (cog-logger-warn-enabled? icl-logger))
(define (icl-logger-info-enabled?) (cog-logger-info-enabled? icl-logger))
(define (icl-logger-debug-enabled?) (cog-logger-debug-enabled? icl-logger))
(define (icl-logger-fine-enabled?) (cog-logger-fine-enabled? icl-logger))
(define (icl-logger-error . args) (apply cog-logger-error (cons icl-logger args)))
(define (icl-logger-warn . args) (apply cog-logger-warn (cons icl-logger args)))
(define (icl-logger-info . args) (apply cog-logger-info (cons icl-logger args)))
(define (icl-logger-debug . args) (apply cog-logger-debug (cons icl-logger args)))
(define (icl-logger-fine . args) (apply cog-logger-fine (cons icl-logger args)))
(define (icl-logger-flush) (cog-logger-flush icl-logger))
(define alphabet-list
(string->list "abcdefghijklmnopqrstuvwxyz"))
(define (alphabet-ref i)
(list->string (list (list-ref alphabet-list i))))
(define (gen-random-target)
(let* ((Ai (cog-randgen-randint 24))
(offset (+ Ai 2))
(Bi (+ offset (random (- 26 offset))))
(A (alphabet-ref Ai))
(B (alphabet-ref Bi)))
(Inheritance (Concept A) (Concept B))))
(define (gen-random-targets N)
(if (= N 0)
'()
(cons (gen-random-target) (gen-random-targets (- N 1)))))
(define (icl-logger-info-atomspace as)
(if (icl-logger-info-enabled?)
(icl-logger-info "~a" (atomspace->string as))))
(define (icl-logger-debug-atomspace as)
(if (icl-logger-debug-enabled?)
(icl-logger-debug "~a" (atomspace->string as))))
(define (icl-logger-fine-atomspace as)
(if (icl-logger-fine-enabled?)
(icl-logger-fine "~a" (atomspace->string as))))
(define (atomspace->string as)
(let* ((old-as (cog-set-atomspace! as))
(all-atoms (get-all-atoms))
(all-atoms-strings (map atom->string (get-all-atoms)))
(all-atoms-string (apply string-append all-atoms-strings)))
(cog-set-atomspace! old-as)
all-atoms-string))
(define (get-all-atoms)
(apply append (map cog-get-atoms (cog-get-types))))
(define (atom->string h)
(if (null? (cog-incoming-set h))
(format #f "~a" h)
""))
(define (remove-dangling-atoms as)
(let* ((old-as (cog-set-atomspace! as)))
(remove-dangling-atom-list (get-all-atoms))
(cog-set-atomspace! old-as)))
(define (remove-dangling-atom-list atoms)
(for-each remove-dangling-atom atoms))
(define (remove-dangling-atom atom)
(if (and (cog-atom? atom)
(null-incoming-set? atom)
(null-confidence? atom))
(let* ((outgoings (cog-outgoing-set atom)))
(cog-delete atom)
(remove-dangling-atom-list outgoings))))
(define (remove-almost-false-atoms)
(remove-almost-false-atom-list (get-all-atoms)))
(define (remove-almost-false-atom-list atoms)
(for-each remove-almost-false-atom atoms))
(define (remove-almost-false-atom atom)
(if (and (cog-atom? atom)
(not (null-confidence? atom))
(almost-null-strength? atom))
(extract-hypergraph atom)))
(define (null-incoming-set? atom)
(null? (cog-incoming-set atom)))
(define (null-confidence? atom)
(= 0 (cog-confidence atom)))
(define (almost-null-strength? atom)
(< (cog-mean atom) 0.1))
(define (cp-as src dst)
(let ((old-as (cog-set-atomspace! src)))
(icl-cp-all dst)
(cog-set-atomspace! old-as)))
(define (cog-get-atoms-as as type)
(let ((old-as (cog-set-atomspace! as))
(atoms (cog-get-atoms type)))
(cog-set-atomspace! old-as)
atoms))
(define (clear-as as)
(let ((old-as (cog-set-atomspace! as)))
(clear)
(cog-set-atomspace! old-as)))
(define (apply-rule rule . atoms)
(let ((tmp-as (cog-new-atomspace)))
(icl-cp tmp-as (cons rule atoms))
(let* ((init-as (cog-set-atomspace! tmp-as))
(results (cog-outgoing-set (cog-execute! rule)))
(init-results (icl-cp init-as results)))
(cog-set-atomspace! init-as)
init-results)))
(define (repeat-apply-rule rule n)
(if (< 0 n)
(let* ((results-n (cog-outgoing-set (cog-execute! rule)))
(results-rec (repeat-apply-rule rule (- n 1))))
(lset-union equal? results-n results-rec))
'()))
(define (count-atoms-as as)
(let ((old-as (cog-set-atomspace! as))
(result (count-all)))
(cog-set-atomspace! old-as)
result))
(define (union-as dst atomspaces)
(for-each (lambda (src) (cp-as src dst)) atomspaces))
(define (icl-cp AS LST)
"
icl-cp AS LST - Copy the atoms in LST to the given atomspace AS and
return the list of atoms now in AS. Only overwrite
existing TVs by TVs with higher confidences.
"
(define initial-as (cog-atomspace))
(if (equal? AS initial-as)
(error "Destination atomspace is the same as the current atomspace\n"))
(cog-set-atomspace! AS)
(let ((results (map icl-cp-atom LST)))
(cog-set-atomspace! initial-as)
results))
(define (icl-cp-atom a)
"
icl-cp AS LST - Copy ATOM to current atomspace and return the atom once
copied. If ATOM is already in the current atomspace,
then only overwrite the TV if its confidence is lower
than ATOM's TV confidence.
"
(let* ((a-type (cog-type a))
(a-out (cog-outgoing-set a))
(a-name (cog-name a))
(a-tv (cog-tv a))
(a-cp-out (map icl-cp-atom a-out))
(a-cp (if (cog-node? a)
(cog-new-node a-type a-name)
(cog-new-link a-type a-cp-out))))
(cog-merge-hi-conf-tv! a-cp a-tv)))
(define (icl-cp-all AS)
"
icl-cp-all AS - Copy all atoms in the current atomspace to the given
atomspace AS and returns the list of copied atoms.
"
(icl-cp AS (apply append (map cog-get-atoms (cog-get-types)))))
(define (icl-count-all AS)
"
Return the total number of atoms in atomspace AS
"
(let ((old-as (cog-set-atomspace! AS))
(as-count (count-all)))
(cog-set-atomspace! old-as)
as-count))
(define (preproof-of-predicate)
(Predicate "URE:BC:preproof-of"))
(define (preproof-of arg)
(Evaluation
(preproof-of-predicate)
arg))
(define (preproof-of? atom)
(and (cog-atom? atom)
(equal? (cog-type atom) 'EvaluationLink)
(equal? (cog-outgoing-atom atom 0) (preproof-of-predicate))))
(define (expand input output)
(Execution
(Schema "URE:BC:expand-and-BIT")
input
output))
(define (preproof-of->inference ppo)
(and (preproof-of? ppo)
(cog-outgoing-atom (cog-outgoing-atom ppo 1) 0)))
(define (dontexec-typed x)
(TypedVariable x (Type "DontExecLink")))
(define (get-inference-rules as)
(let* ((old-as (cog-set-atomspace! (cog-new-atomspace as)))
(vardecl (VariableList
(dontexec-typed (Variable "$A"))
(dontexec-typed (Variable "$B"))
(dontexec-typed (Variable "$R"))
(Variable "$L")))
(input (List
(Variable "$A")
(Variable "$L")
(Variable "$R")))
(pattern (expand input (Variable "$B")))
(bind (Bind vardecl pattern (Variable "$R")))
(results (cog-execute! bind))
(get-first-outgoing (lambda (x) (cog-outgoing-atom x 0)))
(inference-rules (map get-first-outgoing (cog-outgoing-set results))))
(cog-set-atomspace! old-as)
inference-rules))