(load "icl-parameters.scm")
(load "icl-utilities.scm")
(load "mk-history.scm")
(load "mk-control-rules.scm")
(load "mine-control-rules.scm")
(cog-randgen-set-seed! 1)
(cog-logger-set-level! "info")
(icl-logger-set-level! "info")
(ure-logger-set-level! "info")
(icl-logger-set-stdout! #t)
(cog-logger-set-sync! #t)
(icl-logger-set-sync! #t)
(ure-logger-set-sync! #t)
(define (reload)
  (clear)
  (load "kb.scm")
  (load "pln-rb.scm"))
(define targets-as (cog-new-atomspace))
(define (run-experiment)
  (icl-logger-info "Start experiment")
  (let* ((default-as (cog-set-atomspace! targets-as))
         (targets (gen-random-targets pss)))
    (cog-set-atomspace! default-as)
    (map (lambda (i) (run-iteration targets i)) (iota niter))))
(define (run-iteration targets i)
  (icl-logger-info "Run iteration (i=~a/~a)" (+ i 1) niter)
  (let* (
         (run (lambda (j)
                (let* (
                       (trg (list-ref targets j))
                       (result (run-bc-mk-history trg i j)))
                  result)))
         (histories-results (map run (iota pss)))
         (histories (map car histories-results))
         (results (map cdr histories-results))
         (sol_count (count values results)))
    (icl-logger-info "Number of solved problems = ~a/~a" sol_count pss)
    (icl-logger-info "Move all problem histories to history-as")
    (union-as history-as histories)
    (icl-logger-info "Remove dangling atoms from history-as")
    (remove-dangling-atoms history-as)
    (icl-logger-info "Build inference control rules from history-as")
    (mk-control-rules)
    results))
(define (run-bc-mk-history target i j)
  (let* ((trace-as (cog-new-atomspace))
         (result (run-bc target i j trace-as))
         (history-as (mk-history trace-as)))
    (cons history-as result)))
(define (run-bc target i j trace-as)
  (icl-logger-info "Run BC (i=~a/~a,j=~a/~a) with target:\n~a"
                   (+ i 1) niter (+ j 1) pss target)
  (reload)
  (let* ((result (pln-bc target #:trace-as trace-as #:control-as control-as))
         (result-size (length (cog-outgoing-set result)))
         (success (if (= 1 result-size)
                      (tv->bool (cog-tv (gar result)))
                      #f)))
    (icl-logger-info (if success "Success" "Failure"))
    success))
(run-experiment)