(define (gen-knowledge-base)
(gen-inheritance-contiguous-letters)
(gen-a-before-all-letters-stupid))
(define (gen-a-before-all-letters-smart)
(gen-a-inherits-all-letters-smart-rule))
(define (gen-a-before-all-letters-stupid)
(gen-a-before-all-letters-stupid-facts)
(gen-X-is-before-Y-then-X-inherits-Y-rule))
(define (gen-inheritance-contiguous-letters)
(let* ((letters (gen-letters)))
(map gen-alphabet-letter-member letters)
(map gen-inheritance-letter-pair (drop-right letters 1) (cdr letters))))
(define (gen-a-inherits-all-letters-smart-rule)
(let* ((X (Variable "$X"))
(a (Concept "a"))
(ConceptT (Type "ConceptNode")))
(ImplicationScope (stv 1 1)
(TypedVariable X ConceptT)
(Member X latin-alphabet)
(Inheritance a X))))
(define (gen-a-before-all-letters-stupid-facts)
(let* ((letters (gen-letters))
(a (Concept "a"))
(a-before-letters (lambda (X) (gen-alphabetical-order-letter-pair a X))))
(map a-before-letters (cdr letters))))
(define (gen-X-is-before-Y-then-X-inherits-Y-rule)
(let* ((X (Variable "$X"))
(Y (Variable "$Y"))
(ConceptT (Type "ConceptNode")))
(ImplicationScope (stv 1 1)
(VariableList
(TypedVariable X ConceptT)
(TypedVariable Y ConceptT))
(Evaluation alphabetical-order (List X Y))
(Inheritance X Y))))
(define (gen-letters)
(map gen-letter alphabet-list (iota 26)))
(define (gen-letter X i)
(Concept (list->string (list X)) (stv (/ (+ i 1) 26) 1)))
(define latin-alphabet
(Concept "latin-alphabet"))
(define (gen-alphabet-letter-member X)
(Member (stv 1 1) X latin-alphabet))
(define (gen-inheritance-letter-pair X Y)
(Inheritance (stv 1 1) X Y))
(define alphabetical-order
(Predicate "alphabetical-order"))
(define (gen-alphabetical-order-letter-pair X Y)
(Evaluation (stv 1 1) alphabetical-order (List X Y)))
(gen-knowledge-base)