(define history-as (cog-new-atomspace))
(define (mk-history trace-as)
(let* ((local-history-as (cog-new-atomspace)))
(icl-logger-info "Post-process trace, add to inference history")
(apply-proof-is-preproof trace-as local-history-as)
(apply-preproof-expander-is-preproof trace-as local-history-as)
(apply-and-bit-prior trace-as local-history-as)
(icl-cp local-history-as (cog-get-atoms-as trace-as 'ExecutionLink))
(remove-dangling-atoms local-history-as)
(icl-logger-debug "Size of local history: ~a" (icl-count-all local-history-as))
local-history-as))
(define (apply-proof-is-preproof trace-as history-as)
(let* ((default-as (cog-set-atomspace! trace-as))
(dummy (load "proof-is-preproof.scm"))
(results (cog-execute! proof-is-preproof-rule)))
(icl-cp history-as (cog-outgoing-set results))
(remove-dangling-atoms trace-as)
(extract-hypergraph proof-is-preproof)
(cog-set-atomspace! default-as)))
(define (apply-preproof-expander-is-preproof trace-as history-as)
(let* (
(default-as (cog-set-atomspace! trace-as))
(dummy (load "preproof-expander-is-preproof.scm"))
(results (repeat-apply-rule pep-rule (- piter 1))))
(icl-cp history-as results)
(remove-dangling-atoms trace-as)
(cog-set-atomspace! default-as)))
(define (apply-and-bit-prior trace-as history-as)
(let* (
(default-as (cog-set-atomspace! trace-as))
(dummy (load "and-bit-prior.scm"))
(target (preproof-of
(List
(Variable "$A")
(Variable "$T"))))
(vardecl (VariableList
(dontexec-typed (Variable "$A"))
(Variable "$T")))
(results (abp-bc target #:vardecl vardecl)))
(icl-cp history-as (cog-outgoing-set results))
(remove-dangling-atoms trace-as)
(cog-set-atomspace! default-as)))