(load "../meta-rules/conditional-instantiation-meta-rule.scm")
(load "../rules/fuzzy-conjunction-introduction-rule.scm")
(define ci-rbs (ConceptNode "ci-rbs"))
(ure-add-rule ci-rbs conditional-full-instantiation-meta-rule-name (stv 1 1))
(ure-add-rule ci-rbs fuzzy-conjunction-introduction-2ary-rule-name (stv 1 1))
(ure-set-maximum-iterations ci-rbs 20)
(ure-set-attention-allocation ci-rbs #f)