(use-modules (opencog) (opencog exec))
(load "moses-model.scm")
(load "background-knowledge.scm")
(load "pln-fc-config.scm")
(for-each (lambda (i) (cog-execute! implication-partial-instantiation-rule))
          (iota 2))
(cog-execute! implication-scope-to-implication-rule)
(cog-execute! and-lambda-distribution-rule)
(cog-execute! closed-lambda-evaluation-rule)
(cog-execute! implication-introduction-rule)
(cog-execute! implication-implicant-distribution-rule)
(cog-execute! implication-and-lambda-factorization-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! implication-total-instantiation-rule)
(cog-execute! equivalence-to-implication-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! deduction-implication-rule)
(cog-execute! implication-implicant-disjunction-rule)