(use-modules (srfi srfi-1))
(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-dht))
(dht-open "dht:///test-atomspace")
(dht-bootstrap "dht://localhost:4444")
(define c (Concept "foo"))
(fetch-atom c)
(cog-keys c)
(cog-value c (first (cog-keys c)))
(cog-value c (second (cog-keys c)))
(cog-value c (third (cog-keys c)))
(for-each
	(lambda (key)
		(format #t "Key ~A   has value ~A\n" key (cog-value c key)))
	(cog-keys c))
(fetch-incoming-set c)
(cog-incoming-set c)
(define ll (first (cog-incoming-set c)))
(fetch-incoming-set ll)
(cog-incoming-set ll)
(dht-stats)
(dht-close)