(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "class-data.scm")
(define t-class-connector "class connector merge test")
(test-begin t-class-connector)
(setup-database)
(setup-ej-sections)
(setup-ej-extra)
(define pca (make-pseudo-cset-api))
(define gsc (add-covering-sections pca))
(test-equal 3 (length (gsc 'right-stars (WordClass "e j"))))
(test-equal 3 (length (gsc 'right-stars (WordClass "r s"))))
(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
(gsc 'explode-sections)
(test-equal 18 (length (cog-get-atoms 'CrossSection)))
(test-equal 1 (length (gsc 'right-stars (Word "g"))))
(test-equal 1 (length (gsc 'right-stars (Word "h"))))
(test-equal 4 (length (gsc 'right-stars (WordClass "e j"))))
(test-equal 4 (length (gsc 'right-stars (WordClass "r s"))))
(test-equal 3 (len-type (WordClass "e j") 'Section))
(test-equal 1 (len-type (WordClass "e j") 'CrossSection))
(test-equal 3 (len-type (WordClass "r s") 'Section))
(test-equal 1 (len-type (WordClass "r s") 'CrossSection))
(test-equal 6 (length (cog-get-atoms 'Section)))
(merge gsc (WordClass "e j") (WordClass "r s") 0)
(test-equal 5 (len-type (WordClass "e j") 'Section))
(test-equal 2 (len-type (WordClass "e j") 'CrossSection))
(test-equal 0 (len-type (WordClass "r s") 'Section))
(test-equal 7 (length (gsc 'right-stars (WordClass "e j"))))
(test-equal 5 (length (cog-get-atoms 'Section)))
(test-equal 15 (length (cog-get-atoms 'CrossSection)))
(define epsilon 1.0e-8)
(test-approximate cnt-ej-klm
	(cog-count (car (gsc 'right-stars (WordClass "e j")))) epsilon)
(expected-ej-sections)
(test-approximate (+ cnt-ej-abc cnt-rs-abc) (cog-count sec-ej-abc) epsilon)
(test-approximate cnt-rs-dgh (cog-count sec-ej-dgh) epsilon)
(test-approximate cnt-ej-klm (cog-count sec-ej-klm) epsilon)
(test-approximate (+ cnt-ej-abc cnt-rs-abc) (cog-count xes-b-ej-avc) epsilon)
(test-approximate cnt-ej-klm (cog-count xes-k-ej-vlm) epsilon)
(test-approximate cnt-rs-dgh (cog-count xes-d-ej-vgh) epsilon)
(test-equal 15 (length (cog-get-atoms 'CrossSection)))
(expected-ej-extra-sections)
(test-approximate cnt-rs-abej (cog-count sec-ej-abej) epsilon)
(test-approximate cnt-ej-klrs (cog-count sec-ej-klej) epsilon)
(test-approximate cnt-rs-abej (cog-count xes-ej-ej-abv) epsilon)
(test-approximate cnt-ej-klrs (cog-count xes-ej-ej-klv) epsilon)
(test-assert (check-sections gsc epsilon))
(test-assert (check-crosses gsc epsilon))
(test-assert (check-shapes gsc epsilon))
(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
	epsilon)
(test-end t-class-connector)
(opencog-test-end)