(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "connector-data.scm")
(define (run-test WA WB WC-NAME)
	(setup-e-j-sections)
	(setup-f-sections)
	(define pca (make-pseudo-cset-api))
	(set! gsc (add-covering-sections pca))
	(test-equal 3 (length (gsc 'right-stars (Word "e"))))
	(test-equal 2 (length (gsc 'right-stars (Word "j"))))
	(test-equal 3 (length (gsc 'right-stars (Word "f"))))
	(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
	(gsc 'explode-sections)
	(test-equal 24 (length (cog-get-atoms 'CrossSection)))
	(test-equal 3 (length (gsc 'right-stars (Word "g"))))
	(test-equal 3 (length (gsc 'right-stars (Word "h"))))
	(test-equal 3 (length (gsc 'right-stars (Word "e"))))
	(test-equal 2 (length (gsc 'right-stars (Word "j"))))
	(test-equal 3 (length (gsc 'right-stars (Word "f"))))
	(test-equal 8 (length (cog-get-atoms 'Section)))
	(define frac 0.25)
	(merge gsc WA WB frac)
	(define WC-EJ (WordClassNode WC-NAME))
	(define epsilon 1.0e-8)
	(test-equal 7 (length (cog-get-atoms 'Section)))
	(test-equal 21 (length (cog-get-atoms 'CrossSection)))
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(merge gsc WC-EJ (Word "f") frac)
	(test-equal 1 (length (gsc 'right-stars (Word "e"))))
	(test-equal 0 (length (gsc 'right-stars (Word "j"))))
	(test-equal 0 (length (gsc 'right-stars (Word "f"))))
	(test-equal 3 (length (gsc 'right-stars WC-EJ)))
	(test-equal 4 (length (cog-get-atoms 'Section)))
	(test-equal 12 (length (cog-get-atoms 'CrossSection)))
	(test-approximate (* cnt-e-klm (- 1.0 frac))
		(cog-count (car (gsc 'right-stars (Word "e")))) epsilon)
	(expected-e-j-sections WC-EJ)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count sec-ej-abc) epsilon)
	(test-approximate (+ cnt-e-dgh cnt-j-dgh cnt-f-dgh)
		(cog-count sec-ej-dgh) epsilon)
	(test-approximate (+ cnt-f-klm (* frac cnt-e-klm))
		(cog-count sec-ej-klm) epsilon)
	(test-approximate (* (- 1 frac) cnt-e-klm) (cog-count sec-e-klm) epsilon)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count xes-b-ej-avc) epsilon)
	(test-approximate (+ cnt-f-klm (* frac cnt-e-klm))
		 (cog-count xes-k-ej-vlm) epsilon)
	(test-approximate (* (- 1 frac) cnt-e-klm) (cog-count xes-k-e-vlm) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-assert (check-shapes gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
)
(define t-merge-into-cluster "simple merge-into-cluster test")
(test-begin t-merge-into-cluster)
	(setup-database)
	(run-test (Word "e") (Word "j") "e j")
	(setup-database)
	(run-test (Word "j") (Word "e") "j e")
(test-end t-merge-into-cluster)
(opencog-test-end)