(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "balance-data.scm")
(define (run-balance WA WB WAB-NAME)
(setup-a-b-sections)
(define pca (make-pseudo-cset-api))
(define gsc (add-covering-sections pca))
(test-equal 1 (length (gsc 'right-stars (Word "a"))))
(test-equal 1 (length (gsc 'right-stars (Word "b"))))
(test-equal 1 (length (gsc 'right-stars (Word "c"))))
(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
(gsc 'explode-sections)
(test-equal 9 (length (cog-get-atoms 'CrossSection)))
(define totcross (fold + 0 (map cog-count (cog-get-atoms 'CrossSection))))
(test-equal 4 (length (gsc 'right-stars (Word "a"))))
(test-equal 1 (length (gsc 'right-stars (Word "b"))))
(test-equal 1 (length (gsc 'right-stars (Word "c"))))
(test-equal 1 (length (gsc 'right-stars (Word "k"))))
(test-equal 1 (length (gsc 'right-stars (Word "m"))))
(test-equal 3 (length (cog-get-atoms 'Section)))
(merge gsc WA WB 1)
(define WC-AB (WordClassNode WAB-NAME))
(test-equal 0 (length (gsc 'right-stars (Word "a"))))
(test-equal 0 (length (gsc 'right-stars (Word "b"))))
(test-equal 1 (length (gsc 'right-stars (Word "c"))))
(test-equal 4 (length (gsc 'right-stars WC-AB)))
(test-equal 2 (length (cog-get-atoms 'Section)))
(test-equal 7 (length (cog-get-atoms 'CrossSection)))
(define tot-ab
(fold (lambda (atm cnt) (+ cnt (cog-count atm))) 0
(gsc 'right-stars WC-AB)))
(define epsilon 1.0e-8)
(test-approximate (+ cnt-a-gh cnt-b-gh (* 3 cnt-c-aaa)) tot-ab epsilon)
(expected-a-b-sections WC-AB)
(test-approximate (+ cnt-a-gh cnt-b-gh) (cog-count sec-ab-gh) epsilon)
(test-approximate cnt-c-aaa (cog-count sec-c-aaa) epsilon)
(test-approximate cnt-c-aaa (cog-count xes-k-c-vaaam) epsilon)
(test-approximate cnt-c-aaa (cog-count xes-a-c-kvaam) epsilon)
(test-approximate cnt-c-aaa (cog-count xes-a-c-kavam) epsilon)
(test-approximate cnt-c-aaa (cog-count xes-a-c-kaavm) epsilon)
(test-approximate cnt-c-aaa (cog-count xes-m-c-kaaav) epsilon)
(test-assert (check-sections gsc epsilon))
(test-assert (check-crosses gsc epsilon))
(test-assert (check-shapes gsc epsilon))
(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
epsilon)
(test-approximate totcross (fold + 0 (map cog-count (cog-get-atoms 'CrossSection)))
epsilon)
)
(define t-start-cluster "connector balance test")
(test-begin t-start-cluster)
(setup-database)
(run-balance (Word "a") (Word "b") "a b")
(setup-database)
(run-balance (Word "b") (Word "a") "b a")
(test-end t-start-cluster)
(opencog-test-end)