(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "connector-data.scm")
(define (run-test WA WB WC-NAME)
	(setup-e-j-sections)
	(setup-f-sections)
	(setup-j-double-e)
	(setup-f-double-e)
	(define pca (make-pseudo-cset-api))
	(set! gsc (add-covering-sections pca))
	(test-equal 3 (length (gsc 'right-stars (Word "e"))))
	(test-equal 4 (length (gsc 'right-stars (Word "j"))))
	(test-equal 5 (length (gsc 'right-stars (Word "f"))))
	(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
	(gsc 'explode-sections)
	(test-equal 36 (length (cog-get-atoms 'CrossSection)))
	(test-equal 3 (length (gsc 'right-stars (Word "g"))))
	(test-equal 5 (length (gsc 'right-stars (Word "h"))))
	(test-equal 11 (length (gsc 'right-stars (Word "e"))))
	(test-equal 4 (length (gsc 'right-stars (Word "j"))))
	(test-equal 5 (length (gsc 'right-stars (Word "f"))))
	(test-equal 3 (len-type (Word "e") 'Section))
	(test-equal 8 (len-type (Word "e") 'CrossSection))
	(test-equal 4 (len-type (Word "j") 'Section))
	(test-equal 0 (len-type (Word "j") 'CrossSection))
	(test-equal 5 (len-type (Word "f") 'Section))
	(test-equal 0 (len-type (Word "f") 'CrossSection))
	(test-equal 12 (length (cog-get-atoms 'Section)))
	(define frac1 0.25)
	(merge gsc WA WB frac1)
	(define WC-EJ (WordClassNode WC-NAME))
	(test-equal 15 (length (cog-get-atoms 'Section)))
	(test-equal 1 (length (filter-type (Word "e") 'Section)))
	(test-equal 5 (length (filter-type WC-EJ 'Section)))
	(test-equal 8 (length (filter-type (Word "e") 'CrossSection)))
	(test-equal 8 (length (filter-type WC-EJ 'CrossSection)))
	(define epsilon 1.0e-8)
	(expected-e-j-sections WC-EJ)
	(test-approximate (+ cnt-e-abc cnt-j-abc) (cog-count sec-ej-abc) epsilon)
	(test-approximate (+ cnt-e-dgh cnt-j-dgh) (cog-count sec-ej-dgh) epsilon)
	(test-approximate (* frac1 cnt-e-klm) (cog-count sec-ej-klm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm) (cog-count sec-e-klm) epsilon)
	(test-approximate (+ cnt-e-abc cnt-j-abc) (cog-count xes-b-ej-avc) epsilon)
	(test-approximate (* frac1 cnt-e-klm) (cog-count xes-k-ej-vlm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm) (cog-count xes-k-e-vlm) epsilon)
	(expected-j-double-e WC-EJ)
	(test-approximate (* frac1 cnt-j-ebe) (cog-count sec-ej-vbv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-ebe) (cog-count sec-j-ebe) epsilon)
	(test-approximate (* frac1 cnt-j-eeh) (cog-count sec-ej-vvh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-eeh) (cog-count sec-j-eeh) epsilon)
	(expected-f-double-e WC-EJ)
	(test-approximate (* frac1 cnt-f-ebe) (cog-count sec-f-ejbej) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-ebe) (cog-count sec-f-ebe) epsilon)
	(test-approximate (* frac1 cnt-f-eeh) (cog-count sec-f-ejejh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-eeh) (cog-count sec-f-eeh) epsilon)
	(test-approximate (* frac1 cnt-f-ebe) (cog-count xes-ej-f-ejbv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-ebe) (cog-count xes-e-f-ebv) epsilon)
	(test-approximate (* frac1 cnt-f-eeh) (cog-count xes-ej-f-vejh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-eeh) (cog-count xes-e-f-veh) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
	(format #t "Now merging 'f' into 'ej'\n")
	(define frac2 0.35)
	(merge gsc WC-EJ (Word "f") frac2)
	(test-equal 4 (length (filter-type WC-EJ 'CrossSection)))
	(test-equal 1 (len-type (Word "e") 'Section))
	(test-equal 8 (len-type (Word "e") 'CrossSection))
	(test-equal 9 (length (gsc 'right-stars (Word "e"))))
	(test-equal 2 (len-type (Word "j") 'Section))
	(test-equal 0 (len-type (Word "j") 'CrossSection))
	(test-equal 2 (length (gsc 'right-stars (Word "j"))))
	(test-equal 2 (len-type (Word "f") 'Section))
	(test-equal 0 (len-type (Word "f") 'CrossSection))
	(test-equal 2 (length (gsc 'right-stars (Word "f"))))
	(test-equal 5 (len-type WC-EJ 'Section))
	(test-equal 4 (len-type WC-EJ 'CrossSection))
	(test-equal 9 (length (gsc 'right-stars WC-EJ)))
	(test-equal 10 (length (cog-get-atoms 'Section)))
	(test-approximate (* cnt-e-klm (- 1.0 frac1))
		(cog-count (car (filter-type (Word "e") 'Section))) epsilon)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count sec-ej-abc) epsilon)
	(test-approximate (+ cnt-e-dgh cnt-j-dgh cnt-f-dgh)
		(cog-count sec-ej-dgh) epsilon)
	(test-approximate (+ (* frac1 cnt-e-klm) cnt-f-klm)
		(cog-count sec-ej-klm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm)
		(cog-count sec-e-klm) epsilon)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count xes-b-ej-avc) epsilon)
	(test-approximate (+ (* frac1 cnt-e-klm) cnt-f-klm)
		(cog-count xes-k-ej-vlm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm) (cog-count xes-k-e-vlm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-ebe) (cog-count sec-j-ebe) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-eeh) (cog-count sec-j-eeh) epsilon)
	(test-approximate (* (- 1 frac1) (- 1 frac2) cnt-f-ebe)
		(cog-count sec-f-ebe) epsilon)
	(test-approximate (* (- 1 frac1) (- 1 frac2) cnt-f-eeh)
		(cog-count sec-f-eeh) epsilon)
	(define expected-sec-ej-vbv-count
		(+ (* frac1 (+ cnt-j-ebe cnt-f-ebe))
			(* frac2 (- 1 frac1) cnt-f-ebe)))
	(test-approximate expected-sec-ej-vbv-count
		(cog-count sec-ej-vbv) epsilon)
	(define expected-sec-ej-vvh-count
		(+ (* frac1 (+ cnt-j-eeh cnt-f-eeh))
			(* frac2 (- 1 frac1) cnt-f-eeh)))
	(test-approximate expected-sec-ej-vvh-count
		(cog-count sec-ej-vvh) epsilon)
	(test-equal 30 (length (cog-get-atoms 'CrossSection)))
	(test-approximate (* (- 1 frac1) cnt-j-ebe) (cog-count xes-e-j-ebv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-eeh) (cog-count xes-e-j-veh) epsilon)
	(test-approximate expected-sec-ej-vbv-count
		(cog-count xes-ej-ej-ebv) epsilon)
	(test-approximate expected-sec-ej-vvh-count
		(cog-count xes-ej-ej-veh) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-assert (check-shapes gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
)
(define t-two-three-cluster "two-connector-2-word 3-cluster merge test")
(test-begin t-two-three-cluster)
	(setup-database)
	(run-test (Word "e") (Word "j") "e j")
	(setup-database)
	(run-test (Word "j") (Word "e") "j e")
(test-end t-two-three-cluster)
(opencog-test-end)