(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "connector-data.scm")
(define (run-test WA WB WC-NAME)
	(setup-e-j-sections)
	(setup-f-sections)
	(setup-j-extra)
	(setup-f-extra)
	(define pca (make-pseudo-cset-api))
	(set! gsc (add-covering-sections pca))
	(test-equal 3 (length (gsc 'right-stars (Word "e"))))
	(test-equal 4 (length (gsc 'right-stars (Word "j"))))
	(test-equal 5 (length (gsc 'right-stars (Word "f"))))
	(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
	(gsc 'explode-sections)
	(test-equal 36 (length (cog-get-atoms 'CrossSection)))
	(test-equal 5 (length (gsc 'right-stars (Word "g"))))
	(test-equal 5 (length (gsc 'right-stars (Word "h"))))
	(test-equal 7 (length (gsc 'right-stars (Word "e"))))
	(test-equal 4 (length (gsc 'right-stars (Word "j"))))
	(test-equal 5 (length (gsc 'right-stars (Word "f"))))
	(test-equal 3 (len-type (Word "e") 'Section))
	(test-equal 4 (len-type (Word "e") 'CrossSection))
	(test-equal 4 (len-type (Word "j") 'Section))
	(test-equal 0 (len-type (Word "j") 'CrossSection))
	(test-equal 5 (len-type (Word "f") 'Section))
	(test-equal 0 (len-type (Word "f") 'CrossSection))
	(test-equal 12 (length (cog-get-atoms 'Section)))
	(define frac1 0.25)
	(merge gsc WA WB frac1)
	(define WC-EJ (WordClassNode WC-NAME))
	(test-equal 15 (length (cog-get-atoms 'Section)))
	(test-equal 1 (length (filter-type (Word "e") 'Section)))
	(test-equal 5 (length (filter-type WC-EJ 'Section)))
	(test-equal 4 (length (filter-type (Word "e") 'CrossSection)))
	(test-equal 4 (length (filter-type WC-EJ 'CrossSection)))
	(define epsilon 1.0e-8)
	(expected-e-j-sections WC-EJ)
	(test-approximate (* frac1 cnt-e-klm) (cog-count sec-ej-klm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm) (cog-count sec-e-klm) epsilon)
	(expected-j-extra-sections WC-EJ)
	(test-approximate (* frac1 cnt-j-abe) (cog-count sec-ej-abv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-abe) (cog-count sec-j-abe) epsilon)
	(test-approximate (* frac1 cnt-j-egh) (cog-count sec-ej-vgh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-egh) (cog-count sec-j-egh) epsilon)
	(expected-f-extra-sections WC-EJ)
	(test-approximate (* frac1 cnt-f-abe) (cog-count sec-f-abej) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-abe) (cog-count sec-f-abe) epsilon)
	(test-approximate (* frac1 cnt-f-egh) (cog-count sec-f-ejgh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-egh) (cog-count sec-f-egh) epsilon)
	(test-approximate (* frac1 cnt-f-abe) (cog-count xes-ej-f-abv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-abe) (cog-count xes-e-f-abv) epsilon)
	(test-approximate (* frac1 cnt-f-egh) (cog-count xes-ej-f-vgh) epsilon)
	(test-approximate (* (- 1 frac1) cnt-f-egh) (cog-count xes-e-f-vgh) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
	(format #t "Now merging 'f' into 'ej'\n")
	(define frac2 0.35)
	(merge gsc WC-EJ (Word "f") frac2)
	(test-equal 2 (length (filter-type WC-EJ 'CrossSection)))
	(test-equal 1 (len-type (Word "e") 'Section))
	(test-equal 4 (len-type (Word "e") 'CrossSection))
	(test-equal 5 (length (gsc 'right-stars (Word "e"))))
	(test-equal 2 (len-type (Word "j") 'Section))
	(test-equal 0 (len-type (Word "j") 'CrossSection))
	(test-equal 2 (length (gsc 'right-stars (Word "j"))))
	(test-equal 2 (len-type (Word "f") 'Section))
	(test-equal 0 (len-type (Word "f") 'CrossSection))
	(test-equal 2 (length (gsc 'right-stars (Word "f"))))
	(test-equal 5 (len-type WC-EJ 'Section))
	(test-equal 2 (len-type WC-EJ 'CrossSection))
	(test-equal 7 (length (gsc 'right-stars WC-EJ)))
	(test-equal 10 (length (cog-get-atoms 'Section)))
	(test-approximate (* cnt-e-klm (- 1.0 frac1))
		(cog-count (car (filter-type (Word "e") 'Section))) epsilon)
	(expected-e-j-sections WC-EJ)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count sec-ej-abc) epsilon)
	(test-approximate (+ cnt-e-dgh cnt-j-dgh cnt-f-dgh)
		(cog-count sec-ej-dgh) epsilon)
	(test-approximate (+ (* frac1 cnt-e-klm) cnt-f-klm)
		(cog-count sec-ej-klm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm)
		(cog-count sec-e-klm) epsilon)
	(test-approximate (+ cnt-e-abc cnt-j-abc cnt-f-abc)
		(cog-count xes-b-ej-avc) epsilon)
	(test-approximate (+ (* frac1 cnt-e-klm) cnt-f-klm)
		(cog-count xes-k-ej-vlm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-e-klm) (cog-count xes-k-e-vlm) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-abe) (cog-count sec-j-abe) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-egh) (cog-count sec-j-egh) epsilon)
	(test-approximate (* (- 1 frac1) (- 1 frac2) cnt-f-abe)
		(cog-count sec-f-abe) epsilon)
	(test-approximate (* (- 1 frac1) (- 1 frac2) cnt-f-egh)
		(cog-count sec-f-egh) epsilon)
	(define expected-sec-ej-abv-count
		(+ (* frac1 (+ cnt-j-abe cnt-f-abe))
			(* frac2 (- 1 frac1) cnt-f-abe)))
	(test-approximate expected-sec-ej-abv-count
		(cog-count sec-ej-abv) epsilon)
	(define expected-sec-ej-vgh-count
		(+ (* frac1 (+ cnt-j-egh cnt-f-egh))
			(* frac2 (- 1 frac1) cnt-f-egh)))
	(test-approximate expected-sec-ej-vgh-count
		(cog-count sec-ej-vgh) epsilon)
	(test-equal 30 (length (cog-get-atoms 'CrossSection)))
	(test-approximate (* (- 1 frac1) cnt-j-abe) (cog-count xes-e-j-abv) epsilon)
	(test-approximate (* (- 1 frac1) cnt-j-egh) (cog-count xes-e-j-vgh) epsilon)
	(test-approximate expected-sec-ej-abv-count
		(cog-count xes-ej-ej-abv) epsilon)
	(test-approximate expected-sec-ej-vgh-count
		(cog-count xes-ej-ej-vgh) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-assert (check-shapes gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
)
(define t-three-cluster "one-connector-2-word 3-cluster merge test")
(test-begin t-three-cluster)
	(setup-database)
	(run-test (Word "e") (Word "j") "e j")
	(setup-database)
	(run-test (Word "j") (Word "e") "j e")
(test-end t-three-cluster)
(opencog-test-end)