(use-modules (opencog) (opencog matrix))
(use-modules (opencog nlp))
(use-modules (opencog learn))
(use-modules (opencog test-runner))
(use-modules (srfi srfi-64))
(opencog-test-runner)
(load "connector-setup.scm")
(load "shape-data.scm")
(define (run-shapes WA WB WC-NAME)
	(setup-f-sections)
	(define pca (make-pseudo-cset-api))
	(set! gsc (add-covering-sections pca))
	(test-equal 2 (length (gsc 'right-stars (Word "f"))))
	(define totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section))))
	(gsc 'explode-sections)
	(test-equal 4 (length (cog-get-atoms 'CrossSection)))
	(test-equal 3 (length (gsc 'right-stars (Word "a"))))
	(test-equal 1 (length (gsc 'right-stars (Word "b"))))
	(test-equal 2 (length (cog-get-atoms 'Section)))
	(define frac 0)
	(merge gsc WA WB frac)
	(define WC-AB (WordClassNode WC-NAME))
	(test-equal 0 (length (gsc 'right-stars (Word "a"))))
	(test-equal 0 (length (gsc 'right-stars (Word "b"))))
	(test-equal 2 (length (gsc 'right-stars WC-AB)))
	(test-equal 1 (length (cog-get-atoms 'Section)))
	(test-equal 2 (length (cog-get-atoms 'CrossSection)))
	(define epsilon 1.0e-8)
	(define cnt-mrg (+ cnt-f-aa cnt-f-ba))
	(test-approximate cnt-mrg
		(cog-count (car (gsc 'right-stars (Word "f")))) epsilon)
	(expected-a-b-sections WC-AB)
	(test-approximate cnt-mrg (cog-count sec-f-mm) epsilon)
	(test-approximate cnt-mrg (cog-count xes-m-f-vm) epsilon)
	(test-approximate cnt-mrg (cog-count xes-m-f-mv) epsilon)
	(test-assert (check-sections gsc epsilon))
	(test-assert (check-crosses gsc epsilon))
	(test-assert (check-shapes gsc epsilon))
	(test-approximate totcnt (fold + 0 (map cog-count (cog-get-atoms 'Section)))
		epsilon)
)
(define t-shape-merge "shape merge test")
(test-begin t-shape-merge)
	(setup-database)
	(run-shapes (Word "a") (Word "b") "a b")
	(setup-database)
	(run-shapes (Word "b") (Word "a") "b a")
(test-end t-shape-merge)
(opencog-test-end)