(use-modules (system repl server))
(use-modules (system repl common))
(spawn-server (make-tcp-server-socket  #:port 18001))
(define shell-prompt "[0;34mopencog-scheme[1;34m> [0m")
(repl-default-prompt-set! shell-prompt)