#ifndef _I386_KERNEL_I386_VM_PARAM_
#define _I386_KERNEL_I386_VM_PARAM_
#include <kern/macros.h>
#include <mach/vm_param.h>
#ifdef MACH_PV_PAGETABLES
#include <xen/public/xen.h>
#endif
#ifndef KERNEL_MAP_BASE
#ifdef __x86_64__
#define KERNEL_MAP_BASE 0xffffffff80000000ULL
#else
#define KERNEL_MAP_BASE 0xC0000000UL
#endif
#endif
#define VM_MIN_USER_ADDRESS VM_MIN_ADDRESS
#define VM_MAX_USER_ADDRESS VM_MAX_ADDRESS
#ifdef __x86_64__
#define VM_MIN_KERNEL_ADDRESS KERNEL_MAP_BASE
#else
#define VM_MIN_KERNEL_ADDRESS 0xC0000000UL
#endif
#if defined(MACH_XEN) || defined (__x86_64__)
#define INIT_VM_MIN_KERNEL_ADDRESS VM_MIN_KERNEL_ADDRESS
#else
#define INIT_VM_MIN_KERNEL_ADDRESS 0x00000000UL
#endif
#ifdef MACH_PV_PAGETABLES
#ifdef __i386__
#if PAE
#define HYP_VIRT_START HYPERVISOR_VIRT_START_PAE
#else
#define HYP_VIRT_START HYPERVISOR_VIRT_START_NONPAE
#endif
#define VM_MAX_KERNEL_ADDRESS (HYP_VIRT_START - LINEAR_MIN_KERNEL_ADDRESS + VM_MIN_KERNEL_ADDRESS)
#else
#define HYP_VIRT_START HYPERVISOR_VIRT_START
#define VM_MAX_KERNEL_ADDRESS (LINEAR_MAX_KERNEL_ADDRESS - LINEAR_MIN_KERNEL_ADDRESS + VM_MIN_KERNEL_ADDRESS)
#endif
#else
#define VM_MAX_KERNEL_ADDRESS (LINEAR_MAX_KERNEL_ADDRESS - LINEAR_MIN_KERNEL_ADDRESS + VM_MIN_KERNEL_ADDRESS)
#endif
#ifdef __x86_64__
#define VM_KERNEL_MAP_SIZE (512 * 1024 * 1024)
#else
#define VM_KERNEL_MAP_SIZE (152 * 1024 * 1024)
#endif
#ifdef __x86_64__
#define LINEAR_MIN_KERNEL_ADDRESS VM_MIN_KERNEL_ADDRESS
#define LINEAR_MAX_KERNEL_ADDRESS (0xffffffffffffffffUL)
#else
#define LINEAR_MIN_KERNEL_ADDRESS (VM_MAX_USER_ADDRESS)
#define LINEAR_MAX_KERNEL_ADDRESS (0xffffffffUL)
#endif
#ifdef MACH_PV_PAGETABLES
#define KERNEL_STACK_SIZE (4*I386_PGBYTES)
#define INTSTACK_SIZE (4*I386_PGBYTES)
#else
#define KERNEL_STACK_SIZE (1*I386_PGBYTES)
#define INTSTACK_SIZE (1*I386_PGBYTES)
#endif
#define trunc_i386_to_vm(p) (atop(trunc_page(i386_ptob(p))))
#define round_i386_to_vm(p) (atop(round_page(i386_ptob(p))))
#define vm_to_i386(p) (i386_btop(ptoa(p)))
#define phystokv(a) ((vm_offset_t)(a) + VM_MIN_KERNEL_ADDRESS)
#define _kvtophys(a) ((vm_offset_t)(a) - VM_MIN_KERNEL_ADDRESS)
#define kvtolin(a) ((vm_offset_t)(a) - VM_MIN_KERNEL_ADDRESS + LINEAR_MIN_KERNEL_ADDRESS)
#define lintokv(a) ((vm_offset_t)(a) - LINEAR_MIN_KERNEL_ADDRESS + VM_MIN_KERNEL_ADDRESS)
#define VM_PAGE_DMA_LIMIT DECL_CONST(0x1000000, UL)
#ifdef MACH_XEN
#ifdef __LP64__
#define VM_PAGE_MAX_SEGS 4
#define VM_PAGE_DMA32_LIMIT DECL_CONST(0x100000000, UL)
#define VM_PAGE_DIRECTMAP_LIMIT DECL_CONST(0x400000000000, UL)
#define VM_PAGE_HIGHMEM_LIMIT DECL_CONST(0x10000000000000, ULL)
#else
#define VM_PAGE_MAX_SEGS 4
#define VM_PAGE_DMA32_LIMIT DECL_CONST(0x100000000, UL)
#define VM_PAGE_DIRECTMAP_LIMIT (VM_MAX_KERNEL_ADDRESS \
- VM_MIN_KERNEL_ADDRESS \
- VM_KERNEL_MAP_SIZE)
#define VM_PAGE_HIGHMEM_LIMIT DECL_CONST(0x10000000000000, ULL)
#endif
#else
#ifdef __LP64__
#define VM_PAGE_MAX_SEGS 4
#define VM_PAGE_DMA32_LIMIT DECL_CONST(0x100000000, UL)
#define VM_PAGE_DIRECTMAP_LIMIT (VM_MAX_KERNEL_ADDRESS \
- VM_MIN_KERNEL_ADDRESS \
- VM_KERNEL_MAP_SIZE + 1)
#define VM_PAGE_HIGHMEM_LIMIT DECL_CONST(0x10000000000000, UL)
#else
#define VM_PAGE_DIRECTMAP_LIMIT (VM_MAX_KERNEL_ADDRESS \
- VM_MIN_KERNEL_ADDRESS \
- VM_KERNEL_MAP_SIZE + 1)
#ifdef PAE
#define VM_PAGE_MAX_SEGS 4
#define VM_PAGE_DMA32_LIMIT DECL_CONST(0x100000000, UL)
#define VM_PAGE_HIGHMEM_LIMIT DECL_CONST(0x10000000000000, ULL)
#else
#define VM_PAGE_MAX_SEGS 3
#define VM_PAGE_HIGHMEM_LIMIT DECL_CONST(0xfffff000, UL)
#endif
#endif
#endif
#define VM_PAGE_SEG_DMA 0
#if defined(VM_PAGE_DMA32_LIMIT) && (VM_PAGE_DMA32_LIMIT != VM_PAGE_DIRECTMAP_LIMIT)
#if VM_PAGE_DMA32_LIMIT < VM_PAGE_DIRECTMAP_LIMIT
#define VM_PAGE_SEG_DMA32 (VM_PAGE_SEG_DMA+1)
#define VM_PAGE_SEG_DIRECTMAP (VM_PAGE_SEG_DMA32+1)
#define VM_PAGE_SEG_HIGHMEM (VM_PAGE_SEG_DIRECTMAP+1)
#else
#define VM_PAGE_SEG_DIRECTMAP (VM_PAGE_SEG_DMA+1)
#define VM_PAGE_SEG_DMA32 (VM_PAGE_SEG_DIRECTMAP+1)
#define VM_PAGE_SEG_HIGHMEM (VM_PAGE_SEG_DMA32+1)
#endif
#else
#define VM_PAGE_SEG_DIRECTMAP (VM_PAGE_SEG_DMA+1)
#define VM_PAGE_SEG_DMA32 VM_PAGE_SEG_DIRECTMAP
#define VM_PAGE_SEG_HIGHMEM (VM_PAGE_SEG_DIRECTMAP+1)
#endif
#endif