(define-module (opencog spacetime))
(use-modules (opencog))
(use-modules (opencog sp-config))
(load-extension (string-append opencog-ext-path-spacetime-types "libspacetime-types") "spacetime_types_init")
(load "spacetime/spacetime_types.scm")