extern char	**argv;
extern int	argc;
extern int	x_stat;
extern int	debug;
extern int	ignore;
extern long	lineno;
extern long	position;
extern char	*prog_name;
extern char	*temp_file;
extern char	*fontencoding;
extern int	dobbox;
extern double	pageheight;
extern double	pagewidth;
extern int	reading;
extern int	writing;
extern char	*optarg;
extern int	optind;
extern int	cat(char *);
extern void	error(int, char *, ...);
extern int	in_olist(int);
extern void	interrupt(int);
extern int	out_list(char *);
extern int	setencoding(char *);
extern char	*tempnam(char*,char*);