(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-ipfs))
(ipfs-open "ipfs:///demo-atomspace")
(Concept "example concept" (stv 0.45 0.33))
(Evaluation
(Predicate "Some relationship")
(List (Concept "foo") (Concept "bar")))
(store-atomspace)
(ipfs-stats)
(ipfs-close)