(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-ipfs))
(ipfs-open "ipfs:///")
(ipfs-fetch-atom "bafyreigx524ryjvcjvph4eyihduqspxctgjx5gvyxhpgjbwmrifgpctmoa")
(ipfs-fetch-atom "bafyreigll67ssepbqfhtooqobirodyyhsq3ptmxseuwxwnxs5aci75hpoq")
(ipfs-stats)
(ipfs-load-atomspace "QmVz6C1F1xYYYZM3L8a3BpGd41pY35SbkAL4P4pGGbgK4w")
(cog-prt-atomspace)
(ipfs-load-atomspace "/ipfs/QmVz6C1F1xYYYZM3L8a3BpGd41pY35SbkAL4P4pGGbgK4w")
(ipfs-load-atomspace "/ipns/QmVkzxhCMDYisZ2QEMA5WYTjrZEPVbETZg5rehsijUxVHx")
(ipfs-stats)
(ipfs-close)