(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-ipfs))
(ipfs-open "ipfs:///ipfs/QmUqobJLPNyB7kQcczLo3GrJBDpXJG2JcHqfDCCWCt2NCg")
(define c (ConceptNode "example concept"))
(fetch-atom c)
(define ll (List (Concept "foo") (Concept "bar")))
(fetch-incoming-set ll)
(cog-prt-atomspace)
(ipfs-stats)
(load-atomspace)
(cog-prt-atomspace)
(ipfs-stats)
(ipfs-close)