(use-modules (opencog))
(define a (Concept "a"))
(define b (Concept "b"))
(cog-set-tv! a (cog-new-stv 0.1 0.1))
(cog-atomspace-ro!)
(define c (Concept "c"))
(cog-prt-atomspace)
(cog-set-tv! a (cog-new-stv 0.2 0.2))
(cog-prt-atomspace)
(define base (cog-atomspace))
(define ovly (cog-new-atomspace base))
(cog-set-atomspace! ovly)
(cog-set-tv! a (cog-new-stv 0.3 0.3))
(cog-prt-atomspace)
(cog-set-tv! a (cog-new-stv 0.4 0.4))
(cog-prt-atomspace)
(cog-set-atomspace! base)
(cog-prt-atomspace)
(cog-set-atomspace! ovly)
(cog-prt-atomspace)
(OrderedLink a b)
(define averly (Concept "a"))
(ListLink averly b)
(cog-prt-atomspace)
(cog-atomspace-rw! base)
(cog-atomspace-cow! #t ovly)
(cog-set-atomspace! base)
(cog-set-tv! a (cog-new-stv 0.222 0.222))
(cog-prt-atomspace)
(cog-set-atomspace! ovly)
(cog-prt-atomspace)
(cog-set-tv! a (cog-new-stv 0.5 0.5))
(cog-prt-atomspace)
(cog-set-tv! b (cog-new-stv 0.6 0.6))
(cog-prt-atomspace)
(cog-set-atomspace! base)
(cog-prt-atomspace)
(ListLink a b (stv 0.7 0.7))
(cog-set-tv! b (cog-new-stv 0.8 0.8))
(cog-prt-atomspace)
(cog-set-atomspace! ovly)
(cog-prt-atomspace)