(use-modules (opencog))
(define base-space (cog-atomspace))
(ConceptNode "foo")
(cog-set-value!
	(ConceptNode "foo") (Predicate "bunch o numbers")
		(FloatValue 1 2 3.14159 4 5 6))
(cog-set-value!
	(ConceptNode "foo") (Predicate "some words")
		(StringValue "once" "upon" "a" "time"))
(cog-set-value!
	(ConceptNode "foo") (Predicate "some atoms")
		(LinkValue (Concept "dog") (Concept "cat") (Concept "mouse")))
(cog-keys (ConceptNode "foo"))
(cog-value (ConceptNode "foo") (Predicate "some words"))
(cog-report-counts)
(cog-set-value!
	(ConceptNode "foo") (Predicate "real life")
		(AtomSpace "happy thoughts"))
(cog-set-value!
	(ConceptNode "foo") (Predicate "repressed mem")
		(AtomSpace "crushing defeat"))
(cog-value (ConceptNode "foo") (Predicate "real life"))
(cog-value (ConceptNode "foo") (Predicate "repressed mem"))
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(cog-set-atomspace! as-one)
(ListLink (Concept "mom") (Concept "dad"))
(ListLink (Concept "first crush") (Concept "Gilanda"))
(cog-prt-atomspace)
(cog-set-atomspace! base-space)
(cog-set-atomspace!
	(cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(ListLink (Concept "misdemeanor") (Concept "vandalism"))
(ListLink (Concept "furious") (Concept "anger"))
(cog-prt-atomspace)
(cog-set-atomspace! base-space)
(cog-prt-atomspace)
(cog-prt-atomspace (cog-value (ConceptNode "foo") (Predicate "real life")))
(cog-prt-atomspace (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(use-modules (opencog persist))
(use-modules (opencog persist-file))
(define fsn (FileStorageNode "/tmp/foo"))
(cog-open fsn)
(store-atomspace)
(cog-close fsn)
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(define as-two (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(define fsa (FileStorageNode "/tmp/foo-one"))
(define fsb (FileStorageNode "/tmp/foo-two"))
(cog-open fsa)
(cog-open fsb)
(cog-set-atomspace! as-one)
(store-atomspace fsa)
(cog-close fsa)
(cog-set-atomspace! as-two)
(store-atomspace fsb)
(cog-close fsb)
(cog-set-atomspace! base-space)
(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-file))
(define base-space (cog-atomspace))
(define fsn (FileStorageNode "/tmp/foo"))
(cog-open fsn)
(load-atomspace)
(cog-close fsn)
(cog-prt-atomspace)
(cog-keys (Concept "foo"))
(cog-value (Concept "foo") (Predicate "real life"))
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(define as-two (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(define fsa (FileStorageNode "/tmp/foo-one"))
(define fsb (FileStorageNode "/tmp/foo-two"))
(cog-open fsa)
(cog-open fsb)
(cog-set-atomspace! as-one)
(load-atomspace fsa)
(cog-close fsa)
(cog-set-atomspace! as-two)
(load-atomspace fsb)
(cog-close fsb)
(cog-set-atomspace! base-space)
(cog-prt-atomspace)
(cog-prt-atomspace as-one)
(cog-prt-atomspace as-two)
(use-modules (opencog persist))
(use-modules (opencog persist-rocks))
(define rsn (RocksStorageNode "rocks:///tmp/blob"))
(cog-open rsn)
(store-atomspace)
(store-atomspace (AtomSpace "happy thoughts"))
(store-atomspace (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(cog-close rsn)
(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(define base-space (cog-atomspace))
(define rsn (RocksStorageNode "rocks:///tmp/blob"))
(cog-open rsn)
(load-atomspace)
(cog-close rsn)
(cog-prt-atomspace)
(define as-one (cog-value (ConceptNode "foo") (Predicate "real life")))
(define as-two (cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(cog-open rsn)
(load-atomspace as-one)
(cog-set-atomspace! as-two)
(load-atomspace)
(cog-set-atomspace! base-space)
(cog-close rsn)
(cog-prt-atomspace as-one)
(cog-prt-atomspace as-two)
(cog-prt-atomspace)