(use-modules (opencog))
(define root-as (cog-atomspace))
(State (Concept "robot arm") (Concept "empty"))
(cog-prt-atomspace)
(cog-push-atomspace)
(cog-prt-atomspace)
(State (Concept "robot arm")
(Evaluation (Predicate "holding") (Concept "block 42")))
(cog-prt-atomspace)
(cog-map-type (lambda (A) (format #t "This is the state: ~A\n" A) #f) 'State)
(cog-prt-atomspace root-as)
(cog-map-type (lambda (A) (format #t "Before, it was: ~A\n" A) #f)
'State root-as)
(cog-pop-atomspace)
(cog-prt-atomspace)