#!/usr/bin/env guile
!#
(use-modules (opencog))
(use-modules (ice-9 format))
(use-modules (srfi srfi-19))
(define (make-node-and-link prefix n)
(define (make-atoms prefix node n)
(define cpt (ConceptNode
(string-append/shared prefix (number->string n))))
(ListLink node cpt)
(if (< 0 n)
(make-atoms prefix cpt (- n 1))
'()
)
)
(make-atoms prefix (ConceptNode prefix) n)
)
(define (make-link-tree depth)
(define (make-atoms atom n)
(if (< 0 n)
(make-atoms (ListLink atom atom) (- n 1))
'()
)
)
(make-atoms (ConceptNode "nil") depth)
)
(define (report-perf id start stop niter)
(define elapsed (time-difference stop start))
(define delta
(+ (time-second elapsed)
(/ (time-nanosecond elapsed) 1000000000.0)))
(define rate (round (/ niter delta)))
(format #t "~A\n" id)
(format #t "\tElapsed time (secs): ~A\n" delta)
(format #t "\tLoops per second: ~A\n\n" rate)
)
(display "\nRunning the benchmark. Please wait ...\n\n")
(define niter 250000)
(define start (current-time))
(make-node-and-link "hello world" niter)
(define stop (current-time))
(report-perf "Nodes and Links, first time:" start stop niter)
(set! start (current-time))
(make-node-and-link "hello world" niter)
(set! stop (current-time))
(report-perf "Nodes and Links, second time:" start stop niter)
(set! start (current-time))
(make-link-tree niter)
(set! stop (current-time))
(report-perf "Binary tree, first time:" start stop niter)
(set! start (current-time))
(make-link-tree niter)
(set! stop (current-time))
(report-perf "Binary tree, second time:" start stop niter)