(use-modules (opencog) (opencog logger))
(cog-logger-info "First info message")
(cog-logger-debug "First debug message")
(cog-logger-set-level! "debug")
(cog-logger-debug "Second debug message")
(cog-logger-set-filename! "opencog-scm-logger-example.log")
(cog-logger-info "Third info message")
(cog-logger-set-stdout! #t)
(cog-logger-info "Fourth info message")
(cog-logger-error "First error message (comes with the stack trace)")
(cog-logger-set-sync! #t)
(define Ohi (ConceptNode "O Hi!"))
(cog-logger-info "My concept: ~a" Ohi)