(use-modules (opencog) (opencog exec))
(define a (AtomSpace))
(define b (AtomSpace))
(define c (AtomSpace a b))
(cog-set-atomspace! a)
(Concept "I'm in A")
(cog-prt-atomspace)
(cog-set-atomspace! b)
(Concept "I'm in B")
(cog-prt-atomspace)
(cog-set-atomspace! c)
(cog-prt-atomspace)
(define get-concepts
	(Get (TypedVariable (Variable "$x") (Type 'Concept))
		(Variable "$x")))
(cog-prt-atomspace)
(cog-execute! get-concepts)
(cog-prt-atomspace)
(cog-set-atomspace! a)
(cog-prt-atomspace)
(cog-set-atomspace! b)
(cog-prt-atomspace)
(cog-execute! get-concepts)