:   https://github.com/opencog/atomspace-pgres/blob/master/opencog/persist/sql/README.md
(use-modules (ice-9 readline))
(activate-readline)
(use-modules (opencog) (opencog persist))
(store-atom (Concept "asdf" (stv 0.42 0.24)))
(use-modules (opencog persist-rocks))
(use-modules (opencog persist-sql))
(use-modules (opencog persist-cog))
(define rsn (RocksStorageNode "rocks:///tmp/atomspace-rocks-demo"))
(define psn (PostgresStorageNode "postgres://opencog_tester:cheese@localhost/opencog_test"))
(define csn (CogStorageNode "cog://localhost:17001"))
(cog-open rsn)
(store-atom (Concept "asdf" (stv 0.318309886 0.36787944)))
(cog-close rsn)
(fetch-atom (Concept "asdf"))
(cog-open rsn)
(fetch-atom (Concept "asdf"))
(cog-set-value!
	(Concept "asdf")
	(Predicate "my key")
	(StringValue "Humpty" "Dumpty"))
(store-atom (Concept "asdf"))
(cog-close rsn)
(cog-set-tv! (Concept "asdf") (stv 0.25 0.75))
(cog-set-value!
	(Concept "asdf")
	(Predicate "my key")
	(StringValue "sat" "on" "a" "wall"))
(cog-open rsn)
(fetch-atom (Concept "asdf"))
(cog-keys (Concept "asdf"))
(cog-value (Concept "asdf") (Predicate "my key"))