(use-modules (ice-9 readline))
(activate-readline)
(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-sql))
(use-modules (opencog persist-rocks))
(use-modules (opencog persist-cog))
(define psn (PostgresStorageNode "postgres://opencog_tester:cheese@localhost/opencog_test"))
(define rsn (RocksStorageNode "rocks:///tmp/atomspace-rocks-demo"))
(define csn (CogStorageNode "cog://localhost:17001"))
(cog-open psn)
(store-atom (Concept "asdf" (stv 0.318309886 0.36787944)))
(cog-close psn)
(cog-extract! (Concept "asdf"))
(cog-prt-atomspace)
(cog-open psn)
(cog-open rsn)
(load-atomspace psn)
(store-atomspace rsn)
(cog-close psn)
(cog-close rsn)
(cog-extract! (Concept "asdf"))
(cog-prt-atomspace)
(cog-open rsn)
(load-atomspace)
(cog-close rsn)
(cog-prt-atomspace)
(cog-set-tv! (Concept "asdf") (stv 0.25 0.75))
(cog-open rsn)
(store-atom (Concept "asdf"))
(cog-close rsn)
(cog-open psn)
(cog-open rsn)
(fetch-atom (Concept "asdf") psn)
(fetch-atom (Concept "asdf") rsn)
(fetch-atom (Concept "asdf") psn)
(fetch-atom (Concept "asdf") rsn)
(fetch-atom (Concept "asdf") psn)
(fetch-atom (Concept "asdf") rsn)
(cog-set-tv! (Concept "asdf") (stv 0.1 0.8))
(store-atom (Concept "asdf") psn)
(fetch-atom (Concept "asdf") rsn)
(fetch-atom (Concept "asdf") psn)
(fetch-atom (Concept "asdf") rsn)
(fetch-atom (Concept "asdf") psn)
(cog-close psn)
(cog-close rsn)