(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(cog-set-value!
(WriteBufferProxy "write buffer") (*-proxy-parts-*)
(RocksStorageNode "rocks:///tmp/foo.rdb"))
(cog-set-value!
(WriteBufferProxy "write buffer") (*-decay-const-*)
(Number 42))
(cog-open (WriteBufferProxy "write buffer"))
(for-each
(lambda (N)
(cog-set-value! (Concept "foo") (Predicate "bar") (FloatValue 1 2 N))
(store-value (Concept "foo") (Predicate "bar")))
(iota 10))
(barrier)
(define (show-stats STORG)
(display (cog-value-ref STORG (*-monitor-*) 0)))
(show-stats (WriteBufferProxy "write buffer"))
(show-stats (RocksStorageNode "rocks:///tmp/foo.rdb"))
(for-each
(lambda (N)
(cog-set-value! (Concept "foo") (Predicate "fizz")
(FloatValue 4 (* 5 N) (+ N 6)))
(store-atom (Concept "foo")))
(iota 10))
(cog-close (WriteBufferProxy "write buffer"))
(cog-set-value!
(ReadWriteProxy "read w/write buffer")
(*-proxy-parts-*)
(List
(RocksStorageNode "rocks:///tmp/foo.rdb")
(WriteBufferProxy "write buffer")))
(cog-open (ReadWriteProxy "read w/write buffer"))
(fetch-atom (Concept "foo"))
(cog-set-value! (Concept "foo") (Predicate "fizz") (Concept "oh hi"))
(store-atom (Concept "foo"))
(cog-close (ReadWriteProxy "read w/write buffer"))
(cog-set-value!
(CachingProxy "read cache") (*-proxy-parts-*)
(RocksStorageNode "rocks:///tmp/foo.rdb"))
(cog-set-value!
(ReadWriteProxy "full cache") (*-proxy-parts-*)
(List
(CachingProxy "read cache")
(WriteBufferProxy "write buffer")))
(cog-open (ReadWriteProxy "full cache"))
(fetch-atom (Concept "foo"))
(cog-set-value! (Concept "foo") (Predicate "fizz") (Number 42))
(store-atom (Concept "foo"))
(show-stats (ReadWriteProxy "full cache"))
(cog-close (ReadWriteProxy "full cache"))