(use-modules (opencog) (opencog persist) (opencog persist-file))
(define a (Concept "foo"))
(cog-set-value! a (Predicate "num") (FloatValue 1 2 3))
(cog-set-value! a (Predicate "str") (StringValue "p" "q" "r"))
(define li (Link (Concept "foo") (Concept "bar")))
(cog-set-value! li (Predicate "num") (FloatValue 4 5 6))
(cog-set-value! li (Predicate "str") (StringValue "x" "y" "z"))
(define fsn (FileStorageNode "/tmp/foo.scm"))
(cog-open fsn)
(store-atom a fsn)
(store-value a (Predicate "num") fsn)
(store-value a (Predicate "num") fsn)
(store-value a (Predicate "num") fsn)
(barrier fsn)
(store-atomspace fsn)
(cog-close fsn)
(use-modules (opencog) (opencog persist) (opencog persist-file))
(define fsn (FileStorageNode "/tmp/foo.scm"))
(cog-open fsn)
(load-atomspace fsn)
(cog-close fsn)
(cog-prt-atomspace)
(define li (Link (Concept "foo") (Concept "bar")))
(cog-keys li)
(cog-value li (Predicate "num"))
(cog-value li (Predicate "str"))