(use-modules (opencog) (opencog exec))
(define k (Predicate "key"))
(define a (Concept "my atom"))
(cog-set-value! a k (FloatValue 1 2 3))
(define vo (ValueOf a k))
(cog-execute! vo)
(define fvo (FloatValueOf a k))
(cog-execute! fvo)
(define tym (Times (Plus fvo (Number 6)) (Number 2)))
(cog-execute! tym)
(define b (Concept "other atom"))
(cog-set-value! b k (RandomStream 24))
(cog-execute! (ValueOf b k))
(cog-execute! (StreamValueOf b k))
(cog-execute! (StreamValueOf b k))
(cog-execute! (StreamValueOf b k))
(cog-execute! (StreamValueOf b k))
(define tymb (Times (Number 2) (Plus (StreamValueOf b k) (Number 6)) ))
(cog-execute! tymb)
(cog-execute! tymb)
(cog-execute! tymb)
(cog-execute! tymb)
(cog-execute! tymb)
(define c (Concept "coin atom"))
(cog-set-value! c k (RandomStream 1))
(define flipkey (PredicateNode "*-coinflip-*"))
(cog-set-value! c flipkey (GreaterThan (Number 0.5) (FloatValueOf c k)))
(cog-evaluate! (ValueOf c flipkey))
(cog-evaluate! (ValueOf c flipkey))
(cog-evaluate! (ValueOf c flipkey))
(cog-evaluate! (ValueOf c flipkey))
(cog-evaluate! (ValueOf c flipkey))
(define coin-tv (ValueOf c flipkey))
(cog-evaluate! coin-tv)
(cog-evaluate! coin-tv)
(cog-evaluate! coin-tv)
(cog-evaluate! coin-tv)
(cog-evaluate! coin-tv)