(use-modules (opencog))
(define tv (SimpleTruthValue 0.1 0.2))
(cog-value->list tv)
(cog-value-ref tv 0)
(cog-value-ref tv 1)
,d cog-value->list
,d cog-value-ref
(define a (Concept "some atom"))
(cog-set-tv! a tv)
(cog-tv a)
(cog-set-tv! a (SimpleTruthValue 0.333 0.789))
(cog-tv a)
(cog-set-tv! a (CountTruthValue 1.0e-6 -19.9316 55))
(use-modules (opencog attention-bank))
(cog-set-av! a (AttentionValue 3 2 1))
(cog-av a)