(use-modules (opencog))
(use-modules (opencog cogserver))
(start-cogserver "../scripts/opencog.conf")
(use-modules (opencog eva-behavior))
(use-modules (opencog movement))
(start-ros-movement-node)
(add-to-load-path "../src")
(load-from-path "cfg-eva.scm")
(load-from-path "old-tree.scm")
(define (run) (behavior-tree-run))
(define (halt) (behavior-tree-halt))
(run-behavior-tree-gc)
(TrueLink)
(all-threads)
(run)