(use-modules (opencog) (opencog exec) (opencog openpsi))
(use-modules (opencog openpsi dynamics))
(use-modules (opencog nlp) (opencog nlp chatbot) (opencog nlp chatbot-psi))
(use-modules (opencog eva-behavior))
(define openpsi-modulators (psi-default-modulator-alist))
(define arousal (assoc-ref openpsi-modulators "arousal"))
(define neg-valence (assoc-ref openpsi-modulators "neg-valence"))
(define pos-valence (assoc-ref openpsi-modulators "pos-valence"))
(define resolution-level (assoc-ref openpsi-modulators "resolution-level"))
(define goal-directedness (assoc-ref openpsi-modulators "goal-directedness"))
(define openpsi-secs (psi-default-sec-alist))
(define power (assoc-ref openpsi-secs "power"))
(define valence-activation-level .5)
(define psi-verbose #t)
(define single-dimension-valence #t)
(define prev-value-node (Concept "previous value"))
(define current-sentence-node (Concept "current sentence"))
(define (psi-expression-callback)
	(define dominant-emotion (psi-get-current-emotion))
	(define emotion-value (psi-get-number-value dominant-emotion))
	(if (equal? dominant-emotion psi-happy)
		(be-happy emotion-value))
	(if (equal? dominant-emotion psi-sad)
		(be-sad emotion-value))
	(if (equal? dominant-emotion psi-angry)
		(be-irritated emotion-value))
	(if (equal? dominant-emotion psi-relaxed)
		(be-comprehending emotion-value))
)
(psi-set-expression-callback! psi-expression-callback)
(define (do-random-positive-expression intensity)
	 (cog-evaluate!
		 (Put (DefinedPredicate "Show facial expression")
			 (ListLink
				 (PutLink (DefinedSchemaNode "Pick random expression")
					 (ConceptNode "positive"))
				 (Number 8) (Number intensity)))))
(define (do-random-negative-expression intensity)
	 (cog-evaluate!
		 (Put (DefinedPredicate "Show facial expression")
			 (ListLink
				 (PutLink (DefinedSchemaNode "Pick random expression")
					 (ConceptNode "frustrated"))
				 (Number 8) (Number intensity)))))
(define (show-emotion emotion intensity)
	(cog-evaluate! (Put (DefinedPredicate "Show facial expression")
		(ListLink (Concept emotion) (Number 8) (Number intensity)))))
(define (be-happy intensity)
	(cog-evaluate! (Put (DefinedPredicate "Show facial expression")
		(ListLink (Concept "happy") (Number 8) (Number intensity)))))
(define (be-sad intensity)
	(cog-evaluate! (Put (DefinedPredicate "Show facial expression")
		(ListLink (Concept "sad") (Number 8) (Number intensity)))))
(define (be-irritated intensity)
	(cog-evaluate! (Put (DefinedPredicate "Show facial expression")
		(ListLink (Concept "irritated") (Number 8) (Number intensity)))))
(define (be-comprehending intensity)
	(cog-evaluate! (Put (DefinedPredicate "Show facial expression")
		(ListLink (Concept "comprehending") (Number 8) (Number intensity)))))
(define (do-catch function . params)
	(catch #t
	  (lambda ()
		(apply function params))
	(lambda (key . parameters)
		(format (current-error-port)
				  "\nUncaught throw to '~a: ~a\n" key parameters)
		)
	)
)
(define new-face (psi-create-monitored-event "new-face"))
(define speech-giving-starts
	(psi-create-monitored-event "speech-giving-starts"))
(define positive-sentiment-dialog
	(psi-create-monitored-event "positive-sentiment-dialog"))
(define negative-sentiment-dialog
	(psi-create-monitored-event "negative-sentiment-dialog"))
(define loud-noise-event
	(psi-create-monitored-event "loud-noise"))
(use-modules (opencog eva-model))
(define loud-noise (DefinedPredicate "Heard Loud Sound?"))
(define new-loud-noise? #f)
(define (psi-check-for-loud-noise)
	(if (equal? (cog-evaluate! loud-noise)
				(stv 1 1))
		(psi-set-event-occurrence! loud-noise-event)))
(psi-set-event-callback! psi-check-for-loud-noise)
(define loud-noise->arousal
	(psi-create-interaction-rule loud-noise-event "increased" arousal .9))
(define loud-noise->neg-valence
	(psi-create-interaction-rule loud-noise-event "increased" neg-valence .7))
(define room-got-bright-event (psi-create-monitored-event "room-got-bright"))
(define room-got-dark-event (psi-create-monitored-event "room-got-dark"))
(define room-was-bright #f)
(define room-was-dark #f)
(define (psi-detect-room-got-bright)
	(if (room-is-bright?)
		(if (not room-was-bright)
			(begin
				(psi-set-event-occurrence! room-got-bright-event)
				(set! room-was-bright #t)
			)
		)
		(if room-was-bright
			(set! room-was-bright #f))
	)
)
(define (psi-detect-room-got-dark)
	(if (room-is-dark?)
		(if (not room-was-dark)
			(begin
				(psi-set-event-occurrence! room-got-dark-event)
				(set! room-was-dark #t)
			)
		)
		(if room-was-dark
			(set! room-was-dark #f))
	)
)
(psi-set-event-callback! psi-detect-room-got-bright)
(psi-set-event-callback! psi-detect-room-got-dark)
(define room-got-bright->arousal
	(psi-create-interaction-rule room-got-bright-event "changed" arousal .5))
(define room-got-dark->arousal
	(psi-create-interaction-rule room-got-dark-event "changed" arousal -.4))
(define (get-luminance-value)
    (define result (cog-outgoing-set (cog-execute!
        (Get (State (Anchor "luminance") (Variable "$x"))))))
    (if (not (null? result))
		(set! result (cog-number (car result)))
		(set! result #f))
    result
)
(define (room-is-bright?)
	(define val (get-luminance-value))
	(define return)
	(if val
		(if (> val 50)
			(set! return #t)
			(set! return #f) )
		(set! return room-was-bright)
	)
	return
)
(define (room-is-dark?)
	(define val (get-luminance-value))
	(define return)
	(if val
		(if (< val 20)
			(set! return #t)
			(set! return #f) )
		(set! return room-was-bright)
	)
	return
)
(define (psi-detect-dialog-sentiment)
	(define current-input (get-input-sent-node))
	(define previous-input (psi-get-value current-sentence-node))
	(if (and (not (equal? current-input '()))
			 (not (equal? current-input previous-input)))
		(begin
			(StateLink current-sentence-node current-input)
			(let ((inher-super (cog-chase-link 'InheritanceLink 'ConceptNode
					current-input)))
				(for-each (lambda (concept)
							(if (equal? concept (Concept "Positive"))
								(psi-set-event-occurrence!
									positive-sentiment-dialog))
							(if (equal? concept (Concept "Negative"))
								(psi-set-event-occurrence!
									negative-sentiment-dialog)))
						inher-super)))))
(psi-set-event-callback! psi-detect-dialog-sentiment)
(define psi-happy (psi-create-emotion "happy"))
(define psi-sad (psi-create-emotion "sad"))
(define psi-angry (psi-create-emotion "angry"))
(define psi-relaxed (psi-create-emotion "relaxed"))
(define psi-excited (psi-create-emotion "excited"))
(define psi-tired (psi-create-emotion "tired"))
(define (psi-update-emotion-states)
	(define arousal (psi-get-arousal))
	(define pos-valence (psi-get-pos-valence))
	(define neg-valence (psi-get-neg-valence))
	(define emotionality-factor 1.2)
	(define e emotionality-factor)
	(define (limit value)
		(min value 1))
	(psi-set-value! psi-happy
		(limit (* pos-valence arousal e)))
	(psi-set-value! psi-angry
		(limit (* neg-valence arousal e)))
	(psi-set-value! psi-sad
		(limit (* neg-valence (- 1 arousal) e)))
	(psi-set-value! psi-relaxed
		(limit (* pos-valence (- 1 arousal) e)))
	(psi-set-current-emotion-state)
	(True)
)
(define-public psi-current-emotion-state
	(Concept (string-append psi-prefix-str "current emotion state")))
(define (psi-set-current-emotion-state)
	(define emotions (psi-get-emotions))
	(define strongest-emotion)
	(define highest-emotion-value -1)
	(for-each
		(lambda (emotion)
			(define emotion-value (psi-get-number-value emotion))
			(if (> emotion-value highest-emotion-value)
				(begin
					(set! strongest-emotion emotion)
					(set! highest-emotion-value emotion-value))))
		emotions)
	(if (not (equal? (psi-get-value psi-current-emotion-state) strongest-emotion))
		(begin
			(StateLink psi-current-emotion-state strongest-emotion)
		)
	)
)
(define-public (psi-get-current-emotion)
	(psi-get-value psi-current-emotion-state))
(define pau-prefix-str psi-prefix-str)
(define (create-pau name initial-value)
	(define pau
		(Concept (string-append pau-prefix-str name)))
	(Inheritance
		pau
		(Concept "PAU"))
	(psi-set-value! pau initial-value)
	pau)
(define default_B .05)
(define default_w .02)
(define default_noise .015)
(define arousal_B .05)
(define arousal_w .02)
(define arousal_offset (get-random-cycle-offset arousal_w))
(define arousal_noise .03)
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-ultradian-update")
	(List arousal (Number arousal_B) (Number arousal_w) (Number arousal_offset)))
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-noise-update")
	(List arousal (Number arousal_noise)))
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-ultradian-update")
	(List pos-valence (Number default_B) (Number default_w)
		(Number (get-random-cycle-offset default_w))))
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-noise-update")
	(List pos-valence (Number default_noise)))
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-ultradian-update")
	(List neg-valence (Number default_B) (Number default_w)
		(Number (get-random-cycle-offset default_w))))
(psi-create-general-rule (TrueLink)
	(GroundedSchemaNode "scm: psi-noise-update")
	(List neg-valence (Number default_noise)))
(psi-create-interaction-rule pos-valence "increased" neg-valence -.2)
(psi-create-interaction-rule neg-valence "increased" pos-valence -.2)
(psi-create-interaction-rule arousal "changed" resolution-level .5)
(psi-create-interaction-rule arousal "changed" goal-directedness .5)
(psi-create-interaction-rule power "changed" neg-valence -.2)
(psi-create-interaction-rule arousal "increased" pos-valence .1)
(psi-create-interaction-rule pos-valence "changed" power .2)
(define pos-sentiment->pos-valence
	(psi-create-interaction-rule positive-sentiment-dialog
		"increased" pos-valence .3))
(define pos-sentiment->neg-valence
	(psi-create-interaction-rule positive-sentiment-dialog
		"increased" neg-valence -.3))
(define neg-sentiment->neg-valence
	(psi-create-interaction-rule negative-sentiment-dialog
		"increased" neg-valence .3))
(define neg-sentiment->pos-valence
	(psi-create-interaction-rule negative-sentiment-dialog
		"increased" pos-valence -.3))
(define speech->power
	(psi-create-interaction-rule speech-giving-starts "increased"
		power .5))
(define new-face->arousal
	(psi-create-interaction-rule new-face "increased" arousal .3))
(define voice-width (create-pau "voice width" .2))
(define power->voice
	(psi-create-interaction-rule power "changed" voice-width .7))
(define arousal->voice
	(psi-create-interaction-rule arousal "changed" voice-width -.3))
(define psi-update-emotions-rule
	(psi-create-general-rule (TrueLink)
		(GroundedSchemaNode "scm: psi-update-emotion-states")
		(List)))
(psi-updater-run)
(define e psi-set-event-occurrence!)
(define halt psi-updater-halt)
(define h halt)
(define r psi-updater-run)
(define value psi-get-number-value)
(define rules psi-get-interaction-rules)
(define (psi-decrease-value target)
	(psi-set-value! target
		(max 0 (- (psi-get-number-value target) .1))))
(define (psi-increase-value target)
	(psi-set-value! target
		(min 1 (+ (psi-get-number-value target) .1))))
(define d psi-decrease-value)
(define i psi-increase-value)
(define (psi-set-pred-true target)
	(Evaluation target (List) (stv 1 1)))
(define (psi-set-pred-false target)
	(Evaluation target (List) (stv 0 1)))
(define t psi-set-pred-true)
(define f psi-set-pred-false)
(define nv neg-valence)
(define pv pos-valence)
(define (place-neg-dialog)
	(define sentence (SentenceNode (number->string (random 1000000000))))
	(State (Anchor "Chatbot: InputUtteranceSentence")  sentence)
	(Inheritance sentence (Concept "Negative")))
(define (place-pos-dialog)
	(define sentence (SentenceNode (number->string (random 1000000000))))
	(State (Anchor "Chatbot: InputUtteranceSentence")  sentence)
	(Inheritance sentence (Concept "Positive")))
(define (simulate-loud-noise)
	(cog-execute!
		(Put (State (AnchorNode "Decibel value") (Variable "$y")) (Number "100")))
	(sleep 1)
	(cog-execute! (Put (State (AnchorNode "Decibel value") (Variable "$y")) (Number "50")))
)
(define v voice-width)
(define p power)
(define a arousal)
(define n simulate-loud-noise)
(define ln simulate-loud-noise)
(define nd place-neg-dialog)
(define pd place-pos-dialog)
(define s speech-giving-starts)
(define pos positive-sentiment-dialog)
(define neg negative-sentiment-dialog)
(define nf new-face)