(use-modules (opencog eva-model))
(define do-print-msg #f)
(define keep-looping #t)
(define (run-face-test)
(define face-id 0)
(define (prt-msg x)
(if do-print-msg (begin (display x) (force-output)))
)
(define (chat-for-a-while n)
(do ((i 1 (1+ i))) ((> i n))
(prt-msg "chat start\n")
(StateLink chat-state chat-start)
(sleep 1)
(prt-msg "chat stop\n")
(StateLink chat-state chat-stop)
(sleep 2))
)
(define (come-and-go)
(sleep 2)
(set! face-id (+ 2 face-id))
(prt-msg "new face\n")
(make-new-face (number->string face-id))
(sleep 3)
(chat-for-a-while 6)
(prt-msg "second face\n")
(make-new-face (number->string (+ 1 face-id)))
(chat-for-a-while 6)
(sleep 3)
(prt-msg "first face exits\n")
(remove-face (number->string face-id))
(chat-for-a-while 6)
(prt-msg "second face exits\n")
(remove-face (number->string (+ 1 face-id)))
(sleep 90)
(if keep-looping (come-and-go))
)
(call-with-new-thread come-and-go)
)
(define (get-total-atoms-in-atomspace)
(define cnt 0)
(define (ink a) (set! cnt (+ cnt 1)) #f)
(define (cnt-type x) (cog-map-type ink x))
(map cnt-type (cog-get-types))
cnt)
(define (print-toplevel-counts)
(define a-cnt 0)
(define t-cnt 0)
(define (ink a)
(set! a-cnt (+ a-cnt 1))
(if (eq? 0 (length (cog-incoming-set a)))
(set! t-cnt (+ t-cnt 1)))
#f)
(define (cnt-type x)
(set! a-cnt 0)
(set! t-cnt 0)
(cog-map-type ink x)
(if (< 100 a-cnt)
(display (format "type: ~A total ~A  top ~A\n" x a-cnt t-cnt)))
)
(for-each cnt-type (cog-get-types))
)