(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-ipfs))
(ipfs-open "ipfs:///demo-atomspace")
(ipfs-atomspace-cid)
(ipns-atomspace-cid)
(define c (Concept "example concept"))
(store-atom c)
(ipfs-atom-cid c)
(ipfs-publish-atomspace)
(define e
(Evaluation
(Predicate "Some relationship")
(List (Concept "foo") (Concept "bar"))))
(store-atom e)
(ipfs-publish-atomspace)
(ipfs-atom-cid e)
(ipfs-stats)
(ipfs-close)