(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-ipfs))
(ipfs-open "ipfs:///demo-atomspace")
(define c (Concept "example concept"))
(cog-set-tv! c (SimpleTruthValue 0.45 0.33))
(store-atom c)
(ipfs-atom-cid c)
(cog-set-value! c (Predicate "position") (FloatValue 1.1 2.2 3.3))
(cog-set-value! c (Predicate "velocity") (FloatValue 4.4 5.5 6.6))
(store-atom c)
(define e
(Evaluation
(Predicate "Some relationship")
(List (Concept "foo") (Concept "bar"))))
(cog-set-value! e (Predicate "position") (FloatValue 3 2 1))
(cog-set-value! e (Predicate "velocity") (FloatValue 42 41 40))
(store-atom e)
(ipfs-close)