from opencog.atomspace import *
from opencog.type_constructors import *
set_default_atomspace(AtomSpace())
A = ConceptNode('Apple')
B = ConceptNode('Berry')
C = ConceptNode('Comestible')
weights = FloatValue([1, 0.8, 42, 3.14159])
key = PredicateNode('my favorite keyname')
A.set_value(key, weights)
B.set_value(key, FloatValue([0.5, 0.333, 66, 2.71828]))
C.set_value(key, StringValue(['just', 'some', 'words']))
A.get_value(key)
B.get_value(key)
C.get_value(key)
print('ello, there:', list(C.get_value(key)))
InheritanceLink(A, B)
InheritanceLink(B, C)
InheritanceLink(A, C)
EdgeLink(PredicateNode('is a'), ListLink(A, ConceptNode('fruit')))
EdgeLink(PredicateNode('has a'), ListLink(A, ConceptNode('stem')))
is_red = EdgeLink(PredicateNode('often colored'), ListLink(A, ConceptNode('red')))
is_red.set_value(key, FloatValue(0.5))
setter_graph = SetValueLink(is_red, key, NumberNode(0.777))
is_red.get_value(key)
setter_graph.execute()
is_red.get_value(key)
ValueOfLink(is_red, key).execute()
print('The atomspace contains:\n\n', MeetLink(VariableNode('x')).execute())