from opencog.atomspace import AtomSpace, types
from opencog.type_constructors import *
set_default_atomspace(AtomSpace())
tag = PredicateNode('word-pair')
EdgeLink(tag, ListLink(ItemNode('the'), ItemNode('dog')))
EdgeLink(tag, ListLink(ItemNode('dog'), ItemNode('chased')))
EdgeLink(tag, ListLink(ItemNode('the'), ItemNode('cat')))
EdgeLink(tag, ListLink(ItemNode('chased'), ItemNode('cat')))
EdgeLink(tag, ListLink(ItemNode('chased'), ItemNode('around')))
EdgeLink(tag, ListLink(ItemNode('the'), ItemNode('house')))
EdgeLink(tag, ListLink(ItemNode('around'), ItemNode('house')))
EdgeLink(tag, ListLink(ItemNode('cat'), ItemNode('around')))
EdgeLink(tag, ListLink(ItemNode('HEAD'), ItemNode('dog')))
EdgeLink(tag, ListLink(ItemNode('HEAD'), ItemNode('chased')))
pair_pattern = EdgeLink(tag, ListLink(VariableNode('$left-word'), VariableNode('$right-word')))
pair_vardecls = VariableList(TypedVariableLink(VariableNode('$left-word'), TypeNode('ItemNode')), TypedVariableLink(VariableNode('$right-word'), TypeNode('ItemNode')))
basic_query = QueryLink(pair_vardecls, PresentLink(pair_pattern), pair_pattern)
basic_query.execute()
print('Basic query returned:', ValueOfLink(basic_query, basic_query).execute())
print('')
count_key = PredicateNode('counter')
counting_query = QueryLink(pair_vardecls, PresentLink(pair_pattern), IncrementValueLink(VariableNode('$left-word'), count_key, NumberNode([1, 0])), IncrementValueLink(VariableNode('$right-word'), count_key, NumberNode([0, 1])))
counting_query.execute()
get_words = MeetLink(TypedVariableLink(VariableNode('$word'), TypeNode('ItemNode')), PresentLink(VariableNode('$word')))
print('The set of words is:', get_words.execute())
print('')
the_unique_set_object = ValueOfLink(get_words, get_words).execute()
list_of_atoms = list(the_unique_set_object)
print('The list of word-atoms is', list_of_atoms)
print('')
list_of_word_strings = map(lambda wrd: wrd.name, list_of_atoms)
print('The list of word-strings is', list_of_word_strings)
print('')
for wrd in list_of_atoms:
    print(f"The word '{wrd.name}' has count {wrd.get_value(count_key)}")
print('')
word_counts = QueryLink(TypedVariableLink(VariableNode('$word'), TypeNode('ItemNode')), PresentLink(VariableNode('$word')), ValueOfLink(VariableNode('$word'), count_key))
print('The left and right counts on the words are:', word_counts.execute())
print('')
two_columns = TransposeColumn(ValueOfLink(word_counts, word_counts))
print('Here are the left and right counts, again:', two_columns.execute())
print('')
counts_and_names = QueryLink(TypedVariableLink(VariableNode('$word'), TypeNode('ItemNode')), PresentLink(VariableNode('$word')), ElementOfLink(NumberNode(0), ValueOfLink(VariableNode('$word'), count_key)), ElementOfLink(NumberNode(1), ValueOfLink(VariableNode('$word'), count_key)), SexprColumn(VariableNode('$word')))
print('Words and their counts:', counts_and_names.execute())
print('')
three_columns = TransposeColumn(ValueOfLink(counts_and_names, counts_and_names))
print('And again, with columns:', three_columns.execute())
print('')