(use-modules (opencog) (opencog exec) (opencog persist))
(use-modules (opencog nlp) (opencog nlp lg-parse))
(use-modules (opencog matrix))
(use-modules (srfi srfi-1))
(define-public (make-parse-pipe PARSE-STREAM STORAGE PARSE-CNT)
"
  make-parse-pipe PARSE-STREAM STORAGE PARSE-CNT - Create and return a
  counter that increments counts on Atoms being delivered via the
  PARSE-STREAM.
  This counter takes a stream of parsing results (a stream of Atoms),
  generated on PARSE-STREAM, increments the count on each Atom, and
  then stores the Atoms to STORAGE. For each specific parse, the count
  on the Atom PARSE-CNT is incremented by one.
  A very specific format is assumed for the parse-stream
  to be stream of parses, with each parse being two distinct streams of
  Atoms. This is exactly the format generated by both LgParseBonds
  and LgParseSections, and so this counter can count observed words,
  edges and sections.
  The counting is done entirely in Atomese, not scheme.
  Requires the following arguments:
    PARSE-STREAM should be either (LgParseBonds ...) or (LgParseSections ...)
    STORAGE a StorageNode
    PARSE-CNT an Atom which is incremented for each parse.
  Experimental
  the sensory-agent API. The current structure here is a bit hacky.
"
	(define COUNT-PRED (PredicateNode "*-TruthValueKey-*"))
	(define COUNT-ZERO (Number 0 0 0))
	(define COUNT-ONE (Number 0 0 1))
	(define (incr-cnt atom)
		(SetValue atom COUNT-PRED
			(Plus COUNT-ONE
				(FloatValueOf atom COUNT-PRED
					(FetchValueOf atom COUNT-PRED STORAGE
						(FloatValueOf COUNT-ZERO))))))
	(define (store-cnt atom)
		(StoreValueOf atom COUNT-PRED STORAGE))
	(define (atom-counter ATOM-LIST)
		(Filter
			(Rule
				(Variable "$atom")
				(Variable "$atom")
				(incr-cnt (Variable "$atom"))
				(store-cnt (Variable "$atom"))
			)
			ATOM-LIST))
	(define (stream-splitter PASRC FUNKY)
		(Filter
			(Rule
				(LinkSignature
					(Type 'LinkValue)
					(Variable "$word-list")
					(Variable "$edge-list"))
				(FUNKY (Variable "$word-list"))
				(FUNKY (Variable "$edge-list"))
				(incr-cnt PARSE-CNT)
				(store-cnt PARSE-CNT))
			PASRC))
	(stream-splitter PARSE-STREAM atom-counter)
)
(define-public (make-random-pair-parser txt-stream STORAGE)
"
  make-random-pair-parser TXT-STREAM STORAGE - Count random word pairs.
  Return a text parser that counts words and random word-pairs obtained
  from parsing text on TXT-STREAM. The TXT-STREAM must be an Atom that,
  when executed, delivers a stream of text. In the typical case, the
  TXT-STREAM atom will be
     (ValueOf (Concept \"some atom\") (Predicate \"some key\"))
  and the Value there will provide a LinkStream of text to be parssed
  and counted.
  Counts in the parse stream are incremented, and then written out to
  STORAGE, which must be a StorageNode.
  The Link Grammar (LgDict \"any\") is used for parsing. This dict creates
  random planar graphs. The graph edges are the random word-pairs that
  get counted.
"
	(define NUML (Number 6))
	(define DICT (LgDict "any"))
	(define any-parse (ParseNode "ANY"))
	(define parser (LgParseBonds txt-stream DICT NUML))
	(make-parse-pipe parser STORAGE any-parse)
)
(define-public (make-disjunct-parser TXT-STREAM STORAGE)
"
  make-disjunct-parser TXT-STREAM STORAGE - Count disjuncts.
  Return a text parser that counts Edges and Sections obtained
  from MST/MPG parsing text on TXT-STREAM. The TXT-STREAM must be
  an Atom that, when executed, delivers a stream of text. In the
  typical case, the TXT-STREAM atom will be
     (ValueOf (Concept \"some atom\") (Predicate \"some key\"))
  and the Value there will provide a LinkStream of text to be parssed
  and counted.
  Counts in the parse stream are incremented, and then written out to
  STORAGE, which must be a StorageNode.
  The Link Grammar (LgDict \"dict-pair\") is used for parsing. This dict
  creates MST/MPG planar graphs, maximing the sum of MI of the edges
  occuring in the parse.
"
	(define NUML (Number 3))
	(define DICT (LgDict "dict-pair"))
	(define mst-parse (ParseNode "MST"))
	(define parser (LgParseSections TXT-STREAM DICT NUML (cog-atomspace)))
	(make-parse-pipe parser STORAGE mst-parse)
)