typedef struct Card Card;
typedef struct Type Type;
typedef struct Ctlr Ctlr;
struct Card {
ISAConf;
int	(*reset)(Ctlr*);
void	(*attach)(Ctlr*);
void	*(*read)(Ctlr*, void*, ulong, ulong);
void	*(*write)(Ctlr*, ulong, void*, ulong);
void	(*receive)(Ctlr*);
void	(*transmit)(Ctlr*);
void	(*intr)(Ureg*, void*);
void	(*overflow)(Ctlr*);
uchar	bit16;
uchar	ram;
ulong	dp8390;
ulong	data;
uchar	nxtpkt;
uchar	tstart;
uchar	pstart;
uchar	pstop;
uchar	dummyrr;
};
struct Ctlr {
Card	card;
int	ctlrno;
int	present;
Queue*	iq;
Queue*	oq;
int	inpackets;
int	outpackets;
int	crcs;
int	oerrs;
int	frames;
int	overflows;
int	buffs;
};
extern int sccethreset(Ctlr*);
extern int	etheriq(Ctlr*, Block*, int);