(use-modules (opencog pln))
(pln-load-rule 'inheritance-present-deduction)
(load "kb.scm")
(define A (Concept "A"))
(define X (Variable "$X"))
(define vardecl (TypedVariable X (Type "ConceptNode")))
(define AX (Inheritance A X))
(define fcresults (pln-fc AX #:vardecl vardecl))
(define ancestors (cog-execute! (Get vardecl AX)))