(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (setup-and-store)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define surface-space (cog-new-atomspace mid2-space))
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! mid1-space)
(Concept "foo" (ctv 1 0 33))
(Concept "bar" (ctv 1 0 4))
(cog-set-atomspace! mid2-space)
(Concept "foo" (ctv 1 0 333))
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 5))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames surface-space)
(store-atom (ListLink (Concept "foo") (Concept "bar")))
(store-atom (Concept "bar"))
(store-atom (Concept "foo"))
(cog-set-atomspace! mid1-space)
(store-atom (Concept "foo"))
(cog-set-atomspace! base-space)
(store-atom (Concept "foo"))
(cog-close storage)
(cog-atomspace-clear surface-space)
(cog-atomspace-clear mid2-space)
(cog-atomspace-clear mid1-space)
(cog-atomspace-clear base-space)
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-load-single)
(setup-and-store)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(fetch-atom (Concept "foo"))
(cog-close storage)
(define surface-space top-space)
(define mid2-space (cog-outgoing-atom surface-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(test-equal "foo-space" top-space (cog-atomspace (Concept "foo")))
(cog-set-atomspace! mid2-space)
(test-equal "foo-mid2-tv" 333 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! mid1-space)
(test-equal "foo-mid1-tv" 33 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! base-space)
(test-equal "foo-base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
)
(define load-single "test load-single")
(test-begin load-single)
(test-load-single)
(test-end load-single)
(whack "/tmp/cog-rocks-unit-test")
(define (test-load-of-type)
(setup-and-store)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atoms-of-type 'Concept)
(cog-close storage)
(define surface-space top-space)
(define mid2-space (cog-outgoing-atom surface-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! mid2-space)
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(test-equal "link-space" mid2-space (cog-atomspace lilly))
(test-equal "foo-space" mid2-space (cog-atomspace (gar lilly)))
(test-equal "bar-space" mid1-space (cog-atomspace (gdr lilly)))
(test-equal "foo-mid2-tv" 333 (get-cnt (cog-node 'Concept "foo")))
(test-equal "bar-tv" 4 (get-cnt (cog-node 'Concept "bar")))
(cog-set-atomspace! mid1-space)
(test-equal "foo-mid1-tv" 33 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! base-space)
(test-equal "foo-base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
)
(define load-of-type "test load-of-type")
(test-begin load-of-type)
(test-load-of-type)
(test-end load-of-type)
(whack "/tmp/cog-rocks-unit-test")
(define (test-load-incoming)
(setup-and-store)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(fetch-incoming-set (Concept "foo"))
(cog-close storage)
(define surface-space top-space)
(define mid2-space (cog-outgoing-atom surface-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(define lilly (ListLink (Concept "foo") (Concept "bar")))
(test-equal "lilly-tv" 5 (get-cnt lilly))
(cog-set-atomspace! mid2-space)
(define lulu (cog-link 'ListLink (Concept "foo") (Concept "bar")))
(test-equal "lulu-space" mid2-space (cog-atomspace lulu))
)
(define load-incoming "test load-incoming")
(test-begin load-incoming)
(test-load-incoming)
(test-end load-incoming)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)