(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (test-print)
(define a (AtomSpace))
(define b (AtomSpace))
(define c (AtomSpace a b))
(cog-set-atomspace! a)
(Concept "I'm in A")
(cog-prt-atomspace)
(cog-set-atomspace! b)
(Concept "I'm in B")
(cog-prt-atomspace)
(cog-set-atomspace! c)
(define rsn (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open rsn)
(store-atomspace)
(cog-prt-atomspace)
(cog-close rsn)
)
(define test-name "test print")
(test-begin test-name)
(test-print)
(test-end test-name)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)