(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(opencog-test-runner)
(define (setup-and-store DELETE)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define mid3-space (cog-new-atomspace mid2-space))
(define surface-space (cog-new-atomspace mid3-space))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames surface-space)
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! mid1-space)
(DELETE (Concept "foo"))
(cog-set-atomspace! mid2-space)
(Concept "foo" (ctv 1 0 5))
(cog-set-atomspace! mid3-space)
(DELETE (Concept "foo"))
(cog-set-atomspace! surface-space)
(Concept "foo" (ctv 1 0 7))
(cog-set-atomspace! base-space)
(store-atomspace)
(cog-set-atomspace! mid1-space)
(store-atomspace)
(cog-set-atomspace! mid2-space)
(store-atomspace)
(cog-set-atomspace! mid3-space)
(store-atomspace)
(cog-set-atomspace! surface-space)
(store-atomspace)
(cog-close storage)
surface-space
)
(define (test-deep DELETE)
(cog-set-atomspace! (cog-new-atomspace))
(setup-and-store DELETE)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(define surface-space top-space)
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! base-space)
(test-assert "base-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "base-tv" 3 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! mid1-space)
(test-assert "mid1-absent" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! mid2-space)
(test-assert "mid2-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "mid2-tv" 5 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! mid3-space)
(test-assert "mid3-absent" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! surface-space)
(test-assert "surface-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "surface-tv" 7 (get-cnt (cog-node 'Concept "foo")))
)
(define deep-extract "test deep extract")
(test-begin deep-extract)
(test-deep cog-extract!)
(test-end deep-extract)
(whack "/tmp/cog-rocks-unit-test")
(define deep-delete "test deep delete")
(test-begin deep-delete)
(test-deep cog-delete!)
(test-end deep-delete)
(whack "/tmp/cog-rocks-unit-test")
(define (setup-deep-change DELETE)
(define surface-space (setup-and-store DELETE))
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(cog-set-atomspace! base-space)
(cog-set-tv! (Concept "foo") (ctv 1 0 2))
(cog-set-atomspace! mid2-space)
(cog-set-tv! (Concept "foo") (ctv 1 0 4))
(cog-set-atomspace! surface-space)
(cog-set-tv! (Concept "foo") (ctv 1 0 6))
(cog-set-atomspace! base-space)
(store-atomspace)
(cog-set-atomspace! mid1-space)
(store-atomspace)
(cog-set-atomspace! mid2-space)
(store-atomspace)
(cog-set-atomspace! mid3-space)
(store-atomspace)
(cog-set-atomspace! surface-space)
(store-atomspace)
(cog-close storage)
)
(define (test-deep-change DELETE)
(cog-set-atomspace! (cog-new-atomspace))
(setup-deep-change DELETE)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(define surface-space top-space)
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! base-space)
(test-assert "base-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "base-tv" 2 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! mid1-space)
(test-assert "mid1-space" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! mid2-space)
(test-assert "mid2-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "mid2-tv" 4 (get-cnt (cog-node 'Concept "foo")))
(cog-set-atomspace! mid3-space)
(test-assert "mid3-space" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! surface-space)
(test-assert "surface-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "surface-tv" 6 (get-cnt (cog-node 'Concept "foo")))
)
(define deep-change-extract "test deep change-extract")
(test-begin deep-change-extract)
(test-deep-change cog-extract!)
(test-end deep-change-extract)
(whack "/tmp/cog-rocks-unit-test")
(define deep-change-delete "test deep change-delete")
(test-begin deep-change-delete)
(test-deep-change cog-delete!)
(test-end deep-change-delete)
(whack "/tmp/cog-rocks-unit-test")
(define (setup-link-check DELETE-REC)
(define surface-space (cog-atomspace))
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames surface-space)
(cog-set-atomspace! base-space)
(Concept "bar")
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 10))
(cog-set-atomspace! mid1-space)
(DELETE-REC (Concept "foo"))
(cog-set-atomspace! mid2-space)
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 20))
(cog-set-atomspace! mid3-space)
(DELETE-REC (Concept "foo"))
(cog-set-atomspace! surface-space)
(ListLink (Concept "foo") (Concept "bar") (ctv 1 0 30))
(cog-set-atomspace! base-space)
(store-atomspace)
(cog-set-atomspace! mid1-space)
(store-atomspace)
(cog-set-atomspace! mid2-space)
(store-atomspace)
(cog-set-atomspace! mid3-space)
(store-atomspace)
(cog-set-atomspace! surface-space)
(store-atomspace)
(cog-close storage)
)
(define (test-deep-link DELETE-REC)
(setup-link-check DELETE-REC)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(define surface-space top-space)
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! base-space)
(test-assert "base-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "base-tv" 2 (get-cnt (Concept "foo")))
(test-equal "base-litv" 10 (get-cnt
(ListLink (Concept "foo") (Concept "bar"))))
(cog-set-atomspace! mid1-space)
(test-assert "mid1-space" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! mid2-space)
(test-assert "mid2-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "mid2-tv" 4 (get-cnt (Concept "foo")))
(test-equal "mid2-litv" 20 (get-cnt
(ListLink (Concept "foo") (Concept "bar"))))
(cog-set-atomspace! mid3-space)
(test-assert "mid3-space" (nil? (cog-node 'Concept "foo")))
(cog-set-atomspace! surface-space)
(test-assert "surface-space" (cog-atom? (cog-node 'Concept "foo")))
(test-equal "surface-tv" 6 (get-cnt (Concept "foo")))
(test-equal "surface-litv" 30 (get-cnt
(ListLink (Concept "foo") (Concept "bar"))))
)
(whack "/tmp/cog-rocks-unit-test")
(define deep-link-extract "test deep link-extract")
(test-begin deep-link-extract)
(test-deep-link cog-extract-recursive!)
(test-end deep-link-extract)
(whack "/tmp/cog-rocks-unit-test")
(define deep-link-delete "test deep link-delete")
(test-begin deep-link-delete)
(test-deep-link cog-delete-recursive!)
(test-end deep-link-delete)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)