(use-modules (opencog) (opencog persist) (opencog persist-rocks))
(use-modules (opencog test-runner))
(opencog-test-runner)
(define tname "store_episodes")
(test-begin tname)
(define base-space (cog-atomspace))
(ConceptNode "foo")
(cog-set-value! (ConceptNode "foo") (Predicate "bunch o numbers")
		(FloatValue 1 2 3.14159 4 5 6))
(cog-set-value! (ConceptNode "foo") (Predicate "some words")
		(StringValue "once" "upon" "a" "time"))
(cog-set-value! (ConceptNode "foo") (Predicate "some atoms")
		(LinkValue (Concept "dog") (Concept "cat") (Concept "mouse")))
(cog-set-value! (ConceptNode "foo") (Predicate "real life")
		(AtomSpace "happy thoughts"))
(cog-set-value! (ConceptNode "foo") (Predicate "repressed mem")
		(AtomSpace "crushing defeat"))
(cog-set-atomspace!
	(cog-value (ConceptNode "foo") (Predicate "real life")))
(ListLink (Concept "mom") (Concept "dad"))
(ListLink (Concept "first crush") (Concept "Gilanda"))
(ListLink (Concept "stack blocks"))
(cog-set-atomspace! base-space)
(cog-set-atomspace!
	(cog-value (ConceptNode "foo") (Predicate "repressed mem")))
(ListLink (Concept "misdemeanor") (Concept "vandalism"))
(ListLink (Concept "furious") (Concept "anger"))
(cog-set-atomspace! base-space)
(format #t "Atom counts in subspaces are ~A ~A ~A\n"
	(count-all)
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem"))))
(test-assert "base-count" (equal? 11 (count-all)))
(test-assert "space1-count" (equal? 8
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 6
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(define rsn (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open rsn)
(store-atomspace)
(store-atomspace (AtomSpace "happy thoughts"))
(store-atomspace (AtomSpace "crushing defeat"))
(cog-close rsn)
(cog-prt-atomspace)
(cog-prt-atomspace (AtomSpace "happy thoughts"))
(cog-prt-atomspace (AtomSpace "crushing defeat"))
(set! rsn #f)
(gc) (gc)
(cog-atomspace-clear)
(define gsn (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open gsn)
(load-atomspace)
(format #t "Loaded Atom counts ~A ~A ~A\n"
	(count-all)
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem"))))
(test-assert "base-count" (equal? 16 (count-all)))
(test-assert "space1-count" (equal? 0
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 0
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(load-atomspace (AtomSpace "happy thoughts"))
(load-atomspace (AtomSpace "crushing defeat"))
(cog-close gsn)
(test-assert "base-count" (equal? 17 (count-all)))
(test-assert "space1-count" (equal? 8
	(count-all (cog-value (ConceptNode "foo") (Predicate "real life")))))
(test-assert "space2-count" (equal? 6
	(count-all (cog-value (ConceptNode "foo") (Predicate "repressed mem")))))
(cog-prt-atomspace)
(cog-prt-atomspace (AtomSpace "happy thoughts"))
(cog-prt-atomspace (AtomSpace "crushing defeat"))
(test-end tname)
(opencog-test-end)