(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-rocks))
(use-modules (ice-9 threads))
(define sto (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(define (open-sto) (cog-open sto))
(define (close-sto) (cog-close sto))
(define (observe TXTA TXTB)
	(define ca (Concept TXTA))
	(define cb (Concept TXTB))
	(define edge (Edge (Predicate "foo") (List ca cb)))
	(cog-inc-count! ca 1)
	(cog-inc-count! cb 1)
	(cog-inc-count! edge 1)
	(store-atom ca)
	(store-atom cb)
	(store-atom edge)
)
(define (pushy TXTA TXTB)
	(define base-as (cog-push-atomspace))
	(define ca (Concept TXTA))
	(define cb (Concept TXTB))
	(define edge (Edge (Predicate "foo") (List ca cb)))
	(cog-set-atomspace! base-as)
	(cog-inc-count! ca 1)
	(cog-inc-count! cb 1)
	(cog-inc-count! edge 1)
	(store-atom ca)
	(store-atom cb)
	(store-atom edge)
	(cog-pop-atomspace)
)
(define mtx (make-mutex))
(define (fetchy TXTA TXTB)
	(define ca (Concept TXTA))
	(define cb (Concept TXTB))
	(define edge (Edge (Predicate "foo") (List ca cb)))
	(if (not (cog-ctv? (cog-tv edge)))
		(begin
			(lock-mutex mtx)
			(if (not (cog-ctv? (cog-tv edge)))
				(fetch-atom edge))
			(cog-inc-count! edge 1)
			(unlock-mutex mtx))
		(cog-inc-count! edge 1))
	(fetch-atom ca)
	(fetch-atom cb)
	(cog-inc-count! ca 1)
	(cog-inc-count! cb 1)
	(store-atom ca)
	(store-atom cb)
	(store-atom edge)
)
(define (letch TXTA TXTB)
	(define ca (Concept TXTA))
	(define cb (Concept TXTB))
	(define edge (Edge (Predicate "foo") (List ca cb)))
	(when (not (cog-ctv? (cog-tv edge)))
		(lock-mutex mtx)
		(if (not (cog-ctv? (cog-tv edge)))
			(fetch-atom edge))
		(unlock-mutex mtx))
	(cog-inc-count! edge 1)
	(fetch-atom ca)
	(fetch-atom cb)
	(cog-inc-count! ca 1)
	(cog-inc-count! cb 1)
	(store-atom ca)
	(store-atom cb)
	(store-atom edge)
)