(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-rocks))
(include "test-utils.scm")
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-runner)
(define (setup-and-store)
(define base-space (cog-atomspace))
(define mid1-space (cog-new-atomspace base-space))
(define mid2-space (cog-new-atomspace mid1-space))
(define mid3-space (cog-new-atomspace mid2-space))
(define surface-space (cog-new-atomspace mid3-space))
(cog-set-atomspace! base-space)
(Concept "foo" (ctv 1 0 3))
(cog-set-atomspace! mid1-space)
(Concept "bar" (ctv 1 0 4))
(cog-set-atomspace! mid2-space)
(List (Concept "bar") (ctv 1 0 5))
(cog-set-atomspace! mid3-space)
(List (Concept "foo") (List (Concept "bar")) (ctv 1 0 6))
(cog-set-atomspace! surface-space)
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(store-frames surface-space)
(store-atom (ListLink (Concept "foo") (List (Concept "bar"))))
(cog-close storage)
(cog-atomspace-clear surface-space)
(cog-atomspace-clear mid3-space)
(cog-atomspace-clear mid2-space)
(cog-atomspace-clear mid1-space)
(cog-atomspace-clear base-space)
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-save-value)
(setup-and-store)
(cog-set-atomspace! (cog-new-atomspace))
(define storage (RocksStorageNode "rocks:///tmp/cog-rocks-unit-test"))
(cog-open storage)
(define top-space (car (load-frames)))
(cog-set-atomspace! top-space)
(load-atomspace)
(cog-close storage)
(define surface-space top-space)
(define mid3-space (cog-outgoing-atom surface-space 0))
(define mid2-space (cog-outgoing-atom mid3-space 0))
(define mid1-space (cog-outgoing-atom mid2-space 0))
(define base-space (cog-outgoing-atom mid1-space 0))
(cog-set-atomspace! surface-space)
(define lilly (ListLink (Concept "foo") (List (Concept "bar"))))
(test-equal "link-space" mid3-space (cog-atomspace lilly))
(test-equal "foo-space" base-space (cog-atomspace (gar lilly)))
(test-equal "link-bar-space" mid2-space (cog-atomspace (gdr lilly)))
(test-equal "bar-space" mid1-space (cog-atomspace (gadr lilly)))
(test-equal "base-tv" 0 (get-cnt (cog-node 'Concept "foo")))
(test-equal "mid1-tv" 0 (get-cnt (cog-node 'Concept "bar")))
(test-equal "mid2-tv" 0 (get-cnt (cog-link 'List (Concept "bar"))))
(test-equal "mid3-tv" 6 (get-cnt lilly))
)
(define save-value "test save links")
(test-begin save-value)
(test-save-value)
(test-end save-value)
(whack "/tmp/cog-rocks-unit-test")
(opencog-test-end)