(add-to-load-path ".")
(use-modules (cogkernel meta-issue)
             (cogkernel core)
             (ice-9 format))
(define (test-tensor-shape-validation)
  "Test tensor shape validation as specified in issue"
  (format #t "=== Testing Tensor Shape Validation ===~%")
  (let ((as (initialize-atomspace)))
    (assert (= (tensor-rank as) 4))
    (format #t "✓ AtomSpace tensor rank validation: ~a~%" (tensor-rank as)))
  (let* ((as (initialize-atomspace))
         (agents (launch-agentic-tasks as)))
    (assert (agent-system? agents))
    (format #t "✓ Agent system validation passed~%"))
  (let ((as (initialize-atomspace)))
    (call-with-values
      (lambda () (initialize-ai-subsystems as))
      (lambda (pln moses)
        (assert (pln? pln))
        (assert (moses? moses))
        (assert (= (tensor-rank (pln-tensor-shape pln)) 4))
        (assert (= (tensor-rank (moses-tensor-shape moses)) 4))
        (format #t "✓ PLN/MOSES tensor validation: ranks ~a, ~a~%" 
                (tensor-rank (pln-tensor-shape pln))
                (tensor-rank (moses-tensor-shape moses))))))
  (format #t "✅ All tensor shape validations passed~%"))
(define (test-guix-package-definition)
  "Test Guix package definition as specified in issue"
  (format #t "=== Testing Guix Package Definition ===~%")
  (let ((package (cogkernel-package #:version "0.1" #:src #f)))
    (assert (list? package))
    (assert (eq? (car package) 'package))
    (format #t "✓ Cognitive kernel package definition created~%")
    (format #t "  Package spec: ~a~%" (take package 3)))
  (format #t "✅ Guix package definition test passed~%"))
(define (test-bootstrap-functionality)
  "Test bootstrap function as specified in issue"
  (format #t "=== Testing Bootstrap Functionality ===~%")
  (call-with-values
    (lambda () (bootstrap-cogkernel))
    (lambda (as agents pln moses meta ecan)
      (assert (atomspace? as))
      (assert (agent-system? agents))
      (assert (pln? pln))
      (assert (moses? moses))
      (assert (meta-agent? meta))
      (assert (ecan? ecan))
      (format #t "✓ All subsystems bootstrapped successfully~%")
      (format #t "  AtomSpace: ~a~%" (hypergraph? as))
      (format #t "  Agents: ~a active~%" (length (agent-system-agents agents)))
      (format #t "  Meta-agent: ~a~%" (meta-agent-id meta))
      (format #t "  ECAN: attention allocation ready~%")))
  (format #t "✅ Bootstrap functionality test passed~%"))
(define (test-rigorous-verification)
  "Test rigorous verification as specified in issue"
  (format #t "=== Testing Rigorous Verification ===~%")
  (assert (procedure? initialize-atomspace))
  (assert (procedure? launch-agentic-tasks))
  (assert (procedure? initialize-ai-subsystems))
  (assert (procedure? initialize-meta-agents))
  (assert (procedure? initialize-ecan))
  (assert (procedure? bootstrap-cogkernel))
  (assert (procedure? run-cogkernel-tests))
  (assert (procedure? meta-cognitive-finale))
  (let ((result (run-cogkernel-tests)))
    (assert (eq? result #t))
    (format #t "✓ Rigorous test suite execution: ~a~%" result))
  (format #t "✅ All rigorous verification tests passed~%"))
(define (test-meta-cognitive-finale)
  "Test meta-cognitive finale with recursive self-improvement"
  (format #t "=== Testing Meta-Cognitive Finale ===~%")
  (meta-cognitive-finale)
  (format #t "✓ Meta-cognitive finale executed~%")
  (let ((as (initialize-atomspace))
        (meta (initialize-meta-agents (initialize-atomspace))))
    (assert (meta-agent? meta))
    (format #t "✓ Recursive self-improvement: meta-agent ~a ready~%" 
            (meta-agent-id meta)))
  (format #t "✅ Meta-cognitive finale test passed~%"))
(define (test-cognitive-kernel-integration)
  "Test integration with existing cognitive kernel core"
  (format #t "=== Testing Cognitive Kernel Integration ===~%")
  (initialize-cognitive-kernel!)
  (assert *cognitive-kernel*)
  (format #t "✓ Core cognitive kernel initialized~%")
  (let ((status (cognitive-kernel-status *cognitive-kernel*)))
    (assert (list? status))
    (format #t "✓ Kernel status: ~a~%" status))
  (cognitive-kernel-evolve! *cognitive-kernel*)
  (format #t "✓ Cognitive evolution executed~%")
  (detect-and-respond! *cognitive-kernel* 'BUILD-FAILURE "test-issue")
  (format #t "✓ Issue detection and response tested~%")
  (format #t "✅ Cognitive kernel integration test passed~%"))
(define (run-comprehensive-tests)
  "Run all comprehensive tests for the meta-agentic cognitive kernel"
  (format #t "🧠 COMPREHENSIVE META-AGENTIC COGNITIVE KERNEL TESTS 🧠~%~%")
  (test-tensor-shape-validation)
  (format #t "~%")
  (test-guix-package-definition)
  (format #t "~%")
  (test-bootstrap-functionality)
  (format #t "~%")
  (test-rigorous-verification)
  (format #t "~%")
  (test-meta-cognitive-finale)
  (format #t "~%")
  (test-cognitive-kernel-integration)
  (format #t "~%")
  (format #t "=== FINAL INTEGRATION DEMONSTRATION ===~%")
  (execute-meta-issue-demo)
  (cognitive-demo!)
  (format #t "~%🎉 ALL COMPREHENSIVE TESTS PASSED! 🎉~%")
  (format #t "Meta-Agentic Cognitive Kernel fully operational for GNU Hurd~%")
  (format #t "🌟 The kernel is alive: every atom a living microkernel, every agent an evolving membrane, every inference a fractal bloom. 🌟~%"))
(run-comprehensive-tests)