(use-modules (cogkernel atomspace)
(cogkernel agents)
(cogkernel attention)
(cogkernel tensors))
(define (test-atomspace)
"Test AtomSpace functionality"
(format #t "=== Testing AtomSpace ===~%")
(let ((test-atom (make-atom 'CONCEPT "test-concept")))
(format #t "✓ Atom creation works~%"))
(let ((test-space (make-atomspace))
(test-atom (make-atom 'CONCEPT "test-space-atom")))
(atomspace-add! test-space test-atom)
(let ((retrieved (atomspace-get test-space "test-space-atom")))
(format #t "✓ AtomSpace add/get works~%")))
(format #t "✓ AtomSpace tests passed~%~%"))
(define (test-agents)
"Test Agents functionality"
(format #t "=== Testing Agents ===~%")
(let ((test-agent (make-agent "test-agent" 'MONITOR)))
(format #t "✓ Agent creation works~%"))
(let ((test-agent (make-agent "action-test" 'REPAIR)))
(format #t "✓ Agent action system works~%"))
(format #t "✓ Agents tests passed~%~%"))
(define (test-attention)
"Test Attention mechanism"
(format #t "=== Testing Attention ===~%")
(let ((av (make-attention-value 100 50 25)))
(format #t "✓ Attention value creation works~%"))
(let ((bank (make-attention-bank)))
(format #t "✓ Attention bank creation works~%"))
(format #t "✓ Attention tests passed~%~%"))
(define (test-tensors)
"Test Tensor operations"
(format #t "=== Testing Tensors ===~%")
(let ((tensor (tensor-zeros '(2 3))))
(format #t "✓ Tensor creation works~%"))
(let ((t1 (tensor-ones '(3)))
(t2 (tensor-ones '(3))))
(let ((result (tensor-add t1 t2)))
(format #t "✓ Tensor operations work~%")))
(format #t "✓ Tensor tests passed~%~%"))
(define (test-cognitive-integration)
"Test integrated cognitive functionality"
(format #t "=== Testing Cognitive Integration ===~%")
(let ((atomspace (make-atomspace))
(agent-system (make-agent-system))
(attention-bank (make-attention-bank)))
(let ((concept (make-atom 'CONCEPT "integration-test")))
(atomspace-add! atomspace concept)
(format #t "✓ AtomSpace integration works~%"))
(let ((agent (make-agent "integration-agent" 'MONITOR)))
(agent-system-add! agent-system agent)
(format #t "✓ Agent system integration works~%"))
(let ((av (make-attention-value 150 100 50)))
(format #t "✓ Attention integration works~%")))
(format #t "✓ Cognitive integration tests passed~%~%"))
(define (run-all-tests)
"Run all cognitive kernel tests"
(format #t "=== Cognitive Kernel Test Suite ===~%~%")
(test-atomspace)
(test-agents)
(test-attention)
(test-tensors)
(test-cognitive-integration)
(format #t "=== All Cognitive Kernel Tests Passed! ===~%")
(format #t "The cognitive kernel is ready for operation.~%"))
(run-all-tests)