#define ENABLE_NLS 1
#define FUNC_REALPATH_WORKS 1
#define GNULIB_CANONICALIZE_LGPL 1
#define GNULIB_SIGPIPE 1
#define GNULIB_STRERROR 1
#define GNULIB_TEST_CANONICALIZE_FILE_NAME 1
#define GNULIB_TEST_ENVIRON 1
#define GNULIB_TEST_LSTAT 1
#define GNULIB_TEST_READ 1
#define GNULIB_TEST_READLINK 1
#define GNULIB_TEST_REALPATH 1
#define GNULIB_TEST_SIGPROCMASK 1
#define GNULIB_TEST_STAT 1
#define GNULIB_TEST_STRERROR 1
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_CANONICALIZE_FILE_NAME 1
#define HAVE_DCGETTEXT 1
#define HAVE_DECL_CLEARERR_UNLOCKED 1
#define HAVE_DECL_FEOF_UNLOCKED 1
#define HAVE_DECL_FERROR_UNLOCKED 1
#define HAVE_DECL_FFLUSH_UNLOCKED 1
#define HAVE_DECL_FGETS_UNLOCKED 1
#define HAVE_DECL_FPUTC_UNLOCKED 1
#define HAVE_DECL_FPUTS_UNLOCKED 1
#define HAVE_DECL_FREAD_UNLOCKED 1
#define HAVE_DECL_FWRITE_UNLOCKED 1
#define HAVE_DECL_GETCHAR_UNLOCKED 1
#define HAVE_DECL_GETC_UNLOCKED 1
#define HAVE_DECL_PROGRAM_INVOCATION_NAME 1
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 1
#define HAVE_DECL_PUTCHAR_UNLOCKED 1
#define HAVE_DECL_PUTC_UNLOCKED 1
#define HAVE_DECL_SETENV 1
#define HAVE_DECL_STRERROR_R 1
#define HAVE_DLFCN_H 1
#define HAVE_ENVIRON_DECL 1
#define HAVE_GETCWD 1
#define HAVE_GETC_UNLOCKED 1
#define HAVE_GETTEXT 1
#define HAVE_ICONV 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_LSTAT 1
#define HAVE_MBRTOWC 1
#define HAVE_MBSINIT 1
#define HAVE_MBSTATE_T 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_RAW_DECL_ATOLL 1
#define HAVE_RAW_DECL_CANONICALIZE_FILE_NAME 1
#define HAVE_RAW_DECL_CHOWN 1
#define HAVE_RAW_DECL_DPRINTF 1
#define HAVE_RAW_DECL_DUP2 1
#define HAVE_RAW_DECL_DUP3 1
#define HAVE_RAW_DECL_ENDUSERSHELL 1
#define HAVE_RAW_DECL_ENVIRON 1
#define HAVE_RAW_DECL_EUIDACCESS 1
#define HAVE_RAW_DECL_FACCESSAT 1
#define HAVE_RAW_DECL_FCHDIR 1
#define HAVE_RAW_DECL_FCHMODAT 1
#define HAVE_RAW_DECL_FCHOWNAT 1
#define HAVE_RAW_DECL_FCNTL 1
#define HAVE_RAW_DECL_FFSL 1
#define HAVE_RAW_DECL_FFSLL 1
#define HAVE_RAW_DECL_FSEEKO 1
#define HAVE_RAW_DECL_FSTATAT 1
#define HAVE_RAW_DECL_FSYNC 1
#define HAVE_RAW_DECL_FTELLO 1
#define HAVE_RAW_DECL_FTRUNCATE 1
#define HAVE_RAW_DECL_FUTIMENS 1
#define HAVE_RAW_DECL_GETCWD 1
#define HAVE_RAW_DECL_GETDELIM 1
#define HAVE_RAW_DECL_GETDOMAINNAME 1
#define HAVE_RAW_DECL_GETDTABLESIZE 1
#define HAVE_RAW_DECL_GETGROUPS 1
#define HAVE_RAW_DECL_GETHOSTNAME 1
#define HAVE_RAW_DECL_GETLINE 1
#define HAVE_RAW_DECL_GETLOADAVG 1
#define HAVE_RAW_DECL_GETLOGIN 1
#define HAVE_RAW_DECL_GETLOGIN_R 1
#define HAVE_RAW_DECL_GETPAGESIZE 1
#define HAVE_RAW_DECL_GETSUBOPT 1
#define HAVE_RAW_DECL_GETUSERSHELL 1
#define HAVE_RAW_DECL_GRANTPT 1
#define HAVE_RAW_DECL_GROUP_MEMBER 1
#define HAVE_RAW_DECL_LCHMOD 1
#define HAVE_RAW_DECL_LCHOWN 1
#define HAVE_RAW_DECL_LINK 1
#define HAVE_RAW_DECL_LINKAT 1
#define HAVE_RAW_DECL_LSEEK 1
#define HAVE_RAW_DECL_LSTAT 1
#define HAVE_RAW_DECL_MEMMEM 1
#define HAVE_RAW_DECL_MEMPCPY 1
#define HAVE_RAW_DECL_MEMRCHR 1
#define HAVE_RAW_DECL_MKDIRAT 1
#define HAVE_RAW_DECL_MKDTEMP 1
#define HAVE_RAW_DECL_MKFIFO 1
#define HAVE_RAW_DECL_MKFIFOAT 1
#define HAVE_RAW_DECL_MKNOD 1
#define HAVE_RAW_DECL_MKNODAT 1
#define HAVE_RAW_DECL_MKOSTEMP 1
#define HAVE_RAW_DECL_MKOSTEMPS 1
#define HAVE_RAW_DECL_MKSTEMP 1
#define HAVE_RAW_DECL_MKSTEMPS 1
#define HAVE_RAW_DECL_OPENAT 1
#define HAVE_RAW_DECL_PIPE 1
#define HAVE_RAW_DECL_PIPE2 1
#define HAVE_RAW_DECL_POPEN 1
#define HAVE_RAW_DECL_PREAD 1
#define HAVE_RAW_DECL_PTHREAD_SIGMASK 1
#define HAVE_RAW_DECL_PTSNAME 1
#define HAVE_RAW_DECL_PWRITE 1
#define HAVE_RAW_DECL_RANDOM_R 1
#define HAVE_RAW_DECL_RAWMEMCHR 1
#define HAVE_RAW_DECL_READLINK 1
#define HAVE_RAW_DECL_READLINKAT 1
#define HAVE_RAW_DECL_REALPATH 1
#define HAVE_RAW_DECL_RENAMEAT 1
#define HAVE_RAW_DECL_RMDIR 1
#define HAVE_RAW_DECL_RPMATCH 1
#define HAVE_RAW_DECL_SETENV 1
#define HAVE_RAW_DECL_SETSTATE_R 1
#define HAVE_RAW_DECL_SETUSERSHELL 1
#define HAVE_RAW_DECL_SIGACTION 1
#define HAVE_RAW_DECL_SIGADDSET 1
#define HAVE_RAW_DECL_SIGDELSET 1
#define HAVE_RAW_DECL_SIGEMPTYSET 1
#define HAVE_RAW_DECL_SIGFILLSET 1
#define HAVE_RAW_DECL_SIGISMEMBER 1
#define HAVE_RAW_DECL_SIGPENDING 1
#define HAVE_RAW_DECL_SIGPROCMASK 1
#define HAVE_RAW_DECL_SLEEP 1
#define HAVE_RAW_DECL_SNPRINTF 1
#define HAVE_RAW_DECL_SRANDOM_R 1
#define HAVE_RAW_DECL_STAT 1
#define HAVE_RAW_DECL_STPCPY 1
#define HAVE_RAW_DECL_STPNCPY 1
#define HAVE_RAW_DECL_STRCASESTR 1
#define HAVE_RAW_DECL_STRCHRNUL 1
#define HAVE_RAW_DECL_STRDUP 1
#define HAVE_RAW_DECL_STRERROR_R 1
#define HAVE_RAW_DECL_STRNCAT 1
#define HAVE_RAW_DECL_STRNDUP 1
#define HAVE_RAW_DECL_STRNLEN 1
#define HAVE_RAW_DECL_STRPBRK 1
#define HAVE_RAW_DECL_STRSEP 1
#define HAVE_RAW_DECL_STRSIGNAL 1
#define HAVE_RAW_DECL_STRTOD 1
#define HAVE_RAW_DECL_STRTOK_R 1
#define HAVE_RAW_DECL_STRTOLL 1
#define HAVE_RAW_DECL_STRTOULL 1
#define HAVE_RAW_DECL_STRVERSCMP 1
#define HAVE_RAW_DECL_SYMLINK 1
#define HAVE_RAW_DECL_SYMLINKAT 1
#define HAVE_RAW_DECL_TMPFILE 1
#define HAVE_RAW_DECL_TTYNAME_R 1
#define HAVE_RAW_DECL_UNLINK 1
#define HAVE_RAW_DECL_UNLINKAT 1
#define HAVE_RAW_DECL_UNLOCKPT 1
#define HAVE_RAW_DECL_UNSETENV 1
#define HAVE_RAW_DECL_USLEEP 1
#define HAVE_RAW_DECL_UTIMENSAT 1
#define HAVE_RAW_DECL_VDPRINTF 1
#define HAVE_RAW_DECL_VSNPRINTF 1
#define HAVE_RAW_DECL__EXIT 1
#define HAVE_READLINK 1
#define HAVE_READLINKAT 1
#define HAVE_REALPATH 1
#define HAVE_SEARCH_H 1
#define HAVE_SETENV 1
#define HAVE_SETLOCALE 1
#define HAVE_SIGSET_T 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRERROR_R 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TSEARCH 1
#define HAVE_UNISTD_H 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_VISIBILITY 1
#define HAVE_WCHAR_H 1
#define HAVE_WCHAR_T 1
#define HAVE_WCRTOMB 1
#define HAVE_WORKING_O_NOATIME 0
#define HAVE_WORKING_O_NOFOLLOW 1
#define HAVE__BOOL 1
#define ICONV_CONST
#define INSTALLPREFIX "/usr/local"
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define LT_OBJDIR ".libs/"
#define MALLOC_0_IS_NONNULL 1
#define PACKAGE "libiconv"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME ""
#define PACKAGE_STRING ""
#define PACKAGE_TARNAME ""
#define PACKAGE_URL ""
#define PACKAGE_VERSION ""
#define STDC_HEADERS 1
#define STRERROR_R_CHAR_P 1
#define USER_LABEL_PREFIX
#define USE_UNLOCKED_IO 1
#define VERSION "1.14"
#define WORDS_LITTLEENDIAN 1
#ifndef _Noreturn
# if (3 <= __GNUC__ || (__GNUC__ == 2 && 8 <= __GNUC_MINOR__) \
|| 0x5110 <= __SUNPRO_C)
#  define _Noreturn __attribute__ ((__noreturn__))
# elif 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn
# endif
#endif
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifndef _DARWIN_C_SOURCE
# define _DARWIN_C_SOURCE 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#ifndef __cplusplus
#endif
#if defined __APPLE__ && defined __MACH__ && __APPLE_CC__ >= 5465 && !defined __cplusplus && __STDC_VERSION__ >= 199901L && !defined __GNUC_STDC_INLINE__
# define __GNUC_STDC_INLINE__ 1
#endif
#define restrict __restrict
#if defined __SUNPRO_CC && !defined __RESTRICT
# define _Restrict
# define __restrict__
#endif
#if __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 7)
# define _GL_UNUSED __attribute__ ((__unused__))
#else
# define _GL_UNUSED
#endif
#define _UNUSED_PARAMETER_ _GL_UNUSED
#if __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 96)
# define _GL_ATTRIBUTE_PURE __attribute__ ((__pure__))
#else
# define _GL_ATTRIBUTE_PURE
#endif
#if __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
# define _GL_ATTRIBUTE_CONST __attribute__ ((__const__))
#else
# define _GL_ATTRIBUTE_CONST
#endif
#if defined _MSC_VER && defined _DLL
# define DLL_VARIABLE __declspec (dllimport)
#else
# define DLL_VARIABLE
#endif