(define-module (opencog vision))
(use-modules (opencog))
(use-modules (opencog sp-config))
(load-extension (string-append opencog-ext-path-vision-types "libvision") "vision_types_init")
(load "vision/vision_types.scm")