enum {
Ehdr32sz	= 52,
Phdr32sz	= 32,
Shdr32sz	= 40,
Ehdr64sz	= 64,
Phdr64sz	= 56,
Shdr64sz	= 64,
};
enum {
MAG0 = 0,
MAG1 = 1,
MAG2 = 2,
MAG3 = 3,
CLASS = 4,
DATA = 5,
VERSION = 6,
ELFCLASSNONE = 0,
ELFCLASS32 = 1,
ELFCLASS64 = 2,
ELFCLASSNUM = 3,
ELFDATANONE = 0,
ELFDATA2LSB = 1,
ELFDATA2MSB = 2,
ELFDATANUM = 3,
NOETYPE = 0,
REL = 1,
EXEC = 2,
DYN = 3,
CORE = 4,
NONE = 0,
M32 = 1,
SPARC = 2,
I386 = 3,
M68K = 4,
M88K = 5,
I486 = 6,
I860 = 7,
MIPS = 8,
S370 = 9,
MIPSR4K = 10,
SPARC64 = 18,
POWER = 20,
POWER64 = 21,
ARM = 40,
AMD64 = 62,
ARM64 = 183,
NO_VERSION = 0,
CURRENT = 1,
NOPTYPE = 0,
PT_LOAD = 1,
DYNAMIC = 2,
INTERP = 3,
NOTE = 4,
SHLIB = 5,
PHDR = 6,
R = 0x4,
W = 0x2,
X = 0x1,
Progbits = 1,
Strtab = 3,
Nobits = 8,
Swrite = 1,
Salloc = 2,
Sexec = 4,
};
typedef void (*Putl)(long);
void	elf32(int mach, int bo, int addpsects, void (*putpsects)(Putl));
void	elf32phdr(void (*putl)(long), ulong type, ulong off, ulong vaddr,
ulong paddr, ulong filesz, ulong memsz, ulong prots, ulong align);
void	elf32shdr(void (*putl)(long), ulong name, ulong type, ulong flags,
ulong vaddr, ulong off, ulong sectsz, ulong link, ulong addnl,
ulong align, ulong entsz);
void	elf64(int mach, int bo, int addpsects, void (*putpsects)(Putl));
void	elf64phdr(void (*putl)(long), void (*putll)(vlong), ulong type,
uvlong off, uvlong vaddr, uvlong paddr, uvlong filesz, uvlong memsz,
ulong prots, uvlong align);
void	elf64shdr(void (*putl)(long), void (*putll)(vlong), ulong name,
ulong type, uvlong flags, uvlong vaddr, uvlong off, uvlong sectsz,
ulong link, ulong addnl, uvlong align, uvlong entsz);