#ifndef	_HURD_PATHS_H
#define	_HURD_PATHS_H
#define	_SERVERS		"/servers/"
#define	_SERVERS_CRASH		_SERVERS "crash"
#define	_SERVERS_EXEC		_SERVERS "exec"
#define _SERVERS_STARTUP	_SERVERS "startup"
#define _SERVERS_PROC		_SERVERS "proc"
#define _SERVERS_PASSWORD	_SERVERS "password"
#define _SERVERS_DEFPAGER	_SERVERS "default-pager"
#define	_SERVERS_SOCKET		_SERVERS "socket"
#define	_SERVERS_BUS		_SERVERS "bus"
#define _SERVERS_ACPI		_SERVERS "acpi"
#define	_HURD		"/hurd/"
#define	_HURD_STARTUP	_HURD "startup"
#define _HURD_PROC	_HURD "proc"
#define _HURD_AUTH	_HURD "auth"
#define	_HURD_SYMLINK	_HURD "symlink"
#define	_HURD_CHRDEV	_HURD "chrdev"
#define	_HURD_BLKDEV	_HURD "blkdev"
#define	_HURD_FIFO	_HURD "fifo"
#define	_HURD_IFSOCK	_HURD "ifsock"
#define _HURD_MAGIC	_HURD "magic"
#define _HURD_MTAB	_HURD "mtab"
#endif