(use-modules (ice-9 threads))
(define (count-quarter-links WORD-LST)
(fold
(lambda (CTR cnt)
(+ cnt (cog-incoming-size-by-type CTR 'ConnectorSeq)))
0
(append-map
(lambda (WRD) (cog-incoming-by-type WRD 'Connector))
WORD-LST))
)
(define (count-half-links WORD-LST)
(define (num-sects-w-con CON)
(fold
(lambda (CONSEQ CNT)
(+ CNT (cog-incoming-size-by-type CONSEQ 'Section)))
0
(cog-incoming-by-type CON 'ConnectorSeq)))
(fold
(lambda (CON cnt)
(+ cnt (num-sects-w-con CON)))
0
(append-map
(lambda (WRD) (cog-incoming-by-type WRD 'Connector))
WORD-LST))
)
(define (count-linkable-word-pairs WORD-LST)
(define (right-con WRD)
(define ctr (cog-link 'Connector WRD (ConnectorDir "+")))
(and (not (equal? ctr '())) ctr))
(define (left-con WRD)
(define ctr (cog-link 'Connector WRD (ConnectorDir "-")))
(and (not (equal? ctr '())) ctr))
(define (sects-w-con CON)
(append-map
(lambda (CONSEQ)
(cog-incoming-by-type CONSEQ 'Section))
(cog-incoming-by-type CON 'ConnectorSeq)))
(define (right-halves LEFT-WRD)
(define rc (left-con LEFT-WRD))
(if rc (sects-w-con rc) '()))
(define (left-halves RIGHT-WRD)
(define rc (right-con RIGHT-WRD))
(if rc (sects-w-con rc) '()))
(define (right-words LEFT-WRD)
(define word-set (make-atom-set))
(for-each word-set (map gar (right-halves LEFT-WRD)))
(word-set #f))
(define (linkables LEFT-WRD)
(filter
(lambda (R-WRD)
(any
(lambda (SECT) (equal? (gar SECT) LEFT-WRD))
(left-halves R-WRD)))
(right-words LEFT-WRD)))
(define (links LEFT-WRD)
(define link-set (make-atom-set))
(for-each link-set (linkables LEFT-WRD))
(link-set #f))
(fold
(lambda (WRD CNT) (+ CNT (length (links WRD))))
0 WORD-LST)
)
(define (count-full-links WORD-LST)
(define blvars
(VariableList
(TypedVariable (Variable "r-word") (Type 'WordNode))
(TypedVariable (Glob "r-pre")
(TypeSet (Type 'Connector)
(Interval (Number 0) (Number -1))))
(TypedVariable (Glob "r-post")
(TypeSet (Type 'Connector)
(Interval (Number 0) (Number -1))))
(TypedVariable (Glob "l-pre")
(TypeSet (Type 'Connector)
(Interval (Number 0) (Number -1))))
(TypedVariable (Glob "l-post")
(TypeSet (Type 'Connector)
(Interval (Number 0) (Number -1))))
))
(define rcon
(ConnectorSeq
(Glob "l-pre")
(Connector (Variable "r-word") (ConnectorDir "+"))
(Glob "l-post")))
(define (make-blink LEFT-WRD)
(BindLink blvars
(And
(Present (Section LEFT-WRD rcon))
(Present
(Section
(Variable "r-word")
(ConnectorSeq
(Glob "r-pre")
(Connector
LEFT-WRD
(ConnectorDir "-"))
(Glob "r-post")))))
(List
(List (Glob "l-pre") (Any "Left") (Glob "l-post"))
(List (Glob "r-pre") (Any "Right") (Glob "r-post")))
))
(define (wrap func)
(cog-push-atomspace)
(let ((rc (func)))
(cog-pop-atomspace)
rc))
(define (link-count LEFT-WRD)
(define (func)
(cog-arity (cog-execute! (make-blink LEFT-WRD))))
(wrap func))
(define wrd-no 0)
(define (word-no) (set! wrd-no (+ wrd-no 1)) wrd-no)
(define start-time (current-time))
(define since-time (current-time))
(define (elapsed-secs)
(define now (current-time))
(define diff (- now since-time))
(set! since-time now)
diff)
(define tot-cnt 0)
(define nwrds (length WORD-LST))
(define (link-count-x LEFT-WRD)
(define lc (link-count LEFT-WRD))
(define ti (- (current-time) start-time))
(if (= 0 ti) (set! ti 1))
(set! tot-cnt (+ tot-cnt lc))
(format #t "~A of ~A count=~A in ~A secs wrd ~A"
(word-no) nwrds lc (elapsed-secs) LEFT-WRD)
(format #t "--- Elapsed: ~D:~2,'0D:~2,'0D Tot-cnt=~A Avg=~6F secs/word Rate=~6F cnts/sec\n"
(inexact->exact (floor (/ ti 3600.0)))
(inexact->exact (floor (/ (remainder ti 3600) 60.)))
(remainder ti 60)
tot-cnt
(/ ti wrd-no)
(/ tot-cnt ti))
lc)
(define sum-cnt 0)
(define mtx (make-mutex))
(par-for-each
(lambda (WRD)
(define cnt (link-count-x WRD))
(lock-mutex mtx)
(set! sum-cnt (+ sum-cnt cnt))
(unlock-mutex mtx))
WORD-LST)
)