(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog persist) (opencog persist-sql))
(use-modules (opencog nlp) (opencog learn))
(use-modules (opencog matrix))
(use-modules (opencog cogserver))
(start-cogserver)
(sql-open "postgres:///en_pairs_rfive_mtwo?user=linas")
(define pca (make-pseudo-cset-api))
(define psa (add-pair-stars pca))
(define psc (add-pair-count-api psa))
(define psf (add-pair-freq-api psa))
(define psu (add-support-api psa))
(psa 'fetch-pairs)
(print-matrix-summary-report psa)
(define ac (psa 'left-basis))
(length ac)
(define ad (psa 'right-basis))
(length ad)
(define (score SCORE-FN WORD-LIST)
(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST))
(define (score-and-rank SCORE-FN WORD-LIST)
(sort
(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST)
(lambda (a b) (> (car a) (car b)))))
(define (print-ts-rank-fn scrs port fn-str)
(define cnt 0)
(for-each
(lambda (pr)
(set! cnt (+ cnt 1))
(format port "~A	~A	\"~A\"\n" cnt (car pr) (fn-str (cdr pr))))
scrs))
(define (print-ts-rank scrs port)
(print-ts-rank-fn scrs port cog-name))
(define (print-ts-rank-cset scrs port)
(print-ts-rank-fn scrs port
(lambda (x) (cog-name (gar x)))))
(define all-cset-words (psa 'left-basis))
(define all-disjuncts (psa 'right-basis))
(define all-csets (get-all-csets))
(define top-cset-words
(filter (lambda (wrd) (<= 100 (cset-vec-word-observations wrd)))
all-cset-words))
(define (show-counts word-str)
(define w (WordNode word-str))
(format #t "Suport=~A Count=~A Length=~A\n"
(psu 'right-support w)
(psu 'right-count w)
(psu 'right-length w)))
(define sorted-word-obs
(score-and-rank cset-vec-word-observations all-cset-words))
(let ((outport (open-file "/tmp/ranked-word-obs.dat" "w")))
(print-ts-rank sorted-word-obs outport)
(close outport))
(define sorted-dj-obs
(score-and-rank cset-vec-dj-observations all-disjuncts))
(let ((outport (open-file "/tmp/ranked-dj-obs.dat" "w")))
(print-ts-rank-fn sorted-dj-obs outport get-disjunct-string)
(close outport))
(define sorted-cset-obs (score-and-rank get-count all-csets))
(let ((outport (open-file "/tmp/ranked-cset-obs.dat" "w")))
(print-ts-rank-fn sorted-cset-obs outport get-cset-string)
(close outport))
(define (avg-obs WORD)
(/ (cset-vec-word-observations WORD) (cset-vec-word-support WORD)))
(define top-sorted-avg
(score-and-rank avg-obs top-cset-words))
(let ((outport (open-file "/tmp/ranked-avg.dat" "w")))
(print-ts-rank top-sorted-avg outport)
(close outport))
(define sorted-avg
(score-and-rank avg-obs all-cset-words))
(define sorted-avg
(score-and-rank avg-obs top-cset-words))
(define binned-avg (bin-count-simple sorted-avg 200 1.0 20.0))
(let ((outport (open-file "/tmp/binned-avg.dat" "w")))
(print-bincounts-tsv binned-avg outport)
(close outport))
(define sorted-support (score-and-rank cset-vec-word-support all-cset-words))
(let ((outport (open-file "/tmp/ranked-support.dat" "w")))
(print-ts-rank sorted-support outport)
(close outport))
(define sorted-lengths (score-and-rank cset-vec-word-len all-cset-words))
(let ((outport (open-file "/tmp/ranked-lengths.dat" "w")))
(print-ts-rank sorted-lengths outport)
(close outport))
(define (lensq-vs-obs wrd)
(define len (cset-vec-word-len wrd))
(/ (* len len) (cset-vec-word-observations wrd)))
(define sorted-lensq-norm-top
(score-and-rank lensq-vs-obs top-cset-words))
(let ((outport (open-file "/tmp/ranked-sqlen-norm.dat" "w")))
(print-ts-rank sorted-lensq-norm-top outport)
(close outport))
(define sorted-lensq-norm
(score-and-rank lensq-vs-obs all-cset-words))
(define binned-sqlen-norm (bin-count-simple sorted-lensq-norm 200 0.0 100.0))
(define binned-sqlen-norm (bin-count sorted-lensq-norm 100
(lambda (item) (/ (log (first item)) (log 2.0)))
(lambda (item) 1)
1.0 10.0))
(let ((outport (open-file "/tmp/binned-sqlen-norm.dat" "w")))
(print-bincounts-tsv binned-sqlen-norm outport)
(close outport))
(define (avg-obs WORD)
(/ (cset-vec-word-observations WORD) (cset-vec-word-support WORD)))
(define (meansq-obs WORD)
(define len (cset-vec-word-len WORD))
(/ (* len len) (cset-vec-word-support WORD)))
(define (rms-deviation WORD)
(define avg (avg-obs WORD))
(sqrt (- (meansq-obs WORD) (* avg avg))))
(define sorted-rms
(score-and-rank rms-deviation top-cset-words))
(let ((outport (open-file "/tmp/ranked-rms.dat" "w")))
(print-ts-rank sorted-rms outport)
(close outport))
(define (avg-con-count wrd)
(/ (cset-vec-connectors wrd) (cset-vec-word-observations wrd)))
(define sorted-avg-connectors
(score-and-rank avg-con-count top-cset-words))
(define sorted-avg-connectors
(score-and-rank avg-con-count all-cset-words))
(let ((outport (open-file "/tmp/ranked-avg-connectors.dat" "w")))
(print-ts-rank sorted-avg-connectors outport)
(close outport))
(define (moment-con-count wrd)
(define meansq
(/ (cset-vec-lp-connectors wrd 2) (cset-vec-word-observations wrd)))
(define avg (avg-con-count wrd))
(sqrt (- meansq (* avg avg))))
(define sorted-hub-connectors
(score-and-rank moment-con-count top-cset-words))
(let ((outport (open-file "/tmp/ranked-hub-connectors.dat" "w")))
(print-ts-rank sorted-hub-connectors outport)
(close outport))
(define dj-prince (score-and-rank get-count
(get-cset-vec (Word "Prince"))))
(define dj-think (score-and-rank get-count
(get-cset-vec (Word "think"))))
(define dj-long (score-and-rank get-count
(get-cset-vec (Word "long"))))
(define dj-fact (score-and-rank get-count
(get-cset-vec (Word "fact"))))
(define dj-from (score-and-rank get-count
(get-cset-vec (Word "from"))))
(define (print-ts-dj-rank cset-a cset-b
cset-c cset-d cset-e port)
(define idx 0)
(for-each
(lambda (pra prb prc  prd pre)
(set! idx (+ idx 1))
(format port "~A	~A	~A	~A	~A	~A\n" idx
(car pra) (car prb)
(car prc) (car prd)
(car pre)))
cset-a cset-b cset-c cset-e cset-e ))
(let ((outport (open-file "/tmp/ranked-dj-prince.dat" "w")))
(print-ts-dj-rank
dj-prince dj-think dj-long dj-fact dj-from outport)
(close outport))
(define dj-sum (make-array 0 312500))
(define (make-ranked-dj-list WORD)
(score-and-rank get-count (get-cset-vec WORD)))
(define (accum-dj-counts WORD)
(define idx 0)
(for-each
(lambda (pr)
(array-set! dj-sum (+ (car pr) (array-ref dj-sum idx)) idx)
(set! idx (+ idx 1)))
(make-ranked-dj-list WORD)))
(define (accum-dj-all WORD-LIST)
(for-each
(lambda (word) (accum-dj-counts word))
WORD-LIST))
(accum-dj-all top-cset-words)
(define (print-dj-acc port)
(define idx 0)
(for-each
(lambda (cnt)
(set! idx (+ idx 1))
(if (< 0 cnt)
(format port "~A	~A\n" idx cnt)))
(array->list dj-sum)))
(let ((outport (open-file "/tmp/ranked-dj-counts.dat" "w")))
(print-dj-acc outport)
(close outport))
(define total-cset-count (get-total-cset-count))
(define (fractional-entropy FUNC LIST)
(fold
(lambda (item sum)
(define pitem (/ (FUNC item) total-cset-count))
(- sum (* pitem (log pitem))))
0
LIST))
(define word-entropy
(fractional-entropy cset-vec-word-observations all-cset-words))
(define word-entropy-bits (/ word-entropy (log 2.0)))
(define disjunct-entropy
(fractional-entropy cset-vec-dj-observations all-disjuncts))
(define disjunct-entropy-bits (/ disjunct-entropy (log 2.0)))
(define cset-entropy-bits
(fold
(lambda (word sum) (+ sum  (cset-vec-word-entropy word)))
0
all-cset-words))
(define (get-total-mi-slow)
(define prog 0)
(define prog-len (length all-csets))
(fold
(lambda (cset sum)
(define word (cset-get-word cset))
(define dj (cset-get-disjunct cset))
(define p-word (cset-vec-frequency word))
(define p-dj (cset-vec-frequency dj))
(define p-cset (get-cset-frequency cset))
(set! prog (+ prog 1))
(if (eqv? 0 (modulo prog 100))
(format #t "doing ~A of ~A\n" prog prog-len))
(+ sum (* p-cset (log (/ p-cset (* p-word p-dj)))))
)
0
all-csets))
(define slow-total-mi (get-total-mi-slow))
(define (get-total-mi-bits)
(define prog 0)
(define prog-len (length all-cset-words))
(define sum 0)
(for-each
(lambda (word)
(set! prog (+ prog 1))
(if (eqv? 0 (modulo prog 100))
(format #t "doing ~A of ~A\n" prog prog-len))
(set! sum (+ sum (cset-vec-word-mi word))))
all-cset-words)
sum
)
(define total-mi-bits (get-total-mi-bits))
(define total-mi-bits
(- (word-entropy-bits disjunct-entropy-bits) cset-entropy-bits)
(define sorted-word-counts
(score-and-rank cset-vec-word-observations all-cset-words))
(define binned-word-counts
(bin-count-simple sorted-word-counts 400 0.5 400.5))
(let ((outport (open-file "/tmp/binned-word-counts.dat" "w")))
(print-bincounts-tsv binned-word-counts outport)
(close outport))
(define (cset-vec-word-logli WORD)
(psf 'right-wild-logli WORD))
(define sorted-word-logli (score-and-rank cset-vec-word-logli all-cset-words))
(define binned-word-logli (bin-count-simple sorted-word-logli 1200 9.0 24.0))
(let ((outport (open-file "/tmp/binned-word-logli.dat" "w")))
(print-bincounts-tsv binned-word-logli outport)
(close outport))
(define (cset-vec-word-ent WORD) (psf 'right-wild-fentropy WORD))
(define sorted-word-ent (score-and-rank cset-vec-word-ent top-cset-words))
(let ((outport (open-file "/tmp/ranked-word-ent.dat" "w")))
(print-ts-rank sorted-word-ent outport)
(close outport))
(define sorted-word-ent (score-and-rank cset-vec-word-ent all-cset-words))
(define binned-word-ent (bin-count-simple sorted-word-ent 100))
(let ((outport (open-file "/tmp/binned-word-ent.dat" "w")))
(print-bincounts-tsv binned-word-ent outport)
(close outport))
(define (cset-vec-word-crazy WORD)
(- (pmi 'compute-right-mi WORD)
(+ (pmi 'right-wild-logli WORD)
(pmi 'compute-right-fentropy WORD))))
(define sorted-word-crazy (score-and-rank cset-vec-word-crazy all-cset-words))
(define binned-word-crazy (bin-count-simple sorted-word-crazy 100))
(let ((outport (open-file "/tmp/binned-word-crazy.dat" "w")))
(print-bincounts-tsv binned-word-crazy outport)
(close outport))
(define (cset-vec-word-crazy2 WORD)
(- (pmi 'compute-right-mi WORD)
(pmi 'compute-right-fentropy WORD)))
(define sorted-word-crazy2 (score-and-rank cset-vec-word-crazy2 all-cset-words))
(define binned-word-crazy2 (bin-count-simple sorted-word-crazy2 100))
(let ((outport (open-file "/tmp/binned-word-crazy2.dat" "w")))
(print-bincounts-tsv binned-word-crazy2 outport)
(close outport))
(define (cset-mi CSET) (psf 'pair-fmi CSET))
(define sorted-cset-mi (score-and-rank cset-mi all-csets))
(define scored-cset-mi (score cset-mi all-csets))
(let ((outport (open-file "/tmp/ranked-cset-mi.dat" "w")))
(print-ts-rank-cset sorted-cset-mi outport)
(close outport))
(define binned-cset-mi (bin-count-simple sorted-cset-mi 100))
(define binned-cset-mi (bin-count-simple scored-cset-mi 200))
(let ((outport (open-file "/tmp/binned-cset-mi.dat" "w")))
(print-bincounts-tsv binned-cset-mi outport)
(close outport))
(define (cset-freq CSET) (psf 'pair-freq CSET))
(define weighted-cset-mi
(bin-count-weighted scored-cset-mi 200
(lambda (scored-item) (cset-freq (cdr scored-item)))))
(let ((outport (open-file "/tmp/weighted-cset-mi.dat" "w")))
(print-bincounts-tsv weighted-cset-mi outport)
(close outport))
(define (cset-logli CSET) (pfrq 'pair-logli CSET))
(define wlogli-cset-mi
(bin-count-weighted sorted-cset-mi 200
(lambda (scored-item) (cset-logli (cdr scored-item)))))
(let ((outport (open-file "/tmp/wlogli-cset-mi.dat" "w")))
(print-bincounts-tsv wlogli-cset-mi outport)
(close outport))
(define (cset-vec-word-mi WORD) (psf 'right-wild-fmi WORD))
(define sorted-word-mi (score-and-rank cset-vec-word-mi all-cset-words))
(define sorted-word-mi-hi-p
(score-and-rank cset-vec-word-mi top-cset-words))
(let ((outport (open-file "/tmp/ranked-word-mi.dat" "w")))
(print-ts-rank sorted-word-mi outport)
(close outport))
(let ((outport (open-file "/tmp/ranked-word-mi-hi-p.dat" "w")))
(print-ts-rank sorted-word-mi-hi-p outport)
(close outport))
(define binned-word-mi (bin-count-simple sorted-word-mi 100))
(define (new-cset-vec-word-mi WORD)
(define pca (make-pseudo-cset-api))
(define pmi (add-pair-mi-compute pca))
(pmi 'compute-right-fmi WORD)
)
(define osorted-word-mi (score-and-rank new-cset-vec-word-mi all-cset-words))
(let ((outport (open-file "/tmp/binned-word-mi.dat" "w")))
(print-bincounts-tsv binned-word-mi outport)
(close outport))
(define (cset-vec-disjunct-mi DJ) (psf 'left-wild-fmi DJ))
(define sorted-dj-mi (score-and-rank cset-vec-disjunct-mi all-disjuncts))
(define scored-dj-mi (score cset-vec-disjunct-mi all-disjuncts))
(define binned-dj-mi (bin-count-simple scored-dj-mi 200))
(let ((outport (open-file "/tmp/binned-dj-mi.dat" "w")))
(print-bincounts-tsv binned-dj-mi outport)
(close outport))
(filter (lambda (cset) (< 0 (get-count cset))) (cog-incoming-by-type
(Word "horses") 'Section))
(define psu (add-support-api psa))
(define long-words
(filter (lambda (word) (<= 256 (psu 'right-length word)))
(psu 'left-basis)))
(length long-words)
(define psm (add-similarity-api psa #f))
(psm 'fetch-pairs)
(define pslon
(add-generic-filter psa
(lambda (word) (<= 16 (psu 'right-length word)))
(lambda (dj) #t)
(lambda (dj) #t)
(lambda (dj) #t)
(lambda (dj) #t)
"cut len<=16"
#f))
(define psls (add-pair-stars pslon))
(define pss (batch-similarity psls #f #f 0.1))
(pss 'batch-compute)
(pss 'paralel-batch 3)
(define ranked-long
(sort long-words
(lambda (a b) (> (psu 'right-count a) (psu 'right-count b)))))
(define cos-key (PredicateNode "*-Cosine Sim Key-*"))
(define all-sims '())
(cog-map-type
(lambda (ato)
(define val (cog-value ato cos-key))
(if (not (null? val))
(set! all-sims (cons ato all-sims)))
#f)
'SimilarityLink)
(length all-sims)
(length all-sims)
(define (sim-cosine SIM)
(define cos-key (PredicateNode "*-Cosine Sim Key-*"))
(cog-value-ref (cog-value SIM cos-key) 0))
(define (filter-sim LEN)
(filter
(lambda (sim) (and
(< LEN (cset-vec-word-len (gar sim)))
(< LEN (cset-vec-word-len (gdr sim)))))
all-sims))
(define good-sims (filter-sim 256))
(length good-sims)
(define (filter-sim)
(filter
(lambda (sim) (< 0.1 (sim-cosine sim)))
all-sims))
(define good-sims (filter-sim))
(length good-sims)
(define ranked-sims
(sort good-sims
(lambda (a b) (> (sim-cosine a) (sim-cosine b)))))
(define (prt-sim sim port)
(format port "~A	'~A .. ~A'\n" (sim-cosine sim)
(cog-name (gar sim)) (cog-name (gdr sim))))
(let ((outport (open-file "/tmp/ranked-sims-256.dat" "w")))
(define cnt 0)
(for-each (lambda (sim)
(set! cnt (+ cnt 1))
(format outport "~A	" cnt)
(prt-sim sim outport))
ranked-sims)
(close outport))
(define scored-sims (score sim-cosine all-sims))
(define scored-sims (score sim-cosine good-sims))
(define binned-sims (bin-count-simple scored-sims 300))
(let ((outport (open-file "/tmp/binned-sims.dat" "w")))
(print-bincounts-tsv binned-sims outport)
(close outport))
(define all-good-sims
(filter
(lambda (sim) (and
(< 4 (cset-vec-word-len (gar sim)))
(< 4 (cset-vec-word-len (gdr sim)))))
all-sims))
(length all-good-sims)
(define scored-good-sims (score sim-cosine all-good-sims))
(define binned-good-sims (bin-count-simple scored-good-sims 100))
(let ((outport (open-file "/tmp/binned-good-sims.dat" "w")))
(print-bincounts-tsv binned-good-sims outport)
(close outport))
(define all-good-words (filter (lambda (w) (< 4 (cset-vec-word-len w))) ac))
(length all-good-words)
(define (print-connector CON)
(string-append (cog-name (gar CON)) (cog-name (gdr CON)) " "))
(define (section->dj-str SEC)
(string-concatenate
(map print-connector (cog-outgoing-set (gdr SEC))))
)
(define (print-disjuncts WORD CUT)
(define cnt 0)
(define all-secs (cog-incoming-by-type WORD 'Section))
(define sorted-secs (sort all-secs
(lambda (a b) (> (get-count a) (get-count b)))))
(define (prt-one con)
(set! cnt (+ 1 cnt))
(if (<= CUT (get-count con))
(format #t "~D  ~A\n" (get-count con) (section->dj-str con))))
(for-each prt-one sorted-secs)
(format #t "Total of ~D disjuncts\n" cnt))
(define wpa (make-any-link-api))
(define wps (add-pair-stars wpa))
(define wpf (add-pair-freq-api wps)
(fetch-incoming-set (List (Word "the") (Word "city"))
(wpf 'pair-fmi (List (Word "the") (Word "city")))
(define (drank-helper wlist drl)
(define (get-cos A B)
(sim-cosine (SimilarityLink A B)))
(define rest (cdr wlist))
(if (null? rest) (cons (car wlist) drl)
(let ((rankw (car drl))
(next-rankw '()))
(fold
(lambda (item biggest)
(define cosi (get-cos rankw item))
(if (and (> cosi biggest) (not (equal? item rankw)))
(begin (set! next-rankw item) cosi) biggest))
-1e20
wlist)
(drank-helper
(remove (lambda (w) (equal? w next-rankw)) wlist)
(cons next-rankw drl)))))
(define (drank wlist)
(drank-helper (cdr wlist) (cons (car wlist) '())))
(define dranked-long (drank (take ranked-long 40)))
(define dranked-long (drank (take ranked-long 300)))
(define dranked-long (drank ranked-long))
(define eranked-long (reverse dranked-long))
(write-flo "/tmp/scat-dcos.flo" eranked-long pair-cos)
(write-flo "/tmp/scat-ecos.flo" eranked-long pair-cos)
(define (prt-sim LST)
(if (not (null? (cdr LST))) (begin
(format #t "~A .. ~A  ~5F\n" (car LST) (cadr LST)
(get-cos (Word (car LST)) (Word (cadr LST))))
(prt-sim (cdr LST)))))
(define (cnt-obs-rows n lst)
(if (<= 0 n)
(let* ((fsa (add-subtotal-filter psa 0 n 0))
(bs (fsa 'left-basis-size)))
(format #t "N=~d  sz=~d\n" n bs)
(cnt-obs-rows (- n 2) (cons (cons n bs) lst)))
lst))
(define row-dist (cnt-obs-rows 100 '()))
(define (print-tsv-count scrs port max)
(define cnt 0)
(for-each
(lambda (pr)
(set! cnt (+ cnt 1))
(format port "~A	~A	~A	~A\n" cnt (car pr) (cdr pr) (/ (cdr pr max)))
scrs))
(let ((outport (open-file "/tmp/count-rows.dat" "w")))
(print-tsv-count row-dist outport)
(close outport))
(define (cnt-obs-cols n lst)
(if (<= 0 n)
(let* ((fsa (add-subtotal-filter psa n 0 0))
(bs (fsa 'right-basis-size)))
(format #t "N=~d  sz=~d\n" n bs)
(cnt-obs-cols (- n 5) (cons (cons n bs) lst)))
lst))
(define col-dist (cnt-obs-cols 100 '()))
(define fsa (add-subtotal-filter psa 1 1 0))
(define fsb (add-subtotal-filter psa 4 4 0))
(define fsc (add-subtotal-filter psa 10 10 0))
(define fsd (add-subtotal-filter psa 30 30 0))
(define ssa (add-support-compute fsa))
(define ssb (add-support-compute fsb))
(define ssc (add-support-compute fsc))
(define ssd (add-support-compute fsd))
(ssa 'total-support)
(ssa 'total-count)
(ssb 'total-support)
(ssb 'total-count)
(ssc 'total-support)
(ssc 'total-count)
(ssd 'total-support)
(ssd 'total-count)
(define fse (add-subtotal-filter psa 30 10 0))
(define fsf (add-subtotal-filter psa 30 10 4))
(define fsg (add-subtotal-filter psa 50 30 0))
(define fsh (add-subtotal-filter psa 50 30 4))
(define fsi (add-subtotal-filter psa 50 30 10))
(define sse (add-support-compute fse))
(define ssf (add-support-compute fsf))
(define ssg (add-support-compute fsg))
(define ssh (add-support-compute fsh))
(define ssi (add-support-compute fsi))
(sse 'total-support)
(sse 'total-count)
(ssf 'total-support)
(ssf 'total-count)
(ssg 'total-support)
(ssg 'total-count)
(ssh 'total-support)
(ssh 'total-count)
(ssi 'total-support)
(ssi 'total-count)
(define ps-128
(add-generic-filter psa
(lambda (word) (<= 128 (psu 'right-length word)))
(lambda (dj) #t)
(lambda (dj) #t)
(lambda (dj) #t)
(lambda (dj) #t)
"cut len<=128"
#f))
(define long-words
(filter (lambda (word) (<= 128 (psu 'right-length word)))
(psu 'left-basis)))
(define pci (make-cosine-matrix ps-128))
(define pti (make-power-iter-pca pci 'left-unit))
(define feig (pti 'make-left-unit long-words))
(define lit (pti 'left-iterate feig 8))
(pti 'left-print lit 20)
---------------------------------------------------------------------
(define sorted-eigen
(sort
(pti 'left-vec lit6)
(lambda (a b) (> (cdr a) (cdr b)))))
(define (print-tsv-pca port)
(define cnt 0)
(for-each
(lambda (pr)
(define w (car pr))
(set! cnt (+ cnt 1))
(format port "~d	\"~A\"	~A	~A	~A	~A	~A	~A\n" cnt (cog-name w)
(lit w) (lit2 w) (lit3 w) (lit4 w) (lit5 w) (lit6 w)))
(take sorted-eigen 40)))
(let ((outport (open-file "/tmp/power-iter.dat" "w")))
(print-tsv-pca outport)
(close outport))