(define covr-obj (add-covering-sections cset-obj))
(covr-obj 'fetch-pairs)
(covr-obj 'explode-sections)
(define star-obj covr-obj)
(batch-all-pair-mi star-obj)
(define (score SCORE-FN WORD-LIST)
	(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST))
(define (score-and-rank SCORE-FN WORD-LIST)
	(sort
		(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) WORD-LIST)
		(lambda (a b) (> (car a) (car b)))))
(define (print-ts-rank-fn scrs port fn-str)
	(define cnt 0)
	(for-each
		(lambda (pr)
			(set! cnt (+ cnt 1))
			(format port "~A  ~A \"~A\"\n" cnt (car pr) (fn-str (cdr pr))))
		scrs))
(define (print-ts-rank scrs port)
	(print-ts-rank-fn scrs port cog-name))
(define (print-histo FILENAME HISTO)
	(define outport (open-file FILENAME "w"))
	(print-bincounts-tsv HISTO outport)
	(close outport))
(define all-words (star-obj 'left-basis))
(length all-words)
(define frq-obj (add-pair-freq-api star-obj))
(define (right-freq WRD) (frq-obj 'right-wild-freq WRD))
(define (right-ent WRD) (frq-obj 'right-wild-entropy WRD))
(define (right-fent WRD) (frq-obj 'right-wild-fentropy WRD))
(define (right-fmi WRD) (frq-obj 'right-wild-fmi WRD))
(define word-freq
	(score-and-rank right-freq all-words))
(let ((outport (open-file "/tmp/rank-wfreq.dat" "w")))
	(print-ts-rank word-freq outport)
	(close outport))
(define (print-ts-rank-scat scrs port)
	(define cnt 0)
	(for-each
		(lambda (pr)
			(define wrd (cdr pr))
			(set! cnt (+ cnt 1))
			(format port "~A\t~10G\t~7F\t~7F\t\"~A\"\n" cnt (car pr)
				(right-fent wrd)
				(right-fmi wrd)
				(cog-name wrd)))
		scrs))
(let ((outport (open-file "/tmp/rank-wfreq.dat" "w")))
	(print-ts-rank-scat word-freq outport)
	(close outport))
(define word-entropy
	(score-and-rank right-ent all-words))
(let ((outport (open-file "/tmp/rank-went.dat" "w")))
	(print-ts-rank word-entropy outport)
	(close outport))
(define word-fentropy
	(score-and-rank right-fent all-words))
(define binned-went (bin-count-simple word-fentropy 200 17.0 24.0))
(print-histo "/tmp/bin-went.dat" binned-went)
(define bin-wei-went
	(bin-count all-words 200
		(lambda (WRD) (frq-obj 'right-wild-fentropy WRD))
		(lambda (WRD) (frq-obj 'right-wild-freq WRD))
		16 24))
(print-histo "/tmp/bin-wei-went.dat" bin-wei-went)
(define bin-wmi
	(bin-count all-words 200
		(lambda (WRD) (frq-obj 'right-wild-fmi WRD))
		(lambda (WRD) 1.0)
		2 22))
(print-histo "/tmp/bin-wmi.dat" bin-wmi)
(define bin-wei-wmi
	(bin-count all-words 200
		(lambda (WRD) (frq-obj 'right-wild-fmi WRD))
		(lambda (WRD) (frq-obj 'right-wild-freq WRD))
		2 22))
(print-histo "/tmp/bin-wei-wmi.dat" bin-wei-wmi)
(define SIM-ID "shape-mi")
(define sap (add-similarity-api LLOBJ #f SIM-ID))
(define smi (add-symmetric-mi-compute LLOBJ))
(define mmt-q (smi 'mmt-q))
(load-atoms-of-type 'Similarity)
(define all-sims (cog-get-atoms 'Similarity))
(define (get-mi PR) (cog-value-ref (sap 'get-count PR) 0))
(define (get-rmi PR) (cog-value-ref (sap 'get-count PR) 1))
(define (get-hmi PR)
	(define WA (gar PR))
	(define WB (gdr PR))
	(+ (get-mi PR) (* 0.5 (+ 
		(frq-obj 'right-wild-fentropy WA)
		(frq-obj 'right-wild-fentropy WB)))))
(define (get-mmi PR)
	(define WA (gar PR))
	(define WB (gdr PR))
	(+ (get-mi PR) (* 0.5 (+ 
		(frq-obj 'right-wild-fmi WA)
		(frq-obj 'right-wild-fmi WB)))))
(define scored-mi (score-and-rank get-mi all-sims))
(define scored-rmi (score-and-rank get-rmi all-sims))
(define scored-hmi (score-and-rank get-hmi all-sims))
(define scored-mmi (score-and-rank get-mmi all-sims))
(define sim-mi (bin-count-simple scored-mi 200 -15.0 15.0))
(define sim-rmi (bin-count-simple scored-rmi 200 -15.0 15.0))
(define sim-hmi (bin-count-simple scored-hmi 200 0 30.0))
(define sim-mmi (bin-count-simple scored-mmi 200 -15.0 15.0))
(print-histo "/tmp/sim-mi.dat" sim-mi)
(print-histo "/tmp/sim-rmi.dat" sim-rmi)
(print-histo "/tmp/sim-hmi.dat" sim-hmi)
(print-histo "/tmp/sim-mmi.dat" sim-mmi)
(define (prt-top LST)
	(define top #f)
	(for-each (lambda (SCPR)
		(if top (format #t "~5F\t" (- (car SCPR) top))
			(begin (set! top (car SCPR)) (format #t "~5F\t" top)))
		(format #t "~A ~A\n"
			(cog-name (gar (cdr SCPR)))
			(cog-name (gdr (cdr SCPR)))))
		LST))
(define (self? SCPR) (not (equal? (gar (cdr SCPR)) (gdr (cdr SCPR)))))
(prt-top (filter self? (take scored-mi 90)))
(define (prt-r LST)
	(define top #f)
	(for-each (lambda (SCPR)
		(if top (format #t "~5F\n" (- (car SCPR) top))
			(begin (set! top (car SCPR)) (format #t "~5F\n" top))))
		LST))
(define (prt-w LST)
	(define top #f)
	(for-each (lambda (SCPR)
		(format #t "~A ~A\n"
			(cog-name (gar (cdr SCPR)))
			(cog-name (gdr (cdr SCPR)))))
		LST))