(define ala (make-any-link-api))
(define als (add-pair-stars ala))
(define alf (add-pair-freq-api als))
(define wl (Word "she"))
(define wr (Word "said"))
(define pr (ala 'get-pair wl wr))
(alf 'pair-logli pr)
(define nwords 391548)
(define (sum-log-left WR)
	(/ (fold (lambda (ITEM ACC) (+ ACC (alf 'pair-logli ITEM)))
			0 (als 'left-stars WR))
		(* 2 nwords)))
(define lap (Predicate "*-Laplacian Marginal-*"))
(define (cache-sum-log-left WR)
	(define lwild (ala 'left-wildcard WR))
	(cog-set-value! lwild lap (FloatValue (sum-log-left WR)))
	(store-atom lwild))
(define rwords (als 'right-basis))
(length rwords)
(define elapsed-secs (make-elapsed-secs))
(elapsed-secs)
(for-each cache-sum-log-left rwords)
(format #t "Right took ~A secs\n" (elapsed-secs))
(define (sum-log-right WL)
	(/ (fold (lambda (ITEM ACC) (+ ACC (alf 'pair-logli ITEM)))
			0 (als 'right-stars WL))
		(* 2 nwords)))
(define (cache-sum-log-right WL)
	(define rwild (ala 'right-wildcard WL))
	(cog-set-value! rwild lap (FloatValue (sum-log-right WL)))
	(store-atom rwild))
(define lwords (als 'left-basis))
(length lwords)
(define lelapse (make-elapsed-secs))
(lelapse)
(for-each cache-sum-log-right lwords)
(format #t "Left took ~A secs\n" (lelapse))
(define all-pairs (als 'get-all-elts))
(length all-pairs)
(define pr (car all-pairs))
(ala 'left-element pr)
(ala 'right-element pr)
(define (get-sum-log-right WL)
	(define rwild (ala 'right-wildcard WL))
	(cog-value-ref (cog-value rwild lap) 0))
(define (get-sum-log-left WR)
	(define lwild (ala 'left-wildcard WR))
	(cog-value-ref (cog-value lwild lap) 0))
(define (get-lap PR)
	(- (alf 'pair-logli PR)
		(+ (get-sum-log-left (ala 'right-element PR))
			(get-sum-log-right (ala 'left-element PR)))))
(define (cache-lap PR)
	(define lapy (get-lap PR))
	(store-atom (cog-set-value! PR lap (FloatValue lapy)))
	lapy)
(for-each cache-lap all-pairs)
(define (fet-lap PR) (cog-value-ref (cog-value PR lap) 0))
(define sorted-pairs
   (sort all-pairs (lambda (A B) (> (cache-lap A) (cache-lap B)))))
(define (lap-hist NBINS LO HI FUN FILENAM PAIR-LIST)
"
  lap-hist NBINS LO HI FILENAM - create histogram of laplacian thing.
  (lap-hist 200 7 30 get-lap \"/tmp/laplace-dist.dat\")
"
	(define WEIFN (lambda (PAIR) 1.0))
	(define bins (bin-count PAIR-LIST NBINS FUN WEIFN LO HI))
	(define counts (array->list (second bins)))
	(define bin-total
		(fold 
			(lambda (bin tot) (+ tot bin))
			0
			counts))
	(define bwid (/ (- HI LO) NBINS))
	(format #t "Total count = ~A bin-width = ~A\n"
		bin-total bwid)
	(define oport (open-file FILENAM "w"))
	(format oport "#\n# Total count = ~A bin-width = ~A\n"
		bin-total bwid)
	(print-bincounts-tsv bins oport)
	(close oport)
)
(lap-hist 200 2 32 get-lap "/tmp/laplace-dist.dat" (take all-pairs 40000))
(lap-hist 400 2 32 get-lap "/tmp/laplace-dist.dat" all-pairs)
(elapsed-secs)
(lap-hist 400 -2 30 get-lap "/tmp/laplace-dist.dat" all-pairs)
(format #t "Bin count took ~A secs\n" (elapsed-secs))
(define (get-dbl PR)
	(- (alf 'pair-logli PR)
		(* 2 (+ (get-sum-log-left (ala 'right-element PR))
			(get-sum-log-right (ala 'left-element PR))))))
(lap-hist 200 0 32 get-dbl "/tmp/dbl-dist.dat" (take all-pairs 140000))
(define (sumo PR)
	(+ (get-sum-log-left (ala 'right-element PR))
		(get-sum-log-right (ala 'left-element PR))))
(lap-hist 200 0 12 sumo "/tmp/sum-dist.dat" (take all-pairs 140000))
(define sup-obj (add-support-api star-obj))