(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog matrix) (opencog persist))
(define pca (make-pseudo-cset-api))
(define pcs (add-pair-stars pca))
(define sim (add-similarity-compute pcs))
(define sap (add-similarity-api pcs))
(pca 'fetch-pairs)
(sap 'fetch-pairs)
(define ol2 (/ 1.0 (log 2.0)))
(define (log2 x)
(if (< 0 x) (* (log x) ol2) (- (inf))))
(for-each store-atom (cog-get-atoms 'Similarity))
(call-with-new-thread
(lambda ()
(define (stosle)
(for-each store-atom (cog-get-atoms 'Similarity))
(sleep 900)
(stosle))
(stosle)))
(define overlap-done? (make-once-predicate))
(define (overlap WA WB)
(if (overlap-done? (Unordered WA WB))
-100000
(log2 (sim 'right-overlap WA WB))))
(define (prt-overlap WA WB)
(define rv (overlap WA WB))
(if (< -5 rv)
(format #t ">>~A<< -- >>~A<< log2 overlap = ~6F\n"
(cog-name WA) (cog-name WB) rv))
rv)
(define bover (batch-similarity pcs #f "overlap" -8.0 prt-overlap))
(define bover (batch-similarity pcs #f "overlap" -88.0 prt-overlap))
(bover 'batch-compute 1200)
(define condjacc-done? (make-once-predicate))
(define (condjacc WA WB)
(if (condjacc-done? (Unordered WA WB))
-100000
(log2 (- 1.0 (sim 'right-cond-jacc WA WB)))))
(define (prt-condjacc WA WB)
(define rv (condjacc WA WB))
(if (< -5 rv)
(format #t ">>~A<< -- >>~A<< log2 condjacc = ~6F\n"
(cog-name WA) (cog-name WB) rv))
rv)
(define bcond (batch-similarity pcs #f "condjacc" -8.0 prt-condjacc))
(define bcond (batch-similarity pcs #f "condjacc" -88.0 prt-condjacc))
(bcond 'batch-compute 1200)
(define mi-done? (make-once-predicate))
(define cmi (add-symmetric-mi-compute pcs))
(define (mi WA WB)
(if (mi-done? (Unordered WA WB))
-100000
(cmi 'mmt-fmi WA WB)))
(define (prt-mi WA WB)
(define rv (mi WA WB))
(if (< 3 rv)
(format #t ">>~A<< -- >>~A<< mi = ~6F\n"
(cog-name WA) (cog-name WB) rv))
rv)
(define bami (batch-similarity pcs #f "mi" 0.0 prt-mi))
(define bami (batch-similarity pcs #f "mi" -100.0 prt-mi))
(bami 'batch-compute 1200)
(define (ranked LLOBJ)
(define sup (add-support-api LLOBJ))
(define (nobs WRD) (sup 'right-count WRD))
(define wrds (LLOBJ 'left-basis))
(define ranked-words
(sort wrds
(lambda (ATOM-A ATOM-B) (> (nobs ATOM-A) (nobs ATOM-B)))))
(format #t "Sorted ~A words\n" (LLOBJ 'left-basis-size))
ranked-words
)
(define ranked-words (ranked pcs))
(define diag-cnt 0)
(for-each
(lambda (WRD)
(set! diag-cnt (+ diag-cnt 1))
(if (equal? 0 (remainder diag-cnt 100)) (format #t "~A " diag-cnt))
(bomi 'compute-similarity WRD WRD))
ranked-words)
(bomi 'batch-list (drop (take ranked-words 900) 300))
(bami 'batch-list (drop (take ranked-words 1200) 900))
(bomi 'batch-list (drop (take ranked-words 900) 300))
(bami 'batch-compute 1200)
(bomi 'batch-list (drop (take ranked-words 1200) 200))
(bumi 'batch-list (drop (take ranked-words 1200) 100))
(define (sim-k n)
(fold (lambda (x cnt)
(if (equal? n (length (cog-keys x))) (+ cnt 1) cnt))
0 (cog-get-atoms 'Similarity)))
(define (sim-rpt)
(format #t "Done 1: ~A   2: ~A  3: ~A  tot: ~A\n"
(sim-k 1) (sim-k 2) (sim-k 3)
(length (cog-get-atoms 'Similarity)))
*unspecified*)