(define (score SCORE-FN ITEM-LIST)
	(map (lambda (itm) (cons (SCORE-FN itm) itm)) ITEM-LIST))
(define (score-and-rank SCORE-FN ITEM-LIST)
	(sort
		(map (lambda (wrd) (cons (SCORE-FN wrd) wrd)) ITEM-LIST)
		(lambda (a b) (> (car a) (car b)))))
(define (print-ts-rank-fn scrs port fn-str)
	(define cnt 0)
	(for-each
		(lambda (pr)
			(set! cnt (+ cnt 1))
			(format port "~A  ~A \"~A\"\n" cnt (car pr) (fn-str (cdr pr))))
		scrs))
(define (print-sparse-rank-fn scrs port fn-str)
	(define cnt 0)
	(define score 1e30)
	(for-each
		(lambda (pr)
			(define iscor (inexact->exact (car pr)))
			(set! cnt (+ cnt 1))
			(when (< iscor score)
				(set! score iscor)
				(format port "~A  ~A \"~A\"\n" cnt iscor (fn-str (cdr pr)))
				(force-output port)))
		scrs)
	(define final (car (take-right scrs 1)))
	(format port "~A  ~A \"~A\"\n" (length scrs)
		(inexact->exact (car final)) (fn-str (cdr final)))
	(force-output port)
)
(define all-pairs (star-obj 'get-all-elts))
(define (pobs ITEM) (star-obj 'get-count ITEM))
(define pair-list (score-and-rank pobs all-pairs))
(define (prt-pair ITEM)
	(string-append (cog-name (star-obj 'left-element ITEM))
		" <<>> " (cog-name (star-obj 'right-element ITEM))))
(let ((outport (open-file "/tmp/pair-rank.dat" "w")))
	(print-sparse-rank-fn pair-list outport prt-pair)
	(close outport))