(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog persist-dht))
(dht-open "dht:///test-atomspace")
(dht-bootstrap "dht://localhost:4444/")
(store-atom (Concept "foo" (stv 0.6 0.8)))
(display (dht-atom-hash (ConceptNode "foo"))) (newline)
(display (dht-examine (dht-atom-hash (ConceptNode "foo"))))
(display (dht-atomspace-hash)) (newline)
(display (dht-examine "d2bf1fd0312cbf309df74c537bea16769b419f44"))
(dht-stats)
(cog-set-value! (Concept "foo") (Predicate "floater")
	(FloatValue 1 2 3 4))
(cog-set-value! (Concept "foo") (Predicate "name list")
	(StringValue "Joe" "Smith" "42nd and Main St."))
(store-atom (Concept "foo"))
(display (dht-examine (dht-atomspace-hash)))
(define e
	(Evaluation (stv 0.2 0.9)
		(Predicate "relation")
		(List (Concept "foo") (Concept "bar"))))
(store-atom e)
(display (dht-examine (dht-atomspace-hash)))
(display (dht-examine (dht-atom-hash (ConceptNode "foo"))))
(display (dht-examine "bc91a93a9a0d046e09cab9b9cea74a16f06c4675"))
(dht-immutable-hash (ListLink (ConceptNode "foo") (ConceptNode "bar")))
(dht-atom-hash (ListLink (ConceptNode "foo") (ConceptNode "bar")))
(dht-close)