(use-modules (opencog) (opencog persist) (opencog persist-sql))
(use-modules (opencog nlp) (opencog nlp learn))
(use-modules (opencog matrix))
(define (fetch-wp cnt-mode)
(define pair-obj '())
(define star-obj '())
(display "Fetching all word-pairs from the database. This may take a few minutes.\n")
(cond
((equal? cnt-mode "any")
(set! pair-obj (make-any-link-api)))
((or (equal? cnt-mode "clique")
(equal? cnt-mode "clique-dist"))
(set! pair-obj (make-clique-pair-api))))
(set! star-obj (add-pair-stars pair-obj))
(pair-obj 'fetch-pairs)
(sql-stats)
(sql-clear-cache)
(sql-clear-stats)
(display "Done fetching pairs.\n")
)