(use-modules (opencog) (opencog persist) (opencog persist-sql))
(use-modules (opencog cogserver))
(use-modules (opencog nlp))
(use-modules (system repl common))
(use-modules (system repl server))
(load-from-path "opencog/nlp/learn/common.scm")
(load "redefine-common.scm")
(load-from-path "opencog/nlp/learn/utilities.scm")
(load-from-path "opencog/nlp/learn/link-pipeline.scm")
(load "redefine-link-pipeline.scm")
(load-from-path "opencog/nlp/learn/singletons.scm")
(load-from-path "opencog/nlp/learn/batch-word-pair.scm")
(load-from-path "opencog/nlp/learn/mst-parser.scm")
(load "redefine-mst-parser.scm")
(load-from-path "opencog/nlp/learn/pseudo-csets.scm")
(load-from-path "opencog/nlp/learn/shape-vec.scm")
(load-from-path "opencog/nlp/learn/summary.scm")
(load-from-path "opencog/nlp/learn/gram-agglo.scm")
(add-to-load-path ".")
(load "utilities.scm")
(define cog-mode (get-mode))
(define language (get-lang))
(define database-uri (get-connection-uri))
(repl-default-option-set! 'prompt (string-append "scheme@("
language "-" cog-mode ")> "))
(start-cogserver (string-append "config/opencog-" cog-mode "-" language ".conf"))
(sql-open database-uri)
(display "Opened database: ")
(display database-uri)
(display "\n")
(display "Fetching all words from database. This may take a few minutes.\n")
(fetch-all-words)