(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog matrix) (opencog persist))
(define (merge-connectors LLOBJ CLS WRD)
"
unfinished prototype
  Get the row for CLS, walk the row, merge connectors on it.
"
(define nsec 0)
(define msec 0)
(format #t "\n")
(format #t "=============================\n")
(format #t "merge ~A into ~A\n" WRD CLS)
	(define all-stars (LLOBJ 'right-stars CLS))
(format #t "there are ~A sections and ~A cross of ~A\n"
(length (filter (lambda (ITEM) (eq? 'Section (cog-type ITEM))) all-stars))
(length (filter (lambda (ITEM) (eq? 'CrossSection (cog-type ITEM))) all-stars))
(length all-stars))
	(define (word-in-connector? CON)
		(equal? (gar CON) WRD))
	(define donor-xes
		(filter-map (lambda (ITEM)
			(if (eq? 'CrossSection (cog-type ITEM))
				(let ((donor (cog-link 'CrossSection WRD (gdr ITEM))))
					(if (nil? donor) #f donor))
				#f))
			all-stars))
(format #t "WRD appears as connector in ~A crosses\n"
(length donor-xes))
	(define is-merged-xsect?  (make-aset-predicate donor-xes))
	(define (revise-section SEC DONOR)
		(define mumble
			(filter is-merged-xsect? (LLOBJ 'get-cross-sections DONOR)))
		(define location-list
			(map
				(lambda (XSECT)
					(define conli (cdr (cog-outgoing-set (gdr XSECT))))
					(list-index
						(lambda (CON)
							(eq? 'VariableNode (cog-type (gar CON))))
						conli))
				mumble))
(set! msec (+ 1 msec))
		(if (null? location-list) '()
			(let* (
					(conli (cog-outgoing-set (gdr SEC)))
					(idx 0)
					(next (car location-list))
					(rest (cdr location-list))
					(newli
						(map
							(lambda (CON)
								(define jdx idx)
								(set! idx (+ 1 idx))
								(if (eq? jdx next)
									(begin
										(when (not (null? rest))
											(set! next (car rest))
											(set! rest (cdr rest)))
										(Connector CLS (gdr CON)))
									CON))
							conli))
					(newsec (Section (gar SEC) (ConnectorSeq newli))))
				(set-count newsec (LLOBJ 'get-count SEC))
				(set-count SEC 0)
				newsec))
	)
	(define (revise-xsect XST)
		#f
	)
	(define donor-sex-shape
		(append-map (lambda (ITEM)
			(if (eq? 'Section (cog-type ITEM))
				(let ((donor (cog-link 'Section WRD (gdr ITEM))))
					(if (nil? donor) '()
						(LLOBJ 'get-cross-sections donor)))
				'()))
			all-stars))
	(define (revise-shape XST)
		(define newx (CrossSection (gar XST)
				(Shape CLS (cdr (cog-outgoing-set (gdr XST))))))
		(set-count newx (LLOBJ 'get-count XST))
		(set-count XST 0))
	(for-each revise-shape donor-sex-shape)
	(define (revise-sect-from-xsect XST)
		(define donor (cog-link 'CrossSection WRD (gdr XST)))
		(when (not (nil? donor))
			(let ((donor-sect (LLOBJ 'get-section donor)))
				(when (not (nil? donor-sect))
					(revise-section donor-sect donor-sect)
			)))
	)
	(define (transfer-xsect XST)
		(define donor (cog-link 'CrossSection WRD (gdr XST)))
		(when (not (nil? donor))
			(let ((orig-sect (LLOBJ 'get-section donor))
					(new-sect (LLOBJ 'make-section XST)))
				(if (nil? orig-sect)
					(throw 'bug 'merge-connectors "donor section is missing"))
				(set-count new-sect (LLOBJ 'get-count orig-sect))
				(set-count orig-sect 0))))
	(define (do-merge-sectn SEC)
		(define conseq (gdr SEC))
		(define conli (cog-outgoing-set conseq))
		(define need-merge (any word-in-connector? conli))
(set! nsec (+ 1 nsec))
		(define donor (cog-link 'Section WRD conseq))
		(when (and (not (nil? donor)) need-merge)
			(revise-section SEC donor))
	)
	(define (do-merge-xsect XST)
		(define shape (gdr XST))
		(define allseq (cog-outgoing-set shape))
		(define conli (cdr allseq))
		(define need-merge (any word-in-connector? conli))
		(if need-merge
			(revise-sect-from-xsect XST)
			(transfer-xsect XST)
		)
	)
	(define (do-merge-cons ITEM)
		(let ((ptype (cog-type ITEM)))
			(cond
				((eq? ptype 'Section) (do-merge-sectn ITEM))
				((eq? ptype 'CrossSection) (do-merge-xsect ITEM))
				(else (throw 'bad-pair-type 'merge-connectors
						"Unexpected pair type for merging!")))))
	(for-each do-merge-cons all-stars)
(format #t "in conclusion sections handled ~A of ~A for ~A in ~A\n" msec nsec WRD CLS)
)