(define-module (opencog eva-model)
#:use-module (opencog)
#:use-module (opencog nlp)
#:use-module (opencog exec)
)
(load "eva-model/faces.scm")
(load "eva-model/self-model.scm")
(load "eva-model/time-map.scm")
(load "eva-model/utilities.scm")