(use-modules (opencog)(opencog exec))
(define my-trans (Concept "My FSM's Transition Rule"))
(define my-state (Anchor  "My FSM's Current State"))
(define halt-state (Concept "halt state"))
(define red-state (Concept "red state"))
(define green-state (Concept "green state"))
(define blue-state (Concept "blue state"))
(define cyan-state (Concept "cyan state"))
(define magenta-state (Concept "magenta state"))
(define yellow-state (Concept "yellow state"))
(define extern-anchor (Predicate "External State"))
(define go-forward (Concept "forward"))
(define go-reverse (Concept "reverse"))
(define halt (Concept "halt"))
(List my-state halt-state)
(Evaluation extern-anchor halt)
(ContextLink (And halt-state halt)  (List my-trans halt-state))
(ContextLink (And red-state halt)   (List my-trans halt-state))
(ContextLink (And green-state halt) (List my-trans halt-state))
(ContextLink (And blue-state halt)  (List my-trans halt-state))
(ContextLink (And cyan-state halt)  (List my-trans halt-state))
(ContextLink (And magenta-state halt) (List my-trans halt-state))
(ContextLink (And yellow-state halt) (List my-trans halt-state))
(ContextLink (And halt-state go-forward)  (List my-trans red-state))
(ContextLink (And red-state go-forward)   (List my-trans green-state))
(ContextLink (And green-state go-forward) (List my-trans blue-state))
(ContextLink (And blue-state go-forward)  (List my-trans red-state))
(ContextLink (And cyan-state go-forward)    (List my-trans halt-state))
(ContextLink (And magenta-state go-forward) (List my-trans halt-state))
(ContextLink (And yellow-state go-forward)  (List my-trans halt-state))
(ContextLink (And halt-state go-reverse) (List my-trans cyan-state))
(ContextLink (And cyan-state go-reverse) (List my-trans magenta-state))
(ContextLink (And magenta-state go-reverse) (List my-trans yellow-state))
(ContextLink (And yellow-state go-reverse) (List my-trans cyan-state))
(ContextLink (And red-state go-reverse) (List my-trans halt-state))
(ContextLink (And green-state go-reverse) (List my-trans halt-state))
(ContextLink (And blue-state go-reverse) (List my-trans halt-state))
(define (create-fsm fsm-name fsm-state extern-state)
(BindLink
(VariableList
(Variable "$extern-state")
(Variable "$curr-state")
(Variable "$next-state")
)
(And
(List
fsm-state
(Variable "$curr-state")
)
(EvaluationLink
extern-state
(Variable "$extern-state")
)
(ContextLink
(And
(Variable "$curr-state")
(Variable "$extern-state")
)
(List
fsm-name
(Variable "$next-state")
)
)
)
(And
(DeleteLink
(List
fsm-state
(Variable "$curr-state")
)
)
(List
fsm-state
(Variable "$next-state")
)
)
)
)
(define my-fsm (create-fsm my-trans my-state extern-anchor))
(define (take-step) (gar (gar (cog-execute! my-fsm))))
(define (show-fsm-state)
(car (cog-chase-link 'ListLink 'ConceptNode my-state)))
(define (show-environment-state)
(car (cog-chase-link 'EvaluationLink 'ConceptNode extern-anchor)))
(define (move-dir dir)
(cog-extract! (Evaluation extern-anchor (show-environment-state)))
(Evaluation extern-anchor dir))
(define (move-forward) (move-dir go-forward))
(define (move-reverse) (move-dir go-reverse))
(define (move-halt) (move-dir halt))
(show-fsm-state)