(use-modules (opencog))
(use-modules (opencog exec))
(Evaluation (Predicate "phone") (List (Concept "Paris") (Number 10)))
(Evaluation (Predicate "pop") (List (Concept "Paris") (Number 5)))
(Evaluation (Predicate "org") (List (Concept "Paris") (Concept "city")))
(Evaluation (Predicate "phone") (List (Concept "Berlin") (Number 10)))
(Evaluation (Predicate "pop") (List (Concept "Berlin") (Number 15)))
(Evaluation (Predicate "org") (List (Concept "Berlin") (Concept "city")))
(Evaluation (Predicate "phone") (List (Concept "Hong Kong") (Number 10)))
(Evaluation (Predicate "pop") (List (Concept "Hong Kong") (Number 20)))
(Evaluation (Predicate "org") (List (Concept "Hong Kong") (Concept "city")))
(Evaluation (Predicate "pop") (List (Concept "Barbados") (Number 7)))
(Evaluation (Predicate "org") (List (Concept "Barbados") (Concept "country")))
(Evaluation (Predicate "pop") (List (Concept "Japan") (Number 30)))
(Evaluation (Predicate "org") (List (Concept "Japan") (Concept "country")))
(define cnt 0)
(define (cmp nx ny)
(define x (string->number (cog-name nx)))
(define y (string->number (cog-name ny)))
(set! cnt (+ cnt 1))
(if (> x y) (stv 1 1) (stv 0 1)))
(define phone-inversion
(Get (And
(Evaluation (Predicate "phone")
(List (Variable "$city") (Variable "#phone")))
(Evaluation (Predicate "pop")
(List (Variable "$city") (Variable "#pop")))
(Evaluation
(GroundedPredicate "scm: cmp")
(List (Variable "#phone") (Variable "#pop")))
))
)
(cog-execute! phone-inversion)
cnt
(define pop-inversion
(Get (And
(Evaluation (Predicate "org")
(List (Variable "$city") (Concept "city")))
(Evaluation (Predicate "pop")
(List (Variable "$city") (Variable "#city-pop")))
(Evaluation (Predicate "org")
(List (Variable "$state") (Concept "country")))
(Evaluation (Predicate "pop")
(List (Variable "$state") (Variable "#state-pop")))
(EvaluationLink
(GroundedPredicateNode "scm: cmp")
(List (Variable "#city-pop") (Variable "#state-pop")))
))
)
(set! cnt 0)
(cog-execute! pop-inversion)
cnt