(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog test-runner))
(use-modules (opencog persist) (opencog persist-mono))
(include "../rocks/test-utils.scm")
(whack "/tmp/cog-mono-unit-test")
(opencog-test-runner)
(define (setup-and-store)
	(Concept "foo" (ctv 1 0 3))
	(Concept "bar" (ctv 1 0 4))
	(ListLink (Concept "bar") (ctv 1 0 5))
	(ListLink (Concept "foo") (List (Concept "bar")) (ctv 1 0 6))
	(define storage (MonoStorageNode "monospace:///tmp/cog-mono-unit-test"))
	(cog-open storage)
	(store-atom (ListLink (Concept "foo") (List (Concept "bar"))))
	(cog-close storage)
	(cog-atomspace-clear (cog-atomspace))
)
(define (get-cnt ATOM) (inexact->exact (cog-count ATOM)))
(define (test-store-link)
	(setup-and-store)
	(cog-atomspace-clear (cog-atomspace))
	(define storage (MonoStorageNode "monospace:///tmp/cog-mono-unit-test"))
	(cog-open storage)
	(load-atomspace)
	(cog-close storage)
	(define lilly (ListLink (Concept "foo") (List (Concept "bar"))))
	(test-equal "link-tv" 6 (get-cnt lilly))
	(test-equal "foo-tv" 0 (get-cnt (cog-node 'Concept "foo")))
	(test-equal "bar-tv" 0 (get-cnt (cog-node 'Concept "bar")))
	(test-equal "link-bar-tv" 0 (get-cnt (cog-link 'List (Concept "bar"))))
)
(define store-link "test store link")
(test-begin store-link)
(test-store-link)
(test-end store-link)
(whack "/tmp/cog-mono-unit-test")
(opencog-test-end)