#ifndef _MACH_KERN_RETURN_H_
#define _MACH_KERN_RETURN_H_
#include <mach/machine/kern_return.h>
#define KERN_SUCCESS 0
#define KERN_INVALID_ADDRESS 1
#define KERN_PROTECTION_FAILURE 2
#define KERN_NO_SPACE 3
#define KERN_INVALID_ARGUMENT 4
#define KERN_FAILURE 5
#define KERN_RESOURCE_SHORTAGE 6
#define KERN_NOT_RECEIVER 7
#define KERN_NO_ACCESS 8
#define KERN_MEMORY_FAILURE 9
#define KERN_MEMORY_ERROR 10
#define KERN_NOT_IN_SET 12
#define KERN_NAME_EXISTS 13
#define KERN_ABORTED 14
#define KERN_INVALID_NAME 15
#define KERN_INVALID_TASK 16
#define KERN_INVALID_RIGHT 17
#define KERN_INVALID_VALUE 18
#define KERN_UREFS_OVERFLOW 19
#define KERN_INVALID_CAPABILITY 20
#define KERN_RIGHT_EXISTS 21
#define KERN_INVALID_HOST 22
#define KERN_MEMORY_PRESENT 23
#define KERN_WRITE_PROTECTION_FAILURE 24
#define KERN_TERMINATED 26
#define KERN_TIMEDOUT 27
#define KERN_INTERRUPTED 28
#endif