(use-modules (opencog ure))
(use-modules (srfi srfi-1))
(define (gen-variable prefix i)
  (Variable (string-append prefix "-" (number->string i))))
(define (gen-variables prefix n)
  (if (= n 0)
      '()
      (append (gen-variables prefix (- n 1))
              (list (gen-variable prefix (- n 1))))))
(define (gen-fuzzy-conjunction-introduction-rule nary)
  (let* ((variables (gen-variables "$X" nary))
         (EvaluationT (Type "EvaluationLink"))
         (InheritanceT (Type "InheritanceLink"))
         (type (TypeChoice EvaluationT InheritanceT))
         (gen-typed-variable (lambda (x) (TypedVariable x type)))
         (vardecl (VariableSet (map gen-typed-variable variables)))
         (pattern (Present variables))
         (rewrite (ExecutionOutput
                    (GroundedSchema "scm: fuzzy-conjunction-introduction")
                    (List (And variables) (Set variables)))))
    (Bind
      vardecl
      pattern
      rewrite)))
(define (is-set l)
  (cond ((null? l) #t)
        ((member (car l) (cdr l)) #f)
        (else (is-set (cdr l)))))
(define (fuzzy-conjunction-introduction-precondition S)
  (bool->tv (is-confident-enough-set (cog-outgoing-set S))))
(define (is-confident-enough-set andees)
  (let* ((confident-enough (lambda (A) (> (cog-confidence A) 0))))
    (and (is-set andees)
         (every confident-enough andees))))
(define (fuzzy-conjunction-introduction A S)
  (let* ((andees (cog-outgoing-set S))
         (min-s-atom (min-element-by-key andees cog-mean))
         (min-c-atom (min-element-by-key andees cog-confidence))
         (min-s (cog-mean min-s-atom))
         (min-c (cog-confidence min-c-atom)))
    (if (is-confident-enough-set andees)
        (cog-set-tv! A (stv min-s min-c)))))
(define fuzzy-conjunction-introduction-2ary-rule
  (gen-fuzzy-conjunction-introduction-rule 2))
(define fuzzy-conjunction-introduction-2ary-rule-name
  (DefinedSchema "fuzzy-conjunction-introduction-2ary-rule"))
(DefineLink
  fuzzy-conjunction-introduction-2ary-rule-name
  fuzzy-conjunction-introduction-2ary-rule)