(use-modules (opencog) (opencog generate))
(use-modules (ice-9 textual-ports))
(load "dict-tree.scm")
(load "dict-loop.scm")
(load "dict-triquad.scm")
(load "dict-mixed.scm")
(define left-wall (Concept "LEFT-WALL"))
(define dir-set (Concept "left-right connectors"))
(Member (Set (ConnectorDir "+") (ConnectorDir "-")) dir-set)
(define no-params (Concept "this is an empty set of parameters"))
(define (export-to-file GRAPH-SET FILENAME)
(define just-one (Set (gar GRAPH-SET)))
(define just-one-gml (export-to-gml just-one))
(let ((outport (open-file FILENAME "w")))
(put-string outport just-one-gml)
(close outport))
*unspecified*)
(define tree-set
(cog-simple-aggregate dir-set dict-tree no-params left-wall))
(cog-arity tree-set)
(export-to-file tree-set "/tmp/corpus-tree.gml")
(export-to-file
(cog-simple-aggregate dir-set dict-loop no-params left-wall)
"/tmp/corpus-loop.gml")
(export-to-file
(cog-simple-aggregate dir-set dict-triquad no-params left-wall)
"/tmp/corpus-triquad.gml")
(export-to-file
(cog-simple-aggregate dir-set dict-mixed no-params left-wall)
"/tmp/corpus-mixed.gml")
*unspecified*