(define max-solutions (Predicate "*-max-solutions-*"))
(define close-fraction (Predicate "*-close-fraction-*"))
(define max-steps (Predicate "*-max-steps-*"))
(define max-depth (Predicate "*-max-depth-*"))
(define max-network-size (Predicate "*-max-network-size-*"))
(define point-set-anchor (Predicate "*-point-set-anchor-*"))
(define basic-net-params (Concept "Basic network demo"))
(State (Member max-solutions basic-net-params) (Number 10))
(State (Member close-fraction basic-net-params) (Number 0.5))
(State (Member max-steps basic-net-params) (Number 123123))
(State (Member point-set-anchor basic-net-params) (Anchor "Basic-Net Points"))
*unspecified*