import pytest
from ..utils import maybe_enable_chunked_prefill
from .conftest import run_equality_correctness_test
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-68m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_mqa_scorer': False}}, {'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_mqa_scorer': True}}])
@pytest.mark.parametrize('output_len', [256])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_ngram_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, common_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-68m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_logprobs': False}}, {'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_logprobs': True}}])
@pytest.mark.parametrize('output_len', [8])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('logprobs', [1, 6])
def test_ngram_e2e_greedy_logprobs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, logprobs: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0, logprobs=logprobs, prompt_logprobs=logprobs, disable_logprobs=test_llm_kwargs['speculative_config']['disable_logprobs'])
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 16, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-160m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3}, 'enable_chunked_prefill': False}, {'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_mqa_scorer': True}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('output_len', [256])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('seed', [1])
def test_ngram_e2e_greedy_correctness_with_preemption(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, temperature=0, seed=seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-68m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': k, 'prompt_lookup_max': 3}} for k in [1, 3, 5]] + [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': k, 'prompt_lookup_max': 1}} for k in [1, 3, 5]])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
def test_ngram_different_k(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-68m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_by_batch_size': 4}}, {'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_by_batch_size': 4, 'disable_mqa_scorer': True}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
def test_ngram_disable_queue(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-68m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'method': 'ngram', 'num_speculative_tokens': 5, 'prompt_lookup_max': 3, 'disable_mqa_scorer': True}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
def test_ngram_scorer(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)