import pytest
from ..utils import maybe_enable_chunked_prefill
from .conftest import run_equality_correctness_test
MAIN_MODEL = 'JackFram/llama-68m'
SPEC_MODEL = 'abhigoyal/aphrodite-medusa-llama-68m-random'
MAX_SPEC_TOKENS = 5
PRECISION = 'float32'
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_logprobs': False}}, {'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_logprobs': True}}])
@pytest.mark.parametrize('output_len', [8])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('logprobs', [1, 6])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_e2e_greedy_logprobs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, logprobs: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0, logprobs=logprobs, prompt_logprobs=logprobs, disable_logprobs=test_llm_kwargs['speculative_config']['disable_logprobs'])
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': False, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_e2e_greedy_correctness_cuda_graph(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 16, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_e2e_greedy_correctness_with_preemption(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': k}} for k in range(1, 1 + MAX_SPEC_TOKENS)])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_different_k(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_by_batch_size': 4}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_medusa_disable_queue(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_by_batch_size': 4, 'disable_mqa_scorer': True}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_mqa_scorer(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
if __name__ == '__main__':
    import pytest
    pytest.main([__file__])