from itertools import cycle
import pytest
from transformers import AutoTokenizer
from aphrodite import SamplingParams
from ...utils import create_new_process_for_each_test
from .conftest import get_output_from_llm_generator, run_equality_correctness_test
@pytest.mark.parametrize('common_llm_kwargs', [{'model': 'JackFram/llama-68m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}, {}])
@pytest.mark.parametrize('test_llm_kwargs', [{}])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_with_detokenization(test_llm_generator, batch_size: int):
    output_len = 32
    temperature = 0.0
    prompts = ['Hello, my name is', 'The president of the United States is', 'The capital of France is', 'The future of AI is']
    prompts = [prompt for prompt, _ in zip(cycle(prompts), range(batch_size))]
    sampling_params = SamplingParams(max_tokens=output_len, ignore_eos=True, temperature=temperature)
    batch_tokens, batch_token_ids, _ = get_output_from_llm_generator(test_llm_generator, prompts, sampling_params)
    assert len(batch_token_ids) == len(prompts)
    assert [len(token_ids) for token_ids in batch_token_ids] == [output_len] * batch_size
    tok = AutoTokenizer.from_pretrained('JackFram/llama-68m')
    for actual_tokens, actual_token_ids in zip(batch_tokens, batch_token_ids):
        expected_tokens = tok.decode(actual_token_ids)
        print(f'actual_token_ids={actual_token_ids!r}')
        assert actual_tokens.strip() == expected_tokens.strip()
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-68m'}, {'model_name': 'JackFram/llama-160m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5, 'disable_logprobs': False}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 3, 'disable_logprobs': False}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('output_len', [10])
@pytest.mark.parametrize('batch_size', [1])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_tiny_model_bs1(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    ensure_all_accepted = per_test_common_llm_kwargs.get('model_name') == test_llm_kwargs.get('speculative_config')['model']
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, prompt_logprobs=2, logprobs=2, disable_logprobs=False, temperature=0.0, ensure_all_accepted=ensure_all_accepted)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-68m'}, {'model_name': 'JackFram/llama-160m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('output_len', [256])
@pytest.mark.parametrize('batch_size', [64])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_tiny_model_large_bs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-68m'}, {'model_name': 'JackFram/llama-160m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('max_output_len', [256])
@pytest.mark.parametrize('batch_size', [32])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_tiny_model_large_bs_diff_output_len(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, max_output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len, seed=seed, temperature=0.0, ignore_eos=False)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'meta-llama/Llama-2-7b-chat-hf', 'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [1])
@pytest.mark.parametrize('output_len', [256])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_real_model_bs1(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'meta-llama/Llama-2-7b-chat-hf', 'enforce_eager': True, 'disable_log_stats': False}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [32])
@pytest.mark.parametrize('output_len', [64])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_real_model_large_bs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 16, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'model_name': 'JackFram/llama-160m'}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('output_len', [256])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_e2e_greedy_correctness_with_preemption(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-160m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{'block_size': 16}, {'block_size': 32}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_spec_decode_different_block_size(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-160m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5, 'max_model_len': 32}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5, 'max_model_len': 32}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('output_len', [64])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_skip_speculation(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-160m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5, 'disable_by_batch_size': 2}, 'enable_chunked_prefill': False}, {'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': 5, 'disable_by_batch_size': 2}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4}])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('output_len', [10])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_disable_speculation(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-68m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': k}, 'enable_chunked_prefill': False} for k in [1, 2, 3, 4, 5, 6, 7, 8, 9, 63]] + [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': k}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4} for k in [1, 2, 3, 4, 5, 6, 7, 8, 9, 63]])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_many_k(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': 'JackFram/llama-160m', 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': k, 'acceptance_method': 'typical_acceptance_sampler'}, 'enable_chunked_prefill': False} for k in [1, 2, 3]] + [{'speculative_config': {'model': 'JackFram/llama-68m', 'num_speculative_tokens': k, 'acceptance_method': 'typical_acceptance_sampler'}, 'enable_chunked_prefill': True, 'max_num_batched_tokens': 4, 'max_num_seqs': 4} for k in [1, 2, 3]])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
@create_new_process_for_each_test()
def test_typical_acceptance_sampling(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)