from unittest.mock import patch
import pytest
from aphrodite.modeling.layers.vocab_parallel_embedding import pad_vocab_size
from ..utils import maybe_enable_chunked_prefill
from .conftest import run_equality_correctness_test
MAIN_MODEL = 'JackFram/llama-160m'
SPEC_MODEL = 'ibm-ai-platform/llama-160m-accelerator'
MAX_SPEC_TOKENS = 3
PRECISION = 'float32'
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [4, 32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 32])
def test_mlp_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'disable_logprobs': False}}, {'speculative_config': {'model': SPEC_MODEL, 'disable_logprobs': True}}])
@pytest.mark.parametrize('output_len', [8])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('logprobs', [1, 6])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
def test_mlp_e2e_greedy_logprobs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, logprobs: int, prefill_chunk_size: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    maybe_enable_chunked_prefill(prefill_chunk_size, baseline_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0, logprobs=logprobs, prompt_logprobs=logprobs, disable_logprobs=test_llm_kwargs['speculative_config']['disable_logprobs'])
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL}}])
@pytest.mark.parametrize('output_len', [2048])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
def test_mlp_e2e_acceptance_rate(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, temperature=0.0, seed=seed, expected_acceptance_rate=0.48)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL, 'speculative_config': {'model': SPEC_MODEL}}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{'seed': 1}])
@pytest.mark.parametrize('test_llm_kwargs', [{'seed': 5}])
@pytest.mark.parametrize('output_len', [64])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('temperature', [1.0])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_mlp_e2e_seeded_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, temperature: float, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    maybe_enable_chunked_prefill(prefill_chunk_size, baseline_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, temperature=temperature, seed=seed)
    with pytest.raises(AssertionError):
        run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, temperature=temperature, seed=seed, disable_seed=True)
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 16, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_mlp_e2e_greedy_correctness_with_preemption(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 16, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
def test_mlp_e2e_greedy_correctness_with_padding(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    def patched_pad_vocab_size(vocab_size, pad_to=None):
        return pad_vocab_size(vocab_size, pad_to=32064)
    with patch('aphrodite.modeling.layers.vocab_parallel_embedding.pad_vocab_size', patched_pad_vocab_size):
        run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': k}} for k in range(1, 1 + MAX_SPEC_TOKENS)])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_mlp_different_k(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, prefill_chunk_size: int, seed: int, output_len: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'disable_by_batch_size': 4}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_mlp_disable_queue(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, prefill_chunk_size: int, seed: int, output_len: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'model_name': MAIN_MODEL, 'enforce_eager': True}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'disable_mqa_scorer': True}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('prefill_chunk_size', [-1, 4])
@pytest.mark.parametrize('seed', [1])
def test_mqa_scorer(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, prefill_chunk_size: int, seed: int):
    maybe_enable_chunked_prefill(prefill_chunk_size, test_llm_kwargs)
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, max_output_len=output_len, seed=seed, temperature=0.0)