import pytest
from .conftest import run_equality_correctness_test
MAIN_MODEL = 'JackFram/llama-68m'
SPEC_MODEL = 'abhigoyal/aphrodite-eagle-llama-68m-random'
MAX_SPEC_TOKENS = 4
PRECISION = 'float32'
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
def test_eagle_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_logprobs': False}}, {'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_logprobs': True}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [8])
@pytest.mark.parametrize('seed', [1])
@pytest.mark.parametrize('logprobs', [1, 6])
def test_eagle_e2e_greedy_logprobs(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int, logprobs: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed, logprobs=logprobs, prompt_logprobs=logprobs, disable_logprobs=test_llm_kwargs['speculative_config']['disable_logprobs'])
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': False, 'disable_log_stats': False, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [1, 32])
@pytest.mark.parametrize('seed', [1])
def test_eagle_e2e_greedy_correctness_cuda_graph(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'block_size': 8, 'num_gpu_blocks_override': 2 + 256 // 8, 'max_model_len': (2 + 256 // 8) * 8, 'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [128])
@pytest.mark.parametrize('batch_size', [4])
@pytest.mark.parametrize('seed', [1])
def test_eagle_e2e_greedy_correctness_with_preemption(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': k}} for k in range(1, 1 + MAX_SPEC_TOKENS)])
@pytest.mark.parametrize('batch_size', [2])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
def test_eagle_different_k(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'dtype': PRECISION, 'model_name': MAIN_MODEL}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': SPEC_MODEL, 'num_speculative_tokens': MAX_SPEC_TOKENS, 'disable_by_batch_size': 4}}])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('seed', [1])
def test_eagle_disable_queue(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': 'float16', 'model_name': 'meta-llama/Llama-2-7b-chat-hf'}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'yuhuili/EAGLE-llama2-chat-7B', 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('seed', [1])
def test_llama2_eagle_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': 'float16', 'model_name': 'meta-llama/Meta-Llama-3-8B-Instruct'}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'yuhuili/EAGLE-LLaMA3-Instruct-8B', 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('seed', [1])
def test_llama3_eagle_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed, temperature=0.0)
@pytest.mark.parametrize('common_llm_kwargs', [{'enforce_eager': True, 'disable_log_stats': False, 'dtype': 'float16', 'model_name': 'Qwen/Qwen2-7B-Instruct'}])
@pytest.mark.parametrize('per_test_common_llm_kwargs', [{}])
@pytest.mark.parametrize('baseline_llm_kwargs', [{}])
@pytest.mark.parametrize('test_llm_kwargs', [{'speculative_config': {'model': 'yuhuili/EAGLE-Qwen2-7B-Instruct', 'num_speculative_tokens': MAX_SPEC_TOKENS}}])
@pytest.mark.parametrize('output_len', [32])
@pytest.mark.parametrize('batch_size', [1, 5])
@pytest.mark.parametrize('seed', [1])
def test_qwen2_eagle_e2e_greedy_correctness(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size: int, output_len: int, seed: int):
    run_equality_correctness_test(aphrodite_runner, common_llm_kwargs, per_test_common_llm_kwargs, baseline_llm_kwargs, test_llm_kwargs, batch_size, output_len, seed, temperature=0.0)
if __name__ == '__main__':
    import pytest
    pytest.main([__file__])