#ifndef _OPENCOG_ATOMSPACE_VER_H
#define _OPENCOG_ATOMSPACE_VER_H
#define ATOMSPACE_MAJOR_VERSION 5
#define ATOMSPACE_MINOR_VERSION 0
#define ATOMSPACE_MICRO_VERSION 5
#ifndef GIT_COMMIT_HASH
#define ATOMSPACE_VERSION_STRING "5.0.5"
#else
#define ATOMSPACE_VERSION_STRING "5.0.5-" GIT_COMMIT_HASH
#endif
#endif