(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-cog))
(use-modules (opencog persist-cog-simple))
(define csna (CogStorageNode "cog://192.168.1.1"))
(define csnb (CogSimpleStorageNode "cog://192.168.1.2"))
(cog-open csna)
(cog-open csnb)
(fetch-atom (Concept "foo") csna)
(store-atom (Concept "foo") csnb)
(load-atomspace csna)
(store-atomspace csnb)
(fetch-atom (Concept "bar") csna)
(fetch-atom (Concept "bar") csnb)
(fetch-atom (Concept "bar") csna)
(fetch-atom (Concept "bar") csnb)
(fetch-atom (Concept "bar") csna)
(fetch-atom (Concept "bar") csnb)
(Concept "bar" (stv 0.3 0.4))
(store-atom (Concept "bar") csna)
(store-atom (Concept "bar") csnb)
(cog-close csna)
(cog-close csnb)