(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-cog))
(cogserver-open "cog://localhost")
(fetch-atom (Concept "b"))
(cog-set-value! (Concept "a") (Predicate "flo") (FloatValue 1 2 3))
(cog-set-value! (Concept "a") (Predicate "blo") (FloatValue 4 5 6))
(store-atom (Concept "a"))
(cog-set-value! (Concept "a") (Predicate "flo") #f)
(cog-set-value! (Concept "a") (Predicate "blo") #f)
(cog-keys (Concept "a"))
(cog-keys->alist (Concept "a"))
(fetch-atom (Concept "a"))
(cog-keys (Concept "a"))
(cog-keys->alist (Concept "a"))
(cog-set-value! (Concept "a") (Predicate "flo") #f)
(cog-set-value! (Concept "a") (Predicate "blo") #f)
(fetch-value (Concept "a") (Predicate "flo"))
(cog-keys->alist (Concept "a"))
(cog-set-value! (Concept "a") (Predicate "blo") (StringValue "a" "b" "c"))
(store-value (Concept "a") (Predicate "blo"))
(cog-set-value! (Concept "a") (Predicate "flo") #f)
(cog-set-value! (Concept "a") (Predicate "blo") #f)
(cog-keys->alist (Concept "a"))
(fetch-value (Concept "a") (Predicate "blo"))
(cog-keys->alist (Concept "a"))
(store-atom (List (Concept "a")(Concept "b")))
(store-atom (Set (Concept "a")(Concept "b")))
(cog-get-all-roots)
(cog-extract-recursive! (Concept "a"))
(cog-get-all-roots)
(cog-incoming-set (Concept "a"))
(fetch-incoming-by-type (Concept "a") 'List)
(cog-incoming-set (Concept "a"))
(fetch-incoming-set (Concept "a"))
(cog-incoming-set (Concept "a"))
(cog-get-all-roots)