(define verbose #f)
(use-modules (srfi srfi-1))
(load "utilities.scm")
(load "local-rules/rule-helpers.scm")
(load "local-rules/subset-direct-evaluation-rule.scm")
(load-from-path "rules/attraction-rule.scm")
(define (cog-create-intensional-similarity-link A B)
    (define attractionLinksA)
    (define attractionLinksB)
    (define ASSOC_sum)
    (define tv-strength)
    (if verbose (display "cog-create-intensional-similarity-link"))
    (if verbose (display-atom "A" A))
    (if verbose (display-atom "B" B))
    (let*
        ((superA (cog-get-supersets A))
         (superB (cog-get-supersets B))
         (superA-length (length superA))
         (superB-length (length superB))
         (superUnion-length (length (lset-union equal? superA superB)))
         (superIntersection (lset-intersection equal? superA superB))
         (superIntersection-length (length superIntersection))
        )
        (if verbose (display-label "superA" superA))
        (if verbose (display-label "superB" superB))
        (if verbose (display-label "superA-length" superA-length))
        (if verbose (display-label "superB-length" superB-length))
        (if verbose (display-label "superIntersection" superIntersection))
        (if verbose (display-label "superInersection length" superIntersection-length))
        (if verbose (display-label "superUnion-length" superUnion-length))
        (if verbose (display
            "\nCreating relationships SubsetAB and SubsetNotAB\n\n"))
        (set! attractionLinksA
            (map-in-order make-attraction-via-subsets
                 (make-list superIntersection-length A) superIntersection
            )
        )
        (set! attractionLinksB
            (map-in-order make-attraction-via-subsets
                 (make-list superIntersection-length B) superIntersection
            )
        )
        (if verbose (display-atom "attractionLinksA" attractionLinksA))
        (if verbose (display-atom "attractionLinksB" attractionLinksB))
        (set! ASSOC_sum
            (fold (lambda(attractA attractB previous_sum)
                    (+ previous_sum
                       (min (cog-stv-strength attractA)
                            (cog-stv-strength attractB))
                    )
                   )
                   0
                   attractionLinksA
                   attractionLinksB
            )
        )
        (if verbose (display-label "ASSOC_sum" ASSOC_sum))
        (set! tv-strength (/ ASSOC_sum superUnion-length))
        (if verbose (display-label "tv-strength" tv-strength))
        (IntensionalSimilarityLink A B (stv tv-strength 1))
     )
)
(define (make-attraction-via-subsets A B)
    (define subsetAB)
    (define NotA)
    (define subsetNotAB)
    (define grounded-attraction-rule)
    (define all-genes)
    (define sizeB)
    (define sNotAB)
    (set! subsetAB (subset-direct-evaluation A B))
    (if verbose (display subsetAB))
#!
    (set! subsetNotAB (SubsetLink (NotLink A) B (stv 0 1)))
    (if verbose (display subsetNotAB))
!#
    (set! sizeB (length (get-set-members B)))
    (if verbose (display-label "sizeB" sizeB))
    (set! sNotAB (/ (- sizeB 1.0) (- num-genes 1)))
    (if verbose (display-label "sNotAB" sNotAB))
    (set! subsetNotAB (SubsetLink (NotLink A) B (stv sNotAB 1)))
    (if verbose (display subsetNotAB))
    #!
    (set! all-genes (SetLink (cog-get-atoms 'GeneNode)))
    (set! NotA (SetLink (delete A (cog-outgoing-set all-genes))))
    (set! subsetNotAB (subset-direct-evaluation NotA B))
    (if verbose (display subsetNotAB))
    !#
    (pln-attraction-rule-no-variables subsetAB subsetNotAB)
)
(define (test)
    (use-modules (opencog))
    (use-modules (opencog query))
    (use-modules (opencog rule-engine))
    (load-from-path "av-tv.scm")
    (load "substitute.scm")
    (load "background-knowledge.scm")
    (load "local-rules/member-to-subset.scm")
    (cog-bind pln-rule-member-to-subset)
    (cog-create-intensional-links setL long-set)
)