(use-modules (opencog))
(define REDUCED_BIOSPACE_FILE "reduced-biospace-LY96-TBK1.scm")
(define (set-tvs-for-type strength confidence type)
    (let ([atoms (cog-get-atoms type)])
       (for-each (lambda (atom)
            (cog-set-tv! atom (cog-new-stv strength confidence)))
            atoms)))
(define (set-gene-tvs strength confidence)
    (set-tvs-for-type strength confidence 'GeneNode))
(define (set-concept-tvs strength confidence)
    (set-tvs-for-type strength confidence 'ConceptNode))
(define (set-default-gene-tvs) (set-gene-tvs .00001 .9))
(define (set-default-concept-tvs) (set-concept-tvs .001 .9))
(define (set-computed-gene-tvs)
    (set-gene-tvs (/ 1 24000) .9))
(define (set-bio-tvs)
    (set-default-gene-tvs)
    (set-computed-gene-tvs)
    (set-default-concept-tvs))
(load "utilities.scm")
(display "\"")(display REDUCED_BIOSPACE_FILE)(display "\"")(newline)
(load REDUCED_BIOSPACE_FILE)
(set-bio-tvs)
(define num-genes 24000)
(display-var "num-genes" num-genes)