(use-modules (srfi srfi-1))
(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog matrix))
(define-public (make-bond-link-api)
"
make-bond-link-api -- Associate word-pairs and LG connector names.
The matrix consists of (word,word) pairs and the corresponding LG
connector name. Matrix elements have the form
(Edge (Bond \"XYZ\") (List (Word ...) (Word ...)))
where XYZ is the Link Grammar connector (link) name.
For a detailed description, see the `bond-links.scm` file.
"
(define any-left (AnyNode "bond-left"))
(define any-right (AnyNode "bond-right"))
(define (get-left-type) (Type 'WordNode))
(define (get-right-type) (Type 'WordNode))
(define (get-pair-type) (Type 'EdgeLink))
(define bany (BondNode "ANY"))
(define (get-pair L-ATOM R-ATOM)
(define pr #f)
(define wp (cog-link 'List L-ATOM R-ATOM))
(if (nil? wp) wp
(for-each
(lambda (EDGE)
(if (not (equal? bany (gar EDGE)))
(set! pr EDGE)))
(cog-incoming-by-type wp 'EdgeLink)))
pr)
(define (make-id-str nid lst)
(if (> 0 nid)
(list->string lst)
(make-id-str (- (floor (/ nid 26)) 1)
(cons (integer->char (+ 65 (modulo nid 26))) lst))))
(define idanch (Anchor "*-LG-issued-link-id-*"))
(define (issue-link)
(define nid (cog-count idanch))
(define linkstr (make-id-str nid '()))
(set! nid (+ 1 nid))
(if (equal? nid 1064) (set! nid (+ 1 nid)))
(cog-set-tv! idanch (CountTruthValue 1 0 nid))
(store-atom idanch)
linkstr)
(define (make-pair L-ATOM R-ATOM)
(define pr (get-pair L-ATOM R-ATOM))
(if (not (nil? pr)) pr
(Edge (Bond (issue-link)) (ListLink L-ATOM R-ATOM))))
(define (get-left-element EDGE) (gadr EDGE))
(define (get-right-element EDGE) (gddr EDGE))
(define (get-left-wildcard WORD)
(Edge idanch (ListLink any-left WORD)))
(define (get-right-wildcard WORD)
(Edge idanch (ListLink WORD any-right)))
(define (get-wild-wild)
(Edge idanch (ListLink any-left any-right)))
(define (load-all-bonds)
(define mon (make-rate-monitor))
(fetch-atom idanch)
(load-atoms-of-type 'BondNode)
(for-each
(lambda (BOND)
(mon #f)
(fetch-incoming-by-type BOND 'EdgeLink))
(cog-get-atoms 'BondNode))
(fetch-incoming-by-type idanch 'EdgeLink)
(mon "Loaded ~D edges in ~D secs; rate=~5F\n"))
(define (describe)
(display (procedure-property make-bond-link-api 'documentation)))
(define (store-aux) (store-atom idanch))
(define (provides meth)
(case meth
((store-aux)        store-aux)
(else #f)
))
(lambda (message . args)
(apply (case message
((name) (lambda () "LG-Link - word-pair Association"))
((id)             (lambda () "bond-link"))
((left-type)      get-left-type)
((right-type)     get-right-type)
((pair-type)      get-pair-type)
((get-pair)       get-pair)
((make-pair)      make-pair)
((left-element)   get-left-element)
((right-element)  get-right-element)
((left-wildcard)  get-left-wildcard)
((right-wildcard) get-right-wildcard)
((wild-wild)      get-wild-wild)
((fetch-pairs)    load-all-bonds)
((provides)       provides)
((store-aux)      store-aux)
((filters?)       (lambda () #f))
((help)           describe)
((describe)       describe)
((obj)            (lambda () "make-bond-link-api"))
((base)           (lambda () #f))
(else (error "Bad method call on bond-link:" message)))
args))
)