(use-modules (srfi srfi-1))
(use-modules (opencog))
(use-modules (opencog persist))
(use-modules (opencog matrix))
(define-public (make-pseudo-cset-api)
"
make-pseudo-cset-api -- Create a word-disjunct matrix.
The matrix consists of (word,disjunct) pairs (a 'disjunct' and a
'cset' or 'connector set' are all different names for the same thing).
The words appear as rows of the matrix
For a detailed description, see the `pseudo-csets.scm` file.
"
(define any-left (AnyNode "cset-word"))
(define any-right (AnyNode "cset-disjunct"))
(define (get-left-type) (Type 'WordNode))
(define (get-right-type) (Type 'ConnectorSeq))
(define (get-pair-type) (Type 'Section))
(define (get-pair L-ATOM R-ATOM)
(cog-link 'Section L-ATOM R-ATOM))
(define (make-pair L-ATOM R-ATOM)
(Section L-ATOM R-ATOM))
(define (get-left-element PAIR) (gar PAIR))
(define (get-right-element PAIR) (gdr PAIR))
(define (get-left-wildcard DJ)
(ListLink any-left DJ))
(define (get-right-wildcard WORD)
(ListLink WORD any-right))
(define (get-wild-wild)
(ListLink any-left any-right))
(define (fetch-pseudo-csets)
(define start-time (current-time))
(fetch-incoming-by-type any-left 'ListLink)
(fetch-incoming-by-type any-right 'ListLink)
(load-atoms-of-type 'Section)
(format #t "Elapsed time to load csets: ~A secs\n"
(- (current-time) start-time)))
(define (describe)
(display (procedure-property make-pseudo-cset-api 'documentation)))
(lambda (message . args)
(apply (case message
((name) (lambda () "Word-Disjunct Pairs (Connector Sets)"))
((id)             (lambda () "cset"))
((left-type)      get-left-type)
((right-type)     get-right-type)
((pair-type)      get-pair-type)
((get-pair)       get-pair)
((make-pair)      make-pair)
((left-element)   get-left-element)
((right-element)  get-right-element)
((left-wildcard)  get-left-wildcard)
((right-wildcard) get-right-wildcard)
((wild-wild)      get-wild-wild)
((fetch-pairs)    fetch-pseudo-csets)
((provides)       (lambda (symb) #f))
((filters?)       (lambda () #f))
((help)           describe)
((describe)       describe)
((obj)            (lambda () "make-pseudo-cset-api"))
((base)           (lambda () #f))
(else (error "Bad method call on pseudo-cset:" message)))
args))
)