(use-modules (srfi srfi-1))
(use-modules (opencog) (opencog persist))
(use-modules (opencog persist-bridge))
(define flystore (BridgeStorageNode "postgres:///flybase"))
(cog-open flystore)
(cog-connected? flystore)
(define table-descs (cog-bridge-load-tables flystore))
(length table-descs)
(third table-descs)
(cog-prt-atomspace)
(cog-report-counts)
(display (monitor-storage flystore))
(cog-incoming-set (Variable "genotype_id"))
(define (print-tables NAME)
(define column (Variable NAME))
(define coldesc (car (cog-incoming-by-type column 'TypedVariable)))
(define rowdescs (cog-incoming-by-type coldesc 'VariableList))
(map
(lambda (ROWDESC)
(define siggy (car (cog-incoming-by-type ROWDESC 'Signature)))
(cog-value-ref siggy 0))
rowdescs))
(print-tables "genotype_id")
(fetch-incoming-set (Predicate "genotype"))
(cog-report-counts)
(count-all)
(display (monitor-storage flystore))
(cog-incoming-by-type (Predicate "genotype") 'Signature)
(list-ref (cog-incoming-set (Predicate "genotype")) 42)
(fetch-incoming-set (Number 362100))
(cog-get-root (Number 362100))
(fetch-incoming-set (Number 51808))
(cog-get-root (Number 51808))
(cog-bridge-load-row flystore
(Predicate "genotype")
(Variable "genotype_id")
(Number 464522))
(fetch-incoming-set (Variable "genotype_id"))
(cog-report-counts)
(count-all)
(display (monitor-storage flystore))
(use-modules (opencog cogserver))
(start-cogserver)
(define all-tables (cog-get-atoms 'PredicateNode))
(length all-tables)
(define big-tables (list
(Predicate "featureloc")
(Predicate "feature")
(Predicate "analysisfeature")
(Predicate "feature_relationship")
(Predicate "library_featureprop")
(Predicate "feature_dbxref")
(Predicate "dbxref")
(Predicate "library_feature")
(Predicate "featureprop")
))
(define smaller-tables (atoms-subtract all-tables big-tables))
(define (load-tables TABLE-LIST)
(define tabno 0)
(for-each
(lambda (PRED)
(define start-time (current-time))
(set! tabno (+ 1 tabno))
(format #t "Start loading table ~A/~A  ~A\n"
tabno (length TABLE-LIST) (cog-name PRED))
(fetch-incoming-set PRED)
(let* ((elapsed (- (current-time) start-time))
(num-rows (cog-incoming-size PRED)))
(format #t "... Done loading ~A rows in ~A secs\n"
num-rows elapsed)
(when (< 20 elapsed)
(format #t "... Rate: ~8,1F rows/sec\n"
(exact->inexact (/ num-rows elapsed))))
)
(format #t "----------------------\n"))
TABLE-LIST))
(load-tables smaller-tables)
(for-each
(lambda (PRED)
(format #t "Found ~A \trows in table ~A\n"
(cog-incoming-size-by-type PRED 'EdgeLink)
(cog-name PRED)))
(cog-get-atoms 'PredicateNode))
(define all-sizes (map cog-incoming-size (cog-get-atoms 'PredicateNode)))
(fold + 0 all-sizes)
(/ (count-all) (fold + 0.0 all-sizes))
: Time to say goodnight.
(cog-close flystore)