#ifndef _LINUX_HDREG_H
#define _LINUX_HDREG_H
#define HD_IRQ 14
#define HD_DATA		0x1f0
#define HD_ERROR	0x1f1
#define HD_NSECTOR	0x1f2
#define HD_SECTOR	0x1f3
#define HD_LCYL		0x1f4
#define HD_HCYL		0x1f5
#define HD_CURRENT	0x1f6
#define HD_STATUS	0x1f7
#define HD_FEATURE HD_ERROR
#define HD_PRECOMP HD_FEATURE
#define HD_COMMAND HD_STATUS
#define HD_CMD		0x3f6
#define HD_ALTSTATUS	0x3f6
#define ERR_STAT	0x01
#define INDEX_STAT	0x02
#define ECC_STAT	0x04
#define DRQ_STAT	0x08
#define SEEK_STAT	0x10
#define WRERR_STAT	0x20
#define READY_STAT	0x40
#define BUSY_STAT	0x80
#define WIN_RESTORE		0x10
#define WIN_READ		0x20
#define WIN_WRITE		0x30
#define WIN_VERIFY		0x40
#define WIN_FORMAT		0x50
#define WIN_INIT		0x60
#define WIN_SEEK 		0x70
#define WIN_DIAGNOSE		0x90
#define WIN_SPECIFY		0x91
#define WIN_SETIDLE1		0xE3
#define WIN_SETIDLE2		0x97
#define WIN_DOORLOCK		0xde
#define WIN_DOORUNLOCK		0xdf
#define WIN_ACKMC		0xdb
#define WIN_MULTREAD		0xC4
#define WIN_MULTWRITE		0xC5
#define WIN_SETMULT		0xC6
#define WIN_IDENTIFY		0xEC
#define WIN_SETFEATURES		0xEF
#define WIN_READDMA		0xc8
#define WIN_WRITEDMA		0xca
#define WIN_READDMA_EXT		0x25
#define WIN_WRITEDMA_EXT	0x35
#define WIN_PIDENTIFY		0xA1
#define WIN_SRST		0x08
#define WIN_PACKETCMD		0xa0
#define EXABYTE_ENABLE_NEST	0xf0
#define MARK_ERR	0x01
#define TRK0_ERR	0x02
#define ABRT_ERR	0x04
#define ID_ERR		0x10
#define MC_ERR		0x20
#define ECC_ERR		0x40
#define	BBD_ERR		0x80
#define	ICRC_ERR	0x80
struct hd_geometry {
unsigned char heads;
unsigned char sectors;
unsigned short cylinders;
unsigned long start;
};
#define HDIO_GETGEO		0x0301
#define HDIO_GET_UNMASKINTR	0x0302
#define HDIO_GET_MULTCOUNT	0x0304
#define HDIO_OBSOLETE_IDENTITY	0x0307
#define HDIO_GET_KEEPSETTINGS 	0x0308
#define HDIO_GET_32BIT 		0x0309
#define HDIO_GET_NOWERR		0x030a
#define HDIO_GET_DMA		0x030b
#define HDIO_GET_IDENTITY	0x030d
#define HDIO_DRIVE_CMD		0x031f
#define HDIO_SET_MULTCOUNT	0x0321
#define HDIO_SET_UNMASKINTR	0x0322
#define HDIO_SET_KEEPSETTINGS	0x0323
#define HDIO_SET_32BIT		0x0324
#define HDIO_SET_NOWERR		0x0325
#define HDIO_SET_DMA		0x0326
#define HDIO_SET_PIO_MODE	0x0327
struct hd_driveid {
unsigned short	config;
unsigned short	cyls;
unsigned short	reserved2;
unsigned short	heads;
unsigned short	track_bytes;
unsigned short	sector_bytes;
unsigned short	sectors;
unsigned short	vendor0;
unsigned short	vendor1;
unsigned short	vendor2;
unsigned char	serial_no[20];
unsigned short	buf_type;
unsigned short	buf_size;
unsigned short	ecc_bytes;
unsigned char	fw_rev[8];
unsigned char	model[40];
unsigned char	max_multsect;
unsigned char	vendor3;
unsigned short	dword_io;
unsigned char	vendor4;
unsigned char	capability;
unsigned short	reserved50;
unsigned char	vendor5;
unsigned char	tPIO;
unsigned char	vendor6;
unsigned char	tDMA;
unsigned short	field_valid;
unsigned short	cur_cyls;
unsigned short	cur_heads;
unsigned short	cur_sectors;
unsigned short	cur_capacity0;
unsigned short	cur_capacity1;
unsigned char	multsect;
unsigned char	multsect_valid;
unsigned int	lba_capacity;
unsigned short	dma_1word;
unsigned short	dma_mword;
unsigned short  eide_pio_modes;
unsigned short  eide_dma_min;
unsigned short  eide_dma_time;
unsigned short  eide_pio;
unsigned short  eide_pio_iordy;
unsigned short  word69;
unsigned short  word70;
unsigned short  word71;
unsigned short  word72;
unsigned short  word73;
unsigned short  word74;
unsigned short  word75;
unsigned short  word76;
unsigned short  word77;
unsigned short  word78;
unsigned short  word79;
unsigned short  word80;
unsigned short  word81;
unsigned short  command_sets;
unsigned short  command_set_2;
unsigned short  word84;
unsigned short  word85;
unsigned short  word86;
unsigned short  word87;
unsigned short  dma_ultra;
unsigned short	word89;
unsigned short	word90;
unsigned short	word91;
unsigned short	word92;
unsigned short	word93;
unsigned short	word94;
unsigned short	word95;
unsigned short	word96;
unsigned short	word97;
unsigned short	word98;
unsigned short	word99;
unsigned long long lba_capacity_2;
unsigned short	word104;
unsigned short	word105;
unsigned short	word106;
unsigned short	word107;
unsigned short	word108;
unsigned short	word109;
unsigned short	word110;
unsigned short	word111;
unsigned short	word112;
unsigned short	word113;
unsigned short	word114;
unsigned short	word115;
unsigned short	word116;
unsigned short	word117;
unsigned short	word118;
unsigned short	word119;
unsigned short	word120;
unsigned short	word121;
unsigned short	word122;
unsigned short	word123;
unsigned short	word124;
unsigned short	word125;
unsigned short	word126;
unsigned short	word127;
unsigned short	security;
unsigned short	reserved[127];
};
#ifdef __KERNEL__
#include <linux/config.h>
#ifdef CONFIG_BLK_DEV_HD
void hd_setup(char *, int *);
#endif
#ifdef CONFIG_BLK_DEV_IDE
void ide_setup(char *);
#ifdef CONFIG_BLK_DEV_IDE_PCMCIA
int ide_register(int io_port, int ctl_port, int irq);
void ide_unregister(unsigned int);
#endif
#endif
#endif
#endif